### ISSUE TITLE
Retrieve codice tributo per le posizioni debitorie

### ISSUE THREAD

**Issue by acoviello** [link-it/govpay#101]
Ciao @nardil,
ho notato che tra i servizi web, sempre per la versione 2.5.7 di GovPay, non è possibile recuperare il codice tributo inserito nel momento in cui si carica un versamento, nello specifico invocando il servizio web gpCaricaVersamento.
Mi servirebbe soprattutto nel momento in cui sul portale recupero le informazioni del pagamento e do la possibilità di pagare online una posizione debitoria, quindi oltre alle informazioni del barcode, causale etc mi servirebbe anche il codice tributo per poter avviare il pagamento secondo il modello 1.
E' possibile aggiungere questo campo nei versamenti ricevuti nella risposta del servizio gpChiediListaVersamenti?
Grazie,
Alessandra

**Comment by nardil** [comment]
Ciao Alessandra ,
con la versione 3.x di govpay le api di integrazione soap sono state abbandonate in favore delle API REST. 
Una soluzione quindi quella di migrare alla nuova versione del prodotto, altrimenti puoi fare un fork della versione di tuo interesse e modificare le API secondo le tue esigenze.
