### ISSUE TITLE
Filtri di ricerca delle Pendenze

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#108]
Sono necessarie queste modifiche alla pagina di ricerca delle pendenze:

Aggiungere il filtro per IUV/Numero avviso (la stringa inserita viene usata come filtro parziale su entrambi i campi della pendenza)
Non prefillare alcun campo
Ordinamento dei filtri:
1. Ente creditore
1. iuv/numero avviso
1. Identificativo A2A
1. Identificativo Pendenza
1. Stato pendenza
1. Tipo pendenza
1. Identificativo Pagamento

**Comment by pintorig** [comment]
Risolto nel commit: https://github.com/link-it/govpay/commit/0bc06211d5a6c5d5aca7c780cb21b3b2bce4782d
