### ISSUE TITLE
Modifiche elenco delle applicazioni

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#112]
Il principal potrebbe essere un subject di certificato, pertanto poco leggibile da cruscotto nella pagina di elenco.

Meglio utilizzare come titolo l'idA2A e rimuovere il principal.

**Comment by nardil** [comment]
Aggiungere anche la possibilita' di ricercare per principal, ricerca in like, case insensitive

**Comment by simo-git** [comment]
Realizzare supporto lato server per "Aggiungere anche la possibilita' di ricercare per principal, ricerca in like, case insensitive"

**Comment by pintorig** [comment]
Aggiunto filtro per principal al servizio di ricerca Applicazioni API-Backoffice.
