### ISSUE TITLE
Errore di autorizzazione in lettura evento

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#117]
**Descrizione del Bug**
Un operatore autorizzato nella consultazione delle pendenze riesce a ricercare gli eventi relativi alle pendenze per cui e' autorizzato, ma non ad accedere al loro dettaglio

**Come riprodurlo:**
Accedere alla console con un'utenza di tipo operatore, accedere ad una pendenza, accedere agli eventi della pendenza e aprire la vista completa per ricevere l'errore di autorizzazione

**Risultato atteso:**
L'accesso alla risorsa dovrebbe essere consentito.

**Screenshots:**
![Schermata da 2019-10-18 12-09-25](https://user-images.githubusercontent.com/12340738/67086173-7dd9d500-f1a0-11e9-9de8-85cfd83fe172.png)
![Schermata da 2019-10-18 12-09-37](https://user-images.githubusercontent.com/12340738/67086190-83371f80-f1a0-11e9-9ead-9241b791dc67.png)

**Ambiente:**
 - GovPay: 3.1.0

**Note aggiuntive:**
n/a

**Comment by nardil** [comment]
@pintorig : aggiunti test che riproducono l'errore in [branch dedicato](/link-it/govpay/tree/117_errore_di_autorizzazione_in_lettura_evento)

```
---------------------------------------------------------
feature: classpath:test/api/backoffice/v1/eventi/eventi-interfaccia-autorizzazione.feature
scenarios:  1 | passed:  0 | failed:  1 | time: 8,2970
---------------------------------------------------------
HTML report: (paste into browser to view) | Karate version: 0.9.2
file:/home/nardi/github/govpay/integration-test/target/surefire-reports/test.api.backoffice.v1.eventi.eventi-interfaccia-autorizzazione.html
---------------------------------------------------------
```

**Comment by pintorig** [comment]
Corretta autorizzazione per la visualizzazione del dettaglio eventi collegati ad una pendenza
