### ISSUE TITLE
Integrazione App IO per avvisatura digitale

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#118]
**Necessità:**
Integrazione app IO per notificare al cittadino registrato l'emissione di avvisi di pagamento a suo carico.

**Soluzione:**
Prevedere nella configurazione generale le seguenti nuove proprieta':
- `io.backend.url`: url del servizio di backend di IO
- `io.message.timeToLive`: valore in secondi del retry per la consegna dei messaggi da parte di agid. Default NULL
- `io.message.subject`: freemarker per la compilazione dell'oggetto del messaggio (_default da definire_)
- `io.message.body`: freemarker per la compilazione dell'corpo del messaggio (_default da definire_)

Prevedere nella configurazione del tipoPendenza associato all'Ente Creditore le seguenti nuove proprieta':
- `io.enable`: indica se la spedizione del messaggio e' prevista per questo tipo pendenza. default false.
- `io.apikey`: obbligatorio se abilitata l'integrazione. E' la API Key per le invocazioni.
- `io.message.subject`: freemarker per la compilazione dell'oggetto del messaggio. Se valorizzato sovrascrive il default
- `io.message.body`: freemarker per la compilazione dell'corpo del messaggio. Se valorizzato sovrascrive il default

All'atto dell'emissione di una pendenza con avviso, realizzare il seguente processo se l'integrazione ad IO e' configurata:

_HAPPY PATH_

```
GET /profile/{codice_fiscale}

HTTP 200 OK
{
  "sender_allowed": true,
  "preferred_languages": [
    "en_US",
    "it_IT"
  ]
}
```

```
POST /message/
{
  "time_to_live": {io.message.timeToLive},
  "content": {
    "subject": "{io.message.subject}",
    "markdown": "${io.message.body}",
    "payment_data": {
      "amount": {versamento.importo},
      "notice_number": "{versamento.numeroAvviso}",
      "invalid_after_due_date": "{versamento.dataScadenza == due_date}"
    },
    "due_date": "{versamento.dataValidita o versamento.dataScadenza}"
  },
  "fiscal_code": "{versamento.soggettoDebitore.identificativoUnivoco}"
}

HTTP 201 CREATED
{
  "id": "01BX9NSMKVXXS5PSP2FATZMYYY"
}
```

_PATH ALTERNATIVI_

- 404 da `/profile`: Utente non registrato su IO. Processo terminato
- 200 da `/profile` && `sender_allowed=false`: Utente registrato su IO, ma con notifiche disabilitate. Processo terminato
- 429 da `/profile`: Rischedulo successivamente
- 400 o 401 da `/messages`: Fail. Processo terminato
- 429 o 500  da `/messages`: Rischedulo successivamente

L'interazione con l'api di backoffice di pagoPA viene registrata sul giornale degli eventi. La configurazione del giornale viene dunque estesa in tal senso con la seguente configurazione di default:
- LETTURE: log & dump solo errore
- SCRITTURE: log sempre, dump solo errore.
Le registrazioni devono essere legate alla pendenza e figurare nella vista degli eventi per pendenza.

**Alternative:**
n/a

**Note:**
n/a

**Comment by nardil** [comment]
#173

Alle API estendere la pendenza:
* dataNotificaAvviso (data, opzionale)
* dataPromemoriaScadenza (data, opzionale)

Realizzare un batch che periodicamente scansional l'archivio delle pendenze per individuare nuove messaggio IO o email da schedulare.

A tale scopo aggiungere alla tabella versamenti i campi:
* `dataNotificaAvviso` (date nullable)
* `dataPromemoriaScadenza` (date nullable)
* `isAvvisoNotificato` (boolean nullable default null)
* `isPromemoriaNotificato` (boolean nullable default null)

dove:
* `dataNotificaAvviso` = null se la notifica sia IO che mail non e' prevista, altrimenti il valore indicato nella pendenza oppure la data di caricamento se non fornita.
* `dataNotificaPromemoria` = null se la notifica sia IO che mail non e' prevista, altrimenti il valore indicato nella pendenza oppure la data di validita' meno i giorni di preavviso configurati nel tipo pendenza.
* `isAvvisoNotificato` = null se dataNotificaAvviso = null, altrimenti false.
* `isPromemoriaNotificato` = null se dataNotificaPromemoria = null, altrimenti false.

Il batch di predisposizione delle spedizioni recupera le seguenti pendenze:
* Notifica Avviso: tutte le pendenze con `dataNotificaAvviso != null`, `dataNotificaAvviso <= oggi`, `isAvvisoNotificato == false`, `stato = DA_PAGARE`
* Notifica Promemoria: tutte le pendenze con `dataNotificaPromemoria != null`, `dataNotificaPromemoria <= oggi`, `isPromemoriaNotificato == false`, `stato = DA_PAGARE`

Per ogni versamento individuato, schedulare la spedizione della mail e/o l'invio del messaggio IO e aggiornare il versamento impostando a `true` il parametro `isAvvisoNotificato` o `isPromemoriaNotificato`

Quando un pagamento passa in stato "Eseguito" o "Annullato", impostare a null isAvvisoNotificato e isPromemoriaNotificato.

Quando un pagamento passa da "Annullato" a "Non eseguto" reimpostare i valori secondo la logica originale:
* `isAvvisoNotificato` = null se dataNotificaAvviso = null, altrimenti false.
* `isPromemoriaNotificato` = null se dataNotificaPromemoria = null, altrimenti false.

Inserire indice (isAvvisoNotificato, dataNotificaAvviso)
Inserire indice (isPromemoriaNotificato, dataNotificaPromemoria)

**Comment by nardil** [comment]
@simo-git per il servizio di avvisatura IO manca la possibilita' di impostare la configurazione nelle impostazioni. 

Vanno quindi aggiunte le seguenti sezioni: 
* App IO - Generale
  * `Abilitato`: true/false
  * `URL Backend IO`: obbligatorio testuale
  * `Time to live`: numerico, opzionale, default vuoto (null)
* App IO - Promemoria di pagamento
  * Equivalente al promemoria via mail (tipo, oggetto, messaggio)
* App IO - Notifica della ricevuta
  * Equivalente al promemoria via mail (tipo, oggetto, messaggio)
* App IO - Promemoria di scadenza
  * Equivalente al promemoria via mail (tipo, oggetto, messaggio, preavviso)

**Comment by simo-git** [comment]
Realizzata modifica alla sezione 'Impostazioni' per supportare la configurazione del servizio 'AppIO'. Commit: 68c340a

**Comment by pintorig** [comment]
@nardil Realizzate tutte le modifiche richieste ai servizi e alla console di configurazione.

**Comment by nardil** [comment]
@simo-git Nella schermata delle impostazioni risulta questo elenco:
- Giornale degli Eventi
- Mail - Server di posta
- Comunicazioni via App IO
- Batch App IO
- Comunicazioni via mail
- Parser tracciati csv
- Protezione API pubbliche

Vorrei rimodularlo come segue:

- Giornale degli Eventi
- Mail - Server di posta
- Mail - Comunicazioni
- AppIO - Backend
- AppIO - Comunicazioni
- Parser tracciati csv
- Protezione API pubbliche

O ancora meglio, se possibile:

- Giornale degli Eventi
- Comunicazioni Mail
- Comunicazioni AppIO
- Parser tracciati csv
- Protezione API pubbliche

aggiungendo un tab agli accordion gia presenti per fondere le voci indicate.

@pintorig 

Aggiornando il giornale degli eventi ricevo l'errore `Richiesta non valida: Il campo apiBackendIO non deve essere vuoto.` Premesso che il backendIO effettivamente non e' configurato, mi aspetterei che comunue la patch richiesta venisse accettata.

**Comment by nardil** [comment]
@simo-git 

Nella schemata di configurazione del Backend IO, la URL deve risultare obbligatoria solo se e' abilitato

![Schermata da 2020-06-30 16-25-38](https://user-images.githubusercontent.com/12340738/86138582-f09c9d80-baee-11ea-82f6-13a4628a4019.png)

**Comment by pintorig** [comment]
> @simo-git Nella schermata delle impostazioni risulta questo elenco:
> 
> * Giornale degli Eventi
> * Mail - Server di posta
> * Comunicazioni via App IO
> * Batch App IO
> * Comunicazioni via mail
> * Parser tracciati csv
> * Protezione API pubbliche
> 
> Vorrei rimodularlo come segue:
> 
> * Giornale degli Eventi
> * Mail - Server di posta
> * Mail - Comunicazioni
> * AppIO - Backend
> * AppIO - Comunicazioni
> * Parser tracciati csv
> * Protezione API pubbliche
> 
> O ancora meglio, se possibile:
> 
> * Giornale degli Eventi
> * Comunicazioni Mail
> * Comunicazioni AppIO
> * Parser tracciati csv
> * Protezione API pubbliche
> 
> aggiungendo un tab agli accordion gia presenti per fondere le voci indicate.
> 
> @pintorig
> 
> Aggiornando il giornale degli eventi ricevo l'errore `Richiesta non valida: Il campo apiBackendIO non deve essere vuoto.` Premesso che il backendIO effettivamente non e' configurato, mi aspetterei che comunue la patch richiesta venisse accettata.

L'errore si riferisce alla sezione del giornale degli eventi che e' incaricata di salvare gli eventi relativi alle chiamate verso il server di AppIO, bisogna quindi aggiungere la voce corrispondente in questa sezione:

![Screenshot from 2020-06-30 18-04-51](https://user-images.githubusercontent.com/12812160/86149544-60fdeb80-bafc-11ea-9fca-66cbe22b578b.png)

**Comment by nardil** [comment]
Riepilogando:

- [ ] Riordinare le voci del menu delle impostazioni
- [ ] Compattare le voci di menu delle comunicazioni
- [ ] Correggere l'obbligatorieta' dei parametri di configurazione del backend IO
- [ ] Aggiungere alla configurazione del Giornale Degli Eventi le `API Backend IO`

**Comment by simo-git** [comment]
Commit: 3e94200
- Modifica/raggruppamento sezioni impostazioni;
- Modifica validatori campi required in base al toggle 'abilita';
- Aggiunta configurazione radio 'API Backend IO' per opzioni di lettura/scrittura in GdE
