### ISSUE TITLE
Campo importo fisso per entrate

### ISSUE THREAD

**Issue by acoviello** [link-it/govpay#128]
Al fine di censire tutte le entrate per i domini configurati, è emersa la necessità di inserire un importo fisso per entrate quali diritti di segreteria, tasse di abilitazioni etc. 
E' possibile poter inserire un importo predeterminato per questo tipo di entrate in modo che esca precompilato nel caso di pagamento spontaneo?
Grazie

**Comment by nardil** [comment]
Ciao Alessandra,
nella versione 3.1 sono state introdotte le funzioni di trasformazione e validazione a livello di tipologia di pendenza che gestiscono il caso che hai individuato. 

E' possibile infatti configurare GovPay per ricevere i dati variabili del dovuto in un formato json arbitrario e predisporre la pendenza desiderata configurando un trasformatore freemarker.

https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/index.html#elaborazione

Prendiamo come esempio il pagamento dei buoni pasto. L'utente fornisce il numero di buoni pasto che vuole acquistare ed i propri dati (se il processo di business richiede di identificate il pagatore):
```json
POST /pagamenti
{
    "versante": {
        "tipo": "F",
        "identificativo": "RSSMRA30A01H501I",
        "anagrafica": "Mario Rossi",
        "email": "mario.rossi@host.eu"
    },
    "pendenze": [
        {
	    "idDominio": "01234567890",
            "idTipoPendenza": "Buoni pasto",
            "dati" :  {
                "buoni_pasto": 15
            }
        }
    ]
}
```
Nella configurazione della tipologia di pendenza "Buoni pasto" in GovPay viene abilitata la funzione di validazione predisponendo un JsonSchema che valida l'input dell'utente e la trasformazione predisponendo un Freemarker che trasforma la richiesta dell'utente in una pendenza pagabile, impostando i valori fissi (iban accredito, codici contabilità, etc...) e calcolando quelli variabili (importo dovuto, etc...).

**Comment by acoviello** [comment]
Perfetto, grazie credo di configurare tutte le pendenze in questo modo!

**Comment by acoviello** [comment]
Ciao Lorenzo,
riapro questa issue in quanto ho un dubbio sul funzionamento del pagamento di pagamenti spontanei.
Ho configurato una pendenza libera con uno schema, in modo da avere sul mio portale una form dinamica, quando provo ad effettuare una post e nella lista delle pendenze a mettere un oggetto  di tipo "NuovaPendenza", con un idPendenza che creo al momento, ottengo in risposta "PAA_PAGAMENTO_SCONOSCIUTO"  mentre se inserisco un idPendenza che si riferisce ad una pendenza precaricata sul sistema non ho errori. Ciò significa che non è possibile creare una pendenza nel momento in cui si fa una post su pagamenti?

**Comment by nardil** [comment]
Se hai configurato un tipoPendenza per sfruttare la funzione di trasformazione, devi effettuare la richiesta nella forma suggerita nel post precedente:

```json
POST /pagamenti
{
    "versante": {
        "tipo": "F",
        "identificativo": "RSSMRA30A01H501I",
        "anagrafica": "Mario Rossi",
        "email": "mario.rossi@host.eu"
    },
    "pendenze": [
        {
	    "idDominio": "01234567890",
            "idTipoPendenza": "Buoni pasto",
            "dati" :  {
                "buoni_pasto": 15
            }
        }
    ]
}
```

se invece si tratta di un diverso scenario indicami meglio i dettagli ed la richiesta che stai inviando

**Comment by acoviello** [comment]
Il mio schema è molto semplice, serve solo per preimpostarmi dei valori di default quali l'importo etc. Ti riporto i dettagli della richiesta e della risposta:
{"urlRitorno":null,"contoAddebito":null,"dataEsecuzionePagamento":null,"credenzialiPagatore":null,"soggettoVersante":{"tipo":"F","identificativo":"MROSSI88A53G942M","anagrafica":"Mario Rossi","indirizzo":null,"civico":null,"cap":null,"localita":null,"provincia":null,"nazione":null,"email":"mail@mail.it","cellulare":null},"autenticazioneSoggetto":null,"pendenze":[{"idA2A":"Portale","idPendenza":"CdmdjmMiHc","idDominio":"01226000634","idUnitaOperativa":null,"descrizione":"Pagamento Lampade Votive","soggettoPagatore":{"tipo":"F","identificativo":"MROSSI88A53G942M","anagrafica":"Mario Rossi","indirizzo":null,"civico":null,"cap":null,"localita":null,"provincia":null,"nazione":null,"email":"mail@mail.it","cellulare":null},"importo":20.0,"numeroAvviso":null,"tassonomiaAvviso":null,"dataValidita":null,"dataScadenza":null,"annoRiferimento":null,"cartellaPagamento":null,"datiAllegati":null,"voci":[{"idVocePendenza":"CdmdjmMiHc_1","importo":20.0,"descrizione":"Pagamento Lampade Votive","datiAllegati":null,"dettaglioVoce":{"ibanAccredito":"IT29M0306940273100000046008","ibanAppoggio":null,"tipoContabilita":"CAPITOLO","codiceContabilita":"LAMPADE_VOTIVE"}}]}]}
 in risposta ho:
{"detail":"La verifica del versamento ha dato esito PAA_PAGAMENTO_SCONOSCIUTO","status":422,"title":"Unprocessable Entity","type":"https://govpay.readthedocs.io/it/latest/integrazione/errori/errore-http-422.html"}
 l'url è:
https://mio.dominio.it:443/govpay/frontend/api/pagamento/rs/basic/v2/pagamenti?modalitaAvvisaturaDigitale=Immediata
 se invece l'idPendenza è avvalorato con uno già presente in govpay ho esito positivo

**Comment by nardil** [comment]
Ciao Alessandra,

puoi aggiornare alla versione? La richiesta che stai inviando non e' valida. Avresti dovuto ricevere un errore di sintassi

**Comment by acoviello** [comment]
Purtroppo non riesco ad aggiornare govpay all'ultima versione nell'immediato. Ad ogni modo se dal portale  un cittadino volesse fare un pagamento spontaneo i passaggi che bisogna fare sono:
- cittadino compila la form con i dati del pagamento (anagrafica, importo, causale etc)
-  il portale richiamare  la post https://mio.dominio.it:443/govpay/frontend/api/pagamento/rs/basic/v2/pagamenti?modalitaAvvisaturaDigitale=Immediata
 in modo che govpay crei  al volo una pendenza
- successivamente il cittadino sceglie i metodo di pagamento

oppure bisogna fare questi passaggi: 

-  cittadino compila la form con i dati del pagamento (anagrafica, importo, causale etc)
-  il portale tramite una post carica una pendenza su govpay 
- il portale richiama  la post https://mio.dominio.it:443/govpay/frontend/api/pagamento/rs/basic/v2/pagamenti?modalitaAvvisaturaDigitale=Immediata passandogli l'id della pendenza creata al passo precedente
- successivamente il cittadino sceglie i metodo di pagamento

**Comment by nardil** [comment]
Ciao Alessandra,
sono validi entrambi i modelli, chiaramente il primo, in caso di pagamento spontaneo, risulta più efficiente. Puoi vederne [un esempio](https://govpay.readthedocs.io/it/3.1.x/integrazione/pagamentiente/index.html#avvio-del-pagamento) nel manuale di GovPay.

Ti faccio notare che il parametro di `modalitaAvvisaturaDigitale` è stato introdotto a seguito dell'emissione da parte di AgID delle specifiche del servizio di Avvisatura Digitale descritto nelle SANP 2.0, ma poi il servizio non è stato mai attivato da pagoPA, pertanto risulta non utilizzato. Siamo in attesa di sviluppi sul tema da parte di pagoPA per valutarne la dismissione.

E' molto più promettente in ottica di avvisatura al cittadino in forma digitale il progetto [IO](https://io.italia.it/) con il quale è già in corso di analisi l'integrazione di GovPay (#118)
