### ISSUE TITLE
Test modello 3 - bug importi con .00

### ISSUE THREAD

**Issue by acoviello** [link-it/GovPay#13]
1) caricamento pagamento in attesa con invocazione primitiva:gpCaricaVersamento -  IUV generato:000000000000141 - importo 300.0
HTTP Headers: 
	Accept: */*
	Authorization: Basic cHViYXBwMTpwYXNzd29yZA==
	cache-control: no-cache
	connection: Keep-Alive
	Content-Length: 1182
	content-type: text/xml; charset=UTF-8
	host: 127.0.0.1:6080
	pragma: no-cache
	SOAPAction: "gpCaricaVersamento"
	user-agent: Apache CXF 2.7.18
	x-forwarded-for: 172.16.171.198
	x-forwarded-host: govpay-test.regione.basilicata.it
	x-forwarded-server: govpay-test.regione.basilicata.it
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header/><soap:Body><ns2:gpCaricaVersamento xmlns:ns2="http://www.govpay.it/servizi/gpApp/" xmlns:ns3="http://www.govpay.it/servizi/pa/"><generaIuv>true</generaIuv><aggiornaSeEsiste>true</aggiornaSeEsiste><versamento><codApplicazione>PubApp1</codApplicazione><codVersamentoEnte>1464183452332</codVersamentoEnte><codDominio>80002950766</codDominio><debitore><codUnivoco>RSSMRA85T10A562S</codUnivoco><ragioneSociale>Rossi Mario</ragioneSociale><indirizzo>Viale dei Giardini</indirizzo><civico>99 Interno 1A</civico><cap>56017</cap><localita>San Giuliano Terme</localita><provincia>PZ</provincia><nazione>IT</nazione><email>MarioRossi@email.it</email><telefono>900900900</telefono><cellulare>333333333333</cellulare><fax>800800800</fax></debitore><importoTotale>300.0</importoTotale><dataScadenza>2016-10-31T00:00:00+01:00</dataScadenza><aggiornabile>false</aggiornabile><causale>Causale</causale><singoloVersamento><codSingoloVersamentoEnte>1464183452332_1</codSingoloVersamentoEnte><importo>300.0</importo><codTributo>BOLLO</codTributo></singoloVersamento></versamento></ns2:gpCaricaVersamento></soap:Body></soap:Envelope>
2016-05-25 15:39:06.596 | INFO  | it.govpay.web.ws.PagamentiTelematiciGPAppImpl:139 | 293ed84b7faf4ba0b29240fe47240421 | Richiesta operazione gpCaricaVersamento per il versamento (1464183452332) dell'applicazione (PubApp1) con generazione IUV (true)
2016-05-25 15:39:06.618 | INFO  | it.govpay.core.business.Versamento:86 | 293ed84b7faf4ba0b29240fe47240421 | Generato IUV [CodDominio: 80002950766][CodIuv: 000000000000141]
2016-05-25 15:39:06.620 | INFO  | it.govpay.core.business.Versamento:100 | 293ed84b7faf4ba0b29240fe47240421 | Versamento (1464183452332) dell'applicazione (PubApp1) inserito
2016-05-25 15:39:06.625 | TRACE | it.govpay.web.handler.MessageLoggingHandlerUtils:49 | 293ed84b7faf4ba0b29240fe47240421 | 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:gpCaricaVersamentoResponse xmlns:ns2="http://www.govpay.it/servizi/gpApp/" xmlns:ns3="http://www.govpay.it/servizi/pa/"><codOperazione>293ed84b7faf4ba0b29240fe47240421</codOperazione><codEsitoOperazione>OK</codEsitoOperazione><iuvGenerato><codApplicazione>PubApp1</codApplicazione><codVersamentoEnte>1464183452332</codVersamentoEnte><codDominio>80002950766</codDominio><iuv>000000000000141</iuv><qrCode>UEFHT1BBfDAwMnwwMTAwMDAwMDAwMDAwMDE0MXw4MDAwMjk1MDc2NnwzMDAwMA==</qrCode><barCode>NDE1ODAwMDI5NTA3NjY4MDIwMDEwMDAwMDAwMDAwMDAxNDEzOTAyMzAwMDA=</barCode></iuvGenerato></ns2:gpCaricaVersamentoResponse></soap:Body></soap:Envelope>

1) Primo tentativo da parte di SIA per la verifica del pagamento (problema relativo alle stringhe vuote nella tabella iban_accredito)

	HTTP Headers: 
	connection: Keep-Alive
	Content-Length: 1208
	content-type: text/xml;
	host: 127.0.0.1:6080
	SOAPAction: paaVerificaRPT
	spcoopdestinatario: RegioneBasilicata
	spcoopid: NodoDeiPagamentiDellaPATest_NodoDeiPagamentiDellaPATestSPCoopIT_1224147_2016-05-27_12:26
	spcoopmittente: NodoDeiPagamentiDellaPATest
	spcoopservizio: PagamentiTelematiciCCP6T
	spcooptipodestinatario: SPC
	spcooptipomittente: SPC
	spcooptiposervizio: SPC
	user-agent: Jakarta Commons-HttpClient/3.1-rc1
	x-forwarded-for: 172.18.17.227
	x-forwarded-host: govpay-test.regione.basilicata.it
	x-forwarded-server: govpay-test.regione.basilicata.it
<SOAP_ENV:Envelope xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP_ENV:Header><ppt:intestazionePPT xmlns:ppt="http://ws.pagamenti.telematici.gov/ppthead" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.pagamenti.telematici.gov/" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/">
         <identificativoIntermediarioPA>80002950766</identificativoIntermediarioPA>
         <identificativoStazioneIntermediarioPA>80002950766_01</identificativoStazioneIntermediarioPA>
         <identificativoDominio>80002950766</identificativoDominio>
         <identificativoUnivocoVersamento>000000000000141</identificativoUnivocoVersamento>
         <codiceContestoPagamento>CCPSIA001</codiceContestoPagamento>
      </ppt:intestazionePPT></SOAP_ENV:Header><SOAP_ENV:Body><ws:paaVerificaRPT xmlns:ws="http://ws.pagamenti.telematici.gov/" xmlns:ppt="http://ws.pagamenti.telematici.gov/ppthead" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/">
         <identificativoPSP>idPsp1</identificativoPSP>
      </ws:paaVerificaRPT></SOAP_ENV:Body></SOAP_ENV:Envelope>
2016-05-27 12:28:50.924 | INFO  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:313 | b5dffe92f7794039b53d58ad8623dd8c | Ricevuta richiesta di verifica RPT [80002950766][80002950766_01][80002950766][000000000000141][CCPSIA001]
2016-05-27 12:28:50.975 | TRACE | it.govpay.web.handler.MessageLoggingHandlerUtils:49 | b5dffe92f7794039b53d58ad8623dd8c | 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Marshalling Error: cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}' for type 'stBICIdentifier'.</faultstring></soap:Fault></soap:Body></soap:Envelope>

3) Impostando i valori della tabella iban_accredito a null il primo step di verifica è andato a buon fine:

HTTP Headers: 
	accept-encoding: gzip,deflate
	connection: Keep-Alive
	Content-Length: 1208
	content-type: text/plain; charset=UTF-8
	host: 127.0.0.1:6080
	user-agent: Apache-HttpClient/4.3.5 (java 1.5)
	x-forwarded-for: 172.16.170.222
	x-forwarded-host: govpay-test.regione.basilicata.it
	x-forwarded-server: govpay-test.regione.basilicata.it
<SOAP_ENV:Envelope xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP_ENV:Header><ppt:intestazionePPT xmlns:ppt="http://ws.pagamenti.telematici.gov/ppthead" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.pagamenti.telematici.gov/" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/">
         <identificativoIntermediarioPA>80002950766</identificativoIntermediarioPA>
         <identificativoStazioneIntermediarioPA>80002950766_01</identificativoStazioneIntermediarioPA>
         <identificativoDominio>80002950766</identificativoDominio>
         <identificativoUnivocoVersamento>000000000000141</identificativoUnivocoVersamento>
         <codiceContestoPagamento>CCPSIA001</codiceContestoPagamento>
      </ppt:intestazionePPT></SOAP_ENV:Header><SOAP_ENV:Body><ws:paaVerificaRPT xmlns:ws="http://ws.pagamenti.telematici.gov/" xmlns:ppt="http://ws.pagamenti.telematici.gov/ppthead" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/">
         <identificativoPSP>idPsp1</identificativoPSP>
      </ws:paaVerificaRPT></SOAP_ENV:Body></SOAP_ENV:Envelope>
2016-05-27 16:41:27.697 | INFO  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:313 | 2874f4af9d57444a80ff44db98159da8 | Ricevuta richiesta di verifica RPT [80002950766][80002950766_01][80002950766][000000000000141][CCPSIA001]
2016-05-27 16:41:27.726 | TRACE | it.govpay.web.handler.MessageLoggingHandlerUtils:49 | 2874f4af9d57444a80ff44db98159da8 | 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns5:paaVerificaRPTRisposta xmlns:ns5="http://ws.pagamenti.telematici.gov/" xmlns:ns2="http://www.digitpa.gov.it/schemas/2011/Pagamenti/" xmlns:ns3="http://ws.pagamenti.telematici.gov/ppthead" xmlns:ns4="http://www.digitpa.gov.it/schemas/2011/Pagamenti/Revoche/"><paaVerificaRPTRisposta><esito>OK</esito><datiPagamentoPA><importoSingoloVersamento>300.0</importoSingoloVersamento><ibanAccredito>IT79Q0542404297000011700994</ibanAccredito><enteBeneficiario><ns2:identificativoUnivocoBeneficiario><ns2:tipoIdentificativoUnivoco>G</ns2:tipoIdentificativoUnivoco><ns2:codiceIdentificativoUnivoco>80002950766</ns2:codiceIdentificativoUnivoco></ns2:identificativoUnivocoBeneficiario><ns2:denominazioneBeneficiario>Regione Basilicata</ns2:denominazioneBeneficiario><ns2:codiceUnitOperBeneficiario>EC</ns2:codiceUnitOperBeneficiario><ns2:indirizzoBeneficiario>Via V. Verrastro</ns2:indirizzoBeneficiario><ns2:capBeneficiario>85100</ns2:capBeneficiario><ns2:localitaBeneficiario>Potenza</ns2:localitaBeneficiario><ns2:provinciaBeneficiario>Potenza</ns2:provinciaBeneficiario><ns2:nazioneBeneficiario>IT</ns2:nazioneBeneficiario></enteBeneficiario><causaleVersamento>Causale</causaleVersamento></datiPagamentoPA></paaVerificaRPTRisposta></ns5:paaVerificaRPTRisposta></soap:Body></soap:Envelope>

4) Secondo step di attivazione da parte del sia con esito KO (l'importo risulta troncato a 300 euro):
HTTP Headers: 
	connection: Keep-Alive
	Content-Length: 1616
	content-type: text/xml;
	host: 127.0.0.1:6080
	SOAPAction: paaAttivaRPT
	spcoopdestinatario: RegioneBasilicata
	spcoopid: NodoDeiPagamentiDellaPATest_NodoDeiPagamentiDellaPATestSPCoopIT_1229091_2016-05-27_16:42
	spcoopmittente: NodoDeiPagamentiDellaPATest
	spcoopservizio: PagamentiTelematiciCCP6T
	spcooptipodestinatario: SPC
	spcooptipomittente: SPC
	spcooptiposervizio: SPC
	user-agent: Jakarta Commons-HttpClient/3.1-rc1
	x-forwarded-for: 172.18.17.227
	x-forwarded-host: govpay-test.regione.basilicata.it
	x-forwarded-server: govpay-test.regione.basilicata.it
<SOAP_ENV:Envelope xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP_ENV:Header><ppt:intestazionePPT xmlns:ppt="http://ws.pagamenti.telematici.gov/ppthead" xmlns:pag="http://www.digitpa.gov.it/schemas/2011/Pagamenti/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.pagamenti.telematici.gov/" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/">
         <identificativoIntermediarioPA>80002950766</identificativoIntermediarioPA>
         <identificativoStazioneIntermediarioPA>80002950766_01</identificativoStazioneIntermediarioPA>
         <identificativoDominio>80002950766</identificativoDominio>
         <identificativoUnivocoVersamento>000000000000141</identificativoUnivocoVersamento>
         <codiceContestoPagamento>CCPSIA003</codiceContestoPagamento>
      </ppt:intestazionePPT></SOAP_ENV:Header><SOAP_ENV:Body><ws:paaAttivaRPT xmlns:ws="http://ws.pagamenti.telematici.gov/" xmlns:pag="http://www.digitpa.gov.it/schemas/2011/Pagamenti/" xmlns:ppt="http://ws.pagamenti.telematici.gov/ppthead" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/">
         <identificativoPSP>idPsp1</identificativoPSP>
         <datiPagamentoPSP>
            <importoSingoloVersamento>300</importoSingoloVersamento>
         </datiPagamentoPSP>
         <identificativoIntermediarioPSP>idIntermediario1</identificativoIntermediarioPSP>
         <identificativoCanalePSP>idCanale13</identificativoCanalePSP>
      </ws:paaAttivaRPT></SOAP_ENV:Body></SOAP_ENV:Envelope>
2016-05-27 16:45:20.240 | INFO  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:112 | 661e61f272f048ff9654e6eee7ce50e9 | Ricevuta richiesta di attiva RPT [80002950766][80002950766_01][80002950766][000000000000141][CCPSIA003]
2016-05-27 16:45:20.251 | ERROR | it.govpay.web.ws.PagamentiTelematiciCCPImpl:485 | 661e61f272f048ff9654e6eee7ce50e9 | Rifiutata Attiva RPT con Fault PAA_ATTIVA_RPT_IMPORTO_NON_VALIDO
2016-05-27 16:45:20.255 | TRACE | it.govpay.web.handler.MessageLoggingHandlerUtils:49 | 661e61f272f048ff9654e6eee7ce50e9 | 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns5:paaAttivaRPTRisposta xmlns:ns5="http://ws.pagamenti.telematici.gov/" xmlns:ns2="http://www.digitpa.gov.it/schemas/2011/Pagamenti/" xmlns:ns3="http://ws.pagamenti.telematici.gov/ppthead" xmlns:ns4="http://www.digitpa.gov.it/schemas/2011/Pagamenti/Revoche/"><paaAttivaRPTRisposta><fault><faultCode>PAA_ATTIVA_RPT_IMPORTO_NON_VALIDO</faultCode><faultString>L'importo del pagamento in attesa non è congruente con il dato indicato dal PSP</faultString><id>80002950766</id></fault><esito>KO</esito></paaAttivaRPTRisposta></ns5:paaAttivaRPTRisposta></soap:Body></soap:Envelope>

N.B: I test con importi 12.91, 13.91, 500 sono andati tutti a buon fine, quindi sembrerebbe un problema solo di importi con .00

**Comment by nardil** [comment]
Verificato bug nella gestione del bic di accredito. Risolto in [GP-244] e portato in master: aebb1f1af2f676fb24007c0a22392fee3425f6bd
Verificato bug nella verifica degli importi. Aperto bug [GP-246]

**Comment by nardil** [comment]
Risolto in [GP-246] e portato in master: 0099c62
