### ISSUE TITLE
Errore avvio pagamento da numero avviso ed idDominio

### ISSUE THREAD

**Issue by acoviello** [link-it/govpay#132]
Sto provando ad effettuare una post per il pagamento di una pendenza precaricata su Govpay  e per il quale ho numero avviso e idDominio.
Chiamando la Post dei pagamenti ...frontend/api/pagamento/rs/basic/v2/pagamenti ed inserendo nel corpo della chiamata i valodi per idDominio e NumeroAvviso ho come risultato: 400 Bad Request e nel log govpay.log:
.._.Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "idPagatore" (class it.govpay.pagamento.v2.beans.NuovaPendenza), not marked as ignorable (15 known properties: "numeroAvviso", "dataValidita", "datiAllegati", "tassonomiaAvviso", "importo", "dataScadenza", "descrizione", "idUnitaOperativa", "idDominio", "idA2A", "idPendenza", "soggettoPagatore", "cartellaPagamento", "annoRiferimento", "voci"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: it.govpay.pagamento.v2.beans.NuovoPagamento["pendenze"]->it.govpay.pagamento.v2.beans.NuovaPendenza["idPagatore"])_

Se invece seguo l'alternativa di effettuare la post con idA2A e idPendenza la richiesta va a buon fine. In cosa sbaglio?

Grazie, 
Alessandra

**Comment by nardil** [comment]
Ciao Alessandra,
puoi riportare il json della richiesta? Puoi recuperarlo dal giornale degli eventi se e' abilitato il dump dei contenuti.

**Comment by acoviello** [comment]
ecco qui {
  "urlRitorno": "http://pagopa.publisys.it/pagonline/callback",
  "pendenze": [
    {
      "idDominio": "01226000634",
      "numeroAvviso": "300000000000000205",
      "idPagatore": "CVLLSN88A52G942M"
    }
  ]
}

**Comment by nardil** [comment]
Grazie,
puoi confermarmi che omettendo il parametro `idPagatore` la richiesta viene processata correttamente?

**Comment by acoviello** [comment]
Si si confermo

**Comment by nardil** [comment]
Il field corretto è `idDebitore` e, se passato, viene controllato che corrisponda con quello dell'intestatario della pendenza.
Nella versione 3.2 prevediamo di includere questa funzione tra quelle di hardening in modo da poter configurare il parametro come obbligatorio.

**Comment by acoviello** [comment]
Lorenzo, ho un dubbio su quanto mi hai scritto:
_Puoi recuperarlo dal giornale degli eventi se e' abilitato il dump dei contenuti._
In realtà il json della richiesta non l'ho reperito dal dump dei contenuti, anche se sembra essere abilitato, infatti se chiamo la get sulla configurazione del giornale ottengo:
{
    "interfacce": {
        "apiEnte": {
            "letture": {
                "log": "sempre",
                "dump": "sempre"
            },
            "scritture": {
                "log": "sempre",
                "dump": "sempre"
            }
        },
        "apiPagamento": {
            "letture": {
                "log": "sempre",
                "dump": "sempre"
            },
            "scritture": {
                "log": "sempre",
                "dump": "sempre"
            }
        },
        "apiRagioneria": {
            "letture": {
                "log": "sempre",
                "dump": "sempre"
            },
            "scritture": {
                "log": "sempre",
                "dump": "sempre"
            }
        },
        "apiBackoffice": {
            "letture": {
                "log": "sempre",
                "dump": "sempre"
            },
            "scritture": {
                "log": "sempre",
                "dump": "sempre"
            }
        },
        "apiPagoPA": {
            "letture": {
                "log": "sempre",
                "dump": "sempre"
            },
            "scritture": {
                "log": "sempre",
                "dump": "sempre"
            }
        }
    }
}
Sul cruscotto ho configurato la mia applicazione in questo modo:
Autorizzazioni Backoffice

Anagrafica Applicazioni:Lettura
Anagrafica Enti:Lettura
Anagrafica Operatori:Lettura
Anagrafica PagoPA:Lettura
Backoffice Pagamenti:Lettura, Scrittura
Backoffice Pendenze:Lettura, Scrittura
Backoffice Ragioneria:Lettura, Scrittura
Gestione Batch:Lettura, Scrittura
Giornale degli Eventi:Lettura, Scrittura
Nei vari file di log io non trovo i tracciati sui json delle chiamate rest nè le richieste e risposte all'invocazione delle primitive del nodoDeiPagamenti, che sulla vecchia versione 2.5.7 erano presenti sul file govpay_dump.log. Ho saltato qualche configurazione?
Grazie come sempre!

**Comment by nardil** [comment]
Ciao Alessandra,
errore mio, l'evento in caso di richiesta malformata non viene registrato nel giornale degli eventi, ma solo nel log se impostata la proprieta `it.govpay.context.savataggioDumpSuFile.enabled=true` (gia cosi per configurazione di default)

Con la configurazione di default del giornale, quando effettui un pagamento dovresti vedere registrati i seguenti eventi:

![Schermata da 2019-11-14 12-08-57](https://user-images.githubusercontent.com/12340738/68853018-51e73c00-06d9-11ea-98bb-f826bfb41ea2.png)

Entrando nel dettaglio puoi visualizzare i dati dell'evento ed eventualmente anche il contenuto della richiesta e della risposta (al momento esposti come raw in base64, ma sono in valutazione soluzioni per integrare la visualizzazione grafica dei contenuti)

L'estratto di configurazione che mi hai inviato tu sono invece i diritti che hai dato all'applicazione sulle API di Backoffice, non la configurazione del giornale degli eventi la cui integrazione grafica e' attualmente in sviluppo in #127 .

**Comment by nardil** [comment]
Scusa, ho avuto un abbaglio :)

In caso di errore di sintassi l'evento e' registrato:

![Schermata da 2019-11-14 12-29-47](https://user-images.githubusercontent.com/12340738/68853695-e1d9b580-06da-11ea-9c86-55d40901d511.png)

Dal dettaglio si evince la causa del rifiuto:

![Schermata da 2019-11-14 12-30-44](https://user-images.githubusercontent.com/12340738/68853760-fe75ed80-06da-11ea-9c20-57877e669751.png)

Ed aprendo la `Vista completa` puoi consultare anche i messaggi di richiesta e risposta (codificati in base64):

![Schermata da 2019-11-14 12-32-28](https://user-images.githubusercontent.com/12340738/68853904-4268f280-06db-11ea-9f2f-c595799e6349.png)

**Comment by nardil** [comment]
> L'estratto di configurazione che mi hai inviato tu sono invece i diritti che hai dato all'applicazione sulle API di Backoffice, non la configurazione del giornale degli eventi la cui integrazione grafica e' attualmente in sviluppo in #127 .

Preciso meglio: il primo estratto che mi hai inviato è la configurazione del giornale degli eventi che stiamo rendendo consultabile e modificabile dal cruscotto con #127, mentre il secondo estratto sono le autorizzazioni dell'applicazione, che non influenzano quali eventi vengono registrati sul giornale ne' quali eventi puoi consultare con la tua utenza personale (che ha i suoi diritti specifici)

**Comment by acoviello** [comment]
Ok grazie, attualmente ho la versione 3.1.0 RC1 e non vedo la voce "vista completa" nel dettaglio di un evento del giornale, provvederò ad aggiornarla.
Inoltre ho scaricato l'installer dell'ultima release 3.1.1 e aprendo il compilato .ear nel file di properties di govpay trovo la voce it.govpay.context.savataggioDumpSuFile.enabled=false così come per la versione 3.1.0 RC1 mi servirebbe estrarre  le chiamate da govpay  verso il nodo dei pagamenti attulmente non le vedo nei file di log. Sarebbe possibile aggiornare l'installer?

**Comment by nardil** [comment]
Puoi modificare il valore delle properties in tre modi (di seguito elencati in ordine di priorita):
1. Impostandola come property della JVM
2. Impostandola nel file govpay.properties nella cartella di lavoro indicata nell'installer
3. Modificando il govpay.properties interno all'EAR

**Comment by acoviello** [comment]
Ok perfetto, l'ho impostata come property della JVM e adesso vedo le chiamate nel file govpay_dump.log.

Grazie mille per il supporto!
