### ISSUE TITLE
Estrazione tabella delle controparti

### ISSUE THREAD

**Issue by acoviello** [link-it/govpay#141]
Per quanto riguarda l'estrazione della tabella delle controparti dalla gui Govpay, è possibile farla anche nella versione 3.x ? Fino alla v 2.7 era possibile scaricare dal dettaglio del Dominio gli xml relativi all'informativa e gli iban.

Grazie, 
Alessandra

**Comment by nardil** [comment]
Ciao Alessandra,
no, questo servizio non è stato mantenuto, ma possiamo però rivedere la decisione... 

Nelle versioni 2.x era stato introdotto in quanto la tabella delle controparti era necessaria per effettuare il censimento dei conti di accredito a pagoPA, ma adesso questa funzionalità viene fornita dal Portale delle Adesioni ai Referenti dei Pagamenti.

E' invece ancora un servizio necessario? In quale scenario?

**Comment by acoviello** [comment]
Ciao Lorenzo, 
in realtà è richiesto nella compilazione dei test forniti da AgID , bisogna fornire evidenze sull'invocazione della primitiva nodoPAChiediInformativaPA assieme anche alle altre operazioni quali, ad esempio, nodoChiediListaPendentiRPT.

**Comment by nardil** [comment]
Il test case WS-5.7.1 è di tipo OSP in tutti gli ambienti, pertanto non sei tenuta a fornirne le evidenze

> OSP (obbligatoria se presente), ovvero obbligatorio solo se la funzionalità in esame è
tra quelle previste dall'Ente Creditore;

**Comment by acoviello** [comment]
Il Piano dei test per l'Ente Creditore da compilare è di giugno 2019 ed il test case è EC-AUX-04 fa riferimento alle funzionalità ausiliari (SANP 2.2.x - Sezione III Capitolo 13 - §13.2.5), a differenza dei precedenti template  non ci sono indicazioni sull'obbligatorietà o meno dell'esecuzione del test, se può esserti utile te lo invio

**Comment by nardil** [comment]
Pardon, avevo seguito la documentazione ufficiale:

https://www.pagopa.gov.it/it/pubbliche-amministrazioni/documentazione-tecnica/

Anche nella nuova versione i test da realizzare e documentare sono solo quelli relativi ai servizi effettivamente utilizzati (quella versione del modello, compilata omettendo il test EC-AUX-04, EC-BKO-01, EC-BKO-02, EC-BKO-05, è stata accettata da pagoPA).

Ti consiglio comunque di chiedere conferma ufficiale a pagoPA su quali test siano mandatori ai fini dell'adesione, cosi da valutare con maggior sicurezza la necessità del servizio.

**Comment by acoviello** [comment]
Ok, ho appena scritto al supporto pagoPA in modo da essere certi su cosa è ad oggi obbligatorio.
Ti scrivo appena ho notizie.
Grazie, 
Alessandra
