### ISSUE TITLE
Tassonomia della pendenza

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#142]
**Descrizione del Bug**
Risulta mancante il campo tassonomia nella pendenza come definita nelle API Pagamento, Pendenze e Ragioneria v2, mentre è presente nelle API Backoffice

**Risultato atteso:**
Aggiungere alle api v2 il field tassonomia dove mancante.

**Ambiente:**
 - GovPay:  3.2.0

**Comment by pintorig** [comment]
Aggiunta gestione del campo Tassonomia di una Pendenza nelle API V2 Pagamento, Pendenze e Ragioneria
