### ISSUE TITLE
Perfezionamento form di caricamento tracciati CSV

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#144]
**Necessità:**
Nella form di caricamento del tracciato CSV mostrare nella lista dei tipi pendenza le sole tipologie che presentano in configurazione la trasformazione.

Inoltre consentire la spedizione del tracciato anche senza selezionare un tipo pendenza, andando ad utilizzare il parser di default.

**Soluzione:**
Aggiungere ai filtri gia' utilizzati per avere la lista dei tipi pendenza `trasformazione=true` e rendere il campo della form `Tipo pendenza` opzionale.

Aggiungere lato backoffice il supporto al filtro `trasformazione` che se valorizzato esclude i tipi pendenza che non hanno configurata la trasformazione e la possibilita' di inviare i tracciati alla risorsa `/pendenze/tracciati/{idDominio}` senza indicare il tipoPendenza

**Comment by pintorig** [comment]
Aggiunto filtro 'trasformazione' per la ricerca dei tipiPendenza di un dominio. Aggiunti case test per il controllo del template di trasformazione utilizzato durante il caricamento dei tracciati in formato CSV.
