### ISSUE TITLE
Filtri su riscossioni per individuare i raggruppamenti delle quadrature

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#145]
**Necessità:**
Possibilita' di individuare gli elementi raggruppati dal servizio di quadratura.Il servizio di quadrature delle riscossioni consente di effettuare dei raggruppamenti ed il servizio riscossioni consente di vederne il dettaglio delle singole entita', ma mancano i filtri per alcuni raggruppamenti.

**Soluzione:**
Verificare la presenza dei filtri:
- Divisione
- Direzione
- dataDa
- dataA
- Tassonomia
- TipoPendenza
- Dominio
- UnitaOperativa
- Tipo (riscossione)
- Applicazione

**Comment by pintorig** [comment]
Nelle API-Backoffice sono stati allineati i filtri per il servizio Riscossioni con quelli presenti nel servizio QuadratureRiscossioni.
