### ISSUE TITLE
Filtri su quadrature influenzano le modalita' di raggruppamento

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#146]
**Descrizione del Bug**
Il servizio di quadratura mostra le riscossioni correttamente raggruppate per i gruppi indicati. Quando ai gruppi si aggiungono filtri, questi vengono interpretati anche come raggruppamenti.

**Risultato atteso:**
L'aggiunta di filtri non deve modificare le modalità di raggruppamento, ma solo risurre l'insieme di elemento oggetto del raggruppamento

**Ambiente:**
 - GovPay: 3.2.x

**Comment by pintorig** [comment]
Corretta segnalazione sul numero di gruppi prodotti quando si impostano i filtri di ricerca del servizio QuadratureRiscossioni di API-Backoffice.
