### ISSUE TITLE
Salvataggio del tipo pendenza in dominio errato

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#147]
**Descrizione del Bug**
Il salvataggio di una pendenza associata ad un dominio senza impostare alcun valore custom non funziona correttamente.

La richiesta viene prodotta malformata dal cruscotto poichè il campo `codificaIUV` viene valorizzato come stringa vuota invece che come `null`.

La richiesta viene memorizzata in modo errato, poichè in tabella, in alcuni campi (vedi immagine) viene salvata la stringa `null` piuttosto del nullvalue.

![Schermata da 2019-12-04 22-47-48](https://user-images.githubusercontent.com/12340738/70184635-83579400-16e8-11ea-97a9-848cb967e612.png)

**Ambiente:**
 - GovPay: 3.2.x

**Comment by pintorig** [comment]
Corretto salvataggio dei campi vuoti per i TipiPendenza e TipiPendenzaDominio.
