### ISSUE TITLE
Reset Cache distribuito

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#151]
**Necessità:**
E' necessario poter resettare la cache dal cruscotto esplicitamente e nel caso di installazioni multinodo che tale reset si propaghi su tutti i nodi.

**Soluzione:**
Memorizzare la data di reset globale all'interno del DB condiviso tra i nodi.
In ogni nodo memorizzare la data di reset locale.
La procedura deve prevedere un batch da eseguire in ogni nodo che tramite un confronto tra la data di reset locale e globale, decide se invocare la procedura di reset della cache in locale.
Appoggiarsi all'operazione gia' esposta nelle API-Backoffice per fare in modo di aggiornare la data di reset globale.  

**Note:**
Appoggiarsi alla tabella dei batch per memorizzare la data di reset globale.
L'attuale procedura che resetta la cache ogni due ore dovra' aggiornare anche la data di reset globale.

**Comment by nardil** [comment]
@simo-git  Aggiungere l'operazione "Reset cache" tra le voci di Manutenzione che esegue una `GET /operazioni/resetCacheAnagrafica`
