### ISSUE TITLE
Supporto autenticazione per sessione

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#154]
**Necessità:**
Aggiungere il supporto all'autenticazione per sessione.

**Soluzione:**
Aggiungere un endpoint che consenta di stabilire una sessione autenticata valida per le API di GovPay

> /govpay/frontend/api/user/rs/spid/v1/login?redirectURL=TARGET_URL

Il parametro _redirectURL_ deve essere utilizzato per indicare la URL dove si vuole essere ricondotti in caso di autenticazione completata con successo.

Sara' possibile utilizzare la nuova modalita' di autenticazione in tutte le API di Govpay che dovranno esporre i servizi sotto il path _'/session'_:
- [x] API-Backoffice
- [x] API-Pagamento

La nuova _API-User_ dovra' esporre tutte le modalita' di autenticazione attualmente previste su Govpay:
- [x] SPID

Utilizzare il file _jboss-all.xml_ per la condivisione della sessione tra le API:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss umlns="urn:jboss:1.0">  
    <shared-session-config xmlns="urn:jboss:shared-session-config:1.0">  
        <session-config>  
            <session-timeout>${it.govpay.sharedSessionConfig.session.timeout}</session-timeout>  
            <cookie-config>  
                <path>${it.govpay.sharedSessionConfig.cookie.path}</path>  
                <name>${it.govpay.sharedSessionConfig.cookie.name}</name>  
		<domain>${it.govpay.sharedSessionConfig.cookie.domain}</domain>
            </cookie-config>  
        </session-config>  
    </shared-session-config>  
</jboss>
```
dando la possibilita' di configurare le varie opzioni in fase di compilazione dell'ear:

- _it.govpay.sharedSessionConfig.session.timeout_: durata della sessione in minuti;
- _it.govpay.sharedSessionConfig.cookie.path_: path del cookie di sessione;
- _it.govpay.sharedSessionConfig.cookie.name_: nome del cookie di sessione;
- _it.govpay.sharedSessionConfig.cookie.domain_: domain del cookie di sessione;

**Note:**
Le nuove modalita' di autenticazione dovranno essere configurabili in fase di creazione dell'ear come avviene attualmente.

**Comment by nardil** [comment]
Modificare la gestione della redirezione dell'utente al termine della sessione

> > /govpay/frontend/api/user/rs/spid/v1/login?redirectURL=TARGET_URL
> 
> Il parametro _redirectURL_ deve essere utilizzato per indicare la URL dove si vuole essere ricondotti in caso di autenticazione completata con successo.

Prevedere una URL di questa forma:

`/govpay/frontend/api/user/rs/spid/v1/login/{URL-ID}`

e nel file `govpay.properties` una proprieta' con nome:

`it.govpay.login-redirect.{URL-ID}=https://...`

che sara' utilizzata da GovPay per gestire il redirect. Nell'eventualità che non venga configurato il redirect, viene ritornato un errore HTTP 404
