### ISSUE TITLE
Problema invocazione da AGID servizio RT

### ISSUE THREAD

**Issue by argomauro** [link-it/govpay#164]
Ciao Lorenzo, abbiamo configurato un ambiente che stiamo cercando di qualificare come piattaforma per un nostro Comune. Abbiamo seguito la guida e quanto da te suggerito nella Issue 80 per quanto riguarda l'installazione e configurazione dei certificati ed infatti quando siamo noi ad avviare il processo di comunicazione con AGID e a sottomettere un pagamento il giro si conclude correttamente. Abbiamo però un problema quando sono loro che provano ad invocarci e più precisamente quando provano ad invocare il servizio https://{dominio}/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl.
Il server, crediamo l'application server, risponde in questo modo:
{"categoria":"AUTORIZZAZIONE","codice":"401","descrizione":"Richiesta non autorizzata","dettaglio":"Full authentication is required to access this resource"}
La nostra configurazione prevede un Apache configurato come web server a monte del Wildfly 11 di Govpay.
Grazie
Maurizio

**Comment by nardil** [comment]
Ciao @argomauro , 

se non lo avete fatto dovreste configurare Apache per propagare le informazioni del certificato client che ha invocato il servizio, ad esempio usando il connettore ajp:

```
<VirtualHost *:443>
  ....
  SSLOptions +StdEnvVars +ExportCertData
  ....
  <Location /govpay/govpay/frontend/api/pagopa/>
     SSLVerifyClient require
     ProxyPass  /govpay/govpay/frontend/api/pagopa/ ajp://127.0.0.1:9009/govpay/govpay/frontend/api/pagopa/
  </Location>
  ....
</VirtualHost>
```

nella configurazione del connettore pagoPA dell'intermediario dovete poi indicare come `principal` il Subject del certificato che il Nodo dei Pagamenti usa per contattarvi.

**Comment by argomauro** [comment]
Ciao @nardil ho configurato il sistema seguendo le tue indicazioni ed ora l'errore che mi restituisce Apache è di tipo 403. In particolare l'errore che mi restituisce adesso è Errore: 193.203.229.21 - - [29/Jan/2020:18:16:20 +0100] "POST /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice HTTP/1.1" 403 -
L'attuale configurazione di Apache è la seguente:
<Location /govpay/frontend/api/pagopa/>
             SSLVerifyClient require
             SSLVerifyDepth 10
             SSLOptions +StdEnvVars +ExportCertData
             SSLCACertificatePath /etc/httpd/certificates/pagopa.publisys.it/2019/CADIR/
            ProxyPass  http://srv-pagopa:8080/govpay/frontend/api/pagopa/
        </Location>
Ed ho configurato il certificato sotto il TRUSTSTORE di Apache oltre che sotto l'applicazione
