### ISSUE TITLE
Servizio RPP con sommario della pendenza associata

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#168]
**Necessità:**
Interrogando il servizio `rpp` si ottiene la lista delle transazioni di pagamento, con RPT ed RT scambiate con il nodo, ma non sono disponibili le informazioni della pendenza oggetto di pagamento, ma solo la URL dove acquisirle.

**Soluzione:**
Sostituire la URL al dettaglio della pendenza con il sommario della stessa

**Comment by pintorig** [comment]
Realizzare la modifica verra' nelle seguenti API:
-[ ] Backoffice V1;
-[ ] Pagamento V2;
-[ ] Pendenze V2;

Implementare la nuova funzionalita' nel branch: `feature/168_servizio_rpp_con_sommario_della_pendenza_associata`

Utilizza la seguente vista:
```sql
CREATE VIEW v_rpt_versamenti AS
 SELECT 
  rpt.*
  versamenti.*
FROM rpt JOIN versamenti ON rpt.id_versamento = versamenti.id;
```
I filtri e le restrizioni applicate nella versione attuale del servizio dovranno restare invariati.
