### ISSUE TITLE
Test modello 1 - bug pagamento con carrello 

### ISSUE THREAD

**Issue by acoviello** [link-it/GovPay#17]
Invocando il metodo gpAvviaTransazionePagamento con un codice WISP generato dal portale WISP predisposta per l'ambiente con emulatori (come primitiva ho inserito nodoInviaCarrelloRPT ) ottengo la seguente risposta:

<?xml version='1.0' encoding='UTF-8'?><SOAP_ENV:Envelope xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP_ENV:Body><ns4:nodoInviaCarrelloRPTRisposta xmlns:ns4="http://ws.pagamenti.telematici.gov/" xmlns:ns3="http://ws.pagamenti.telematici.gov/ppthead" xmlns:SOAP_ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><esitoComplessivoOperazione>KO</esitoComplessivoOperazione><listaErroriRPT><fault><faultCode>PPT_TIPOFIRMA_SCONOSCIUTO</faultCode><faultString>Il campo tipoFirma non corrisponde ad alcun valore previsto.</faultString><id>NodoDeiPagamentiSPC</id><description>Errore in Carrello [9d5ec7ada7b6466d86e1593bc32fef79] -  RPT [idDominio=80002950766/IUV=RF40000000000000031/CCP=n/a]: Firma non valida:0</description><serial>1</serial></fault><fault><faultCode>PPT_TIPOFIRMA_SCONOSCIUTO</faultCode><faultString>Il campo tipoFirma non corrisponde ad alcun valore previsto.</faultString><id>NodoDeiPagamentiSPC</id><description>Errore in Carrello [9d5ec7ada7b6466d86e1593bc32fef79] -  RPT [idDominio=80002950766/IUV=RF13000000000000032/CCP=n/a]: Firma non valida:0</description><serial>2</serial></fault></listaErroriRPT></ns4:nodoInviaCarrelloRPTRisposta></SOAP_ENV:Body></SOAP_ENV:Envelope>

Sulla Console ho provato anche ad associare una diversa tipologia di firma richiesta , tipo 1 cades, ma restituisce sempre un fault bean con codice PPT_TIPOFIRMA_SCONOSCIUTO

**Comment by nardil** [comment]
L'implementazione del nodo viola la specifica aspettandosi un TIPO FIRMA vuoto nel caso di nessuna firma (invece che 0 come indicato nelle SANP).

Aperto branch GP-254 per la risoluzione.

**Comment by nardil** [comment]
@acoviello Abbiamo implementato il fix. Puoi confermare la risoluzione? 

SHA: c42dcea

**Comment by nardil** [comment]
Confermata. Si procede al merge.
