### ISSUE TITLE
Estendere la sintassi ammessa dei codici pendenza e tributo con il carattere `.`

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#172]
**Necessità:**
Una modalita' di censimento delle tipologie pendenza e tributo prevede l'uso della codifica SIOPE+, che risulta non applicabile a causa della presenza del carattere punto non prevista dalla sintassi GovPay

**Soluzione:**
Modificare la regex dall'attuale `^[a-zA-Z0-9\\-_]{1,35}$` a `^[a-zA-Z0-9\\-_\\.]{1,35}$`

**Note:**
Aggiornare sia lo yaml che il validatore sia v1 che v2. Incrementare la minor version delle api.

**Comment by nardil** [comment]
Creato branch di sviluppo: feature/172_estendere_la_sintassi_ammessa_dei_codici_pendenza_e_tributo_con_il_punto

**Comment by pintorig** [comment]
9ba362df9
Allineato pattern di validazione di tipologie pendenza e tributi previsti per la codifica SIOPE+. 
Unificato validatore Pendenza e VocePendenza utilizzato da tutte le API. 
Allineati schemi yaml delle API per esporre i nuovi pattern.
