### ISSUE TITLE
API Backoffice GET  ​/avvisi​/{idDominio}​/{numeroAvviso} Avviso di pagamento: ritornare idPendenza ?

### ISSUE THREAD

**Issue by andrespada** [link-it/govpay#174]
Attualmente questa API non ritorna idPendenza.
Non riusciamo quindi ad ottenere alcuni dati che ci servono per adeguare la nostra attuale implementazione alla nuova versione di Govpay.
In documentazione troviamo una API analoga in API Applicazioni GET /avvisi/{idDomino}/{iuv}, che ritorna molte più info e tra queste idPendenza, ma non capiamo come si determina/configura il Base Url. Inoltre, se ben capiamo, queste API servono per essere esposte direttamente all'ente creditore, che non è il nostro caso.
Grazie 
Andrea Spada FORJ

**Comment by nardil** [comment]
Aggiungere alle API Backoffice e API Applicazioni la risorsa `GET /pendenze/byAvviso/{idDomino}/{numeroAvviso}` che ritorna la pendenza associata individuata dal riferimento avviso fornito, fermo restando l'applicazione delle policy di autorizzazione previste per la risorsa `GET /pendenze/{idA2A}/{idPendenza}`.

**Comment by nardil** [comment]
feature: classpath:test/api/backoffice/v1/pendenze/get/pendenze-get-operatori.feature
scenarios: 240 | passed: 238 | failed:  2 | time: 448,8396
