### ISSUE TITLE
Invocazione primitive: nodoChiediCopiaRT e nodoChiediStatoRPT

### ISSUE THREAD

**Issue by argomauro** [link-it/govpay#180]
CIao Lorenzo, sto provando a continuare i test per il nostro ambiente e non sono riuscito a capire come scatenare gli eventi , riportati in oggetto, da Govpay.
Potresti darmi qualche indicazione gentilmente? Grazie
P.S: sto utilizzando la versione 3.1.1

Maurizio

**Comment by nardil** [comment]
Ciao Maurizio,
le primitive in questione sono utilizzate nel caso ci siano pagamenti pendenti per i quali GovPay individua la necessita' di attivare le strategie di recupero. Queste situazioni si realizzano in presenza di anomalie che eventualmente si possono ricreare artificialmente. 

Prima di darti indicazioni in merito ti chiedo: come mai hai questa necessita'?

**Comment by argomauro** [comment]
Ciao e grazie come sempre del rapido riscontro.
Nei test di collaudo ci sono due casi d'uso dove richiedono di riportare le evidenze dell'invocazione di queste primitive ed io ne ho trovate solo due e di vecchia data per cui mi chiedevo se ci fosse un modo funzione per scatenarne l'invocazione.

**Comment by nardil** [comment]
Procedi in questo modo:

1. Esegui un pagamento senza successo e recupera `idDominio`, `IUV` e `CCP`
1. Accedi al database di GovPay ed effettua la seguente query: `update rpt set stato='RPT_ACCETTATA_NODO' where cod_dominio='{idDominio}' and iuv='{IUV}' and ccp='{CCP}';`
1. Sempre dal cruscotto, vai nella sezione Manutenzione e avvia il Recupero pagamenti pendenti
1. Al termine del processo, nel giornale degli eventi dovresti trovare le primitive `nodoChiediListaPendenti`, `nodoChiediStatoRPT` e `nodoChiediCopiaRT`

**Comment by argomauro** [comment]
Grazie mille per le info, le utilizzerò subito.
Maurizio
