### ISSUE TITLE
Filtro dataRptA non funzionante

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#181]
**Descrizione del Bug**
Filtro `dataRptA` per la risorsa `/rpp` non correttamente funzionante

**Come riprodurlo:**
`/govpay/backend/api/backoffice/rs/basic/v1/rpp?pagina=1&risultatiPerPagina=25&dataRptDa=2020-03-04&dataRptA=2020-03-05`

I risultati non presentano gli elementi del 2020-03-05.

**Risultato atteso:**
I risultati devono comprendere quelli nella data `dataRptDa`

**Ambiente:**
 - GovPay:  3.2.0]

**Note aggiuntive:**
Verificare il comportamento anche per gli altri filtri sulle date

**Comment by pintorig** [comment]
Riportate modifiche effettuate nei branch 3.2.x e 3.3.x.
