### ISSUE TITLE
Errore accesso risorse con CCP=n/a

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#183]
**Descrizione del Bug**
Quando si scarica il resoconto di un pagamento spontaneo, ovvero con `ccp` valorizzato a `n/a` il cruscotto da errore.

Questo accade perche' non viene gestito correttamente il valore del parametro `ccp` dal servizio. Infatti il cruscotto richiama la risorsa `/rpp/01234567890/RF90000000000000000000004/n%2Fa/rpt` che restituisce un 404, mentre funziona richiamando la risorsa come `/rpp/01234567890/RF90000000000000000000004/n/a/rpt`. 

Risulta quindi che se lo slash viene passato codificato (come e' corretto che sia) questo non viene gestito correttamente.

**Comment by nardil** [comment]
Non si e' riusciti a riprodurre il problema in ambiente di sviluppo. La problematica non e' relativa a GovPay poiche' le richieste in questione non arrivano all'applicazione.

@simo-git  Procediamo ad aggirare il problema modificando il cruscotto in modo che il parametro `ccp`, quando valorizzato ad `n/a`, non venga encodato.

**Comment by simo-git** [comment]
Suggerirei di evitare la limitazione puntuale e non eseguire l'encoding per i valori che contengono il carattere / . 
Nel caso, la stessa logica può essere applicata ovunque ci sia una codifica di una stringa che serve per creare la url completa?

**Comment by nardil** [comment]
La presenza dello `/` non codificato in un path parameter deve essere opportunamente prevista dal servizio, come e' stato fatto per il valore `n/a` del CCP, pertanto la gestione non puo' essere generalizzata.
