### ISSUE TITLE
Anomalie in fase di accreditamento

### ISSUE THREAD

**Issue by argomauro** [link-it/govpay#186]
Ciao Lorenzo, ho sottomesso il primo verbale in ambiente di Test a pagoPA e mi sono state fatte alcune osservazioni che volevo condividere (io sto usando sempre la versione 3.1.1), almeno per capire se mi serve un salto di versione oppure se sono semplici errori di configurazione. Spero tu possa darmi un riscontro.

- La prima legata alla "causale del versamento" riportata nelle stampe e nelle email che differisce da quella indicata nella RPT 
![image](https://user-images.githubusercontent.com/13645352/77305010-97ee8500-6cf5-11ea-9212-090a5764ce7b.png)

- La seconda è nell'esposizione del CCP (Codice Contesto Pagamento) di cui, nella stampa pdf della ricevuta manca sempre l'ultimo carattere 
![image](https://user-images.githubusercontent.com/13645352/77305104-c0767f00-6cf5-11ea-8a72-68c2c9e1d81e.png)

- La terza è che le RPT "utilizzate" non sono mai "universali". Ma questa non l'ho proprio decodificata come osservazione

Grazie
Maurizio

**Comment by argomauro** [comment]
OK, mando subito una email. Grazie del feedback.

**Comment by argomauro** [comment]
Ciao Lorenzo, ti riporto la risposta per intero perchè credo che alla fine facciano riferimento alla modalità di esecuzione dei test e la disponibilità di un altro IBAN , seppur non obbligatorio, come conto di appoggio. Ora come questo si possa definire "UNIVERSALE" ancora mi sfugge...

"
Buongiorno, 
nel piano di test viene richiesto di fare un carrello di RPT (almeno 2) "universali".
Per RPT "universale" si intende che l’EC deve seguire le seguenti indicazioni per rendere la RPT utilizzabile da ogni PSP aderente al
sistema pagoPA.

Per la regolazione del pagamento associato alla RPT, l’EC valorizza il dato ibanAccredito della
struttura datiSingoloVersamento della RPT con codice IBAN relativo al conte aperto presso la propria
banca tesoriera/cassiera.

Nel caso che l’EC disponga di un conto aperto presso Poste Italiane e abbia valorizzato il dato
ibanAccredito con un IBAN bancario, in osservanza di quanto previsto dalle Linee guida, valorizza
il dato ibanAppoggio della struttura datiSingoloVersamento della RPT con il codice IBAN del
predetto conto postale.

In ogni caso l’EC cura che i conti indicati come ibanAccredito e ibanAppoggio siano relativi a due
diversi prestatori di servizi di pagamento.

E' altresì vero che per quanto riguarda ibanAppoggio e bicAppoggio nello XSD della RPT il dato è
facoltativo per gestire il caso in cui l’EC effettivamente non disponga di un conto corrente
alternativo. 

Nei test EC-PEC-01 e EC-PEC-02 viene indicato che L'EC sottomette al NodoSPC un carrello di RPT (almeno 2 e di tipo “universale”) mediante la primitiva nodoInviaCarrelloRPT

Da tutte queste considerazioni è nata la segnalazione di utilizzare delle RPT "universali". 

La cosa comunque molto più importante che ci preme sapere è se voi utilizzate WISP 2.0 nativo oppure l'emulato. 

Cordiali Saluti
"

**Comment by nardil** [comment]
Non mi sembra abbiano dato indicazioni sul perché le RPT emesse da GovPay non dovrebbero essere universali.

Comunque:
> La cosa comunque molto più importante che ci preme sapere è se voi utilizzate WISP 2.0 nativo oppure l'emulato.

GovPay utilizza il WISP 2.0 nativo.

**Comment by argomauro** [comment]
Non era chiaro neanche a me...almeno adesso mi sento meno solo :-D. Credo
che fondamentalmente vogliano che si faccia quel tipo di test indicando
anche un IBAN di appoggio, ma sul discorso dell'universalità...mi sfugge
ancora.
Grazie del supporto
Maurizio

Il giorno gio 26 mar 2020 alle ore 16:00 Lorenzo Nardi <
notifications@github.com> ha scritto:

**Comment by nardil** [comment]
La stampa della ricevuta e' stata corretta e rivista. Il codice e' gia' disponibile nel branch 3.2.x e 3.3.x, oppure nel prossimo rilascio 3.2.1
