### ISSUE TITLE
Aggiungere descrizione all'iban di accredito

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#193]
**Necessità:**
Gli iban di accredito sono difficili da ricordare ed e' utile, come avviene sul portale delle adesioni, poterci associare una descrizione.

**Soluzione:**
Aggiungere al censimento di un iban la possibilita' di indicare una descrizione (max 256 char) che sara visualizzato in elenco nel titolo di secondo livello al posto dei dati attuali.

Con l'occasione rimuovere dall'interfaccia grafica l'indicazione mybank ormai deprecata, sia su grafica che su database. Nell'openapi aggiungere il tag `deprecated: true` al field corrispondente.

**Comment by pintorig** [comment]
Aggiunto supporto per la gestione della descrizione degli Iban Accredito.
Eliminata gestione del campo mybank.
Implementazione realizzata nel branch [feature/193_descrizione_iban_accredito](https://github.com/link-it/govpay/tree/feature/193_descrizione_iban_accredito)
Commit: 2d0e429
