### ISSUE TITLE
Mancata valorizzazione del placeholder @GOVPAY_SPRING_SEC_FOLDER@

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#199]
Premetto che le precedenti versioni hanno funzionato. Oggi provo a installare l'ultima release ma mi da errore il file govpay.ear non passa in deployed su wildfly, ma va in failed.
Qui il log:

[log.txt](https://github.com/link-it/govpay/files/4522660/log.txt)

**Comment by temptationisla** [comment]
Ho eseguito l'installer e copiato il file ear in wildfly, ma non va a buon fine. Qui un log aggiornato:

[log.txt](https://github.com/link-it/govpay/files/4522909/log.txt)

Mauro Bresolin

**Comment by nardil** [comment]
Dal momento che non riesco a riprodurre il problema, avrei bisogno di conoscere:
- ambiente di esecuzione dell'installer (windows, linux, macos....)
- versione di java di esecuzione dell'installer
- parametri impostati nell'installer

**Comment by temptationisla** [comment]
- Linux Debian
- openjdk version "1.8.0_242"
- wildfly 11
- mysql
- database e configurazione già funzionante dalla versione 3.1.1

**Comment by nardil** [comment]
Puoi inviarmi a nardi@link.it i file `ant.install.log`  `ant.install.properties` prodotti dall'installer?

Eventualmente puoi camuffare dati che non vuoi condividere.

Grazie.

**Comment by temptationisla** [comment]
inviati

**Comment by nardil** [comment]
Non riesco a riprodurre il tuo problema... hai apportato qualche modifica al codice dell'installer?

**Comment by temptationisla** [comment]
No

Il gio 23 apr 2020, 18:02 Lorenzo Nardi <notifications@github.com> ha
scritto:

**Comment by temptationisla** [comment]
A questo indirizzo puoi scaricare l'ultimo ear deployed:
http://pagopa.swdweb.it/govpay-3.1.1.ear
Questo è invece l'ear che fallisce:
http://pagopa.swdweb.it/govpay-3.2.1.ear

**Comment by nardil** [comment]
Il problema e' chiaro, ma non riesco a riprodurlo....

Nel frattempo, se vuoi aggirare il problema, modifica il file `WEB-INF/web.xml` di ciascun war contenuto nell'ear sostituendo le occorrenze di `@GOVPAY_SPRING_SEC_FOLDER@` con il valore `/WEB-INF`

**Comment by temptationisla** [comment]
Scusa Lorenzo, avevo una non so quale instabilità del server, perchè mi dava lo stesso errore con tutte le versioni compilate da capo: ho riavviato il server e ha fatto il deploy anche della 3.2.1
