### ISSUE TITLE
Errore java.net.UnknownHostException: gad.pagopa.gov.it

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#203]
Scaricando il file PdA_ManualeConnettività_GAD_PROD_partner_tecnologico.pdf dal portale alle adesioni pagopa trovo questo parametro che ho impostato in GovPay:
https://gad.pagopa.gov.it/openspcoop2/proxy/PA/RPT60

Eseguendo un pagamento singolo però ho l'errore  java.net.UnknownHostException e infatti da browser non è raggiungibile il dominio. Dove sbaglio?

In collaudo la risposta nel browser è forbidden, quindi c'è.

Grazie per il supporto

**Comment by nardil** [comment]
L'host `gad.pagopa.gov.it` non e' risolto dai DNS pubblici, quindi devi configurarne localmente la risoluzione con l'IP indicato nel manuale che hai scaricato dal portale.
