### ISSUE TITLE
Qual è il principal da settare nell'intermediario per gad.pagopa.gov.it?

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#204]
Dal 13 maggio 2020 hanno cambiato il certificato in esercizio del portale alle adesioni. Qual è il principal da settare nell'intermediario per gad.pagopa.gov.it?

**Comment by nardil** [comment]
Sia nella confiugrazione dell'intermediario che in quella della applicazioni, il principal nel caso di autenticazione SSL coincide con il Subject del certificato utilizzato dal chiamante.
