### ISSUE TITLE
Non riesco ad effettuare una riconciliazione dal backoffice

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#210]
**Descrizione del Bug**
Quando aggiungo una riconciliazione e scelgo l'EC il software va in errore 500 e il pulsante salva non si abilita mai.

**Ambiente:**
 - OS: Debian 9
 - Browser: Chrome
 - GovPay: 3.2.1
 - AS: WildFly 11
 - DBMS: Mysql

**Note aggiuntive:**
Allego log con gli errori
[govpay.log](https://github.com/link-it/govpay/files/4774540/govpay.log)

**Comment by pintorig** [comment]
Segnalazione corretta nel branch bug/210_errore_riconciliazione_backoffice: Commit 170caccc4c8b8e7088843ac39c100d28a26a643a.
Riportata in 3.2.x: d3b0c78fe2b9f18d15cc868f0a0747a22eb13117
Riportata in 3.3.x: 170caccc4c8b8e7088843ac39c100d28a26a643a

**Comment by nardil** [comment]
Risolto in master e incluso nella v3.2.2 di prossimo rilascio
