### ISSUE TITLE
Documentazione modalita' di autenticazione e autorizzazione

### ISSUE THREAD

**Issue by AriciducaZagaria** [link-it/govpay#212]
Salve sto cercando di prendere dimestichezza con il sistema.
Ho installato GovPay in locale e vorrei fare qualche prova su un qualsiasi endpoint dell'applicazione.
Al momento della richiesta tramite indirizzo locale:
`GET localhost:port/govpay/frontend/api/pagamento/pagamenti`
ottengo errore di autenticazione 403

Ho provato a configurare nel pannello "Protezione API Pubbliche" e a inviare richiesta con basic auth, ma nulla di positivo.

**Comment by nardil** [comment]
Ciao @AriciducaZagaria ,

provo a sintetizzare le informazioni precedendo di integrarle nella documentazione quando risultano chiare e organizzate:

**Docs » Integrazione » API di Integrazione » Autenticazione**

Le modalità di autenticazione disponibili sono le seguenti:

| Modalita | Principal | Descrizione |
| ------------- | ------------- | ------------- |
| basic  | username | username e password fornite tramite header `Authorization` |
| ssl  | subject del certificato | invocazione SSL con certificato client |
| ssl-header  | subject del certificato | invocazione con certificato codificato in header HTTP |
| header  | valore dell'header | principal comunicato in header HTTP |
| spid  | codice fiscale o partita iva dell'utenza spid | proprietà dell'utenza SPID propagate in header HTTP |
| session  | principal individuato in sede di creazione della sessione | autenticazione tramite sessione precedentemente creata |
| session  | nessun principal | accesso anonimo |

Per default sono abilitate le modalità `basic` e `ssl` su tutte le API, tranne quella pagoPA dove e' configurata la sola `ssl`. Per abilitare le altre modalità, dove disponibili, è necessario seguire le istruzioni descritte di seguito

_Gestione delle modalità di autenticazione_

Per abilitare o disabilitare le modalità di autenticazione disponibili sono necessarie le seguenti operazioni:
1. Abilitare la configurazione esterna di spring-security: in fase di installazione, spuntare il checkbox "Visualizza impostazioni avanzate" nelle Informazioni Preliminari e spuntare il checkbox "Usa file di configurazione esterni di Spring Security"
2. Estrarre le configurazioni di Spring Security: copiare dagli archivi `war` contenuti nell'`ear`, i file `/WEB-INF/classes/spring-sec/api-***-applicationContext-security.xml` nella della work directory (default `/etc/govpay/`) 
3. Commentare o scommentare le modalità di autenticazione desiderate: la configurazione di spring contiene già il codice necessario a tutte le modalità di autenticazione. Dei commenti individuano i blocchi di codice che gestiscono ciascuna modalità eventualmente inclusa in blocchi commentati. Rimuovendo i commenti o impostandoli se ne determina l'abilitazione o disabilitazione. Eventuali modifiche richiedono il riavvio dell'applicazione per renderle operative.

**Docs » Integrazione » API di Integrazione » Autorizzazione**

Una volta autenticato il soggetto chiamante, la piattaforma GovPay ne valuta l'autorizzazione.

| Api | Autenticazione | Operazioni consentite |
| ------------- | ------------- | ------------- |
| Backoffice  | tutte, tranne anonimo | Il principal individuato deve essere associato ad un Operatore o Applicazione registrato in GovPay a cui sono assegnati uno o più ruoli che determinano le operazioni autorizzate limitatamente ad un insieme di Enti Creditori e Tipologie di Pendenza. |
| Pendenze  | tutte, tranne anonimo | Se il principal individua una applicazione autorizzata all'uso dell'API, questa può inserire nuove pendenze delle Tipologie e per gli Enti creditori autorizzati, mentre la consultazione e  l'aggiornamento e' limitata a quelle da lei create |
| Pagamento  | tutte | Se il principal individua una applicazione autorizzata all'uso dell'API, questa può avviare transazioni di pagamento e consultare le pendenze delle Tipologie di Pendenza per gli Enti creditori autorizzati, mentre la consultazione delle transazioni di pagamento e' limitata a quelle da lei create<br />Se il principal individua un cittadino, questo può vedere le pendenze e pagamenti di cui risulta pagatore o versante e avviare transazioni di pagamento per proprie pendenze, avvisi o spontanei.<br />Se l'accesso e' anonimo, l'utente può avviare pagamenti di avvisi o spontanei e consultare pagamenti associati alla sessione d'uso |
| Ragioneria  | tutte, tranne anonimo | Se il principal individua una applicazione autorizzata all'uso dell'API, questa può creare nuove riconciliazioni e consultare le rendicontazioni, le riscossioni e òe transazioni per gli Enti creditori autorizzati, mentre la consultazione delle riconciliazioni di pagamento e' limitata a quelle da lei create |
| pagoPA  | ssl o basic | Il principal deve corrispondere a quello indicato nel connettore pagoPA configurato nell'intermediario indicato |

_Protezione delle API pubbliche_

GovPay integra alcune protezioni per le API di pagamento esposte ai cittadini per mitigarne l'uso improprio. Abilitando la funzione nella pagina delle impostazioni, si attivano le seguenti funzioni:

- google reCAPTCHA: le operazioni `POST /pagamenti` e `GET /avvisi` vengono autorizzate se superati i controlli previste dal reCAPTCHA v2 o v3
- hardening delle url: per la `GET /avvisi`, in alternativa al reCAPTCHA, è possibile passare il parametro `UUID` in query string, utile per la predisposizione di link diretti alle pagine di pagamento.

**Comment by nardil** [comment]
Nella descrizione delle modalità di autenticazione, sono da indicare anche le URL di invocazione per le diverse modalità di autenticazione:

`BASE_URL + /rs/ + AUTH_METHOD`

dove `BASE_URL` è quella indicata nell'introduzione del capitolo "API di Integrazione" e `AUTH_METHOD` può assumere i valori: `basic`, `ssl`, `sslheader`, `spid`, `public`, `form`, `session`.

Inoltre dovrebbero essere indicate anche istruzioni operative per le configurazioni (ad esempio, nel caso di autenticazione SSL, i certificati utilizzati devono essere trustati)

**Comment by AriciducaZagaria** [comment]
La ringrazio della risposta, non avevo compreso a pieno la questione dei ruoli e dei principal.
Al momento l'autenticazione va a buon fine ma mi ritrovo con un altro problema:

La richiesta
`baseurl/govpay/frontend/api/pagamento/rs/basic/pagamenti`
adesso mi da come response 
```
<html>

<body>No service was found.</body>

</html>
```
E' un errore dovuto dal fatto che non ho ancora configurato Enti Creditori?

**Comment by nardil** [comment]
Gran parte delle configurazioni, come l'anagrafica delle autorizzazioni, sono gestite da cache che memorizzano i dati per due ore. A valle di modifiche, per avere certezza che siano immediatamente operative, ti suggerisco di svuotare manualmente le cache dal cruscotto `Manutenzione > Resetta la cache`.

**Comment by AriciducaZagaria** [comment]
Grazie per il suggerimento

**Comment by nardil** [comment]
Riapro per tracciare l'inserimento delle informazioni discusse nella issue all'interno della documentazione.

**Comment by asterixol2000** [comment]
Buongiorno, anche io ho qualche problema con le autorizzazioni

invocando il servizio di pagamento da swagger

baseurl/govpay/frontend/api/pagamento/rs/basic/v2/pagamenti?
idSessionePortale=c8be909b-2feb-4ffa-8f98-704462abbd1d&gRecaptchaResponse=03AOLTB...

ottengo 

{
  "categoria": "AUTORIZZAZIONE",
  "codice": "403000",
  "descrizione": "Operazione non autorizzata",
  "dettaglio": "Operatore [gpadmin] non autorizzato ad accedere alla risorsa richiesta."
}

verificando le abilitazioni 

invocando il servizio per verificare il profilo 

...baseurl/govpay/frontend/api/pagamento/rs/basic/v2/profilo

ottengo 

{
  "nome": "gpadmin",
  "domini": [],
  "tipiPendenza": [],
  "acl": []
}

 questa risposta sembrerebbe coerente con il 403 ottenuto sulla chiamata di pagamento,
ma verificando sul db e con la gui l'operatore è autorizzato su tutti i pagamenti e su tutti i domini.

dalla documentazione ho visto che esiste anche una modalità di autenticazione HEADER, in questo caso il principal in che campo dell' header va passato?

**Comment by nardil** [comment]
Ciao @asterixol2000 , l'utente amministratore (come tutti gli operatori di backoffice) e' abilitato ad operare sulle API di Backoffice, ma non ha particolari autorizzazioni sulle API Pagamento. Ti rimando alla mia [precedente risposta](https://github.com/link-it/govpay/issues/212#issuecomment-648066787) sulle operazioni consentite in base alla modalita' di autenticazione.

Nel caso in cui tu stia integrando un applicativo che gestisce le transazioni di pagamento e deve colloquiare con GovPay per interfacciarsi con pagoPA, devi:

1. Censire una nuova applicazione assegnando il principal adeguato alla modalita' di autenticazione (eg.il subject del certificato o la username delle credenziali Basic)
2. Autorizzare l'applicazione alle API Pagamento per gli Enti e i Tipi Pendenza desiderati
3. Resettare la cache

Con questa utenza puoi invocare le API Pagamento ed avviare/consultare transazioni di pagamento con pagoPA.

Qualora volessi autenticarti tramite header http, avendo cura di proteggere adeguatamente il servizio, devi:
1. abilitare la modalita' di autenticazione `header` nel file di configurazione di Spring Security, seguendo le istruzionifornite nella mia [precedente risposta](https://github.com/link-it/govpay/issues/212#issuecomment-648066787)
2. Impostare il nome dell'header nel file `/etc/govpay/govpay.properties` (se utilizzati i valori di default nell'installer) valorizzando la property `it.govpay.autenticazioneHeader.nomeHeaderPrincipal`
3. Riavviare GovPay

**Comment by asterixol2000** [comment]
grazie @nardil  chiarissimo un saluto
