### ISSUE TITLE
Errore di autenticazione dopo il dispiegamento

### ISSUE THREAD

**Issue by lucamserra** [link-it/govpay#216]
Salve,

ho eseguito l'installer e seguito le istruzioni di dispiegamento (Wildfly 11, Postgres).
Quando provo il login nella govpay/backend/gui/backoffice/dashboard ottengo un errore di autenticazione "Bad credentials".

ho notato che il file init.sql non era stato eseguito e quindi il db non era stato inizializzato.
L'ho eseguito, ma probabilmente facendo degli errori nella configurazione dell'utenza principale.

Come posso risolvere?
Grazie in anticipo

**Comment by nardil** [comment]
Ciao @lucamserra ,

se hai sbagliato qualcosa nella procedura di inizializzazione, visto che si tratta di una nuova installazione, potresti ripeterla eseguendo l'installer e ricreando il DB. 

se invece pensi di aver solo fatto qualche errore di digitazione della password in sede di esecuzione dell'installer, puoi eseguire questo comando SQL per impostare la password "Password1!" all'utenza di amministazione, modificandola una volta effettuato l'accesso:

```sql
UPDATE utenze SET password = '$1$jil82b4n$GRX4A2H91f7L7dJ3kL2Vc.';
```

per verificare la il nome utente scelto in fase di installazione con questo comando:

```sql
select principal from utenze;
```

**Comment by lucamserra** [comment]
Ho risolto ripetendo l'installazione:
1) mvn -Denv=installer_template clean install
2) prepareSetup.sh
3) install.sh

Ma ho dovuto copiare a mano il file init.sql che l'installer non trovava.

[concat] /media/luca/Data/Eveilidia/Progetti/GovPay/govpay/src/main/resources/setup/core/installer/sql/init.sql does not exist.

Non so se ho sbagliato qualcosa io o il problema potrebbe ripetersi sempre per l'init.sql.

Comunque grazie della risposta, saluti.

**Comment by nardil** [comment]
Grazie per le segnalazioni, integriamo o verifichiamo le informazioni nel manuale di installazione

**Comment by nturri1306** [comment]
confermo init.sql non viene eseguito lo dovuto fare a mano pure io e ci sono anche degli errori di compatibilità con mariadb

**Comment by nardil** [comment]
Ciao @nturri1306 , se ci indichi la versione di mariadb ed eventualmente le modifiche che hai dovuto fare per completare il setup, facciamo delle verifiche e perfezioniamo lo script di inizializzazione.
