### ISSUE TITLE
errore in fase di deploy

### ISSUE THREAD

**Issue by bucchieri** [link-it/govpay#225]
In fase di installazione su windows JBOSS dà come errore : (F:govpay/estrattoConto) non esiste o non e' un folder.
Ovviamente il folder esiste ma temo sia un problema dovuto al fatto che non mette il \ dopo i :

**Ambiente:**
 - Windows 10
 - GovPay: 2.3.3.0
 - AS: jboss 7.1.1
 - Java: 1.7.0.80
 - DBMS: mysql

**Comment by nardil** [comment]
Ciao, 
un paio di chiarimenti:
1. la versione 2.3.3 di GovPay indicata e' corretta?
1. puoi dirmi come hai valorizzato i parametri nell'installer per replicare il problema? 

grazie

**Comment by bucchieri** [comment]
Buon pomeriggio,

 

in effetti è la versione dell’installer.

 



 



 



 

Queste le schermate dell’installer.

 

Poi ho seguito le istruzioni passo passo.

 

Grazie

 

Da: Lorenzo Nardi <notifications@github.com> 
Inviato: giovedì 9 luglio 2020 17:29
A: link-it/govpay <govpay@noreply.github.com>
Cc: bucchieri <bucchieri@cmslabs.it>; Author <author@noreply.github.com>
Oggetto: Re: [link-it/govpay] errore in fase di deploy (#225)

 

Ciao,
un paio di chiarimenti:

1.	la versione 2.3.3 di GovPay indicata e' corretta?
2.	puoi dirmi come hai valorizzato i parametri nell'installer per replicare il problema?

grazie

**Comment by bucchieri** [comment]
Dimenticavo di precisare che Windows 10 è ovviamente il mio PC dove stò provando il sistema, la macchina di destinazione è Windows Server 2016 o successivo.

Vedo che non si 'vedono' le immagini collegate nella mia prima risposta, quindi le inserisco in questa:
![Installer-Passo1](https://user-images.githubusercontent.com/68059545/87064264-c1cda800-c20f-11ea-9041-136769a566e0.png)

![Installer-Passo2](https://user-images.githubusercontent.com/68059545/87064107-8e8b1900-c20f-11ea-9c3b-5f772b3e2a41.png)
![Installer-Passo3](https://user-images.githubusercontent.com/68059545/87064135-96e35400-c20f-11ea-90bf-3e777daf9390.png)

**Comment by nardil** [comment]
La versione 2.x non e' piu' supportata. Dovresti installare/aggiore alla piu' recente (3.2.2) 

https://github.com/link-it/govpay/releases/latest

**Comment by bucchieri** [comment]
Grazie per il riscontro, però adesso ho un altro problemino. L'installer mi chiede una password e qualunque cosa io scrivo mi dà il seguente messaggio 
![RequestPwd](https://user-images.githubusercontent.com/68059545/87153737-39efa880-c2b8-11ea-85a8-b22dbe021607.png)

Qualunque cosa io scrivo....

**Comment by nardil** [comment]
8 caratteri con maiuscola, minuscola, numero e speciale: eg `Password1!`

**Comment by bucchieri** [comment]
Ciao scusami in realtà ho risolto subito dopo tanto che ho cancellato il post. In pratica non accetta tutti i caratteri speciali ad esempio _ o  - non li accetta, anche * o / e nemmeno . o , o ; etc etc.

Magari un messaggio più chiaro sarebbe utile.

Mettendo l’esclamativo è passato oltre.

Scusa ancora 

 

Da: Lorenzo Nardi <notifications@github.com> 
Inviato: venerdì 10 luglio 2020 14:24
A: link-it/govpay <govpay@noreply.github.com>
Cc: bucchieri <bucchieri@cmslabs.it>; Author <author@noreply.github.com>
Oggetto: Re: [link-it/govpay] errore in fase di deploy (#225)

 

8 caratteri con maiuscola, minuscola, numero e speciale: eg Password1!

**Comment by bucchieri** [comment]
Rieccomi, com MySql 8 le istruzioni di questo tipo danno errore:
ALTER TABLE singoli_versamenti ADD CONSTRAINT unique_sng_id_voce UNIQUE USING INDEX idx_sng_id_voce;
Sto installando postgresql per ovviare ma se hai un suggerimento per risolvere preferirei MySql che uso da anni.
Grazie

**Comment by nardil** [comment]
@pintorig facciamo una verifica e ti facciamo sapere

**Comment by bucchieri** [comment]
Ho installato postgresql ma anche qui mi ha dato due errori:
psql:gov_pay.sql:1637: ERRORE:  il valore è troppo lungo per il tipo character varying(255)
psql:gov_pay.sql:1638: ERRORE:  valori null nella colonna "id_utenza" violano il vincolo non-null
DETTAGLI: La riga in errore contiene (Guglielmo Bucchieri, 1, null).
In ogni caso ha creato tutto. 
Devo eseguire anche le patch di sql?
La versione del DB è la 12

**Comment by nardil** [comment]
No, le patch servono in caso di aggiornamento.

Puoi allegare il sql?

**Comment by bucchieri** [comment]
Eccolo

[gov_pay.zip](https://github.com/link-it/govpay/files/4903525/gov_pay.zip)

**Comment by bucchieri** [comment]
Comunque la console di GovPay è partita ma non mi riconosce l'utente, probabilmente per l'errore che ha dato. Posso in qualche modo superare la cosa?
Sempre grazie (anche per la celerità ed efficacia delle risposte)

**Comment by nardil** [comment]
Nello script sql compare un errore di versione di java non supportata emerso in fase di cifratura della password. Quale versione di JAVA hai utilizzato per eseguire l'installer?

Per correggere esegui queste query:

```sql
INSERT INTO utenze (principal,principal_originale,autorizzazione_domini_star,autorizzazione_tipi_vers_star,ruoli,password) VALUES ('gpadmin','gpadmin',true, true, 'Amministratore','$1$jil82b4n$GRX4A2H91f7L7dJ3kL2Vc.');
INSERT INTO operatori (nome, id_utenza) VALUES ('Guglielmo Bucchieri', (select id from utenze where principal = 'gpadmin'));
```

Riavvia l'applicazione e utilizza le credenziali `gpadmin / Password1!`  per accedere al cruscotto.

**Comment by bucchieri** [comment]
Yes, ci siamo.
In effetti può darsi :sono partito con la versione di java jdk1.7.0_80 supportata da JBOSS e poi sono passato alla jdk1.8.0_45 supportata da wildfly-11.0.0.Final. Non ricordo se il passaggio l'ho fatto prima o dopo l'esecuzione dell'installer.
Comunque dato che la settimana prossima dovrà fare il tutto sul server ufficiale Ti saprò dire se in una situazione pulita và tutto bene.
Grazie e buon week end

**Comment by bucchieri** [comment]
Buongiorno, ho installato il tutto su un server web senza problemi stavolta. A questo punto stavo inserendo i dati dell'ente creditore ma mi chiedevo se devo effettuare ugualmente il collaudo sul pannello di pagopa o posso direttamente creare una stazione in ambiente di esercizio.

**Comment by nardil** [comment]
Ciao Guglielmo,

per chiarimenti o deroghe al processo di adesione a pagoPA devi chiedere ai gestori della piattaforma.

**Comment by bucchieri** [comment]
Ok, un ultimo chiarimento. Devo installare l certificato ssl per il sito ma fatta la normale procedura in avvio wildfly mi da una serie dierroi quali:
2020-07-21 18:16:01,351 ERROR [stderr] (ServerService Thread Pool -- 65) SLF4J: Class path contains multiple SLF4J bindings.

2020-07-21 18:16:01,352 ERROR [stderr] (ServerService Thread Pool -- 65) SLF4J: Found binding in [vfs:/C:/PagoPA/wildfly-11.0.0.Final/bin/content/govpay.ear/lib/log4j-slf4j-impl-2.6.2.jar/org/slf4j/impl/StaticLoggerBinder.class]

E' una cosa per cui mi puoi aiutare ?

Grazie anticipatamente

**Comment by nardil** [comment]
E' un problema di librerie che non ha alcun effetto sull'operativita'
del sistema, quindi puoi ignorarlo. E' stato risolto ed il fix sara'
incluso nel prossimo rilascio.




Il giorno mar, 21/07/2020 alle 09.24 -0700, bucchieri ha scritto:

**Comment by bucchieri** [comment]
Ho capito, quindi la connessione ssl dovrebbe funzionare lo stesso immagino.

**Comment by bucchieri** [comment]
Confermo, funziona tutto perfettamente. Grazie.
Se ti interessa, il servizio è per un ente di Catania. Spero di riuscire a metterlo in linea entro questa estate.
Grazie Ancora

**Comment by nardil** [comment]
Prego, se l'ente è d'accordo saremmo interessati a inserirlo tra gli utilizzatori di govpay nel catalogo del software a riuso: https://developers.italia.it/it/software/link-it-govpay-173570

**Comment by bucchieri** [comment]
Non ci sono problemi, però prima devo riuscire a far funzionare il tutto ;-)
