### ISSUE TITLE
Label configurazione notifiche errata

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#227]
**Descrizione del Bug**
Nella form di configurazione dei Tipi Pendenza, nella sezione di configurazione delle notifiche via mail delle ricevute, sostituire la label `Allega pdf avviso` con `Allega pdf ricevuta`.

Sostituire anche la label `Notifica solo pagamenti eseguiti` che non entra nello spazio a disposizione con `Notifica solo eseguiti` o, se anche questo non rientra nello spazio, `Solo eseguiti`

![Schermata da 2020-07-15 11-55-11](https://user-images.githubusercontent.com/12340738/87531521-1babf300-c692-11ea-81fa-49e3f7435f99.png)

**Comment by simo-git** [comment]
Anche in "Impostazioni>Comunicazioni Mail>Notifica Ricevuta" cambio "Allega pdf avviso" con "Allega pdf ricevuta", ed in modo analogo l'etichetta "Notifica solo pagamenti eseguiti"?

**Comment by nardil** [comment]
Si, perfetto
