### ISSUE TITLE
Form backoffice di inserimento pendenza

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#228]
**Necessità:**
Nella form di caricamento di una pendenza, risulta obbligatorio selezionare un'Unita Operativa, eventualmente indicando `Nessuno`. Questa selezione dovrebbe essere opzionale e non selezionare equivale a selezionare `Nessuno`

**Comment by nardil** [comment]
Inoltre nella lista degli Enti Creditori dovrebbero risultare listati solo quelli che presentano almeno una tipologia di pendenza configurata per l'inserimento manuale.

**Comment by simo-git** [comment]
>Nella form di caricamento di una pendenza, risulta obbligatorio selezionare un'Unita Operativa, eventualmente indicando Nessuno. Questa selezione dovrebbe essere opzionale e non selezionare equivale a selezionare Nessuno

Il valore NESSUNA è aggiunto tra le opzioni di scelta solo per le UO con idUnita equivalente ad 'EC'; a questo punto potrei  impostarla come scelta predefinita.
>Inoltre nella lista degli Enti Creditori dovrebbero risultare listati solo quelli che presentano almeno una tipologia di pendenza configurata per l'inserimento manuale.

Non ho possibilità di filtraggio a priori della lista; servirebbe una richiesta simile a quella dei tipiPendenza con parametro form in query string: /domini?associati=true&form=true

**Comment by nardil** [comment]
> > Nella form di caricamento di una pendenza, risulta obbligatorio selezionare un'Unita Operativa, eventualmente indicando Nessuno. Questa selezione dovrebbe essere opzionale e non selezionare equivale a selezionare Nessuno
> 
> Il valore NESSUNA è aggiunto tra le opzioni di scelta solo per le UO con idUnita equivalente ad 'EC'; a questo punto potrei impostarla come scelta predefinita.
> 
> > Inoltre nella lista degli Enti Creditori dovrebbero risultare listati solo quelli che presentano almeno una tipologia di pendenza configurata per l'inserimento manuale.
> 
> Non ho possibilità di filtraggio a priori della lista; servirebbe una richiesta simile a quella dei tipiPendenza con parametro form in query string: /domini?associati=true&form=true

@pintorig Dovresti implementare questo filtro
