### ISSUE TITLE
Integrazione GovPay - GovWay per servizio RT

### ISSUE THREAD

**Issue by paotox** [link-it/govpay#238]
Buongiorno, sto configurando un sistema composto da GowWay 3.2.0 (che sostituisce la vecchia OpenSPCoop) e GovPay 2.6.0 per l'erogazione del servizio PagoPA. Al momento sono in ambiente di test: il servizio PagamentiTelematiciRPT6T funziona correttamente, mentre non riesco a far funzionare l'erogazione PagamentiTelematiciRT6T. I collegamenti fisici col Nodo dei Pagamenti sono corretti, ho configurato su GovWay il connettore verso GovPay in questo modo:

- http://<_URL_GOVPAY_>/govpay/PagamentiTelematiciRTService 

ma ricevo il seguente errore (dal log di govway): "Metodo http 'GET' non supportato dall'API SOAP invocata" (sul Monitor di GovWay ricevo semplicemente un "errore generico" senza alcun dettaglio della transazione).
Sto sbagliando qualcosa nell'invocazione del servizio?
Se richiamo da browser la url http://<URL_GOVPAY>/govpay/PagamentiTelematiciRTService?wsdl mi restituisce correttamente il wsdl del servizio.

Grazie per il supporto, un saluto

**Comment by nardil** [comment]
Ciao @paotox, l'errore restituito mi risulta corretto dal momento che il servizio PagamentiTelematiciRT, come gli altri di pagoPA, e' SOAP e pertanto non prevede l'operazione HTTP `GET`.  

Direi quindi che l'errore riscontrato non dipende dalla configurazione, ma da come il servizio viene invocato perché la richiesta non rispetta le specifiche pagoPA.

**Comment by paotox** [comment]
Grazie per la risposta @nardil , a questo punto però mi viene un dubbio: come devo impostare il connettore della govway per il servizio PagamentiTelematiciRT6T verso la govpay? Dall'interfaccia non ho modo di scegliere il metodo o altro, se non il tipo (http, https, ...).

**Comment by nardil** [comment]
Al netto di particolari trasformazioni configurate nell'erogazione, che non credo siano state impostate, il metodo utilizzato nella chiamata a GovPay e' lo stesso della chiamata a GovWay.

Riassumendo il tuo scenario: e' stata fatta una richiesta al GovWay per il servizio di PagamentiTelematiciRT, ma GovWay l'ha correttamente riconosciuta come non valida e l'ha rigettata senza neanche tentare di inoltrarla a GovPay. L'errore e' nella richiesta, non nella configurazione.

**Comment by paotox** [comment]
Ti ringrazio per la spiegazione, anche se mi sembra strano che la richiesta fatta dal Nodo dei Pagamenti non sia corretta. E' forse più probabile che si tratti di un problema di comunicazione, dato che a fronte di altre richieste RPT non abbiamo ricevuto ancora alcuna RT (e di conseguenza nessun errore).

**Comment by nardil** [comment]
Scusa, un chiarimento: ma se le RT non stanno arrivando, l'errore riportato nel primo commento come e' stato riprodotto?

Non potrebbe esser stata una chiamata di prova o involontaria generata ad esempio inserendo nel browser l'indirizzo di govway, e che in realta' invocazioni da pagoPA non ne siano mai arrivate?

**Comment by paotox** [comment]
Inizialmente eravamo convinti che fossero chiamate reali perché sono arrivate esattamente dopo che è stata attivata la linea fisica col nodo dei pagamenti ed è stato effettuato un test di pagamento, ma a conti fatti è molto probabile che tu abbia ragione. In ogni caso abbiamo contattato il nodo dei pagamenti per verificare con loro che la connessione funzioni. Grazie di nuovo per il supporto.
