### ISSUE TITLE
WFLYJCA0047: Connection is not valid

### ISSUE THREAD

**Issue by giammen** [link-it/govpay#243]
Nel deploy della versione 3.2.2 ho utilizzato la console web ed agganciato il connettore jdbc postgres, ler versioni sono Ubuntu20.04 wildfly20 postgresql12 jdbc postgresql-42.2.14.jar, questo è l'errore a video.

nexpected HTTP response: 500

Request
```
{
"address" => [
("subsystem" => "datasources"),
("xa-data-source" => "MysqlXADS")
],
"operation" => "test-connection-in-pool"
}
```
Response

Internal Server Error
```
{
"outcome" => "failed",
"failure-description" => "WFLYJCA0040: failed to invoke operation: WFLYJCA0047: Connection is not valid",
"rolled-back" => true
}
```

ho eseguito lo stesso procedimento con mysql8 jdbc mysql-connector-java-8.0.21.jar ed appare lo stesso errore.
E' un problema di console web o di qualche versione errata wildfly o DBMS?
Ho eseguito lo stesso procedimento anche con Centos8 WildFly11, sempre lo stesso erroe.

**Comment by nardil** [comment]
Ciao @giammen , 

da una rapida ricerca, il codice `WFLYJCA0040` e' riconducibile ad un errore nel deploy del datasource. Dovresti controllare il log di wildfly per trovare maggiori informazioni sulle origini del problema.
