### ISSUE TITLE
Full authentication is required to access this resource

### ISSUE THREAD

**Issue by giammen** [link-it/govpay#245]
Ciao Lorenzo

sono riuscito ad installare senza apparenti problemi la piattaforma su Ubuntu 20.04 server, versione GovPay 3.1.1, wildfly 11 e mysql 8.0.
Ho avviato la console all'indirizzo http://212.91.88.180:8080/govpay/backend/gui/backoffice e loggato con nome utente e password senza problemi.
ho provato ad effettuare un test agli indirizzi :
http://212.91.88.180:8080/govpay/frontend/api/pagopa/PagamentiTelematiciCCPservice?wsdl
http://212.91.88.180:8080/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl
con il seguente errore per entrabi gli indirizzi:

categoria | "AUTORIZZAZIONE"
-- | --
codice | "401"
descrizione | "Richiesta non autorizzata"
dettaglio | "Full authentication is required to access this resource"

come risolvo questo errore?

Ho, inoltre, seguito e completato tutti i passaggi richiesti da PagoPa nel portale delle Adesioni, l'unico step che manca, credo, è la scelta da parte dell'Ente come Partner Tecnologico, questo influisce sull'iter della configurazione?

Grazie.

**Comment by nardil** [comment]
Ciao @giammen ,

come indicato nella [documentazione](https://govpay.readthedocs.io/it/latest/installazione/dispiegamento/index.html#modalita-di-autenticazione) le API pagoPA sono preconfigurate per l'autenticazione tramite certificato. 

E' quindi necessario:
1. Dal cruscotto di configurazione, indicare nella configurazione del connettore dell'intermediario il subject del certificato pagoPA come `principal`
2. Configurare l'ambiente affinché le informazioni del certificato utilizzato da pagoPA siano comunicate all'applicazione (eg. tramite ajp in caso di apache)

Altrimenti e' possibile predisporre [modalità di autenticazione](https://govpay.readthedocs.io/it/latest/integrazione/api/autenticazione/index.html#tabella-autenticazione) diverse se necessario seguendo [questa procedura](https://govpay.readthedocs.io/it/latest/installazione/dispiegamento/index.html#inst-dispiegamento-auth)

**Comment by nardil** [comment]
Ovviamente poi per chiamare quelle API e' necessario disporre del certificato client di pagoPA. 

Per fare un test preliminare puoi configurare un tuo certificato di prova.
