### ISSUE TITLE
Aiuto riguardo le fasi di dispiegamento di Govpay

### ISSUE THREAD

**Issue by Micheletesta** [link-it/govpay#249]
Qualcuno potrebbe spiegarmi le fasi di dispiegamento di Govpay? Sono uno studente che sta partecipando ad un progetto extra-curricolare e le conoscenze richieste non le ho.
Chiedevo pertanto un aiuto per comprendere i passi necessari al dispiegamento di Govpay.
Grazie
.

**Comment by nardil** [comment]
Ciao Michele, 

puoi seguire la [guida di installazione](https://govpay.readthedocs.io/it/latest/installazione/index.html) ed eventualmente chiedere approfondimenti per passaggi specifici.

**Comment by Micheletesta** [comment]
Sto avendo problemi con il punto 4.
Come posso fare?

**Comment by nardil** [comment]
L'inizializzazione del DB?

> 4. Eseguire lo script sql/gov_pay.sql per la creazione dello schema del database utilizzando un’utenza con sufficienti diritti per la creazione delle tabelle. Ad esempio, nel caso di PostgreSQL, si potrà eseguire il comando:
> 
>    `psql -h <hostname> -d <database> -U <username> -f sql/gov_pay.sql`

Di quale chiarimentohai bisogno?

**Comment by Micheletesta** [comment]
Quando eseguo lo script ho degli errrori:
Aprendolo su mySQL workbench leggo "unconnected" e non posso eseguirlo;
Eseguendolo su Altervista dove devo implementarlo, ho errori sui comandi CREATE.
Potrebbero essere cose davvero banali ma io sono completamente nuovo al mondo dei database

**Comment by nardil** [comment]
> ho errori sui comandi CREATE

Quali errori riscontri?

**Comment by Micheletesta** [comment]
Il mySQL workbench che ho installato è la versione 8.0 CE  e leggo "unconnected" dove dovrei leggere il nome del modello.
Su Altervista è presente la versione 5.6 e, copiando il codice del file sql/gov_pay.sql ed eseguendolo ho errori senza una spiegazione di ciò che sia sbagliato, tuttavia mi rimanda a questa pagina: https://dev.mysql.com/doc/refman/5.6/en/select.html
Non capisco come mai io venga reindirizzato ad una guida sul comando "select" quando nelle righe di codice dove ci sarebbe l'errore non è presente la parola "select"; inoltre ho un messaggio di MySQL(sempre su Altervista) di questo tipo: "#1046 -" e non capisco il motivo.

**Comment by nardil** [comment]
Sembra che non sia un problema dello script, ma di predisposizione del db:

[`#1046 - No database selected`](https://stackoverflow.com/questions/4005409/error-1046-no-database-selected-how-to-resolve)

dovresti verificare che il DB esista e che sia in uso al momento dell'esecuzione dello script.
