### ISSUE TITLE
Errore certificato collaudo PagoPA

### ISSUE THREAD

**Issue by giammen** [link-it/govpay#250]
Ciao Lorenzo

Ho avviato la fase di collaudo con pagoPA, dal Portale delle Adesioni ho inserito il collegamento fisico connessione GAD, ho inserito la configurazione di connessione ma ho qualche problema con ilk certificato del soggetto, infatti dall'help desk mi hanno risposto con un rifiuto;

Note rifiuto:
I dati e il certificato inseriti sono quelli relativi al GAD centrale, dovreste invece fornire i rispettivi lato vostro.

Come risolvo?
Grazie.

**Comment by nardil** [comment]
Il colloquio con pagoPA, come indicato nelle specifiche, prevede la mutua autenticazione tramite certificato. 

Devi quindi

1. dotarti di un certificato conforme ai requisiti
2. configurare la piattaforma affinché utilizzi il certificato nel colloquio con pagoPA
3. caricare il certificato sul Portale delle Adesioni

**Comment by fnc-1** [comment]
grazie

puoi aiutarmi puoi aiutarmi per i passaggi 1 e 2? Se ce una giuda indicarmi quale?

**Comment by nardil** [comment]
Il certificato, se non ne hai già uno, devi acquistarlo presso una Certificate Autority pubblica.
Per la configurazione degli applicativi coinvolti ad utilizzarlo (reverse proxy, application server, etc,..) dovresti consultare la documentazione dello specifico prodotto utilizzato
