### ISSUE TITLE
Diversi errori di SQL

### ISSUE THREAD

**Issue by Micheletesta** [link-it/govpay#253]
Sto cercando ad implementare il servizio Govpay su un sito Altervista ma sto riscontrando diversi problemi.
Altervista stesso non mi dice cosa effettivamente sia sbagliato nel codice, segnando semplicemente l'intera funzione e come messaggio uno tra diversi messaggi d'errore di SQL, tra i quali: #1286, #1046, #1050, #1064...
Qualcuno sa se possa essere un problema legato alle versioni a mia disposizione di MySQL(5.6.33), Apache( 5.0.11) e phpMyAdmin(4.1.7) o altro?

**Comment by nardil** [comment]
Ciao Michele,

puoi condividere lo script cosi da poterne verificare la correttezza?

**Comment by Micheletesta** [comment]
Io ho importato questo su Altervista: sql/gov_pay.sql; tuttavia ho solo 17 tabelle create.
Anche copiando e incollando nella sezione dove si possono eseguire le query, ho gli errori precedentemente citati.

**Comment by nardil** [comment]
Capisco, puoi allegare lo script che stai utilizzando?

**Comment by Micheletesta** [comment]
[govpay.txt](https://github.com/link-it/govpay/files/5387683/govpay.txt)

**Comment by nardil** [comment]
Abbiamo individuato un typo nello script per mysql:

```sql
-       zip_stampe MEDIUMBLOB COMMEYNT 'Zip contenente le stampe degli avvisi del tracciato',
+       zip_stampe MEDIUMBLOB COMMENT 'Zip contenente le stampe degli avvisi del tracciato',
```

potresti verificare che correggendo questa linea (la n. 326) lo script prodotto dall'installer in `dist/sql/gov_pay.sql` viene eseguito correttamente?

**Comment by Micheletesta** [comment]
No, purtroppo ho ancora #1050

**Comment by Micheletesta** [comment]
alla linea 321: "data_caricamento TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Data di caricamento del tracciato'," il secondo 3 mi viene rilevato come errore dal workbench, mentre lasciando le parentesi vuote no

**Comment by Micheletesta** [comment]
> alla linea 321: "data_caricamento TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Data di caricamento del tracciato'," il secondo 3 mi viene rilevato come errore dal workbench, mentre lasciando le parentesi vuote no
Anche ad altre linee(539,680,734,798,830,864,893,927,955,993,1022,1069,1153,1205,1226,1239) ho lo stesso errore. Può essere che questi errori siano la causa?

**Comment by nardil** [comment]
Premesso che, come [indicato nel manuale](https://govpay.readthedocs.io/it/latest/installazione/ambiente/index.html), la versione minima supportata di MySQL e' la 5.7, la sintassi delle date e' quella prevista a partire dalla 5.6.4, dove e' stato introdotta la precisione del tipo Timestamp ai millisecondi.

Il suggerimento comunque e' di passare ad una versione supportata del DBMS.
