### ISSUE TITLE
 problema con login

### ISSUE THREAD

**Issue by nturri1306** [link-it/govpay#255]
login non effettuata, ho fatto tutti passi del manuale ho lanciato applicazione dopo aver configurato db e driver
 ma quando provo a fare login da sempre errore di autenticazione , premetto q indirizzo managment console sulla 9990 funziona con utenza creata in wildfly con adduser
 
![govpay](https://user-images.githubusercontent.com/11473051/96349411-bfe96f80-10af-11eb-9cde-ce30340b8ec9.png)
mentre se vado sia con utente wildfly q con utente create in fase di setup di govpay ricevo sempre errore
ho controllato il db e stranamente le tabelle utenti sono tutti vuote
ce un logs che si puo vedere per capire se ce un errore?

url di riferimento

http://127.0.0.1:8080/govpay/backend/gui/backoffice/dashboard

**Comment by nardil** [comment]
Ciao @nturri1306 , 

da quanto hai scritto in #216 sembra che l'inizializzazione del DB non sia andata a buon fine e per questo trovi la tabella delle utenze e degli operatori vuota. Se lo confermi non mi stupisce quindi che non riesci ad autenticarti.

Per poterti aiutare sarebbe utile sapere:

- tipo e versione del dbms
- sql di inizializzazione (per velocizzarci)

Ti faccio comunque presente che nell'installazione standard le credenziali di autenticazione degli operatori di console sono gestite internamente a GovPay e non ci sono interazioni con le utente di WildFly

**Comment by nturri1306** [comment]
confermo la versione di mariadb su linux è la 10 ma ho avuto lo stesso problema anche sotto windows con la 8
adesso ho inizializzato tutto a mano e funziona
poi ce un altra anomalia  utente di sistema inserito in wildfly della console  non viene mai riconosciuto ho dovuto cambiare dove ce @PRINCIPAL@ con un altro utente  e inserito una password di reset come segnalato in un thread 'Password1!

**Comment by nardil** [comment]
Cosa significa che hai inizializzato a mano? Se ci sono dei problemi di installazione sarebbe utile condividere l'esperienza per correggerli.

Per quanto riguarda il problema della password, significa che c'è stato un errore da parte dell'installer nel preparare lo script di setup del db. Puoi dirmi l'esatta versione di java con cui hai eseguito l'installer?

**Comment by nturri1306** [comment]
a mano che ho lanciato lo script govpay.sql e poi init.sql

è poi ho dovuto ricreare utente con una password di default 'Password1!'
come indicato in un thread del forum

IL JDK è la 1.8





Il giorno dom 18 ott 2020 alle ore 20:39 Lorenzo Nardi <
notifications@github.com> ha scritto:

**Comment by nardil** [comment]
Abbiamo individuato un typo nello script per mysql:

```sql
-       zip_stampe MEDIUMBLOB COMMEYNT 'Zip contenente le stampe degli avvisi del tracciato',
+       zip_stampe MEDIUMBLOB COMMENT 'Zip contenente le stampe degli avvisi del tracciato',
```

potresti verificare che correggendo questa linea (la n. 326) lo script prodotto dall'installer in `dist/sql/gov_pay.sql` viene eseguito correttamente?

**Comment by nturri1306** [comment]
si confermo q alla riga 326 correggendola adesso esegue tutto lo script
senza errori

ovviamente non ho ripetuto ancora tutto il processo di installazione lo
faro' tra poco su una nuova vm

ci aggiorniamo

Il giorno lun 19 ott 2020 alle ore 09:08 Lorenzo Nardi <
notifications@github.com> ha scritto:

**Comment by nardil** [comment]
Grazie per la conferma, procediamo ad includere il fix nel prossimo rilascio (v.3.3.1).

Ti chiedo la cortesia di chiudere la issue #256 se ti risulta risolta da questo fix oppure aggiornarla cosi da includere ulteriori correzioni già nel prossimo rilascio.

**Comment by nturri1306** [comment]
ok chiusa , nei giorni seguenti faro' altri test sulla vm è se trovo
qualcosa di anomalo ve lo segnalo

Saluti
Nicola Turri

Il giorno lun 19 ott 2020 alle ore 11:02 Lorenzo Nardi <
notifications@github.com> ha scritto:
