### ISSUE TITLE
creazione degli utenti

### ISSUE THREAD

**Issue by nturri1306** [link-it/govpay#259]
ho notato che viene creato solo utente gpadmin proposto in fase di setup mentre utente di jboss non compare nello script del db

-- Censimento dell'utenza amministratore

INSERT INTO utenze (principal,principal_originale,autorizzazione_domini_star,autorizzazione_tipi_vers_star,ruoli,password) VALUES ('gpadmin','gpadmin',true, true, 'Amministratore', '$1$Yk$XEVGyZhZf57SW0R37Mhz2.');

INSERT INTO operatori (nome, id_utenza) VALUES ('nicola turri', (select id from utenze where principal = 'gpadmin'));

-- Censimento del ruolo amministratore

**Comment by nardil** [comment]
Risulta tutto regolare. In fase di setup e' prevista la creazione della sola utenza di amministrazione per poter operare sulla console di gestione. Se ritieni utile creare ulteriori utenze puoi farlo dalla console.
