### ISSUE TITLE
Recupero dati di stampa avviso da Portale

### ISSUE THREAD

**Issue by acoviello** [link-it/GovPay#26]
Nello scenario in cui dalla lista dei pagamenti in debito riportata sul portale, l'utente deve stampare l'avviso di pagamento, si ha la necessità di avere i dati necessari per la creazione della stampa quali iuv ed applicationCode per la creazione di qrCode  e barCode

**Comment by nardil** [comment]
Funzionalita implementata nella [versione 2.2 beta]([/link-it/GovPay/tree/v2.2)
