### ISSUE TITLE
messaggi di avviso sul cms sono dovuti alla configurazione ?

### ISSUE THREAD

**Issue by nturri1306** [link-it/govpay#261]
![PAGO1](https://user-images.githubusercontent.com/11473051/97102952-e5770a00-16a9-11eb-9278-7a11e5bd92e9.png)

**Comment by nardil** [comment]
Sono i normali processi di recupero pagamenti sospesi nei quali la piattaforma interroga periodicamente pagoPA. La comunicazione con pagoPA però non sembra correttamente operativa. Trovi maggiori informazioni nel dettaglio degli eventi.
