### ISSUE TITLE
ADOZIONE PAGOPA PER PREAVVISI DI ACCERTAMENTO CDS

### ISSUE THREAD

**Issue by gleopizzi** [link-it/govpay#264]
Salve.

Riscontriamo difficoltà nella gestione del pagoPa in relazione all'utilizzo ordinario dei preavvisi di accertamento del C.d.S.
In dettaglio, prima dell'avvento del sistema di pagamento PagoPa l'agente accertatore poteva compilare manualmente il modello della multa (classico foglio rosa apposto sul parabrezza), indicare solo al momento l'importo dell'infrazione stabilita (spesso dipendente anche dalla tipologia del veicolo in infrazione) e abbinare un bollettino postale vuoto (da compilare a cura del trasgressore).
Il trasgressore una volta trovato il preavviso sul parabrezza e preso atto dell'infrazione poteva recarsi anche subito presso gli sportelli previsti per effettuare il pagamento/conciliazione della stessa sanzione.
Oggi, volendo adottare il sistema PagoPa in questo contesto non troviamo la possibilità di poter assegnare una transazione di pagamento "IUV" preliminarmente (senza importo) al singolo preavviso, magari al momento della stampa/predisposizione dei bollettari cartacei da fornire agli agenti accertatori.
Purtroppo alcune amministrazioni non possono fare a meno dell'utilizzo dei bollettari cartacei per svariati motivi di tipo commerciale, di praticità d'uso da parte di operatori non avanzati, per motivi di deterrenza contro il parcheggio selvaggio, ecc.
E' fondamentale considerare anche il fatto che molte amministrazioni elevano numeri importanti giornalmente e garantire l'introduzione (data entry) degli stessi preavvisi nel sistema gestionale per la contestuale assegnazione di uno IUV e praticamente impossibile.

Confido in una opportuna e celere soluzione della problematica da me evidenziata.

Grazie.
Buon lavoro.

Giovanni Leopizzi
ITALSET SRL

**Comment by nardil** [comment]
Ciao @gleopizzi ,

grazie per la segnalazione. Effettivamente pagoPA non supporta lo scenario di pagamento di avviso "in bianco" ad iniziativa PSP. 

La [best pratice di pagoPA](https://github.com/italia/lg-pagopa-docs/blob/master/documentazione_tecnica_collegata/best_practices/multe_con_preavviso_agid.pdf) infatti prevede l'uso di dispositivi da parte degli accertatori per poter alimentare l'archivio dei pagamenti in attesa in tempo reale e gestire con i bollettari i casi eccezionali. Nello scenario che descrivi, l'uso del bollettario invece e' la situazione ordinaria con le implicazioni che hai descritto.

Allo stato attuale, i servizi pagoPA non supportano questo caso d'uso, ma possiamo provare a proporre di valutarne l'adozione.

**Comment by nardil** [comment]
Abbiamo inviato una [proposta di evolutiva delle API pagoPA](pagopa/pagopa-api#80) e pubblicato un messaggio sul [Forum Italia](https://forum.italia.it/t/pagamento-avvisi-bianchi-ad-iniziativa-psp/17534) per darne risalto.

Ti invito a seguire le discussioni che potranno seguire cosi da contribuire.

**Comment by nardil** [comment]
Le nuove API di pagamento modello 3 aprono alla possibilita' di far decidere l'importo da corrispondere all'utente tramite il parametro `options`:

https://github.com/pagopa/pagopa-api/blob/ce8d4090aaada6ca67098cbdfafe12242430ec61/ec/paForNode.xsd#L216-L236

Sembra quindi che sia possibile prestampare dei verbali pagoPA associati ad una pendenza intestata ad un utente anonimo con un importo fittizio che il cittadino possa poi perfezionare in sede di pagamento.

La funzionalita' (#371) che consente questo scenario e' sara' implementata quando pagoPA ed i PSP la supporteranno pienamente.
