### ISSUE TITLE
Filtro stato gpChiediListaVersamenti

### ISSUE THREAD

**Issue by acoviello** [link-it/GovPay#27]
Invocando la primitiva GpChiediListaVersamenti e specificando uno stato, nella risposta i risultati non sono filtrati per lo stato richiesto

**Comment by nardil** [comment]
Puoi verificare se il patch nel branch [Fix#27](https://github.com/link-it/GovPay/tree/Fix%2327) risolve?

**Comment by acoviello** [comment]
Adesso specificando uno stato ottengo risultati filtrati. Di contro però devo specificarne obbligatoriamente uno altrimenti ottengo in risposta: 
- codEsitoOperazione:INTERNAL
- descrizioneEsitoOperazione: org.openspcoop2.generic_project.exception.ExpressionException: Values[0] is null for field: - field name: statoVersamento
- field type: class java.lang.String
- class name: Versamento
- class type: class it.govpay.orm.Versamento
Inoltre quando ottengo i risultati filtrati non trovo il campo IUV

**Comment by nardil** [comment]
Non sono riuscito a riprodurre il primo problema. Puoi mandarmi il dump della richiesta che stai inviando?

Per avere lo IUV nei risultati, dal momento che e' un campo aggiunto dalla versione 2.2 delle interfacce di integrazione, devi configurare l'applicazione con la versione 2.2 (impostazione avanzata)

![schermata da 2016-08-04 18-18-12](https://cloud.githubusercontent.com/assets/12340738/17409532/ff3f7a26-5a6f-11e6-88bc-c21f92d77b71.png)

Fammi sapere,
Lorenzo

**Comment by acoviello** [comment]
Ho rifatto una prova, probabilmente sbagliavo io ad invocare la primitiva, se non metto lo stato mi da tutti i risultati. L'ordinamento invece è obbligatorio? Se lo ometto ho questo:
<b1457462-90f5-44c5-b527-b1675c121c35>
Type:REQUEST_IN
Content-Type:text/xml; charset=UTF-8
------ Header ------
Accept=*/*
Authorization=Basic cHVicG9ydGFsZTpwYXNzd29yZA==
cache-control=no-cache
connection=Keep-Alive
Content-Length=353
content-type=text/xml; charset=UTF-8
host=127.0.0.1:6080
pragma=no-cache
SOAPAction="gpChiediListaVersamenti"
user-agent=Apache CXF 2.7.18
x-forwarded-for=172.16.171.198
x-forwarded-host=govpay-test.regione.basilicata.it
x-forwarded-server=govpay-test.regione.basilicata.it
------ Content ------
Size:367
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header/><soap:Body><ns2:gpChiediListaVersamenti xmlns:ns2="http://www.govpay.it/servizi/gpPrt/" xmlns:ns3="http://www.govpay.it/servizi/pa/"><codPortale>PubPortale</codPortale><codUnivocoDebitore>RSSANA85T10A542S</codUnivocoDebitore></ns2:gpChiediListaVersamenti></soap:Body></soap:Envelope>



<b1457462-90f5-44c5-b527-b1675c121c35>
Type:RESPONSE_OUT
------ Content ------
Size:353
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unmarshalling Error: cvc-complex-type.2.4.b: The content of element 'ns2:gpChiediListaVersamenti' is not complete. One of '{stato, ordinamento}' is expected. </faultstring></soap:Fault></soap:Body></soap:Envelope>

**Comment by nardil** [comment]
Si esatto, e' un parametro obbligatorio.

Lo iuv ti viene ritornato adesso? posso considerare risolto il bug?

**Comment by acoviello** [comment]
Si adesso ottengo gli iuv con annessi barcode e qrcode (che mi facilitano ancora di più la vita). Ad essere proprio pignoli ottengo un warning  per una richiesta strutturata così: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header/><soap:Body><ns2:gpChiediListaVersamenti xmlns:ns2="http://www.govpay.it/servizi/gpPrt/" xmlns:ns3="http://www.govpay.it/servizi/pa/"><codPortale>PubPortale</codPortale><codUnivocoDebitore>RSSANA85T10A542S</codUnivocoDebitore><stato>NON_ESEGUITO</stato><ordinamento>DATA_SCADENZA_DES</ordinamento></ns2:gpChiediListaVersamenti></soap:Body></soap:Envelope>


AVVERTENZA: Interceptor for {http://www.govpay.it/servizi/}PagamentiTelematiciGPPrtService#{http://www.govpay.it/servizi/}gpChiediListaVersamenti has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Unmarshalling Error: unexpected element (uri:"", local:"codDominio"). Expected elements are <{}stato>,<{}spezzoneCausale>,<{}spezzoneCausaleStrutturata>,<{}codVersamentoEnte>,<{}causale>,<{}codApplicazione>,<{}importoTotale>,<{}dataScadenza>
