### ISSUE TITLE
Esporre i dati relativi alla pendenza collegata ad una riscossione nel dettaglio riconciliazione.

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#276]
**Necessità:**
All'interno del dettaglio di una riconciliazione nella lista riscossioni e' necessario mostrare alcuni dati che sono relativi alla pendenza riferita.

**Soluzione:**
Attualmente all'interno dell'oggetto riscossione troviamo un link al dettaglio pendenza, sostituirlo con il vero oggetto pendenza.

**Comment by nardil** [comment]
@pintorig 

aggiungere nei dati di sommario il campo `data` che corrisponde a `data_ora_incasso` su db e verificare che i filtri `dataDa` e `dataA` agiscano su quello
per i riferimenti alla pendenza, aggiungere l'elemento vocePendenza come fatto nelle riscossioni delle api ragioneria


@simo-git 

Con le nuove informazioni modificare la presentazione delle riconciliazioni come segue (omettere le informazioni null)

- [ ] Aggiungere i filtri di ricerca "dataDa" e "dataA"
- [ ] Lista delle riconciliazioni: Titolo: `{sct}` Sottotitolo: `{causale}`, Sotto l'importo: `{data}`
- [ ] Dettaglio della riconciliazione: 
![Schermata da 2020-12-24 11-43-39](https://user-images.githubusercontent.com/12340738/103083685-502ac000-45dd-11eb-85e2-bb60a5d287c9.png)
- [ ] Gli elementi del dettaglio sono accordion che mostrano le seguenti informazioni aggiuntive:
  - Id voce pendenza: {vocePendenza.idVocePendenza}
  - Indice voce: {indice}
  - Descrizione: {vocePendenza.descrizione}
  - Causale: {vocePendenza.causaleRPT}
  - Id Riscossione: {iur}
  - Id a2a {vocePendenza.pendenza.idA2A}
  - Id pendenza: {vocePendenza.pendenza.idPendenza}

**Comment by pintorig** [comment]
@simo-git quando si inserisce una nuova riconciliazione, si ottiene un errore durante la visualizzazione del dettaglio dell'incasso appena inserito poiche' viene generata una url fatta cosi:

http://localhost:8080/govpay/backend/api/backoffice/rs/form/v1/incassi/undefined/RF32340000000000000009006

dove il valore idDominio risulta undefined

**Comment by pintorig** [comment]
@simo-git 

> Nella form di inserimento di una nuova riconciliazione, nel caso di riconciliazione con un flusso di rendicontazione, precompilare il campo "SCT" con il valore del campo TRN del flusso di rendicontazione

Quando si seleziona un flusso il valore del campo SCT viene correttamente valorizzato con il TRN, ma se poi seleziono uno IUV il campo SCT rimane valorizzato con il TRN, invece dovrebbe essere svuotato.

**Comment by atatarelli** [comment]
- [x] Nel riepilogo delle informazioni aggiungere la "Causale"
