### ISSUE TITLE
Recupero lista singoli versamenti GpChiediListaVersamentiResponse.Versamento

### ISSUE THREAD

**Issue by acoviello** [link-it/GovPay#28]
A seguito del caricamento di una posizione debitoria sul portale dei pagamenti online, nel momento in cui l'utente procede al pagamento tramite carta di credito dovrebbe avere la possibilità di vedere la tipologia di tributo che sta pagando. 
Al momento quando si visualizza la lista dei versamenti in debito, la primitiva GpChiediListaVersamentiResponse restituisce un oggetto Versamento privo della lista dei singoli versamenti che contengono al loro interno il codice tributo

**Comment by nardil** [comment]
la primitiva era pensata per dare informazioni di riepilogo sulla posizione debitoria del cittadino, pertanto si era deciso di fermarsi alle informazioni del versamento, senza scendere nel dettaglio dei singoli versamenti che lo compongono e lasciare questo compito ad altre primitive.
Puoi valutare se le informazioni rese dal dato _causaleVersamento_, magari nella sua forma strutturata (Formato C), ti fornisce le informazioni di cui hai bisogno?

Ti faccio riporto degli esempio di causale fatti da AgID per i tre formati disponibili:
**Formato A:**
Pagamento retta mensa scolastica alunno Mario Rossi
**Formato B:**
Violazione del codice della Strada
Auto targa AA 111 BB
21/12/12 ore 15,42
Importo ridotto
**Formato C:**
Violazione CdS €106,70
Importo sanzione €100,00
Sanzione €5,20
Interessi di mora €1,50

**Comment by nardil** [comment]
@acoviello non hai piu' dato feed... risolto con la causale strutturata?

**Comment by acoviello** [comment]
Si, scusa non ti ho dato un feedback. Abbiamo risolto con un codice versamento codificato in modo da tirar fuori il tributo e la rata collegata al versamento in debito
