### ISSUE TITLE
Integrazione MyPivot per caricamento dei pagamenti

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#282]
**Necessità:**
Integrazione ai servizi di riconciliazione MyPivot : https://www.regione.puglia.it/documents/410606/413675/MyPivot+-+Nota+tecnica+Integrazione+Ente+V.5.6.2.pdf/60cc0453-c0ec-3076-77bf-5794f2171116?t=1591803805170

**Soluzione:**

La piattaforma GovPay deve produrre periodicamente le esportazioni dei pagamenti completati da far riversare nel MyPivot dell'Ente Creditore

_Configurazione_

Aggiungere all'anagrafica dell'Ente Creditore la possibilita' di aggiungere dei connettori.

L'aggiunta di un connettore richiede queste informazioni:

- Tipo connettore: al momento solo MyPivot
- Abilitato (si/no. i campi indicati sotto tutti obbligatori se abilitato)
- Versione CSV (al momento con la sola opzione 1.0)
- Tipi pendenza applicabili (lista dei tipi pendenza tra quelli configurati per l'ente + TUTTI)
- Codice IPA
- Tipo connettore a scelta tra:
  - WebService (richiesti dati: URL e Password) 
  - Email (richiesti dati: indirizzo email a cui spedire)
  - File System (richiesto dati: path dove riversare i file)

_Database_

Aggiungere la tabella MYPIVOT_NOTIFICHE:
- id: notnull PK
- id_domini: notnull FK domini
- nome_file: notnull
- stato: notnull
- data_creazione: notnull
- data_rt_da: notnull
- data_rt_a: notnull
- data_caricamento
- data_completamento
- request_token
- upload_url
- authorization_token
- zip

Aggiungere alla tabella RT la FK a MYPIVOT_NOTIFICHE (nullable)

STATI DEL TRACCIATO
- `FILE_DUPLICATO` (terminale)
- `ERROR_LOAD` (terminale)
- `IMPORT_ESEGUITO` (terminale)
- `FILE_CARICATO`
- `FILE_DA_CARICARE`
- `FILE_NUOVO`

_Batch spedizione e aggiornamento stato_

Questo batch viene eseguito ogni 30 minuti

--- (caso spedizione via web service)

Dei tracciati in stato `FILE_CARICATO` richiede un aggiornamento di stato tramite il servizio “pivotSILChiediStatoImportFlusso”. Se lo stato ricevuto e' uno dei terminali, il tracciato transita in quello stato

Dei tracciati in stato `FILE_NUOVO`  esegue una richiesta al servizio “pivotSILAutorizzaImportFlusso” e salva le informazioni requestToken/uploadURL/authorizationToken su DB aggiornando lo stato in `FILE_DA_CARICARE`

Dei tracciati in stato `FILE_DA_CARICARE` ne esegue l'upload alla URL fornita. Al termine dell'upload aggiorna lo stato in `FILE_CARICATO`

--- (caso spedizione via email)

Dei tracciati in stato `FILE_NUOVO`  esegue la spedizione via mail all'indirizzo configurato. In caso di successo aggiorna lo stato in `FILE_CARICATO`, altrimenti lascia cosi

--- (caso spedizione via fs)

Dei tracciati in stato `FILE_NUOVO`  esegue la scrittura su FS al path indicato. In caso di successo aggiorna lo stato in `FILE_CARICATO`, altrimenti lascia cosi.

_Batch creazione flussi_

Questo batch viene eseguito alle 3 di mattina

Per ciascun ente che ha abilitato il connettore MyPay e che non ha tracciati pendenti ricerca i pagamenti positivi intercorsi dall'ultimo invio in stato `IMPORT_ESEGUITO` eseguito sulla base della ricezione dell'RT fino alla mezzanotte del giorno precedente e produce un CSV che rispetta la sintassi del tracciato della versione corrispondente a quella indicata:

- linea di testata: `IUD;codIuv;tipoIdentificativoUnivoco;codiceIdentificativoUnivoco;anagraficaPagatore;indirizzoP
agatore;civicoPagatore;capPagatore;localitaPagatore;provinciaPagatore;nazionePagatore;mailP
agatore;dataEsecuzionePagamento;importoDovutoPagato;commissioneCaricoPa;tipoDovuto;tip
oVersamento;causaleVersamento;datiSpecificiRiscossione;bilancio`
- separatore punto e virgola ;
- carattere di escape: doppio apice
- IUD: cod_applicazione@cod_versamento_ente
- codIuv: rt.datiPagamento.identificativoUnivocoVersamento
- tipoIdentificativoUnivoco:  rt.datiPagamento.soggettoPagatore.identificativoUnivocoPagatore.tipoIdentificativoUnivoco
- codiceIdentificativoUnivoco: rt.datiPagamento.soggettoPagatore.identificativoUnivocoPagatore.codiceIdentificativoUnivoco
- anagraficaPagatore: rt.datiPagamento.soggettoPagatore.anagraficaPagatore
- indirizzoPagatore: rt.datiPagamento.soggettoPagatore.indirizzoPagatore
- civicoPagatore: rt.datiPagamento.soggettoPagatore.civicoPagatore
- capPagatore: rt.datiPagamento.soggettoPagatore.capPagatore
- localitaPagatore: rt.datiPagamento.soggettoPagatore.localitaPagatore
- provinciaPagatore: rt.datiPagamento.soggettoPagatore.provinciaPagatore
- nazionePagatore: rt.datiPagamento.soggettoPagatore.nazionePagatore
- e-mailPagatore: rt.datiPagamento.soggettoPagatore.e-mailPagatore
- dataEsecuzionePagamento: rt.datiPagamento.datiSingoloPagamento[0].dataEsitoSingoloPagamento  [YYYY]-[MM]-[DD]
- importoDovutoPagato: rt.datiPagamento.importoTotalePagato
- commissioneCaricoPa: vuoto
- tipoDovuto: versamento.datiAllegati.mypivot.tipoDovuto o versamento.tassonomiaEnte o versamento.codTipoPendenza
- tipoVersamento: vuoto
- causaleVersamento: rt.datiPagamento.datiSingoloPagamento[0].causaleVersamento
- datiSpecificiRiscossione: rt.datiPagamento.datiSingoloPagamento[0].datiSpecificiRiscossione
- bilancio: versamento.datiAllegati.mypivot.bilancio o vuoto

Il tracciato viene salvato zippato su database in stato "FILE_NUOVO" con nome file "GOVPAY_{idDominio}_{id}.zip".

**Comment by pintorig** [comment]
Completata realizzazione della spedizione dei tracciati con modalita' Email e File System.
La spedizione tramite connettore WebService sara' realizzata appena avremo a disposizione un ambiente di simulazione per il servizio MyPivot.

**Comment by pintorig** [comment]
@simo-git Realizzare il cruscotto di configurazione per il connettore MyPivot

L'oggetto da utilizzare e' _dominio.connettoreMyPivot_, 

se e' presente tale oggetto in lettura aggiungere una card con i dati ricevuti dal server, nelle maschere di add ed edit invece mostrare una card con la seguente struttura:

- Abilitato (si/no. i campi indicati sotto tutti obbligatori se abilitato)
- Codice IPA: casella di testo
- Versione CSV: select list (al momento con la sola opzione 1.0)
- Tipi pendenza applicabili (lista dei tipi pendenza tra quelli configurati per l'ente + TUTTI, puoi utilizzare la stessa gestione delle autorizzazioni eliminando la voce 'Autodeterminazione')
- Tipo connettore a scelta tra:
  - Email (richiesti dati: indirizzo email a cui spedire)
  - File System (richiesto dati: path dove riversare i file)
 Quando si seleziona il tipo di connettore Email deve apparire casella di testo che consenta di inserire l'elenco dei destinatari separati da virgola;
Quando si seleziona il tipo di connettore FileSystem si deve indicare un path.

![Screenshot from 2021-02-18 11-40-49](https://user-images.githubusercontent.com/12812160/108345174-43da7200-71de-11eb-9568-715e37d3722b.png)

**Comment by nardil** [comment]
I dati di contabilita' prevedono la possibilita' di generare le informazioni come attese da MyPivolt. 
Procedere alle seguenti modifiche:

`tipoDovuto`: al posto di  versamento.datiAllegati.mypivot.tipoDovuto, utilizzare il campo versamento.vocePendenza.contabilita.proprietaCustom.tipoDovuto
`bilancio`: al posto di versamento.datiAllegati.mypivot.bilancio, costruire il json previsto da myPivot con l'array in versamento.vocePendenza.contabilita.quote, se specificate:

```json
<bilancio>
  <capitolo>
    <codice>cod1</codice>
    <importo>0.01</importo>
  </capitolo>
  <capitolo>
     <codice>cod2</codice>
     <importo>0.02</importo>
   </capitolo>
 ...
</bilancio>
```

**Comment by pintorig** [comment]
Intervento effettuato nel branch #309.
