### ISSUE TITLE
Filtri aggiuntivi nella pagina dei Pagamenti

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#283]
**Necessità:**
Aggiungere filtri alla pagina di consultazione dei pagamenti

- [x] @pintorig aggiungere un filtri per `idDominio`, `iuv`, `idA2A` e `idPendenza` alla risorsa `GET /pagamenti` di backoffice
- [x] @simo-git aggiungere un filtro per `Ente Creditore`,  `IUV/Numero Avviso`, `idA2A`, `idPendenza` nella pagina dei pagamenti

**Comment by pintorig** [comment]
@simo-git 
Trasformare il filtro idA2A in una select list allineando il filtro a quello presente nella Lista Pendenze.
