### ISSUE TITLE
Integrazione SECIM per export pagamenti eseguiti

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#285]
**Necessità:**
Analogamente a quanto fatto per l'integrazione a MyPivot (#282), consentire la configurazione di un connettore per l'integrazione a SECIM per la condivisione dei pagamenti relativi ai servizi cimiteriali

**Soluzione:**
Estendere la configurazione dell'ente per impostare i parametri di configurazione del connettore SECIM. Il connettore consentira' l'invio tramite File System o Email e la selezione dei tipi pendenza oggetto dell'export.

**Comment by nardil** [comment]
Per il riferimento ente, prevedere l'uso del parametro `$pendenza.{datiAllegati}.secim.riferimentoCreditore` o, in sua assenza, il campo `$pendenza.voce[0].idVoce`

**Comment by pintorig** [comment]
@simo-git Realizzare il cruscotto di configurazione per il connettore Secim, in maniera simile a quanto realizzato per il connettore MyPivot

L'oggetto da utilizzare e' _dominio.connettoreSecim_:

se e' presente tale oggetto in lettura aggiungere una card con i dati ricevuti dal server, nelle maschere di add ed edit invece mostrare una card con la seguente struttura:

- Abilitato (si/no. i campi indicati sotto tutti obbligatori se abilitato)
- Codice Cliente: casella di testo
- Versione CSV: select list (al momento con la sola opzione 7.0)
- Codice Istituto: casella di testo (opzionale)
- Tipi pendenza applicabili (lista dei tipi pendenza tra quelli configurati per l'ente + TUTTI, puoi utilizzare la stessa gestione delle autorizzazioni eliminando la voce 'Autodeterminazione')
- Tipo connettore a scelta tra:
  - Email (richiesti dati: indirizzo email a cui spedire)
  - File System (richiesto dati: path dove riversare i file)
Quando si seleziona il tipo di connettore Email deve apparire casella di testo che consenta di inserire l'elenco dei destinatari separati da virgola;
Quando si seleziona il tipo di connettore FileSystem si deve indicare un path.

**Comment by nardil** [comment]
L'importazione del tracciato da errore sulla sintassi dell'importo che al momento presenta il separatore dei decimali (`.`) non previsto dalla specifica del formato: 

> IMPORTO PAGATO: importo pagato. Espresso in centesimi di euro;

**Comment by nardil** [comment]
Prevedere la seguente evolutiva:

se il versamento presenta il valore `$pendenza.{datiAllegati}.secim.tipoRiferimentoCreditore` valorizzato allora il pagamento non viene incluso in un tracciato secim ordinario, ma in un nuovo tracciato che ha la stessa sintassi del tracciato SECIM, ma presenta nel campo RIFERIMENTO CREDITORE (16) usando come prefisso quando indicato in `tipoRiferimentoCreditore` al posto del consueto `SECIM`

Il secondo tracciato viene incluso nell'archivio ZIP consegnato all'ente riportante nel nome la dicitura "NOSECIM" .

**Comment by nardil** [comment]
A valle dell'introduzione del campo contabilita (https://github.com/link-it/govpay/issues/309) si rivede la logica di generazione del flusso secim con queste modifiche:

i campi 

- $pendenza.{datiAllegati}.secim.tipoRiferimentoCreditore
- $pendenza.{datiAllegati}.secim.riferimentoCreditore
- $pendenza.{datiAllegati}.secim.tipoflusso

vengono tutti spostati in `$pendenza.vocePendenza[0].contabilita.datiCustom`

**Comment by pintorig** [comment]
Intervento effettuato nel branch #309.
