### ISSUE TITLE
Script di installazione GOVPAY con configurazione http non passa correttamente l'informazione "protocollo"

### ISSUE THREAD

**Issue by johnatandante** [link-it/govpay#288]
**Descrizione del Bug**
Nello script di installazione, indicando protocollo=http, imposta protocollo=https  
Questo invalida la configurazione delle api (es /govpay/backend/api/backoffice/) incorrendo in un cross origin issue 

**Come riprodurlo:**
Avviare lo script install.sh 
Impostare protocollo = "http" e porta "80"

**Risultato atteso:**
Il pacchetto ear viene generato con i riferimenti alle api su protocollo http

**Screenshots:**
Nel file ./govpay-installer-3.3.3/installer/setup/build.xml
![image](https://user-images.githubusercontent.com/1397275/107534211-01061200-6bc0-11eb-9ee2-b06f46b6b320.png)

**Ambiente:**
 - OS: Linux Ami 2
 - Browser: Chrome 75
 - GovPay: 3.3.3
 - AS: WildFly 18
 - Java: OpenJDK 1.8.0_201
 - DBMS: Postgres 9.6

**Note aggiuntive:**
Ulteriori informazioni utili all'identificazione e risoluzione del problema

**Comment by nardil** [comment]
Grazie della segnalazione @johnatandante 

Dovremmo aver corretto, fammi sapere se anche a te risulta.
