### ISSUE TITLE
Servizio di export pagamenti GovPay

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#293]
**Necessità:**
Fornire un servizio di rendicontazione dei pagamenti effettuati agli Enti.

**Soluzione:**
Come gia' fatto per SECIM e MyPivot, prevedere un Connettore di "Rendicontazione pagamenti GovPay". Il connettore inizialmente deve prevedere la sola modalità via email, con possibilità di indicare la lista dei tipiPendenza da esportare e la versione del CSV di export.

All'indirizzo email indicato sara' inviato un archivio (`GovPay_Export_{idTracciato}.zip`) contenente:
- File json con i metadati dell'estrazione, come il periodo di osservazione, tipipendenza estratti, versione, etc.. (metadata.json)
- File CSV con la sintesi dei pagamenti ricevuti (`govpay_rendicontazione.csv`)
- File CSV con la sintesi dei flussi rendicontazione (`govpay_flussi_rendicontazione.csv`) 
- File XML delle ricevute telematiche: (`./RT/{idDominio}_{iuv}_{ccp}.xml`)
- File XML dei flussi di rendicontazione: (`./FlussiRendicontazione/{idFlusso}_{data}.xml`)

Il tracciato CSV deve presentare i seguenti parametri per ogni singola voce di pagamento con importo maggiore di 0 delle RT afferenti alle tipologie pendenze abilitate:

- idA2A: da pendenza
- idPendenza: da pendenza
- idDocumento: da pendenza
- codiceRata: da pendenza
- dataScadenza: da pendenza
- idVocePendenza: da pendenza
- idTipoPendenza: da pendenza
- anno: da pendenza
- identificativoDebitore: da RT
- anagraficaDebitore: da RT
- identificativoDominio: da RT
- identificativoUnivocoVersamento: da RT
- codiceContestoPagamento:da RT
- indiceDati: da RT 
- identificativoUnivocoRiscossione: da RT
- singoloImportoPagato: da RT
- dataEsitoSingoloPagamento: da RT
- causaleVersamento: da RT
- datiSpecificiRiscossione: da RT
- datiAllegati: da Pendenza
- datiAllegatiVoce: da vocePendenza
- denominazioneAttestante: da RT
- identificativoAttestante: da RT

**Comment by pintorig** [comment]
Definizione del formato del file di sintesi dei flussi di rendicontazione:

- identificativoFlusso: da FR.identificativoFlusso
- dataOraFlusso: da FR.dataOraFlusso
- identificativoDominio: da FR.codDominio
- identificativoUnivocoRegolamento: da FR.identificativoUnivocoRegolamento
- dataRegolamento: da FR.dataRegolamento
- codiceBicBancaDiRiversamento: da FR.codiceBicBancaDiRiversamento
- numeroTotalePagamenti: da FR.numeroTotalePagamenti
- importoTotalePagamenti: da FR.importoTotalePagamenti
- identificativoUnivocoVersamento: da FR.ctDatiSingoliPagamenti[i].identificativoUnivocoVersamento
- identificativoUnivocoRiscossione: da FR.ctDatiSingoliPagamenti[i].identificativoUnivocoRiscossione
- indiceDatiSingoloPagamento: da FR.ctDatiSingoliPagamenti[i].indiceDatiSingoloPagamento
- singoloImportoPagato: da FR.ctDatiSingoliPagamenti[i].singoloImportoPagato
- codiceEsitoSingoloPagamento: da FR.ctDatiSingoliPagamenti[i].codiceEsitoSingoloPagamento
- dataEsitoSingoloPagamento: da FR.ctDatiSingoliPagamenti[i].dataEsitoSingoloPagamento
- denominazioneMittente da FR.istitutoMittente.denominazioneMittente
- identificativoMittente da FR.istitutoMittente.identificativoUnivocoMittente.codiceIdentificativoUnivoco
- denominazioneRicevente da FR.istitutoRicevente.denominazioneRicevente
- identificativoRicevente da FR.istitutoRicevente.identificativoUnivocoRicevente.codiceIdentificativoUnivoco

**Comment by pintorig** [comment]
@simo-git Realizzare il cruscotto di configurazione per il connettore GovGay, in maniera simile a quanto realizzato per il connettore Secim #285

In questo caso l'oggetto da utilizzare e' _dominio.connettoreGovPay_:

le maschere di add ed edit invece mostrare una card con la seguente struttura:

- Abilitato (si/no. i campi indicati sotto tutti obbligatori se abilitato)
- Versione CSV: select list (al momento con la sola opzione 7.0)
- Tipi pendenza applicabili (lista dei tipi pendenza tra quelli configurati per l'ente + TUTTI, puoi utilizzare la stessa gestione delle autorizzazioni eliminando la voce 'Autodeterminazione')
- Modalita' Consegna: EMAIL (c'e' solo questa modalita' per adesso, prevederei una label da mostrare all'utente ('Email') e si inserisce il valore 'EMAIL' fisso nel campo  connettoreGovPay.tipoConnettore)
- Destinatari: casella di testo che consenta di inserire l'elenco dei destinatari separati da virgola
- Subject: casella di testo che consenta di inserire un Subject personalizzato per la mail (campo opzionale)

**Comment by pintorig** [comment]
@simo-git 

- [ ] Aggiungere la modalita' di consegna FILE SYSTEM (richiesto dati: path dove riversare i file), come negli altri due connettori.
- [ ] La versione del CSV deve presentare solo l'opzione 1.0
- [ ] Nella lista dei connettori, sostituire i tre dot con il tasto +
![Screenshot from 2021-03-19 15-59-55](https://user-images.githubusercontent.com/12812160/111800538-57a3f180-88cc-11eb-8a4a-33806cc2d953.png)

**Comment by nardil** [comment]
Aggiungere nel tracciato dei pagamenti i campi

- descrizione (pendenza.causale, dopo `idTipoPendenza`)
- descrizioneVoce (dendenza.voce[].descrzione, dopo `descrizione`)
- modelloPagamento (da rt, dopo `identificativoRicevente`)

**Comment by nardil** [comment]
Aggiungere il campo `contabilita` in fondo al record di esportazione. Come valore inserire il json originale.

**Comment by pintorig** [comment]
Intervento effettuato nel branch #309.
