### ISSUE TITLE
Gestione autorizzazioni in api Pendenze

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#295]
**Descrizione del Bug**
La gestione delle autorizzazioni per UO nelle api pendenze non applica i corretti filtri nelle query di ricerca

**Come riprodurlo:**
Impostare autorizzazioni su piu' EC con indicazione di UO specifiche ed acquisire la lista delle pendenze

**Risultato atteso:**
Attualmente alla ricerca su DB sono applicati i seguenti filtri in AND per filtrare le sole pendenze autorizzate:

- idApplicazione
- idDominio
- idUO

I filtri per idDominio e idUO, risultano non opportunamente valorizzati e dovrebbero essere in OR, ma tanto premesso, sono superflui dal momento che dalle API Pendenze l'applicazione chiamante e' autorizzata ad operare per tutte le pendenze a lei intestate, pertanto il filtro per idApplicazione e' sufficiente.

**Comment by pintorig** [comment]
Alla versione 3.4.x e' stata aggiunta un'ottimizzazione nella ricerca dei versamenti, per ottenere anche il documento collegato al versamento con un'unica query.
