### ISSUE TITLE
configurazione web connector per la gestione di più portali per singolo dominio

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#297]
Buongiorno 
oltre all'indicazione della  url di ritorno nella chiamata di pagamento, è necessario procedere con installazione/configurazione del connector ? Nella documentazione ho trovato  genericamente questa indicazione

grazie 

4.7.2 Redirezione con più portali di pagamento
La piattaforma pagoPA consente di configurare una url per Ente Creditore a cui i Soggetti Pagatori vengono rediretti
al temine del processo di pagamento ad iniziativa Ente. Questa URL è la pagina del Portale di Pagamento dove il
pagatore visualizza l’esito della transazione.
Nel caso in cui l’Ente Creditore disponga di più Portali di Pagamento, può gestire la redirezione tramite l’ausilio del
componente Web Connector di GovPay. Il ritorno del Soggetto Pagatore può essere gestito specificando la URL di
ritorno nella richiesta di pagamento.
Il Web Connecctor di GovPay si farà carico di redirigere il navig

 
     }
   ],
    "urlRitorno": "https://comune.forlimpoppoli.it/",
   "autenticazioneSoggetto": "N/A"
}

**Comment by nardil** [comment]
Ciao @asterixol2000 ,

e' sufficiente indicare sul Portale delle Adesioni la URL del Web Connector nella configurazione della Stazione: `/govpay/rs/pub/backUrl`

in questo modo al ritorno dal pagamento pagoPA indirizzera' il Web Connector che redirigera' alla URL indicata in sede di pagamento.

Aggiungiamo questo dettaglio nel manuale.

**Comment by frdidonato** [comment]
Buongiorno,
abbiamo problemi nella configurazione del web connector sul portale delle adesioni.
Dobbiamo fare qualcosa per abilitare sull'installazione di GovPay il connettore o il componente funziona già di default ?
Da quello che leggo bisogna inserire sul portale delle adesioni l'url 
`https://{host}/govpay/rs/pub/backUrl` 
per far in modo che gli esiti dei pagamenti vengano rediretti correttamente agli url di ritorno specificati al momento del pagamento, però non riusciamo a trovare nei sorgenti di GovPay alcun riferimento a questo path.
Leggendo la documentazione, nella parte relativa alla verifica dell'installazione, abbiamo notato che uno dei componenti che vengono installati è 
`/govpay/frontend/web/connector`
 che almeno per il nome sembra fare riferimento alle nostre esigenze. 
Abbiamo così verificato la presenza dell'applicazione che ci ha restituito un wadl e abbiamo testato delle chiamate rest di tipo GET per verificarne il funzionamento.
Il servizio risponde correttamente con i seguenti parametri 
`http://<host>/govpay/frontend/web/connector/ecsp/psp?idSession=<idSessione>&esito=<esito>`

Ora la domanda è, quale url bisogna configurare sul portale delle adesioni ?

1. `https://{host}/govpay/rs/pub/backUrl` 
2. `https://{host}/govpay/frontend/web/connector` 
3. `http://{host}/govpay/frontend/web/connector/ecsp/psp`

Grazie mille in anticipo per la risposta

**Comment by nardil** [comment]
Ciao @frdidonato ,

perdonami, ma la mia precedente indicazione era errata: la URL `/govpay/rs/pub/backUrl` è relativa ad una precedente versione del prodotto.

Quella corretta da indicare nel Portale delle Adesioni è quella che hai indicato al punto 3: `/govpay/frontend/web/connector/ecsp/psp`

**Comment by frdidonato** [comment]
Grazie mille per la risposta celere,
Buon lavoro
