### ISSUE TITLE
Problema permessi da e verso pagoPA con modello 1 e 3

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#299]
Ciao a tutti,
prima di arrivare ai problemi di seguito indicati, faccio un breve riepilogo degli step eseguiti:
- eseguito un installazione, seguendo la documentazione ufficiale, della versione 3.3.3 di Govpay senza nessun problema
- completato le procedure per attivazione della stazione sul PdA 
- usato il certificato di pagoPA nel trutstore e il mio certificato (fornito anche a pagoPA) nel keystore
- in govpay configurato l'intermediario (Principal=subject di pagopa, servizio RPT=URL fornita da pagoPA, autenticazione=nessuna)
- lasciata la conf di default sugli xml spring 

Ho i seguenti problemi MODELLO 3:
- provando ad eseguire un pagamento da appIO (in allegato i log) ricevo le richieste ma ho il seguente errore:
`org.springframework.security.access.AccessDeniedException: Access is denied`

Ho i seguenti problemi MODELLO 1:
- provando ad avviare un pagamento con API pagamento (in allegato i log) ho il seguente errore:
`You don't have permission to access /openspcoop2/proxy/PA/RPT6T`

Non so se sono cause dello stesso problema sui certificati,
grazie in anticipo!
[govpay_log_mod1.log](https://github.com/link-it/govpay/files/6177632/govpay_log_mod1.log)
[govpay_root_log_mod3.log](https://github.com/link-it/govpay/files/6177633/govpay_root_log_mod3.log)
[govpay_dump_log_mod1.log](https://github.com/link-it/govpay/files/6177634/govpay_dump_log_mod1.log)

**Comment by giuseppeformaro** [comment]
Salve,
sui problemi relativi al pagamento MODELLO 1, sono riuscito a RISOLVERE la comunicazione con pagoPA configurando il keystore nelle JAVA_OPTS (cosi come indicato in https://github.com/link-it/govpay/issues/80), nelle prove precedenti era configutato come security-realms in wildfly.

Rimane invece il problema con MODELLO 3.

**Comment by nardil** [comment]
Ciao @giuseppeformaro ,

dalla descrizione e dai log risulta che il traffico verso pagoPA sia operativo, mentre non viene autorizzato il traffico in ingresso. Questo risulta causato dal fatto che la richiesta in arrivo da pagoPA non presenta le informazioni utili all'autenticazione del chiamante. Immaginando che ci sia un frontend che termina la comunicazione SSL, quest'ultimo deve essere configurato per inoltrare le richieste provenienti da pagoPA comprensive dei dati del certificato chiamante. La soluzione più semplice per ottenere questo comportamento e' quella di utilizzare il connettore AJP di Wildfly per l'inoltro piuttosto che quello http.

**Comment by giuseppeformaro** [comment]
Ciao,
per evitare di avere ulteriori strati ho wildfly direttamente esposto sulla 8443 con il certificato nel truststore, ma nulla! 
Dal log che allego di wildfly in DEBUG pare che non trova il certificato nel truststore ma aprendo con un tool quest'ultimo non vedo problemi.
[test_IUV_appIO_truststore.log](https://github.com/link-it/govpay/files/6189185/test_IUV_appIO_truststore.log)
![truststore_pagoPA](https://user-images.githubusercontent.com/72001866/112139738-71e31580-8bd3-11eb-953d-60401c77b0be.PNG)

**Comment by nardil** [comment]
Nel truststore hai inserito tutta la catena di trust del certificato?

**Comment by giuseppeformaro** [comment]
Ciao,
alla fine dovrei avere risolto anche per le invocazioni da pagoPA a GovPay (MOD3). In poche parole:
- va abilitato su wildfly la verifica del certificato client (verify-client="REQUIRED"), ma va fatto su un socket-binding dedicato, ad esempio come da te suggerito su AJP oppure come ho fatto io su un altro https che risponde sulla 9443, altrimenti si creano problemi alle api che non usano autenticazione client
- nel truststore è sufficiente mettere la CA del certificato pagoPA (mentre il certificato fornito è usato per le autorizzazioni confrontando il subject dello stesso con il principal dell'intermediario).

Grazie mille!

**Comment by mallomix** [comment]
Ciao @giuseppeformaro alla fine sono arrivato a questo TOPIC e ho trovato molte attinenze sul mio problema.
Io ho un server che fa da VIP prima di arrivare su GOVPAY dove c'era la terminazione SSL. A questo punto il primo step è ovviamente quello di fare forward di tutto senza che il server VIP termini la connessione SSL, tramite una funziona pass-throught.

Dopo di che la configurazione del trustore e keystore è identica all tua ma tutte le API volevano l'autenticazione client SSL.

Leggendo il tuo topic vedo che tu hai risolto facendo un nuovo socket-binding dedicato alle API di pagopa che risponde alla 9443 e abilitato la (verify-client="REQUIRED") .

Non è che mi puoi dare degli esempi di come hai fatto? condividento i file di configurazione? perchè non ho grossa dimestichezza con wildfly.

**Comment by giuseppeformaro** [comment]
Ciao @mallomix,
certo questo quanto ho configurato:

```
<server name="default-server">
                ...
                <https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="true"/>
                <https-listener name="https-pagopa" socket-binding="https-pagopa" security-realm="ApplicationRealm" verify-client="REQUIRED" enable-http2="true"/>
                ...
</server>
...
<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
...
<socket-binding name="https" port="${jboss.https.port:8443}"/>
<socket-binding name="https-pagopa" port="${jboss.https.port:9443}"/>
...
</socket-binding-group>
```

Spero di aver inteso bene la tua richiesta...

**Comment by mallomix** [comment]
Grazie @giuseppeformaro 

è esattamente ciò che mi serviva. Ti faccio una domanda ma dal momento che hai messo verify-client="REQUIRED"  , per poter accedere alle API di pagopa (ad esempio dal browser per scaricare il wsdl) non hai dovuto impostare nel client il certificato e la chiave PRIVATA? come se il client dovesse criptare i dati ? non dovrebbe essere usata dal client solo la chiave pubblica e verificata dal server con il trustore?
