### ISSUE TITLE
Govpay Docker image

### ISSUE THREAD

**Issue by bhack** [link-it/GovPay#30]
Is it possible starting from one of the Jboss official [docker images](https://hub.docker.com/u/jboss/) to have an official GovPay entry on dockerhub and a dockerfile in this repository?

**Comment by nardil** [comment]
@bhack Yes, we are working on it. I'll keep you updated on the progress.

**Comment by bhack** [comment]
@nardil Thank you. If you need some support on a work in progress please ping me I could have some resources.

**Comment by lenlen** [comment]
@nardil in https://github.com/link-it/GovPay/pull/31 there a first draft for Docker GovPay, What do you think about it?

**Comment by nardil** [comment]
Seems very good on a first look! Thanks @lenlen for the contribution, @marklar79 is verifying it.

**Comment by bhack** [comment]
When will be merged Link-it could add an official entry on [hub](https://hub.docker.com).

**Comment by nardil** [comment]
Merged the docker files sent by @lenlen in master branch (#31) and moved into `resources` folder.
We will add an hub entry and related info on `README.md` soon. Thanks for your contribution!

**Comment by bhack** [comment]
Thanks
