### ISSUE TITLE
Redirezione con più portali di pagamento

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#300]
Buongiorno , 
ho una domanda, sul web connector.
Guardando il wadl del servizio vedo che i parametri accettati sono idsessione ed esito, ovvero quello che pagopa invia sulla redirect alla url settata sulla stazione.

Se provo a simulare una chiamata con i parametri il servizio https://{host}/govpay/frontend/web/connector/ecsp//psp?idSession=1&esito=ok il servizio prende Internal Server Error 

Se invece provo la url da settare sulla stazione presente nella documentazione e simulo la chiamata https://{host}/govpay/rs/pub/backUrl ottengo 404 non trovato . Sbaglio la chiamata , oppure per caso la funzionalità non è prevista sulla versione 3.2.2 ?

**Comment by nardil** [comment]
Ciao @asterixol2000 ,

il path corretto e' `/govpay/frontend/web/connector/ecsp/psp` (hai inserito uno `/` di troppo):

```
curl -k "https://demo.govcloud.it/govpay/frontend/web/connector/ecsp/psp?idSession=1&esito=ok"

< HTTP/1.1 404 Not Found
< X-Govpay-IdTransazione: e3bd8bd0-8bfe-4049-bdd1-16a88184bcd6
< Content-Type: application/json
{
  "categoria":"OPERAZIONE",
  "codice":"404000",
  "descrizione":"Risorsa non trovata",
  "dettaglio":"Non esiste un pagamento associato all'ID sessione Psp [1]"
}
```

Ovviamente con un `idSession` valido si ottiene un `HTTP 303` verso la URL fornita in avvio di pagamento.

Risulta comunque errata la gestione nel caso non vengano passati i parametri previsti (Internal Server Error). Apro un bug a riguardo.
