### ISSUE TITLE
Attivazione Modello 3

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#302]
Premetto che GovPay è in funzione per il modello 1 da mesi con ottimi risultati. Abbiamo ora attivato presso PagoPa il modello 3 per pagare con qr code, ma nonostante tutto sia attivo con anche codice cbill le operazioni non vanno a buon fine e sembra che non riesca a recuperare la pendenza quando pagopa interroga il mio server. Tra le pendenze c'è il codice IUV è corretto ma non la trova. Bisogna per caso fare qualche operazione di configurazione in GovPay per il modello 3?
Grazie.

**Comment by temptationisla** [comment]
Al momento del test ricevo questo warning:
WARN  | org.apache.cxf.common.logging.LogUtils:475 | a1790468-a127-4cdd-ab89-8e2e83e3c32c | Interceptor for {http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciRT}PagamentiTelematiciRTservice has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Message part {http://ws.pagamenti.telematici.gov/}paaVerificaRPT was not recognized.  (Does it exist in service WSDL?)

**Comment by nardil** [comment]
Sembra che la richiesta di verifica, appartenente al servizio `PagamentiTelematiciCCPservice`, stia arrivando al servizio `PagamentiTelematiciRTservice`.

La cosa piu' probabile e' che non sia stato comunicata correttamente la URL del servizio modello 3 sul Portale delle Adesioni.

**Comment by temptationisla** [comment]
E' proprio questo, grazie
