### ISSUE TITLE
Configurazione web connector GovPay

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#303]
Buongiorno,
abbiamo problemi nella configurazione del web connector sul portale delle adesioni.
Dobbiamo fare qualcosa per abilitare sull'installazione di GovPay il connettore o il componente funziona già di default ?
Da quello che leggo bisogna inserire sul portale delle adesioni l'url 
`https://{host}/govpay/rs/pub/backUrl` 
per far in modo che gli esiti dei pagamenti vengano rediretti correttamente agli url di ritorno specificati al momento del pagamento, però non riusciamo a trovare nei sorgenti di GovPay alcun riferimento a questo path.
Leggendo la documentazione, nella parte relativa alla verifica dell'installazione, abbiamo notato che uno dei componenti che vengono installati è 
`/govpay/frontend/web/connector`
 che almeno per il nome sembra fare riferimento alle nostre esigenze. 
Abbiamo così verificato la presenza dell'applicazione che ci ha restituito un wadl e abbiamo testato delle chiamate rest di tipo GET per verificarne il funzionamento.
Il servizio risponde correttamente con i seguenti parametri 
`http://<host>/govpay/frontend/web/connector/ecsp/psp?idSession=<idSessione>&esito=<esito>`

Ora la domanda è, quale url bisogna configurare sul portale delle adesioni ?

1. `https://{host}/govpay/rs/pub/backUrl` 
2. `https://{host}/govpay/frontend/web/connector` 
3. `http://{host}/govpay/frontend/web/connector/ecsp/psp`

Grazie mille in anticipo per la risposta

**Comment by nardil** [comment]
Come risposto e risolto in #297
