### ISSUE TITLE
[paaInviaRT] - Non riesco ad individuare la primitiva in nessuno dei log applicativi

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#305]
Salve e grazie in anticipo per il supporto,
Sto effettuando i test per l'accreditamento e riesco ad effettuare un pagamento con successo. Al termine del pagamento pago pa invia anche la RT di pagamento avvenuto all'indirizzo email indicato.
Su govpay però, nella sezione Pagamenti,  vedo questo pagamento con stato "Pagamento in corso" e rimane sempre così. In nessuno dei log applicativi riesco ad individuare la soap request e response della primitiva "**paaInviaRT**" da fornire in allegato al test case. Sto sbagliando qualcosa oppure ho un problema di configurazione della piattaforma ?

**Comment by nardil** [comment]
Ciao @frdidonato ,

se il pagamento risulta in corso, significa che a GovPay non e' pervenuta la RT. Dovresti verificare sul Giornale degli Eventi se risulta questa chiamata (ad esempio dal dettaglio della pendenza). Se non c'e', dovresti verificare sui componenti di frontiera (firewall, reverse proxy, ...). Se non c'e' niente neppure li, verificare la configurazione comunicata a pagoPA dal portale delle adesioni.

**Comment by frdidonato** [comment]
Grazie mille,
è infatti risultato essere un problema di configurazione della comunicazione con PagoPa e dei certificati sulla macchina di GovPay
