### ISSUE TITLE
Filtri aggiuntivi nella pagina delle Enti creditori

### ISSUE THREAD

**Issue by atatarelli** [link-it/govpay#307]
**Necessità:**
Aggiungere i filtri di ricerca per nome/codice fiscale e per "id dominio"

**Note:**
Aggiungerli in testa come primi elementi.

**Comment by nardil** [comment]
@pintorig 

aggiungere al servizio di ricerca domini i seguenti filtri case insensive in like:
-[] `ragioneSociale` 
-[] `idDominio`

utilizzare questi parametri di ricerca per la realizzazione dei filtri "Ragione sociale" e "Id dominio"

**Comment by nardil** [comment]
Con l'occasione correggere il dettaglio del Dominio sostituendo la label `Codice fiscale` con `Id dominio`
