### ISSUE TITLE
Primitiva nodoChiediCopiaRT non viene invocata

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#312]
Salve e perdonate nuovamente il disturbo,
Ho seguito queste istruzioni per scatenare la primitiva nodoChiediCopiaRT ma sul log e sul giornale degli eventi non ne trovo traccia.
Per effettuare il pagamento senza successo, come suggerite, ho effettuato un pagamento utilizzando una carta non riconosciuta (indicata nel piano dei test come carta fake che avrebbe dato esito fallimentare). L'operazione da pagoPa è stata rifiutata, ho provveduto ad eseguire la query e il recupero dei pagamenti come da indicazioni ma senza successo.
Sto sbagliando qualcosa ?

Grazie come sempre per la cortese sollecitudine

```
Procedi in questo modo:

1. Esegui un pagamento senza successo e recupera `idDominio`, `IUV` e `CCP`
1. Accedi al database di GovPay ed effettua la seguente query: `update rpt set stato='RPT_ACCETTATA_NODO' where cod_dominio='{idDominio}' and iuv='{IUV}' and ccp='{CCP}';`
1. Sempre dal cruscotto, vai nella sezione Manutenzione e avvia il Recupero pagamenti pendenti
1. Al termine del processo, nel giornale degli eventi dovresti trovare le primitive `nodoChiediListaPendenti`, `nodoChiediStatoRPT` e `nodoChiediCopiaRT`

_Originally posted by @nardil in https://github.com/link-it/govpay/issues/180#issuecomment-598801045_
```

**Comment by frdidonato** [comment]
Salve, la issue https://github.com/link-it/govpay/issues/311#issue-855859516 collegata a questa è stata risolta.
In realtà l'errore sembra essere nei sorgenti, in particolare alla riga 272 della classe RptUtils (GovPay core 3.3.1)

`chiediStatoRptClient.getEventoCtx().setIdA2A(rpt.getVersamento().getApplicazione(configWrapper).getCodApplicazione());`

la chiamata get 'rpt.getVersamento()' restituisce un valore null e l'applicazione va in nullpointer. Ho effettuato una prova sostituendo la riga precedente con questa

`chiediStatoRptClient.getEventoCtx().setIdA2A(rpt.getVersamento(configWrapper).getApplicazione(configWrapper).getCodApplicazione());`

Inoltre ho dovuto effettuare un update nella tabella pagamenti, settando per il pagamento l'id_rpt = null per permettere tramite il menu Manutenzione, recupero pagamenti di recuperare l'rt con successo. 
Adesso nel log vedo la chiamata alla primitiva.

Ho analizzato una precedente versione di GovPay (3.2) e la stessa riga sembra essere corretta

**Comment by nardil** [comment]
Dovresti aggiornare all'ultima versione rilasciata dove e' gia' presente il fix da te individuato:

https://github.com/link-it/govpay/blob/6035f661e38cddc3b817d55bd0d7641d12da292d/jars/core/src/main/java/it/govpay/core/utils/RptUtils.java#L272
