### ISSUE TITLE
Possibilita' di indicare Autorizzazione PT per singolo conto postale

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#313]
Salve,
ho un dubbio sulla configurazione in oggetto. Provo a dettagliarla:

**SITUAZIONE ATTUALE**
Ho più Autorizzazione stampa PT per un Ente (sul quale sono in uso diversi IBAN postali) ma posso configurarne solo uno.

**RISULTATO ATTESO**
Poter configurare l'Autorizzazione stampa PT come attributo della Pendenza e non dell'Ente.

Non so se mi sfugge qualcosa,
grazie

**Comment by nardil** [comment]
Grazie per la segnalazione @giuseppeformaro , 

avevamo forse erroneamente considerato l'autorizzazione legata all'ente che prescindesse dal conto utilizzato e l'assunzione aveva sempre trovato riscontro nelle situazioni gestite (o almeno nessuno aveva fatto la tua osservazione).

Potremmo prevedere la possibilità di aggiungere alla configurazione del conto di accredito (quando postale) con questa informazione che verrebbe utilizzata per perfezionare la stampa del bollettino associato, senza doverla indicare nella pendenza.

Ti sembra una soluzione ragionevole?

**Comment by giuseppeformaro** [comment]
Ciao @nardil è il primo posto dove sono andato naturalmente per configirarla, quindi direi di sì, se flag postale è abilitato allora posso inserire anche autorizzazione. 

Grazie!

**Comment by nardil** [comment]
@pintorig 

Aggiungere al servizio di registrazione dei Conti di Accredito il parametro opzionale `autStampaPosteItaliane` che, se impostato, sovrascrive quello configurato a livello di Ente Creditore in sede di stampa dell'avviso.

@simo-git 

Nelle maschere di inserimento/modifica di un Conto di Accredito, quando postale mostrare il campo di test opzionale `Autorizzazione stampa PT`  (alla stregua del campo `Intestatario del conto`) che valorizza il campo `autStampaPosteItaliane`

**Comment by nardil** [comment]
@simo-git 

spostare il parametro `autorizzazione` del tracciato di input al jasper all'interno dell'elemento `rata` per consentire valorizzazioni diverse in caso vengano usati conti diversi
