### ISSUE TITLE
Tracciato CSV di esito con blank line in eccesso

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#316]
**Descrizione del Bug**
Il tracciato CSV di esito di un caricamento massivo presenta i record correttamente, ma intervallati da una linea vuota che non dovrebbe essere presente.

**Comment by pintorig** [comment]
@simo-git nella sezione Impostazioni, quando si caricano i template delle trasformazioni per i tracciati csv, i file caricati vengono codificati in base64 per essere inviati al server. Il Base64 ricevuto dal server (ho decodificato il contenuto della richiesta che fa il cruscotto), contiene una riga bianca in fondo che provoca la generazione del CSV di esito con le righe bianche.

**Comment by simo-git** [comment]
Ho fatto alcune prove di salvataggio e caricamento partendo dai file presenti su dev. Inizialmente il file corrispondente al template del "caricamento" presentava linee vuote al suo interno. Ho ripulito la struttura del file e caricato nuovamente il nuovo contenuto. Tracciando in console, il base64 decodificato, al momento del salvataggio, non mi risultano alterazioni dovute a linee vuote aggiuntive o intermedie. Il componente angular non modifica il contenuto (e ciò che si vede nel preview del browser è indipendente dal valore presente nel json). E' possibile che sia stato caricato in origine già con linee vuote al suo interno?

<img width="580" alt="Screen Shot" src="https://user-images.githubusercontent.com/41443416/119019779-d76a3d00-b99d-11eb-870f-cfc1c0345b8f.png">
<img width="1114" alt="Screen Shot_1" src="https://user-images.githubusercontent.com/41443416/119019753-cde0d500-b99d-11eb-98bc-338fae254603.png">

**Comment by pintorig** [comment]
@simo-git ho fatto un nuovo tentativo, ho caricato il template da file system e poi ho salvato, il contenuto della richiesta visualizzato nel browser e' il seguente (ho fatto anche la decodifica del base64 inviato)

![Screenshot from 2021-06-04 10-53-35](https://user-images.githubusercontent.com/12812160/120775168-4067be00-c523-11eb-8482-92fc4a5e5abe.png)

![Screenshot from 2021-06-04 10-53-57](https://user-images.githubusercontent.com/12812160/120775166-3f369100-c523-11eb-9cc1-42e8167e18a7.png)

Il server riceve il file con la linea bianca aggiuntiva finale

**Comment by pintorig** [comment]
La riga in piu' e' presente in tutti i caricamenti di file della console, ho provato a caricare file in diversi punti e tutti arrivano al server con una riga bianca in fondo.

**Comment by simo-git** [comment]
@pintorig usando i file campione che mi hai passato ho notato che aprendoli in anteprima non presentavano la linea vuota in eccesso ma quelli salvati invece si. La comparsa della nuova riga in fondo ad un file di testo è automatica ed è derivata da una regola universale.
> ...according to POSIX, every text file... should end with a \n, or “newline” (not “a new line”) character. This acts as the eol, or the “end of line” character. It is a line “terminator”.

Ho impostato la rimozione del carattere di eol nella stringa codificata in base64. Questa modifca dovrebbe correggere il problema.
