### ISSUE TITLE
Configurazione SSL nei connettori di Intermediari e Applicazioni

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#317]
Ciao,
lo scenario è il seguente:
- 2 intermediari
- 2 certificati nello stesso keystore

Provando ad eseguire pagamenti da PSP funzionano solo per il primo della lista dei certificati in quanto viene provata l'autenticazione sempre e solo con il primo della lista appunto. Il secondo funziona solo se elimino dalla lista l'altro e ne lascio uno solo.

Vi risulta un problema del genere?

Grazie

**Comment by nardil** [comment]
Ciao @giuseppeformaro , 

si, la configurazione della mutua autenticazione tramite JVM ha questo limite. GovPay prevede la configurazione della mutua autenticazione nel connettore pagoPA di ciascun intermediario, ma manca il supporto lato Console per impostarla:

![Schermata da 2021-04-30 15-50-10](https://user-images.githubusercontent.com/12340738/116704565-d744d600-a9cb-11eb-9a64-688699f638cf.png)

Nell'attesa dell'integrazione di questa funzionalita' nella console, potresti configurare GovPay costruendo in altro modo la richiesta di configurazione (cURL, postman, etc...) e accellerare nelle verifiche funzionali.

**Comment by nardil** [comment]
@simo-git Aggiungere al connettore pagoPA dell'intermediario la possibilita' di selezionare la configurazione SSL. Se selezionato valorizza il campo `auth` con la struttura dati `tipoAutenticazioneSSL`

La form, quando selezionato il tipo SSL, presenta i campi obbligatori:
- Truststore path: testo per `tsLocation`
- Truststore password: testo per `tsPassword`
- Autenticazione client: booleano, default false. Se false allora `tipo = server`, altrimenti `tipo = client`

Quando viene attivata l'autenticazione client, vengono mostrati due campi addizionali obbligatori:

- Keystore path: testo per `ksLocartion`
- Keystore password: testo per `ksPassword`

**Comment by giuseppeformaro** [comment]
Ciao in attesa del rilascio non mi è chiaro se posso eseguire la configurazione direttamente su DB. E' possibile? 

Grazie

**Comment by nardil** [comment]
Non e' consigliabile farlo su DB. E' molto piu' agevole e sicuro farlo da API, che supportano lo scenario.

**Comment by giuseppeformaro** [comment]
Grazie, avevo escluso l'uso delle API perchè non l'ho trovata, mi sai indicare come fare?

**Comment by nardil** [comment]
Avevo riportato un estratto dell'API di Backoffice che evidenzia la porzione interessante in un [commento](https://github.com/link-it/govpay/issues/317#issuecomment-830112012) in questa stessa issue

**Comment by giuseppeformaro** [comment]
Ciao, ti posso chiedere un esempio di come si aspetta il ksLocation (nome file completo di path assoluto?)

**Comment by pintorig** [comment]
@pintorig 
- [ ] Estendere la configurazione ssl dei connettori aggiungendo le seguenti proprieta' per la configurazione dell'autenticazione SERVER:
- sslTsType: tipo truststore, enum per ora con il solo valore 'JKS'
- sslType: tipo di algoritmo utilizzato; 

e le seguenti proprieta' per la configurazione dell'autenticazione CLIENT:
- sslKsType:  tipo keystore, enum per ora con il solo valore 'JKS'
- sslPKeyPasswd: password della chiave del keystore

- [ ] estendere la testsuite per la verifica dei nuovi campi.

**Comment by pintorig** [comment]
@simo-git 
Nelle pagine di add/update Intermediari e Applicazioni modificare le form di configurazione autenticazione SSL per gestire i nuovi campi:

sslType: Label (Tipo SSL) **Obbligatorio** :  Select con valori definiti nella enum _sslConfigType_  tipo di algoritmo utilizzato;
tsType: Label ( Truststore Tipo) **Obbligatorio**:  Select con valori definiti nella enum _keystoreType_ tipo di keystore utilizzato;

![Screenshot from 2021-06-03 17-07-05](https://user-images.githubusercontent.com/12812160/120667970-4cee0700-c48e-11eb-97b5-1e122d733297.png)


Spostare la checkbox Autenticazione Client sotto i campi del che definiscono il truststore;

ksType: Label ( Keystore Tipo) **Obbligatorio**:  Select con valori definiti nella enum _keystoreType_ tipo di keystore utilizzato;
ksPKeyPasswd: Label (Password Chiave Privata) **Obbligatorio**: Input testuale per l'inserimento della password.

![Screenshot from 2021-06-03 18-13-28](https://user-images.githubusercontent.com/12812160/120677497-6a739e80-c497-11eb-95a5-d13f532f9c02.png)

**Comment by pintorig** [comment]
Configurazione SSL testata correttamente verra' rilasciata nella versione 3.4.1
