### ISSUE TITLE
Stampa Avviso di Pagamento con Bollettino Postale

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#319]
Buongiorno,
Avrei bisogno se possibile di informazioni circa la possibilità di stampare il bollettino postale per il pagamento a corredo dell'avviso di pagamento. Leggendo la documentazione sembra possibile, ma si fa solo riferimento ad un campo "Autorizzazione PT" da compilare nella configurazione dell'Ente Creditore e che non so bene a cosa si riferisca.
Facendo una ricerca ho visto che un ente creditore può richiedere una autorizzazione per la stampa dei bollettini postali compilando un apposito modello e immagino che alla fine gli venga fornita questa Autorizzazione PT da inserire su GovPay.
Con questa autorizzazione, in associazione alla definizione "Postale" in relazione all'IBAN/Conto Corrente configurato sull'ente, le stampe dell'avviso di pagamento mostrerebbero anche il bollettino ?

**Comment by nardil** [comment]
Ciao @frdidonato , 

per avere la stampa del bollettino postale sull'avviso e' sufficiente che il conto di accredito o di appoggio sia un CC postale ed indicato come tale nella configurazione di GovPay.

L'autorizzazione alla stampa in proprio non e' tecnicamente necessaria a rendere pagabile il bollettino. E' un adempimento richiesto da Poste Italiane con il quale viene certificata la correttezza delle stampe, ma i bollettini risultano pagabili anche se privi di autorizzazione.

**Comment by frdidonato** [comment]
@nardil grazie mille adesso riesco a stampare
