### ISSUE TITLE
Errore recupero connessione db

### ISSUE THREAD

**Issue by SbGibson** [link-it/GovPay#32]
Ciao,
dopo qualche giorno che govpay è attivo quando faccio le richieste ottengo errori di questo tipo:

`Risposta avvio transazione pagamento KO - ListaDettagliEsiti: INTERNAL - java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for govpay`

Guardando nel log vedo che dopo una serie di log vari fra cui

`2017-05-04 13:00:00.034 | INFO  | it.govpay.core.business.BatchManager:107 | 4ff0b9cd-b14c-4dbd-a925-225e9cca32bb | Batch in esecuzione sul nodo null.`

Cominciano ad esserci log di questo tipo:

```
2017-05-04 13:01:30.016 | ERROR | it.govpay.core.business.Operazioni:200 | 9b569922-10a8-4bf9-8db9-a23efa3e9741 | Non è stato possibile avviare la spedizione delle notifiche
org.openspcoop2.generic_project.exception.ServiceException: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for govpay
	at it.govpay.bd.ConnectionManager.getConnection(ConnectionManager.java:81) ~[govpay-orm-2.3.2.0.jar:?] 
```

La console sembra funzionare correttamente

**Comment by nardil** [comment]
Ciao @SbGibson,
il log relativo al batch e' solo un'informativa incompleta. E' un'istallazione in singola istanza?

Per quanto riguarda l'errore di connessione l'analisi e' piu' complessa. 
Potresti intanto verificare via jconsole il numero di connessioni in uso da GovPay:
1. come root esegui il comando jconsole
2. connettiti al processo jboss
3. seleziona mbeans > it.govpay.core.connection > GovPay > connection
4. esegui il comando "getDatasources" e verifica il numero di connessioni in uso:

![schermata da 2017-05-11 14-57-08](https://cloud.githubusercontent.com/assets/12340738/25950223/79edb21c-365a-11e7-8879-fab7136649d9.png)

**Comment by SbGibson** [comment]
Attualmente mi dice che ci sono 2 connessioni, queste:

(2017-05-11_16:00:00.008)  idTransazione:85899ee3-b68a-4440-92f0-11f4ea5bce8f moduloFunzionale:it.govpay.core.business.Operazioni:143
(2017-05-11_16:00:00.071)  idTransazione:03225bb2-1e3d-4127-966f-d73c5f423d5e moduloFunzionale:it.govpay.core.business.Operazioni:143

Quando si riblocca rifaccio la verifica.
L'installazione è con due istanze su due server in bilanciamento, ho configurato i nodi come descritto nelle istruzioni, almeno credo :-)

**Comment by SbGibson** [comment]
Eccomi, adesso che ho il blocco mi dice che ci sono 50 connessioni 
(2017-05-11_18:01:12.520) idDatasource:89f5165c-5f3c-4fe7-a2f8-2aae49bbe008 jndiName:govpay idApplicativo:GovPay ConnessioniAttive:50

Non le incollo tutte, ce ne sono di tre tipi, la maggior parte del primo tipo:

(2017-05-11_19:00:00.004)  idTransazione:9e5cbe7f-0e0f-41a6-a83d-93230060aedb moduloFunzionale:it.govpay.core.business.Operazioni:143
...
(2017-05-12_00:00:00.015)  idTransazione:c7431ebf-e8f1-4a05-a209-99c1034a6fd7 moduloFunzionale:it.govpay.core.business.Operazioni:264
...
(2017-05-12_04:00:00.170)  idTransazione:c8d88547-3384-476b-b8f2-3a881ac4832d moduloFunzionale:it.govpay.core.business.Operazioni:74

**Comment by nardil** [comment]
Ok, puoi verificare adesso se il numero di connessioni che risultano in GovPay corrisponde a quelle attive sul DB?

**Comment by SbGibson** [comment]
Sembrerebbe di no. Da mysql mi risultano 14 connessioni da govpay, jconsole ne segnala 50. Ho notato che sono circa un paio ogni ora.
Se può essere significativo la mia installazione è su due host in bilanciamento ed il problema non si presenta contemporaneamente su entrambi gli host.

**Comment by nardil** [comment]
Tra l'application server ed il db ci sono altri componenti che entrano in gioco come firewall hw o sw, proxy, etc....?

**Comment by nardil** [comment]
Potresti anche inviarmi il govpay.log?

**Comment by SbGibson** [comment]
Nessun intermediario, ti ho inviato i log via mail, ricevuti?

**Comment by nardil** [comment]
Ciao Gibson,
abbiamo individuato un possibile connection leak.

Potresti aggiornare alla versione 2.3.3 e verificare se il problema si ripresenta?

**Comment by nardil** [comment]
Gibson, sei riuscito a verificare se il problema segnalato persiste?

**Comment by SbGibson** [comment]
Si, ho aspettato un paio di giorni per essere sicuro, non è più capitato quindi direi che il problema è risolto, chiudo la issue.
