### ISSUE TITLE
Traduzione della causale nell'Avviso bilingue

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#323]
**Necessità:**
Prevedere la possibilità di poter indicare anche la traduzione della  causale del versamento nella stampa dell'avviso bilingue. 

**Soluzione:**
La stampa viene realizzata con una grafica simile alle altre stampe. Qualora il testo eccedesse lo spazio a disposizione, viene troncato quello della traduzione.

Il testo tradotto viene fornito:
- nel json come proprieta' `pendenza.proprieta.linguaSecondariaCausale`
- nel csv nello stesso campo della lingua secondaria, separata da un pipe `|`. La sua presenza e' opzionale.

**Comment by pintorig** [comment]
@simo-git :

ho modificato lo schema xsd dell'input per il template jasper spostando l'elemento _oggetto_del_pagamento_ all'interno dell'elemento _Etichette_.
La label in italiano e' sempre valorizzata, quella nella seconda lingua e' opzionale.
