### ISSUE TITLE
Nuovo tipo pendenza per Ente creditore

### ISSUE THREAD

**Issue by atatarelli** [link-it/govpay#324]
**Descrizione del Bug**
Nella form di “Nuovo tipo pendenza”, nel riepilogo delle informazioni, quando la lista dell pendenze è vuota, il campo “Tipo pendenza” non visualizza un dropdown vuoto ma un campo di input testuale che risulterà sempre non valido non disponendo più di pendenza “non associate”.

**Risultato atteso:**
Dropdown vuoto, ma più correttamente, se non esistono più pendenze disponibili per l’ente, la maschera di inserimento di una nuova pendenza non dovrebbe essere mostrata, andrebbe disabilitato il pulsante di inserimento di una nuova pendenza per l’ente.

**Comment by pintorig** [comment]
@simo-git 
Quando un ente creditore non ha dei tipi pendenza associabili, bisogna evitare che l'utente possa andare nella maschera di configurazione di un nuovo tipo, poiche' la maschera si presenta in questo modo:

![Screenshot from 2021-05-25 14-05-38](https://user-images.githubusercontent.com/12812160/119495232-7d34f780-bd62-11eb-855c-e652ba1335c8.png)

puoi nascondere il tasto aggiungi (o disabilitarlo magari aggiungendo un tooltip)

![Screenshot from 2021-05-25 14-05-49](https://user-images.githubusercontent.com/12812160/119495447-b705fe00-bd62-11eb-8d0c-a21272ea1504.png)

effettuando una query di controllo sul numero di pendenze disponibili:

```
/govpay/backend/api/backoffice/rs/form/v1/tipiPendenza?descrizione=&nonAssociati=ID_DOMINIO

```

e controllando che il campo  numRisultati sia maggiore di 0:

```json

{"numRisultati":0,"numPagine":1,"risultatiPerPagina":500,"pagina":1,"risultati":[]}
```
