### ISSUE TITLE
PUT /pendenze - 403 Error

### ISSUE THREAD

**Issue by MatteoT9890** [link-it/govpay#325]
**Problem Statement**
Devo creare un nuovo Intermediario (Partner Tecnologico) all'interno del cruscotto. Richiede però alcuni dati che non mi è chiaro dove andare a pescare. Essi sono:

- Principal: identificativo (subject certificato o principal) corrispondente alle credenziali con cui Govpay riceve le chiamate in entrata da pagoPA.

DOMANDA:
Dove posso reperire questo dato sul portale delle adesioni? A cosa serve?

- Servizio RPT: Riferimenti utilizzati da Govpay per comunicare con il Nodo SPC: Endpoint per le chiamate in uscita verso il Nodo SPC

DOMANDA: 
Se capisco bene si setta in questo scenario un endpoint che govpay utilizzerà internamente per poi comunicare con il nodo SPC. Parlando di endpoint e non di URL, è necessario specificare anche HOSTNAME (locale) e PORT o solo l'endpoint.

- Tipo Autenticazione: Lista a discesa per selezionare il tipo di autenticazione adottata per le comunicazioni con il Nodo SPC. Si può scegliere, al momento, tra Nessuna e HTTP-Basic. Nel caso si scelga quest’ultima modalità di autenticazione, dovranno essere inserite i relativi dati di configurazione (userid/password).

DOMANDA:
La comunicazione settata sul portale delle adesioni è di tipo GAD. Non capisco cosa accade quindi se scelgo nessuna o HTTP-BASIC in funzione del fatto che la comunicazione è via GAD e, nel caso della seconda, a quale userId e password fa riferimento e dove potrei reperirli.

**Comment by MatteoT9890** [comment]
Novità a riguardo? Essendo una situazione bloccante se non risolvo questo problema non posso andare avanti con lo sviluppo della parte applicativa

**Comment by atatarelli** [comment]
Immaginando lo scenario di interfacciamento diretto tra GovPay e il GAD di pagoPA:

il principal è il valore dell'attributo su cui si fa l'autenticazione ed in questo caso corrisponde al subject del certificato.
L’endpoint va specificato completo di PROTOCOLLO, HOSTNAME e di PORT (se necessario) e in questo caso i valori sono:

**PRODUZIONE**
**principal**: CN=gad.pagopa.gov.it, OU=pagoPA, O=SIA S.p.A, L=Milano, ST=Milano, C=IT
**URL**: https://gad.pagopa.gov.it/openspcoop2/proxy/PA/RPT60

**COLLAUDO**:
**principal**: CN=gad.test.pagopa.gov.it, OU=pagoPA, O=SIA S.p.A, L=Milano, ST=Milano, C=IT
**URL**: https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T

L’accesso di tipo GAD è realizzato tramite certificato e pagoPA richiede che le comunicazioni siano con mutua autenticazione SSL.
Attualmente in GovPay non è possibile gestire direttamente la configurazione, quindi il tipo di autenticazione va lasciato a “Nessuna” e bisogna configurare nella JVM il keystore con la chiave privata (quella fornita in fase di configurazione sul portale delle adesioni) ed il trustore con il certificato di pagoPA di collaudo/produzione (il link per il download si trova nel portale delle adesioni).

Nei prossimi rilasci di GovPay sarà possibile configurare il keyStore e il trustore direttamente dall’interfaccia.

Se lo scenario invece prevede un componente tra GovPay e il GAD allora alcune cose deve essere riviste a seconda del componente utilizzato.

**Comment by MatteoT9890** [comment]
Tutto chiaro,  grazie! 
L'unica cosa che rimane scoperta a questo punto è l'endpoint relativo al servizio RPT, è un dato impostavile da me oppure devo attenermi a delle linee guida di GovPay essendo l'endpoint con cui GovPay comunica in uscita con il nodo SCP?

**Comment by MatteoT9890** [comment]
**COLLAUDO**

Essendo attualmente in fase di collaudo ho impostato:
Principal: gad.test.pagopa.gov.it
Servizio RPT: https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T

E' corretto?

**Comment by MatteoT9890** [comment]
**RISOLTO**

Cambiando l'URL base DA _/govpay/backend/api/pendenze_ A _/govpay/backend/api/backoffice_
