### ISSUE TITLE
Pagamento Multi-Beneficiario (TARI/TEFA) Modello 3

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#327]
**Necessità:**
Gestire il pagamento multibeneficiario, introdotto nelle SANP 2.4.2 per lo use case tari/tefa per il modello di pagamento ad iniziativa PSP

**Soluzione:**
_Consentire il censimento di Enti Creditori non intermediati_ 

Su database gli enti creditori non intermediati si distinguono perche' non hanno una stazione di intermediazione. Da console, nella form di creazione, viene aggiunto il checkbox "Intermediato" per default abilitato. Se viene disabilitato, vengono nascoste le porzioni di form "Parametri adesione a pagoPA" e "Autorizzazione alla stampa". 

Come sottoregistri sara' disponibile solo quello degli iban di accredito.

_Consentire di indicare conti di accredito di altri enti_

Rilassare il vincolo per cui i conti i accredito indicati nella pendenza debbano afferire all'ente creditore. Aggiungere il controllo che l'utenza che carica la posizione sia autorizzata su tutti i beneficiari della pendenza.

_Gestire il pagamento ad iniziativa PSP nuovo modello_

Consentire il pagamento della pendenza solo se attivata tramite le nuove API di pagamento modello 3 ed impedirla se avviata tramite modello 1 o modello 3 tradizionale.

Nel caso di pagamento con successo, flaggare la riscossione di importi con conto di accredito afferente ad Enti non Intermediati un il nuovo tipo `ENTRATA_PA_NON_INTERMEDIATA` che saranno ignorati ai fini di riconciliazione.

_Stampa dell'avviso di pagamento_

La stampa segue il nuovo modello gia' utilizzato per il multilingua visualizzando i loghi di entrambi gli enti beneficiari, se diversi. Nel caso gli enti beneficiari siano piu' di due, ci si limita ai primi due. Per la parte di bollettino postale, si rimanda alla issue di chiarimento su pagoPA: https://github.com/pagopa/pagopa-api/issues/176

**Note:**
Il pagamento della pendenza tramite modello 1 sara' oggetto di una successiva evolutiva

**Comment by nardil** [comment]
Informazioni sulla gestione degli errori nel nuovo pagamento modello 3:
https://github.com/pagopa/pagopa-api/issues/136

**Comment by giuseppeformaro** [comment]
Buondi, ho attivato la stazione VER2 di collaudo, quando pensate possiamo fare qualche TEST?

Eventualmente sono a disposizione!

**Comment by nardil** [comment]
Richiesti chiarimenti sulla valorizzazione della ricevuta: https://github.com/pagopa/pagopa-api/issues/195

**Comment by nardil** [comment]
Ciao @giuseppeformaro,

sono stati completati i primi test di pagamento nel caso di successo. Appena completati gli adeguamenti necessari alla console di configurazione per gestire gli Enti Creditori non intermediati, rilasciamo una versione beta.

**Comment by pintorig** [comment]
@simo-git 
Realizzare le seguenti modifiche al cruscotto per supportare la nuova funzionalita':

- [ ] Configurazione Ente Creditore:
 nel dettaglio visualizzare il nuovo campo '_Intermediato_' di tipo boolean:
 quando e' true la visualizzazione resta uguale ad ora:
  ![Screenshot from 2021-07-13 14-39-39](https://user-images.githubusercontent.com/12812160/125453181-bdc62695-071a-4f77-9114-6f64e2679444.png)
 quando invece e' false nascondere le sezioni 'Parametri adesione a pagoPA' e 'Altre Informazioni' nella card principale e  nascondere le card: Unita' operative, Entrate, TipiPendenza e Connettori.
 ![Screenshot from 2021-07-13 14-44-30](https://user-images.githubusercontent.com/12812160/125453638-21e656ac-eba6-4c4c-b679-632d377dca9d.png)
 nelle maschere di creazione/modifica aggiungere il campo '_Intermediato_' di tipo boolean (default true):
 ![Screenshot from 2021-07-13 14-47-15](https://user-images.githubusercontent.com/12812160/125454122-dba6bdc0-a41c-4dbb-960c-40fc7e33da2c.png)
 quando viene impostato a false nascondere le sezioni 'Parametri adesione a pagoPA' e 'Altre Informazioni'
 ![Screenshot from 2021-07-13 15-01-39](https://user-images.githubusercontent.com/12812160/125456160-0b596f78-a875-44a5-993e-9c56ae8d6331.png)

- [ ] Stampa Avviso di pagamento
 nella versione monolingua aggiungere il supporto per la stampa del logo secondario come gia' fatto per il modello bilingua.
 Ho gia' aggiornato lo schema dell'input aggiungendo il campo 'logo_ente_secondario'.

**Comment by pintorig** [comment]
Dopo i primi test e' venuta fuori la necessita' di dover rendicontare i pagamenti per gli enti non intermediati e spedirli tramite i connettori proposti da Govpay:
- @pintorig: ripristinare la possibilita' di configurare e utilizzare i connettori per gli enti non intermendiati.
- @simo-git: ripristinare la sezione Connettori nel dettaglio di un Ente Creditore per consentire all'operatore di configurarli.

**Comment by pintorig** [comment]
Aggiungere la possibilita' di indicare esplicitamente il dominio all'interno della singola voce pendenza.
Nel caso di pendenza di tipo multibeneficiario, tale campo dovra' essere valorizzato con l'identificativo del dominio se diverso da quello indicato nella pendenza.

**Comment by nardil** [comment]
Richiesti chiarimenti a pagoPA sulla modalita' di migrazione alle nuove API e l'interoperabilita' tra versioni diverse usate da PSP ed EC: https://github.com/pagopa/pagopa-api/issues/198

**Comment by nardil** [comment]
Come indicato da pagoPA (https://github.com/pagopa/pagopa-api/issues/197 ) e confermato dalle SANP (https://docs.italia.it/italia/pagopa/pagopa-specifichepagamenti-docs/it/v2.4.0/_docs/sezione3-specifiche-tecniche/3_01_00_pagamento_online.html#pagamento-on-line) anche i pagamenti modello 1 vengono gestiti sulle nuove API per la comunicazione della ricevuta

**Comment by pintorig** [comment]
@simo-git 

- [ ] Aggiungere filtro "Intermediato" nella lista degli enti creditori, una select list con i seguenti valori:
label "Tutti" , valore: null
label "Si", valore: true
label "No", valore: false

- [ ]  All'elemento della lista Ente Creditore, aggiungere nella seconda riga dopo l'identificativo le seguenti informazioni:
se abilitato == false -> "disabilitato"
se intermediato == false -> "non intermediato"

**Comment by nardil** [comment]
- [ ] Consultando il dettaglio di una pendenza multibeneficiario, la navigazione si blocca con lo spinner in primo piano. Nella console compare l'errore `Cannot read properties of undefined (reading 'codiceContestoPagamento')`

**Comment by nardil** [comment]
@pintorig 

- [ ] In caso di mancata valorizzazione della dataScadenza o dataValidita, valorizzare il DueDate della getPaymentPaResponse al 31/12/2999
- [ ] Disabilitare controlli di pagamenti in corso per il nuovo modello 3.
- [ ] Verificare questo errore di gestione del commit:

```
2021-09-21 12:15:01.210 | ERROR | it.govpay.web.ws.PagamentiTelematiciCCPImpl:1610 | 02f74acb-3515-4bbb-924c-73613ddf88d9 | Errore durante l'annullamento della RPT [idDominio:80007080668][iuv:000000000230318][ccp:1632215300370]: Errore durante la gestione della commit della connesione.
org.openspcoop2.generic_project.exception.ServiceException: Errore durante la gestione della commit della connesione.
	at it.govpay.bd.BasicBD.commit(BasicBD.java:800) ~[orm-3.5.0-SNAPSHOT.jar:?]
	at it.govpay.web.ws.PagamentiTelematiciCCPImpl.paGetPayment(PagamentiTelematiciCCPImpl.java:1607) ~[classes:?]
...
Caused by: java.sql.SQLException: IJ031020: You cannot commit with autocommit set
	at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.jdbcCommit(BaseWrapperManagedConnection.java:1066) ~[?:?]
	at org.jboss.jca.adapters.jdbc.WrappedConnection.commit(WrappedConnection.java:834) ~[?:?]
	at org.openspcoop2.utils.datasource.Connection.commit(Connection.java:207) ~[openspcoop2_utils-datasource-3.2.1.jar:?]
```

**Comment by nardil** [comment]
- [ ] In caso di pagamento con le nuove API modello 3, nella ricevuta deve essere sostituita la voce `CCP` con `Identificativo ricevuta` valorizzato con il `receiptId`.
- [ ] Nell'avviso multibeneficiario, la porzione del bollettino postale deve essere presente se il conto dell'Ente emittente e' un cc postale. L'importo nella porzione di bollettino e' quello totale, anche nel datamatrix. (https://github.com/pagopa/pagopa-api/issues/176)

**Comment by giuseppeformaro** [comment]
Ciao,
confermo che il pagamento da PSP è andato a buon fine su una stazione VERSIONE2 (a meno del piccolo problema segnalato in https://github.com/link-it/govpay/issues/448). 

Per il pagamento multibeneficiario da portale ci sono previsioni sul rilascio cosi da organizzarmi con eventuali test?

Grazie
