### ISSUE TITLE
Errore Pagamento ambiente di collaudo da PSP

### ISSUE THREAD

**Issue by MSviluppo** [link-it/govpay#330]
Buongiorno, siamo in fase di accreditamento presso PagoPA come Partner tecnologico, configurato collegamento fisico e Stazione tutto ok, caricate alcune pendenze,  ci siamo appoggiati ad un PSP per effettuare alcune prove di pagamento ma purtroppo ci segnalano questo errore....

            <nodoVerificaRPTRisposta>
                <fault>
                    <faultCode>PPT_STAZIONE_INT_PA_IRRAGGIUNGIBILE</faultCode>
                    <faultString>Errore di connessione verso la Stazione.</faultString>
                    <id>NodoDeiPagamentiSPC</id>
                    <description>Porta di Dominio Temporaneamente non Disponibile (Errori Interni del - Server)</description>
                </fault>
                <esito>KO</esito>
            </nodoVerificaRPTRisposta>

Mi sapete dare qualche indicazione 

Grazie

**Comment by nardil** [comment]
L'errore segnalato da pagoPA indica l'irraggiungibilità dei servizi PagamentiTelematiciCCP esposti da GovPay. Dovete verificare che i parametri inviati a pagoPA tramite Portale delle Adesioni a riguardo siano corretti e che le richieste provenienti da pagoPA siano correttamente instradati verso GovPay.
