### ISSUE TITLE
POST /pagamenti - 403 ERROR

### ISSUE THREAD

**Issue by MatteoT9890** [link-it/govpay#332]
**Problema**
Invocando un HTTP **POST** all'endpoint: _/govpay/frontend/api/pagamento/rs/basic/v2/pagamenti_ ottengo il seguente errore:

`{"categoria":"AUTORIZZAZIONE","codice":"403000","descrizione":"Operazione non autorizzata","dettaglio":"Operatore [Nome Cognome] non autorizzato ad accedere alla risorsa richiesta."}`

Mi sembra di capire che le credenziali di autenticazioni del cruscotto GovPay non abbiano i permessi per avviare un pagamento. Come si risolve?

**Comment by MatteoT9890** [comment]
**RISOLTO**

**Comment by nardil** [comment]
Il Portale e' un'applicazione Angular che gira sul browser del debitore e quindi non deve presentare un'autenticazione di tipo basic.

Deve usare le API senza autenticazione (public) per i servizi fruibili in forma anonima, mentre un'autenticazione di altro tipo (eg. SPID) per le operazioni che invece richiedono l'identificazione dell'utente.

Stiamo aggiornando il codice ed avviando la stesura di una prima documentazione, nel frattempo potreste prendere esempio dalla configurazione del [portale demo](https://demo.govcloud.it/govpay-portal/)

**Comment by nardil** [comment]
Faccio notare a @MatteoT9890 che la configurazione che hai predisposto sul portale fornisce all'utente cittadino le autorizzazioni di un'utenza applicativa.
