### ISSUE TITLE
Servizi esposti da GovPay verso pagoPA

### ISSUE THREAD

**Issue by MSviluppo** [link-it/govpay#333]
Buongiorno, nel verificare che i servizi esposti da GovPay verso pagoPA siano raggiungibili nel browser ai seguenti URL:

https://govpay.mitservizi.com/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl
https://govpay.mitservizi.com/govpay/frontend/api/pagopa/PagamentiTelematiciCCPservice?wsdl

Ci da sempre

{"categoria":"AUTORIZZAZIONE","codice":"401","descrizione":"Autenticazione richiesta.","dettaglio":"Full authentication is required to access this resource"}

Come possiamo modificare o correggere questo comportamento?

Grazie

**Comment by nardil** [comment]
Ciao @MSviluppo ,

i servizi erogati verso pagoPA prevedono l'autenticazione ed autorizzazione del chiamante. La configurazione di default per le API pagoPA prevede l'autenticazione SSL Client, per questo le richieste da voi eseguite risultano in errore 401.

Per maggiori informazioni su come eventualmente modificare la modalità di autenticazione rimando alla documentazione: https://govpay.readthedocs.io/it/latest/installazione/dispiegamento/index.html#inst-dispiegamento-auth

**Comment by mallomix** [comment]
Ciao Nardil,

anche a me da lo stesso problema e nel tentativo di pagare un avviso di pagamento da un canale esterno (ad esempio app io), i tecnici di PAGOPA mi dicono che non riescono a contattare i servizi di govpay per errore 401. 
Avendo messo nel TRUSTORE e KEYSTORE il certificato che protegge l'endpoint e loro hanno nel portale delle adesioni tale certificato come mai ottengono lo stesso errore? 
Mi spiego meglio:
1) Ho omesso qualche configurazione affinchè io stesso possa raggiungere il WSDL tramite autenticazione SSL del client?

**Comment by mallomix** [comment]
@MSviluppo  buongiorno,  come avete risolto voi il problema del 401 nelle chiamate ai servizi GOVPAY pe pagopa?

Vi ringrazio!

**Comment by mallomix** [comment]
Ciao Nardil, si scusami ma allora perchè riesco ad accedere correttamente a https://govpay.mitservizi.com/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl
che è un altro utente di govpay?
