### ISSUE TITLE
WISP - Sessione Scaduta

### ISSUE THREAD

**Issue by MatteoT9890** [link-it/govpay#334]
Dopo aver effettuato un HTTP POST /pagamenti, nel campo _redirect_ viene inviato il link per proseguire sul portale WISP.

Al ritorno da WISP, viene inviato l'esito "OK", "ERROR" o "DIFFERITO" su un nostro URL pre-impostato sul portale delle adesioni, ma il ritorno viene fatto solo se il pagamento segue tutti gli step. Supponiamo invece che per un motivo o per un altro, la scheda WISP venga chiusa senza aver seguito tutti gli steps, a quel punto la sessione scade e il portale dei pagamenti non riceve l'esito da WISP e, nel momento in cui viene richiesto l'esito del pagamento esplicitamente tramite GET /pagamenti/{id} oppure tramite GET /pagamenti/byIdSession/{idSession}, il pagamento risulta "IN CORSO" per tanto tempo, quando in realtà la sessione è scaduta e l'utente non può più pagare tramite WISP attraverso il link iniziale generato nel campo _redirect_.
Da cosa dipende questo disallineamento tra GovPay e il portale WISP? Come mai GovPay ci mette tanti minuti per capire che è il pagamento non è stato eseguito perchè la sessione su WISP è scaduta? C'è una soluzione per velocizzare questo processo di allineamento?

**Comment by nardil** [comment]
Ciao @MatteoT9890 , 

tutte le transazioni di pagamento sono avviate da una RPT creata da GovPay e concluse da una RT creata da pagoPA (WISP o PSP). Anche il caso d'uso che hai descritto ricade in questo scenario e GovPay non può far altro che attendere la notifica di conclusione della transazione tramite la notifica dell'RT da parte di pagoPA e per un'eventuale miglioramento del servizio è necessario intervenire sul WISP o sui processi di pagoPA.

Secondo il [documento](https://github.com/pagopa/lg-pagopa-docs/blob/master/documentazione_tecnica_collegata/documentazione_collegata/SLA_aderente_2.2.pdf) che definisce gli SLA dei soggetti aderenti a pagoPA, il tempo consigliato di attesa per la generazione dell'RT a fronte di timeout è di 20 minuti.
