### ISSUE TITLE
MOD.1 - Pagamento ESITO

### ISSUE THREAD

**Issue by MatteoT9890** [link-it/govpay#335]
Se al termine del portale WISP l'esito è "OK", nonostante il pagamento risulta ancora "IN CORSO" è possibile assumere che con **elevata probabilità** il pagamento vada in stato "ESEGUITO"? 
Se no, quali sono le ragioni per cui il pagamento potrebbe fallire con una probabilità non trascurabile?

**Comment by nardil** [comment]
Ciao @MatteoT9890,
il parametro `esito` viene inviato dal browser dell'utente, pertanto non è un'informazione attendibile. Può essere utilizzata al più per personalizzare una pagina di cortesia da presentare all'utente in attesa dell'RT da pagoPA.

**Comment by MatteoT9890** [comment]
Ma l'attesa media quant'è? Ho notato che a volte più metterci più di un'ora e questo nel nostro specifico scenario è un grosso problema, in quanto pagoPA sarà utilizzato per vendere biglietti on-line. Ciò significa che l'acquisto di un biglietto deve essere fatto in anticipo di un tempo T rispetto all'orario di visita al museo, in modo tale da essere sicuri che nel momento della visita il pagamento sia stato confermato dalla RT. In base alla tua esperienza qual è questo tempo T che ci permettere di stare "tranquilli"?

**Comment by nardil** [comment]
Puoi far riferimento alla monografia "[Indicatori di qualità per i soggetti aderenti](https://github.com/pagopa/lg-pagopa-docs/blob/master/documentazione_tecnica_collegata/documentazione_collegata/SLA_aderente_2.2.pdf)" per una stima dei tempi, ma certamente non è nell'ordine di ore. Dovreste verificare se in questi casi si verificano anomalie.

**Comment by MatteoT9890** [comment]
Dove posso trovare un eventuale log di anomalie gestite dall'applicativo?

**Comment by MatteoT9890** [comment]
**UPDATE**

Buongiorno @nardil,

Nel giornale degli eventi ottengo un errore su "Inviata notifica pagamento all'ente". Di seguo il dettaglio del JSON di risposta:

```
{
  "id": 274,
  "componente": "API_ENTE",
  "categoriaEvento": "INTERFACCIA",
  "ruolo": "CLIENT",
  "tipoEvento": "notifyPagamento",
  "esito": "FAIL",
  "dataEvento": "2021-06-02T12:47:00.501",
  "durataEvento": 125,
  "sottotipoEsito": "null",
  "dettaglioEsito": "java.net.ConnectException: Connection refused (Connection refused)",
  "idDominio": "00378210462",
  "iuv": "41000000000000163",
  "ccp": "310520211237243027",
  "idA2A": "SUMMAE",
  "idPendenza": "_c_p-9w5Z50TXXMl",
  "idPagamento": "2e3e4fd45597489aa832edc5c40f5c47",
  "severita": 5,
  "parametriRichiesta": {
    "dataOraRichiesta": "2021-06-02T12:47:00.501",
    "url": "https://pagopa.culturatela.it/govpay/frontend/api/pagamento/pagamenti/00378210462/41000000000000163?idCarrello=2e3e4fd45597489aa832edc5c40f5c47&idSession=56fac400-7c5f-4f6b-87a0-f4b0011a31f0",
    "headers": [
      {
        "nome": "RequestPath",
        "valore": "https://pagopa.culturatela.it/govpay/frontend/api/pagamento/pagamenti/00378210462/41000000000000163?idCarrello=2e3e4fd45597489aa832edc5c40f5c47&idSession=56fac400-7c5f-4f6b-87a0-f4b0011a31f0"
      },
      {
        "nome": "Accept",
        "valore": "application/json"
      },
      {
        "nome": "HTTP-Method",
        "valore": "POST"
      }
    ],
    "method": "POST"
  },
  "parametriRisposta": {
    "dataOraRisposta": "2021-06-02T12:47:00.626",
    "status": 0,
    "headers": []
  }
}
```



Potrebbe essere questa la causa del problema?

**Comment by nardil** [comment]
Ciao @MatteoT9890 

la transazione era in stato "RT_ERRORE_INVIO_A_PA" per il Nodo e GovPay acquisisce le RT tramite le strategie di recupero. Questo significa che il Nodo non riesce a consegnare la RT a GovPay, per problemi di rete o di autorizzazione. Questa è la causa del ritardo nell'acquisizione della RT.

**Comment by MatteoT9890** [comment]
Ciao @nardil,

innanzitutto grazie per la risposta rapida.  Escluderei la causa internet, penso sia un problema di autenticazione SSL a questo punto. Ti faccio un breve riepilogo delle configurazioni fatte:

**PORTALE DELLE ADESIONI**
- _URL Servizio RT_: https://pagopa.culturatela.it/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice

**CRUSCOTTO GOVPAY (INTERMEDIARIO)**
- _Principal_: /l=Milano/ou=pagoPA/serialnumber=39048250499308995741757054695765881747/o=SIA S.p.A/c=IT/cn=gad.test.pagopa.gov.it/
- _URL Servizio RPT_: https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T

_CONFIGURAZIONE  SSL AUTH APPLICATIVO GOVPAY_:

Generazione del JKS per il **keyStore** (.crt caricato sul portale e .key privata locale personale):
//FROM CRT-KEY TO P12 locally
` openssl pkcs12 -export -in x509certificate.crt -inkey private.key -out pagopa_culturatela.p12`

//GENERATE JKS FROM P12
`keytool -importkeystore -srckeystore pagopa_culturatela.p12 -srcstoretype PKCS12 -destkeystore /etc/govpay/pagopa_culturatela.jks -deststoretype JKS`

Analogamente per il **Trustore** (.crt recuperato sul portale delle adesioni): 

`keytool -import -file GAD.crt -alias firstCA -keystore /etc/govpay/gad.jks -deststoretype JKS`

Tali file vengono poi passati come JAVA_OPTS all'interno del file `$JBOSS_HOME/bin/standalone.conf` nel seguente modo:

```
JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=/etc/govpay/gad.jks -Djavax.net.ssl.trustStorePassword=_mypass_ -Djavax.net.ssl.trustStoreType=jks"

JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.keyStore=/etc/govpay/pagopa_culturatela.jks -Djavax.net.ssl.keyStorePassword=_mypass_ -Djavax.net.ssl.keyStoreType=jks"

```

Tutto ciò che è stato fatto è sufficiente affinchè il nodo comunichi con GovPay? La comunicazione "Govpay->Nodo" avviene correttamente perchè l'esito evento "Richiesto elenco pagamenti sospesi a pagoPA" riceve 200 OK sul giornale degli eventi.

Grazie in anticipo per la disponibilità

**Comment by MatteoT9890** [comment]
@nardil 

Il warning relativo alla consegna della notifica è stato risolto lasciando vuoto il campo _API INTEGRAZIONE_ all'interno della cruscotto GovPay nella sezione _APPLICAZIONE_ 

Di fatto ora non appena si avvia un pagamento il log è il seguente:

```
2021-06-04 12:04:01.466 | INFO  | it.govpay.core.business.Versamento:267 | 11d99bb9-4628-4dd2-8f17-2b70f23a0f1b | Versamento (XF9xSaRhKwWUYkAv) dell'applicazione (SUMMAE) inserito
2021-06-04 12:04:02.076 | INFO  | it.govpay.core.business.Rpt:251 | df0ba827-74f9-4b29-afb4-f7b3daacab8b | Inserita Rpt per il versamento (XF9xSaRhKwWUYkAv) dell'applicazione (SUMMAE) con dominio (00378210462) iuv (41000000000030285) ccp (040620211204946001)
2021-06-04 12:04:03.476 | INFO  | it.govpay.core.business.Rpt:329 | df0ba827-74f9-4b29-afb4-f7b3daacab8b | Rpt accettata dal Nodo dei Pagamenti
2021-06-04 12:04:03.556 | INFO  | it.govpay.core.business.Rpt:531 | df0ba827-74f9-4b29-afb4-f7b3daacab8b | RPT inviata correttamente al nodo
```

Sul giornale degli eventi non viene riportata più nessuna anomalia.


**Nonostante ciò** vi è ancora un notevole ritardo nella passaggio da "IN_CORSO" a "ESEGUITO" (più di 30 minuti).

**Comment by MatteoT9890** [comment]
Apro un'altra issue apposita
