### ISSUE TITLE
Connettore Maggioli (JPPA)

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#337]
**Necessità:**
Sviluppare un connettore per l'integrazione ai servizi della suite Maggioli per la comunicazione dei pagamenti avvenuti.

**Soluzione:**

Il connettore "Maggioli (JPPA)" richiede i seguenti parametri di configurazione:
- `Principal`: principal autenticato dalla chiamata di Maggioli
- `URL`: endpoint del servizio Maggioli per la Notifica dei pagamenti avvenuti
- `Versione`: versione del servizio, al momento la sola disponibile e' la 1.0.
- `Email`: lista degli indirizzi email a cui inviare il resoconto delle notifiche.

Aggiungere alle impostazioni del giornale degli eventi le API Maggioli (JPPA), per indicare se e quali eventi loggare. Le notifiche sono da intendersi scritture, mentre le acquisizioni delle RT sono da intendersi letture.

Un batch seleziona le RPT che hanno ricevuto una RT positiva dall'ultima esecuzione per la quale invoca l'operazione `InvioEsitoPagamento` del servizio `jppapdp-ws-internal.wsdl` :

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:int="http://jcitygov.informatica.maggioli.it/pagopa/payservice/pdp/connector/jppapdp/internal">
   <soap:Header/>
   <soap:Body>
      <int:InviaEsitoPagamentoRichiesta>
         <int:operazione>InviaEsitoPagamento</int:operazione>
         <int:identificativoDominio>${idDominio}</int:identificativoDominio>
         <int:dataOperazione>${dataRT}</int:dataOperazione>
         <int:version>1.0</int:version> <!-- identifica la versione del ws che si vuole utilizzare -->
         <int:xmlDettaglioRichiesta>
         <![CDATA[
           <InviaEsitoPagamentoRichiesta xmlns="http://jcitygov.informatica.maggioli.it/pagopa/payservice/pdp/connector/jppapdp/internal/schema/1_0"> 
             <identificativoUnivocoVersamento>${iuv}</identificativoUnivocoVersamento>
             <codiceContestoPagamento>${ccp}</codiceContestoPagamento>
             <esitoPagamento>ESEGUITO</esitoPagamento>
           </InviaEsitoPagamentoRichiesta>
         ]]>
         </int:xmlDettaglioRichiesta>
      </int:InviaEsitoPagamentoRichiesta>
   </soap:Body>
</soap:Envelope>
```

La spedizione deve essere registrata sul Giornale degli eventi con valorizzati riferimenti della transazione RPT.

Tutte le spedizioni vengono registrate in un CSV che poi viene allegato al messaggio email con i seguenti dati: `idDominio`, `iuv`, `ccp`, `esito`. Nell'`esito` viene indicato l'esito della risposta SOAP o il messaggio dell'eccezione riscontrata dal client http. Nel corpo del messaggio vengono indicati il numero di pagamento gestiti e quanti in con errore di notifica.

Viene inoltre esposto il servizio WSDL `jppapdp-ws-external.wsdl` di cui viene implementata la sola operazione `RecuperaRT`, mentre le altre restituiscono un errore di NotImplementedException. Le richieste sono autorizzare verificando che il principal corrisponda a quello indicato nella configurazione del connettore. La richiesta contiene gli estremi delle RT da recuperare:

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ext="http://jcitygov.informatica.maggioli.it/pagopa/payservice/pdp/connector/jppapdp/external">
   <soapenv:Header/>
   <soapenv:Body>
      <ext:RecuperaRTRichiesta>
         <ext:operazione>RecuperaRT</ext:operazione>
         <ext:identificativoDominio>${idDominio}</ext:identificativoDominio>
         <ext:dataOperazione>2018-11-26T13:45:06Z</ext:dataOperazione>
         <ext:version>1.0</ext:version>
         <ext:xmlDettaglioRichiesta>
         <![CDATA[
          <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
          <RecuperaRTRichiesta xmlns="http://jcitygov.informatica.maggioli.it/pagopa/payservice/pdp/connector/jppapdp/external/schema/1_0">
            <identificativoUnivocoVersamento>${iuv}</identificativoUnivocoVersamento>
            <codiceContestoPagamento>${ccp}</codiceContestoPagamento>
          </RecuperaRTRichiesta>
          ]]>      
         </ext:xmlDettaglioRichiesta>
      </ext:RecuperaRTRichiesta>
   </soapenv:Body>
</soapenv:Envelope>
```

alla quale il servizio risponde con i dati della RT e di contabilita:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soapenv:Body>
      <RecuperaRTRisposta xmlns="http://jcitygov.informatica.maggioli.it/pagopa/payservice/pdp/connector/jppapdp/external">
         <operazione>RecuperaRT</operazione>
         <dataOperazione>2021-04-27T15:09:06.216Z</dataOperazione>
         <esito>OK</esito>
         <xmlDettaglioRisposta><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RecuperaRTRisposta xmlns="http://jcitygov.informatica.maggioli.it/pagopa/payservice/pdp/connector/jppapdp/external/schema/1_0">
    <esito>
        <code>OK</code>
    </esito>
    <ricevutaTelematica>
        <ricevutaXML>...XML della ricevuta in stringa...</ricevutaXML>
        <idDominio>...</idDominio>
        .... copia di tutti i dati della RT ....
    </ricevutaTelematica>
    <dettagliImporto>  <!-- per ogni quota di ogni voce pendenza -->
            <dettaglioImporto>
            <capitoloBilancio>{capitolo}</capitoloBilancio>
            <anno>{annoEsercizio}</anno>
            <importo>{importo}</importo>     
            <descrizione>{vocePendenza.descrizione}</descrizione>
        </dettaglioImporto>
    </dettagliImporto>
</RecuperaRTRisposta>]]>
        </xmlDettaglioRisposta>
      </RecuperaRTRisposta>
   </soapenv:Body>
</soapenv:Envelope>
```

L'invocazione deve essere registrata sul Giornale degli eventi con valorizzati riferimenti della transazione RPT.

**Note:**
WSDL e documentazione dei servizi Maggioli: 
[jppa_20210606.zip](https://github.com/link-it/govpay/files/6621704/jppa_20210606.zip)

**Test:**
- [ ] Verificare che venga eseguita la notifica di un pagamento se e' stato attivato il connettore Maggioli
- [ ] Verificare che il servizio RecuperaRT restituisca la RT secondo specifiche dal principal autorizzato
- [ ] Verificare la corretta risposta del servizio RecuperaRT anche in presenza di dati di contabilità
- [ ] Verificare che il servizio RecuperaRT ritorni errore di autorizzazione se invocato da un soggetto non autorizzato

**Comment by pintorig** [comment]
Sviluppo Backend 

API-Backoffice:
- [ ]  Aggiungere alla configurazione del giornale degli eventi la possibilita' di configurare gli eventi per il connettore Maggioli JPPA.
- [ ]  Test di validazione della nuova configurazione giornale eventi per il connettore Maggioli JPPA.
- [ ]  Aggiungere la possibilita' di configurare il nuovo connettore Maggioli JPPA per gli Enti Creditori
- [ ]  Test di validazione del nuovo connettore Maggioli JPPA per gli Enti Creditori

**Comment by pintorig** [comment]
@simo-git 

Aggiungere al cruscotto la possibilita' di configurare il connettore Maggioli JPPA:

- [ ]  Aggiungere il connettore alla lista dei connettori disponibili (visualizzarli in ordine alfabetico)

![Screenshot from 2021-09-13 16-03-01](https://user-images.githubusercontent.com/12812160/133101996-90fdd101-fc8e-4b27-8ce3-600e87ab2cc8.png)

- [ ] Schermata di configurazione:

![Screenshot from 2021-09-13 16-40-33](https://user-images.githubusercontent.com/12812160/133104275-7c8a652c-de71-4c07-9da2-82f306e41ef3.png)


- La versione disponibile e' solo la 1.0;
- La modalita' di consegna del tracciato di esito e' solo Email;
- La parte di configurazione del servizio InviaNotificaPagamento e' uguale a quella del connettore GovPay in modalita' REST, ma il valore consentito nella versione API e'  SOAP V1 (vedi enum nello yaml);
