### ISSUE TITLE
Utilizzo API GovPay

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#339]
Buonasera,
ho scaricato, compilato ed installato GovPay 3.4.0.
Sto provando ad invocare la :
/govpay/frontend/api/pagamento/rs/basic/v2/pagamenti

Passando i parametri di esempio di Swagger:
```json
{
  "pendenze": [
    {
      "idA2A": "001",
      "idPendenza": "LIBERO"
    },
    {
      "idDominio": "12345678911",
      "numeroAvviso": 123456789012345680,
      "idDebitore": "RSSMRA30A01H501I"
    },
    {
      "idA2A": "001",
      "idPendenza": "LIBERO",
      "idDominio": 12345678911,
      "idUnitaOperativa": "UO33132",
      "idTipoPendenza": "IMU",
      "causale": "Sanzione CdS n. abc00000",
      "soggettoPagatore": {
        "tipo": "F",
        "identificativo": "RSSMRA30A01H501I",
        "anagrafica": "Mario Rossi",
        "indirizzo": "Piazza della Vittoria",
        "civico": "10",
        "cap": 0,
        "localita": "Roma",
        "provincia": "Roma",
        "nazione": "IT",
        "email": "mario.rossi@host.eu"
      },
      "importo": 10.01,
      "numeroAvviso": 123456789012345680,
      "tassonomia": "Sanzioni",
      "tassonomiaAvviso": "Ticket e prestazioni sanitarie",
      "dataValidita": "2020-06-30",
      "dataScadenza": "2020-12-31",
      "annoRiferimento": 2020,
      "cartellaPagamento": "ABC00000001",
      "datiAllegati": {},
      "direzione": "Direzione ABC",
      "divisione": "Divisione001",
      "proprieta": {
        "linguaSecondaria": "false",
        "descrizioneImporto": [
          {
            "voce": "canone annuo",
            "importo": 10.01
          }
        ],
        "lineaTestoRicevuta1": "string",
        "lineaTestoRicevuta2": "string"
      },
      "voci": [
        {
          "idVocePendenza": "12345"
        },
        {
          "codEntrata": "SRV-12345"
        },
        {
          "ibanAccredito": "IT60X0542811101000000123456",
          "ibanAppoggio": "IT60X0542811101000000123456",
          "tipoContabilita": "SIOPE",
          "codiceContabilita": 3321
        },
        {
          "tipoBollo": "Imposta di bollo",
          "hashDocumento": "--- base64 ---",
          "provinciaResidenza": "RO"
        }
      ]
    },
    {
      "idDominio": "01234567890",
      "idTipoPendenza": "IMU",
      "dati": {}
    }
  ],
  "urlRitorno": "https://www.comune.it/pagamentopagopa/abcd-efgh-ijklm-12345",
  "contoAddebito": {
    "iban": "IT60X0542811101000000123456",
    "bic": "DABAIE2D"
  },
  "dataEsecuzionePagamento": "2021-06-30",
  "credenzialiPagatore": "string",
  "soggettoVersante": {
    "tipo": "F",
    "identificativo": "RSSMRA30A01H501I",
    "anagrafica": "Mario Rossi",
    "indirizzo": "Piazza della Vittoria",
    "civico": "10",
    "cap": 0,
    "localita": "Roma",
    "provincia": "Roma",
    "nazione": "IT",
    "email": "mario.rossi@host.eu",
    "cellulare": "+39 000 1234567"
  },
  "autenticazioneSoggetto": "CNS"
}
```
ma ottengo sempre :
```json
{
    "categoria": "RICHIESTA",
    "codice": "SINTASSI",
    "descrizione": "Richiesta non valida",
    "dettaglio": "Il campo importo non deve essere vuoto."
}
```
anche se il campo non è vuoto. 
Sto interagendo tramite Postman

Avete qualche consiglio ?
Ho notato inoltre che da console non riesco ad inserire una nuova pendenza in quanto la combo non trova alcun Ente Creditore.

Grazie,
G

**Comment by nardil** [comment]
La richiesta non e' valida poiche' le voci della pendenza non presentano importo.

Oltre a verificare che il messaggio sia conforme alla definizione openAPI, puoi prendere spunto dai messaggi nella documentazione: https://govpay.readthedocs.io/it/latest/scenari/spontaneo1/realizzazione.html#govpay-scenari-spontaneo1-realizzazione

**Comment by giuseppelab** [comment]
Grazie mille, verifico.
Ma è normale che da console backoffice non si possa inserire una nuova pendenza ?
Ho inserito un ente creditore di prova ma il form nuova pendenza non vede enti.

Grazie,

**Comment by nardil** [comment]
La form di inserimento pendenze deve essere preventivamente configurata tra i dettagli dei Tipi Pendenza dell'Ente Creditore: https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/enti/pendenza_dovuto.html#govpay-configurazione-enti-formoperatore

**Comment by nardil** [comment]
E' un'imperfezione del cruscotto mostrare il pulsante di aggiunta delle pendenze anche se non se ne e' ancora configurata alcuna. Risolveremo nelle prossime versioni.

**Comment by giuseppelab** [comment]
OK, grazie.

**Comment by giuseppelab** [comment]
Ho trovato anche un manuale di qualche anno fa dove leggo che ci sono anche dei servizi soap esporti da govpay tipo Generazione IUV, ed avvia pagamento; vedo url del genere:
http://host:porta/govpay/PagamentiTelematiciGP/soap

Sono state tolte ?

**Comment by giuseppelab** [comment]
Sono riuscito a caricare la pendenza, grazie mille.

**Comment by nardil** [comment]
> Ho trovato anche un manuale di qualche anno fa dove leggo che ci sono anche dei servizi soap esporti da govpay tipo Generazione IUV, ed avvia pagamento; vedo url del genere:
> http://host:porta/govpay/PagamentiTelematiciGP/soap

Si, dalla versione 3.x le API SOAP di integrazione sono state rimosse.

**Comment by giuseppelab** [comment]
Bunasera Lorenzo, scusa una info; esiste una API per annullare una pendenza caricata ?
Grazie.

**Comment by nardil** [comment]
Ciao @giuseppelab 

```json
PATCH /pendenze/{idA2A}/{idPendenza}

[
  {
    "op": "REPLACE",
    "path": "/stato",
    "value": "ANNULLATA"
  },
  {
    "op": "REPLACE",
    "path": "/descrizioneStato",
    "value": "Pagamento non dovuto perche ...."
  }
]
```

Il cambio della descrizione dello stato e' opzionale.

**Comment by giuseppelab** [comment]
Ciao Lorenzo, grazie mille.

**Comment by giuseppelab** [comment]
Buongiorno Lorenzo,
Scusa un paio di info:
Se inserisco una pendenza duplicata ho notato che mi reinvia il numero avviso e l'avvido PDF è normale che non mi dica che esiste già ? posso utilizzare questa modalità per recuperare l'avviso in un momento successivo al rilascio dello stesso ?

Come posso fare a recuperare la ricevuta in PDF ? posso richiamare una API ?

Grazie mille.
Giuseppe

**Comment by giuseppelab** [comment]
Ciao Lorenzo, 
ho trovato solo il recupero del pagamento che mi da anche gli xml di RPT ed RT ma non sono riuscito a trovare una chiamata che mi restituisse il base64 della ricevuta RT in PDF come per l'avviso di pagamento.
Sto sbagliando qualcosa ?
Grazie.

**Comment by nardil** [comment]
> Se inserisco una pendenza duplicata ho notato che mi reinvia il numero avviso e l'avvido PDF è normale che non mi dica che esiste già ?

Si, e' normale e la pendenza viene aggiornata se le modifiche sono valide. L'aggiornamento si differenzia dall'inserimento nel codice di ritorno (200 vs 201)

> posso utilizzare questa modalità per recuperare l'avviso in un momento successivo al rilascio dello stesso ?

Si, ma e' inefficiente. Meglio usare la risorsa `/avvisi/{idDominio}/{numeroAvviso}`

> mi restituisse il base64 della ricevuta RT in PDF

prova con la risorsa `/rpp​/{idDominio}​/{iuv}​/{ccp}​/rt` impostando l'header HTTP `Accept: application/pdf`

Per ulteriori chiarimenti suggerirei di apri nuove issue con titoli pertinenti al quesito, cosi da facilitarne la ricerca per chi affronta le stesse problematiche.
