### ISSUE TITLE
Dati di rendicontazione in formato PagoPA

### ISSUE THREAD

**Issue by SbGibson** [link-it/GovPay#34]
Al fine di rendere la soluzione il più interoperabile possibile potrebbe essere utile un metodo nei ws che restituisca l'xml di rendicontazione così come prodotto dal nodo dei pagamenti.
In questo modo applicazioni che già implementano l'importazione in quel formato, magari fornito su file da qualche intermediario, non dovrebbero implementare una nuova importazione ma potrebbero solamente scaricarlo anche con un'interfaccia ad hoc e poi passarlo alla funzionalità esistente.

**Comment by nardil** [comment]
Ciao @SbGibson,
non avrebbe molto senso invocare il servizio di rendicontazione di GovPay se non interessano i dati di riconciliazione o validazione aggiunti. Se si preferisce l'interfaccia originale, la soluzione migliore e' invocare direttamente la porta di dominio e bypassare GovPay.
