### ISSUE TITLE
Stato PENDENZA pagato e stato PAGAMENTO in corso

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#343]
Ciao,
ci sono delle PENDENZE che sono in stato PAGATA ma il cui pagamento è in stato IN CORSO il che crea una continua richiesta della copia RT verso pagoPA.

Nei casi verificati ho anche ricevuto la rendicontazione del pagamento nei flussi, occorre bonificare in questi casi?
grazie

**Comment by nardil** [comment]
La problematica dovrebbe essere gia' stata risolta nel branch 3.4.x e verra' rilasciata prossimamente con la versione 3.4.2. 

Se hai modo di anticipare l'installazione, puoi farci sapere se risolve il tuo problema?

**Comment by giuseppeformaro** [comment]
Ciao, eseguito aggiornamento alla 3.4.1 ma ancora il problema mi pare rimanga.

Ti inoltro in privato il log.

**Comment by giuseppeformaro** [comment]
Buondi,
dovrebbe essere: Versione: 3.4.1 (83e0184)

**Comment by nardil** [comment]
Come accennato, la patch per il tuo problema è nella versione 3.4.2 ancora non rilasciata. Puoi compilare i sorgenti del branch 3.4.x oppure scaricare i binari da jenkins: https://jenkins.link.it/govpay/blue/organizations/jenkins/govpay/activity?branch=3.4.x
