### ISSUE TITLE
API Ragioneria v3

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#345]
**Necessità:**
Le attuali api di Ragioneria riportano una serie di dati non utili alle finalita' delle API di complessa implementazione e mancano di alcuni dettagli utili in determinati scenari.

Se ne propone quindi una versione migliorativa che nel primo rilascio realizza l'operazione di riconciliazione.

**Comment by nardil** [comment]
Nuove api: https://generator.swagger.io/?url=https://raw.githubusercontent.com/link-it/govpay/feature/345_api_ragioneria_v3/wars/api-ragioneria/src/main/webapp/v3/govpay-api-ragioneria-v3.yaml

**Comment by pintorig** [comment]
Estendere la versione V3 dell'API di Ragioneria includendo le seguenti operazioni sui flussi di rendicontazione:
![Screenshot from 2021-07-20 11-03-30](https://user-images.githubusercontent.com/12812160/126293557-4755b967-9124-405f-bb4c-f3b6c6562d61.png)

**Comment by nardil** [comment]
Mergiato sul branch 3.5.x

- Aggiunte risorse riscossioni
- Aggiunte risorse ricevute
- FlussoRendicontazioneIndex.dataAcquisizione rinominata in FlussoRendicontazioneIndex.data
- RiscossioneIndex rinominata in Riscossione
- Aggiunti a Riscossione i campi idDominio e idRicevuta
