### ISSUE TITLE
MOD.1 Riconciliazione - SCT

### ISSUE THREAD

**Issue by MatteoT9890** [link-it/govpay#346]
Per la riconciliazione dei pagamenti, il flow instaurato è il seguente:

1. GET delle riscossioni che sono in "STATO riscosso"
2. Per ognuna dei pagamenti in stato riscosso, estraggo: IUV, IMPORTO e viene eseguita una richiesta POST /riconciliazioni, in cui viene passato IUV  e IMPORTO, ma richiede anche SCT.

**La prima domanda è**:
E' corretto riconciliare tutte le riscossioni in stato "riscosso"? Non appena viene riconciliata una riscossione in stato "riscosso", il suo stato cambia immediatamente in "incassata" evitando così di rieseguire la riconciliazione sullo stesso IUV qualora il flow venisse invocato 2 volte di seguito (_idempotenza_) ?

**La seconda domanda è**:
Ricercando nella documentazione di pagoPA parla di SCT (SEPA Credit Transfer) come un identificativo che viene rilasciato dal PSP, capisco male? Se si, dove andare a pescarlo? Se no, è un identificativo che può generare liberamente il Partner Tecnologico senza seguire un formato preciso (banalmente un UUID)?

**Comment by nardil** [comment]
Ciao Matteo,

credo ci sia confusione sul processo di riconciliazione e sulle sue finalità. A tal proposito ti suggerisco un approfondimento consultando la documentazione pagoPA: https://docs.italia.it/italia/pagopa/pagopa-codici-docs/it/stabile/index.html

**Comment by MatteoT9890** [comment]
@nardil 

Grazie Lorenzo, ci informeremo a riguardo e chiederemo una call specifica con il team di supporto PagoPA per maggiori dettagli. Per adesso lascio ancora la issue aperta in maniera tale da poterci ritornare in un secondo momento. Se a seguito della call non ci sarà nessun punto da chiarire lato GovPay, provvederò a chiuderla.
