### ISSUE TITLE
Dati govpay sul portale delle adesioni

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#351]
Ciao,
sul portale delle adesioni, per aggiungere una nuova stazione, mi vengono richiesti i dati :
Versione (scelta tra 1 e 2);
URL di redirezione 
Per  govpay quali dati dovrei inserire nella richiesta ?
Grazie,

**Comment by nardil** [comment]
La versione 2 non e' ancora stabile presso il nodo dei pagamenti (e' supportata solo in ambiente di collaudo)

Per quanto riguarda la URL di redirezione, puoi consultare il manuale per decidere quale indicare: https://govpay.readthedocs.io/it/latest/integrazione/altriscenari/index.html?highlight=portale#redirezione-con-piu-portali-di-pagamento
