### ISSUE TITLE
Ricevere RT in modalità PUSH 

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#352]
## Aiutaci ad aiutarti!
Ecco alcuni suggerimenti per avere un aiuto più rapidamente:
* Utilizza un titolo chiaro e coinciso
* Se hai problemi di installazione, indica l'ambiente di deploy e allega i log dell'AS e di GovPay
* Se è un chiarimento sulla configurazione, descrivi lo scenario da realizzare, il risultato atteso e quello attuale.

**Comment by giuseppelab** [comment]
Ciao,
govpay invia all'applicazione interna, per default, in modalità push la RT una volta ricevuta dal nodo ?
Per predisporre l'applicativo interno alla ricezione, cosa ottengo ? un Json ? con quale struttura e campi ?
Grazie,

**Comment by nardil** [comment]
Si tratta delle "API di Verifica e Notifica" presenti nella documentazione alla sezione Integrazione: https://govpay.readthedocs.io/it/latest/integrazione/api/index.html
