### ISSUE TITLE
Attestazione di pagamento prodotta da GovPay - DOC

### ISSUE THREAD

**Issue by MatteoT9890** [link-it/govpay#353]
In riferimento alla issues #347 mi è parso di capire che GovPay produce un'attestazione di pagamento ma non riesco a trovare la relativa documentazione per ottenerla. Mi sapete indicare il link alla doc? 

Grazie mille

**Comment by nardil** [comment]
E' indicato nella definizione OpenAPI delle API utilizzate. E' sufficiente invocare la risorsa `/rpp/{idDominio}/{iuv}/{ccp}/rt` valorizzando l'header `Accept: application/pdf`
