### ISSUE TITLE
Wrong status with MyBank payments

### ISSUE THREAD

**Issue by jacob-y** [link-it/govpay#356]
Hi,

**Descrizione del Bug**

When we use MyBank payments, the donation is charged but the payment status is failed (RT ESITO SCONOSCIUTO PA).

We got this explanaton from pagoPA support:

> Good morning,
> we inform you that the Node tries to send the RT to the PA but the response it receives is KO.
> Moreover, the status remains RT ESITO SCONOSCIUTO PA  (RT result unknown) because your response to paaInviaRT is not validated by the Node, as the tags are missing and inside the fault.
> Therefore we invite you to correct the response by adding the missing tags and then to check why you are responding KO instead of accepting the RT.
> 
> 
> 
> tags are `<faultString> 
` and `  <id>
`  so that fault in the answer is composed like:

```


<fault>

<faultCode>

<faultString>

<id>

</fault>

```
 

 
 Any idea of the problem ?
 
 Thanks,
 Yann

**Comment by nardil** [comment]
You should attach the SOAP response sent to pagoPA (check into `govpay_dump.log`) and tell us the GovPay version in use.
