### ISSUE TITLE
Attivazione Stazione

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#357]
Buonasera,
mi hanno attivato la stazione di collaudo e mi hanno rilasciato una password che vedo sul portale delle adesioni.
questa password devo configurarla da qualche parte su govpay ?
Grazie,

**Comment by nardil** [comment]
Si, nella configurazione della stazione dal dettaglio dell'intermediario: 

https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/intermediari/index.html#stazioni
