### ISSUE TITLE
Limite massimo a 5 delle VOCI PENDENZA

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#360]
Buondi,
avrei bisogno di un suggerimento su come poter gestire pendenze con più VOCI rispetto al limite massimo delle 5 imposte da pagoPA.

Mi sapreste dare indicazioni? Se sono stato poco chiaro e servono altre info sono a disposizione!

Grazie.

**Comment by nardil** [comment]
In prima istanza puoi accorpare le voci omogenee per conto di accredito e tassonomia. Se comunque il numero di voci e' superiore a 5, l'unica alternativa e' quella di predisporre più pendenze.

**Comment by giuseppeformaro** [comment]
Grazie per il supporto!
