### ISSUE TITLE
Emissione Pendenze turisti senza Codice Fiscale

### ISSUE THREAD

**Issue by VinceHpa** [link-it/govpay#363]
Ciao, dovrei emettere pendenze verso turisti che non sono in possesso di CF. 

In particolare faccio riferimento a:

[https://generator.swagger.io/?url=https://raw.githubusercontent.com/link-it/govpay/master/wars/api-pendenze/src/main/webapp/v2/govpay-api-pendenze-v2.yaml]

mi chiedevo come si può emettere una pendenza verso un cittadino non identificato a mezzo CF.

Una pendenza verso "anonimi" facendo riferimento a questa tabella, pag. 94 voce 18:

[https://govpay.readthedocs.io/_/downloads/it/latest/pdf/]

Grazie per l'aiuto
Vincenzo

**Comment by nardil** [comment]
In una [precedente versione delle specifiche pagoPA](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida/specifiche_attuative_nodo_2_0_6.pdf) era indicata la possibilità di valorizzare con `ANONIMO` il campo del codice fiscale (e presumibilmente anche l'anagrafica).

Questa possibilità non e' esplicitata nelle specifiche più recenti pertanto dovresti chiedere a pagoPA se questa possibilità e' ancora contemplata.

**Comment by VinceHpa** [comment]
Perfetto. Mi hanno risposto da PagoPa di usare "ANONIMO" come nella precedente versione.
