### ISSUE TITLE
Errore inserimento PENDENZA MULTIVOCE e NUMERO AVVISO (VER_031)

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#364]
Buondi,
l'inserimento di una pendenza con piu voci va in errore se la stessa presenta anche il numero avviso. C'è una motivazione per tale comportamento? Ovviamente non parliamo di multibeneficiario ma di una casisitica più semplice di più voci dello stesso Ente.

Versione di Govpay in uso: 3.4.1 (83e0184)

Grazie!

**Comment by nardil** [comment]
La versione 3.4.x di GovPay implementa le specifiche SANP v.2.3 di pagoPA che vincolano i pagamenti ad iniziativa PSP ad avere una sola voce. Per questo GovPay non consente l'emissione di un avviso che altrimenti non risulterebbe pagabile.

Questo limite e' stato superato con le specifiche SANP v2.4 che sono in corso di integrazione nella versione 3.5.x di GovPay.

**Comment by giuseppeformaro** [comment]
Chiarissimo come sempre! 

Grazie

**Comment by giuseppeformaro** [comment]
Ciao,
sto iniziando a provare con la 3.5.x il caricamento con più voci, ma ho un dubbio:

- per i casi con più voci non sarà più possibile generare avvisi passandogli anche il numero avviso?

**Comment by nardil** [comment]
> * per i casi con più voci non sarà più possibile generare avvisi passandogli anche il numero avviso?

Si, apri pure una segnalazione nell'eventualità in cui non riuscissi a farlo.

> * il pagamento ad iniziativa ente non è supportato in questa versione o bisogna gestirlo diversamente sui gestionali?

Il pagamento ad iniziativa ente e' supportato, sia di posizioni singole che di carrelli multibeneficiario (fino a 5 posizioni). Non e' ancora supportato il pagamento di un avviso multibeneficiario ad iniziativa ente.
