### ISSUE TITLE
[Api Verifica e Notifica] Errore nella consegna della notifica (GovPay 3.3.4 e successivi)

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#369]
Buongiorno,
Sto utilizzando la versione di GovPay 3.3.4 e ho implementato un client per l'utilizzo delle api di verifica e notifica.
Attualmente, all'avvio di un nuovo pagamento, ricevo correttamente la notifica sul mio portale.
Le notifiche di conclusione del pagamento invece, quelle che dovrebbero inviarmi un pagamento con esito ESEGUITO, non vengono inviate.
Sul log di GovPay vedo questo errore :

`Errore nella consegna della notifica`

Con l'aggiunta di uno stack trace su System.err sono riuscito ad ottenere questa descrizione 

`java.lang.NullPointerException
        at it.govpay.core.utils.client.v1.NotificaConverter.toRiscossione(NotificaConverter.java:67) ~[core-3.3.4.jar:?]
        at it.govpay.core.utils.client.v1.NotificaTerminazioneConverter.toRsModel(NotificaTerminazioneConverter.java:56) ~[core-3.3.4.jar:?]
        at it.govpay.core.utils.client.NotificaClient.getMessaggioRichiesta(NotificaClient.java:180) ~[core-3.3.4.jar:?]
        at it.govpay.core.utils.client.NotificaClient.invoke(NotificaClient.java:142) ~[core-3.3.4.jar:?]
        at it.govpay.core.utils.thread.InviaNotificaThread.run(InviaNotificaThread.java:172) [core-3.3.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]
`

Analizzando lo stacktrace ho visto che la notifica va in NullPointer in questo punto

`riscossione.setIdVocePendenza(pagamento.getSingoloVersamento().getCodSingoloVersamentoEnte());`

Mi viene da pensare che per qualche motivo il metodo getSingoloVersamento() restituisca un valore nullo.
La domanda è
- Sto sbagliando io nell'avvio di un pagamento ?
- E' un bug di GovPay  ?(sembra essere presente anche nelle versioni recenti analizzando il codice da github)

Come posso risolvere ? le notifiche sono essenziali per il funzionamento del nostro ambiente dei pagamenti. Ho visto che il metodo in questione ha anche un'altra definizione con un altro parametro che forse potrebbe essere usata per risolvere il problema.
Per favore mi fate sapere come posso fare ?

**Comment by nardil** [comment]
Ciao @frdidonato , 

non siamo a conoscenza di problemi di questo tipo nelle notifiche dei pagamenti.

Ti chiederei quindi di replicare il problema partendo da una pendenza nuova e, se il problema persiste, condividere le richieste inviate alle API per consentirci di replicarlo.

**Comment by frdidonato** [comment]
Ciao @nardil 
Ho replicato le richieste partendo da una nuova pendenza come mi hai chiesto. Nelle varie prove che ho effettuato riscontro il problema solo in caso di pagamento eseguito con successo. Alcuni tentativi sono stati effettuati con una carta di test non funzionante e la notifica di pagamento non eseguito è arrivata correttamente.
Ti allego le chiamate di creazione pendenze e di avvio del pagamento che uso. Con queste chiamate ricevo solamente la notifica di avvio del pagamento ma non quella di pagamento eseguito per quell'errore che ti ho indicato prima.

[govpay_api.txt](https://github.com/link-it/govpay/files/6890940/govpay_api.txt)

**Comment by pintorig** [comment]
Ciao @frdidonato 
Il problema di cui parli e' stato corretto nella versione 3.4.0, commit b0a70504b75db3e0289da5d2a82a5a2f020cd43c.

**Comment by frdidonato** [comment]
Perfetto grazie mille @pintorig , allora procedo all'aggiornamento alla versione 3.4.0

**Comment by frdidonato** [comment]
Buongiorno, vi confermo che con la versione 3.4.0 non si presenta lo stesso problema, tutto sembra funzionare correttamente.
Grazie per la collaborazione
