### ISSUE TITLE
Errore prova pagamento in ambiente di test

### ISSUE THREAD

**Issue by MSviluppo** [link-it/govpay#376]
Buongiorno, nel tentativo di effettuare un pagamento di prova in ambiante di test ci torna questo errore, mi sapete dare qualche indicazione  

<nodoVerificaRPTRisposta>
                <fault>
                    <faultCode>PPT_ERRORE_EMESSO_DA_PAA</faultCode>
                    <faultString>Errore restituito dalla PAA.</faultString>
                    <id>80000870891</id>
                    <description>FaultCode PA: PAA_SYSTEM_ERROR
FaultString PA: Errore generico.
Description PA: Operazione non autorizzata</description>
                </fault>
                <esito>KO</esito>
            </nodoVerificaRPTRisposta>

Grazie

**Comment by nardil** [comment]
Non è stata correttamente configurata l'erogazione del servizio. Verifica che il principal configurato nell'intermediario corrisponda al subject del certificato con cui si presenta pagoPA. Trovi informazioni utili nei log se configurati in debug.
