### ISSUE TITLE
non riesco a configurare GOVPAY (applicazioni e relazione con connessione verso PAGO PA) aiuto

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#378]
Salve,
premetto che il certificato per mutua autenticazione SSL ha come soggetto un carattere accentato (à) quindi quando lo riporto come principal nell'intermediario e nell'applicazione sul DB postgresql appare con un carattere strano accentato. Questo mi compromette l'autenticazione? non ho capito la relazione tra questo principal e il processo di handshake verso PAGOPA.

La configurazione delle applicazioni va impostata con tipo autenticazione "SSL" e inserimento come "client o server" nel relativo campo "TIPO". Inoltre devo inserire il percorso e la password del truststore e keystore dove ho inserito il certificato fornito da pagopa nel portare delle adesioni?

se uso POSTMAN per fare una prova ad esempio questo servizio "https://govpaytest.iss.it/govpay/backend/api/pendenze/rs/ssl/v2/pendenze/TEST_PAGOPA_API/2" via PUT, devo usare appunto SSL o basic come autenticazione? Lo chiedo perchè quando aggiungo un Applicazione sul portale, di fatto vengono create delle credenziali sul DB che sono utilizzate se scelgo appunto "basic" come sistema di autenticazione, ma poi GOV PAY in automatico usa la configurazione SSL per parlare con PAGO PA?

a cosa serve la password della stazione?

Esiste  un esempio di configurazione di un intermediario e relativa applicazione che deve usare il modulo 1 e 3 di PAGO PA, considerato un certificato SSL con subject: "CN=pippo.prova.it,O=autorità di prova, STREET = Via pippo 1, L = Roma, PostalCode = 00161, C = IT   
Ovviamente è un esempio per capire come devono essere configurati tutti i campi di interesse.

Inoltre io sto utilizzando wildfly18 (sotto microsoft server) e ho creato tramite openSSL e keytool il keytstore e truststore, inseriti in un path locale e puntati tramite JAVA_OPT nello standalone.conf.bat. E' sufficiente affinchè il tutto venga recepito dal server o serve fare altro?

Ringrazio per il supporto, ho trovato tante informazioni utili e sono giusto a questo livello di comprensione grazie a tutti gli spunti trovati.

**Comment by nardil** [comment]
Ciao @mallomix 

> premetto che il certificato per mutua autenticazione SSL ha come soggetto un carattere accentato (à) quindi quando lo riporto come principal nell'intermediario e nell'applicazione sul DB postgresql appare con un carattere strano accentato. Questo mi compromette l'autenticazione? non ho capito la relazione tra questo principal e il processo di handshake verso PAGOPA.

Se la codifica su DB è in UTF-8, [come da istruzioni di installazione](https://govpay.readthedocs.io/it/latest/installazione/dispiegamento/index.html), non dovresti avere problemi in questo senso. Eventualmente nei log in debug puoi verificare il principal usato da GovPay per l'autorizzazione. 

> La configurazione delle applicazioni va impostata con tipo autenticazione "SSL" e inserimento come "client o server" nel relativo campo "TIPO". Inoltre devo inserire il percorso e la password del truststore e keystore dove ho inserito il certificato fornito da pagopa nel portare delle adesioni?

Il modo le applicazioni sono autenticate da GovPay dipende dalla URL che queste usano per fruire dei servizi: https://govpay.readthedocs.io/it/latest/integrazione/api/autenticazione/index.html#integrazione-autenticazione

Invece la configurazione del connettore definisce la modalità con cui GovPay si autentica all'applicazione quando funge da client (SSL Client Auth, HTTP Basic o nessuna autenticazione)
 
> se uso POSTMAN per fare una prova ad esempio questo servizio "https://govpaytest.iss.it/govpay/backend/api/pendenze/rs/ssl/v2/pendenze/TEST_PAGOPA_API/2" via PUT, devo usare appunto SSL o basic come autenticazione? Lo chiedo perchè quando aggiungo un Applicazione sul portale, di fatto vengono create delle credenziali sul DB che sono utilizzate se scelgo appunto "basic" come sistema di autenticazione, ma poi GOV PAY in automatico usa la configurazione SSL per parlare con PAGO PA?

La URL indicata usa l'autenticazione con certificato SSL. 

La configurazione delle applicazioni determina il colloquio tra GovPay ed i gestionali dell'Ente Creditore, mentre il colloquio con pagoPA viene impostato nella configurazione dell'intermediario.
 
> a cosa serve la password della stazione?

Viene assegnata dal Portale delle Adesioni a seguito dell'attivazione di una stazione ed è necessaria all'autenticazione verso pagoPA

**Comment by mallomix** [comment]
Grazie Nardil per le preziose info, quindi ricapitolando:
1) Corretto l'uso del principal = subject del certificato. Devo verificare UTF-8 su DB postgresql e dovrebbe funzionare anche il carattere 'à'

2) se io ho una configurazione di questo tipo: app WEB che chiama i servizi GOVPAY e basta, non mi serve la configurazione della sezione applicazione, corretto? Mentre se io voglio che un'applicazione custom di backoffice utilizzi i dati delle transazioni di gov pay, allora devo impostare l'applicazione mettendo L'URL dei servizi custom sviluppati e la tipologia di autenticazione.

3) Configurato l'intermediario con principal corretto e URL servizi PagoPa corretti, la tipologia di autenticazione la lascio a NESSUNA.... poichè per default gov pay si aspetta i certificati SSL nel keystore e trustore così come configurati sul portare delle adesioni di PAGO PA, corretto? Quindi nel keystore c'è i l certificato per il colloquio GOVPAY to PAGOPA (rilasciato da pagopa) mentre nel truststore c'è quello creato dall'intermediario per il colloquio PAGOPA to GOVPAY, corretto?

ma non esiste una sorta di specchietto di esempio che riporta esattamente come i form di intermediario e applicazione sono settati, in modo che io posso ricondurlo alle mie informazioni?

ti ringrazio e mi scuso se non sono particolarmente preciso!

**Comment by nardil** [comment]
> 2. se io ho una configurazione di questo tipo: app WEB che chiama i servizi GOVPAY e basta, non mi serve la configurazione della sezione applicazione, corretto? Mentre se io voglio che un'applicazione custom di backoffice utilizzi i dati delle transazioni di gov pay, allora devo impostare l'applicazione mettendo L'URL dei servizi custom sviluppati e la tipologia di autenticazione.

Tutte le applicazioni che utilizzano le API di GovPay devono essere censite ed autorizzate secondo necessità, altrimenti riscontreranno un errore di autenticazione/autorizzazione

> 3. Configurato l'intermediario con principal corretto e URL servizi PagoPa corretti, la tipologia di autenticazione la lascio a NESSUNA.... poichè per default gov pay si aspetta i certificati SSL nel keystore e trustore così come configurati sul portare delle adesioni di PAGO PA, corretto? Quindi nel keystore c'è i l certificato per il colloquio GOVPAY to PAGOPA (rilasciato da pagopa) mentre nel truststore c'è quello creato dall'intermediario per il colloquio PAGOPA to GOVPAY, corretto?

Se ho ben interpretato la tua configurazione, hai impostate truststore e keystore come parametri della JVM di WildFly. In questo caso, se il colloquio con pagoPA è diretto, è sufficiente predisporre nel keystore il tuo certificato client (già condiviso con pagoPA nella connessione fisica sul PdA) e nel trustore il certificato di pagoPA.

**Comment by mallomix** [comment]
Grazie come sempre Nardil ma ti prego ancora un briciolo di pazienza se puoi:



> > 1. se io ho una configurazione di questo tipo: app WEB che chiama i servizi GOVPAY e basta, non mi serve la configurazione della sezione applicazione, corretto? Mentre se io voglio che un'applicazione custom di backoffice utilizzi i dati delle transazioni di gov pay, allora devo impostare l'applicazione mettendo L'URL dei servizi custom sviluppati e la tipologia di autenticazione.
> 
> Tutte le applicazioni che utilizzano le API di GovPay devono essere censite ed autorizzate secondo necessità, altrimenti riscontreranno un errore di autenticazione/autorizzazione
> 
quindi se io voglio chiamare le api di gov pay devo creare almeno una sezione "Applicazione". Mi sfugge allora ancora a cosa fa riferimento quell'URL da mettere in "API integrazione" e la modalità di autenticazione ecc. 
Io attualmente ho inserito lo stesso URL di PAGO PA messo su "Intermediario", scegliendo poi autenticazione SSL e proponendo il percorso e password del keystore e trustore. In questo modo ha funzionato ed ho inserito una pendenza. Ma allora a che serve l'URL su "Intermediario"? Scusami ma non riesco a capire bene tutto il giro, colpa mia ovviamente!

> > 1. Configurato l'intermediario con principal corretto e URL servizi PagoPa corretti, la tipologia di autenticazione la lascio a NESSUNA.... poichè per default gov pay si aspetta i certificati SSL nel keystore e trustore così come configurati sul portare delle adesioni di PAGO PA, corretto? Quindi nel keystore c'è i l certificato per il colloquio GOVPAY to PAGOPA (rilasciato da pagopa) mentre nel truststore c'è quello creato dall'intermediario per il colloquio PAGOPA to GOVPAY, corretto?
> 
> Se ho ben interpretato la tua configurazione, hai impostate truststore e keystore come parametri della JVM di WildFly. In questo caso, se il colloquio con pagoPA è diretto, è sufficiente predisporre nel keystore il tuo certificato client (già condiviso con pagoPA nella connessione fisica sul PdA) e nel trustore il certificato di pagoPA.

SI, ho impostato nel keystore e trustore i certificati client e quello di PAGO PA per la connettività da e verso, però la mia configurazione (end to end) non va diretta a PAGO PA ma vuole usare le interfacce di pagamento di GOV PAY, da qui tutte le domande precedenti di configurazione di intermediario e applicazioni.
In sintesi io ho una web APP che porta a carrello un prodotto. Per il pagamento chiama le API GOV PAY che a sua volta sfruttano quelle di PAGO PA.

Ho letto i manuali più volte senza trovare le risposte che cerco... molto probabilmente perchè non ho capito la base del colloquio tra client web -> govpay -> pagoPA per modulo 1 e 3.

mi puoi aiutare con qualche esempio pratico? 
Ad esempio quello che ho fatto ora e che sembra funzionare stona per me! Sicuramente il giro non si chiude correttamente nel successivo pagamento.

Ancora grazie

**Comment by nardil** [comment]
> quindi se io voglio chiamare le api di gov pay devo creare almeno una sezione "Applicazione". Mi sfugge allora ancora a cosa fa riferimento quell'URL da mettere in "API integrazione" e la modalità di autenticazione ecc.

La piattaforma GovPay dialoga con gli applicativi per l'invio di notifiche o per la verifica delle posizioni debitorie tramite le [API di Verifica e Notifica](https://govpay.readthedocs.io/it/latest/integrazione/api/index.html) che le applicazioni devono esporre.

L'esposizione del servizio e la configurazione del connettore non sono strettamente necessaria, ma nel caso non vengano predisposti non si puo' beneficiare dei servizi di aggiornamento automatico dell'Archivio dei Pagamenti in Attesa e del servizio di Notifica dei pagamenti.

**Comment by mallomix** [comment]
Ok ho capito! grazie per le preziose info. Adesso provo a metterle in campo
