### ISSUE TITLE
Acquisizione Psp fallito

### ISSUE THREAD

**Issue by pievealessandro** [link-it/GovPay#38]
Buongiorno
ho eseguito l'installazioe di govpay in locale e volevo eseguire dei test per comprendere maggiormente il suo funzionamento.
Quando però vado su govpayConsole a richiedere "Aggiorna elenco dei Psp" ricevo il seguenti errore

Operazione completata sul nodo: locale
Acquisizione fallita: it.govpay.core.exceptions.GovPayException: Impossibile aggiornare la lista dei Psp.

**Comment by nardil** [comment]
E' stata correttamente configurata l'integrazione con il Nodo dei Pagamenti SPC da cui viene acquisita la lista dei PSP?

Trovi maggiori dettagli sull'errore riscontrato nei file di log (diagnostici e dump).

**Comment by pievealessandro** [comment]
Grazie, credo che non sia configurata correttamente la porta di dominio.
