### ISSUE TITLE
Non si riesce ad inviare email di notifica

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#380]
Buonasera, pur avendo configurato il server email da IMPOSTAZIONI - Comunicazioni Mail, quando viene creata la pendenza con avviso, non parte la mail di notifica.
Occorre eseguire altre configurazioni o abilitazioni ?
Grazie.

**Comment by nardil** [comment]
Ciao @giuseppelab ,

la funzione di invio notifiche per default e' disabilitata e deve essere attivata per [Tipo Pendenza](https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/tipipendenze/index.html)

**Comment by giuseppelab** [comment]
OK, grazie; ma è obbligatorio inserimento template ? non possono essere usati quelli delle impostazioni - comunicazioni email ?
Grazie.

**Comment by nardil** [comment]
No non sono obbligatori, se non si impostano vengono usati quelli delle impostazioni.
