### ISSUE TITLE
Schedulazione recupero RT dal nodo

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#381]
Buonasera, è possibile cambiare la schedulazione delle richieste RT al nodo ?
Se non erro dovrebbe essere ogni ora.
Grazie.

**Comment by nardil** [comment]
La configurazione dei tempi di esecuzione dei batch e' nel file spring-timers: `/wars/api-pagopa/src/main/resources/spring-timers/applicationContext-timers.xml`

Non dovrebbe pero' essere un'operazione necessaria al corretto funzionamento della piattaforma. Quale situazione lo richiede?

**Comment by giuseppelab** [comment]
Era relativo ad un problema di configurazione di autenticazione. Sono riuscito a risolvere e adesso ricevo le RT.
Grazie mille.
