### ISSUE TITLE
SSLhandshake exception in richieste "Richiesto elenco pagamenti sospesi a pagoPA"

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#383]
Ho creato truststore e keystore importando il certificato rilasciato dal portare di PAGO PA per la mutua autenticazione SSL.
ho referenziato i JKS attraverso le JAVA_OPT e vengono recepite da Wildfly 18 sezione "monitor->status->bootstrap"

Però nei log alla chiamata ogni ora del servizio in oggetto, ricevo un FAIL con la seguente dicitura:

"javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target" 

questa la parte del log completa:

"{"id":2082,"componente":"API_PAGOPA","categoriaEvento":"INTERFACCIA","ruolo":"CLIENT","tipoEvento":"nodoChiediListaPendentiRPT","esito":"FAIL","dataEvento":"2021-08-23T13:00:00.004","durataEvento":102,"sottotipoEsito":"null","dettaglioEsito":"javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target","parametriRichiesta":{"dataOraRichiesta":"2021-08-23T11:00:00.004+0000","url":"https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60","headers":[{"nome":"SOAPAction","valore":"\"nodoChiediListaPendentiRPT\""},{"nome":"RequestPath","valore":"https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60"}],"payload":"PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iPjxzb2FwOkJvZHk+PG5zNDpub2RvQ2hpZWRpTGlzdGFQZW5kZW50aVJQVCB4bWxuczpuczI9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIiB4bWxuczpuczM9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvcHB0aGVhZCIgeG1sbnM6bnM0PSJodHRwOi8vd3MucGFnYW1lbnRpLnRlbGVtYXRpY2kuZ292LyI+PGlkZW50aWZpY2F0aXZvSW50ZXJtZWRpYXJpb1BBPjgwMjExNzMwNTg3PC9pZGVudGlmaWNhdGl2b0ludGVybWVkaWFyaW9QQT48aWRlbnRpZmljYXRpdm9TdGF6aW9uZUludGVybWVkaWFyaW9QQT44MDIxMTczMDU4N18wMTwvaWRlbnRpZmljYXRpdm9TdGF6aW9uZUludGVybWVkaWFyaW9QQT48cGFzc3dvcmQ+SVNTYW4wMVRlc3Q8L3Bhc3N3b3JkPjxyYW5nZURhPjIwMjEtMDYtMjRUMTM6MDA6MDA8L3JhbmdlRGE+PHJhbmdlQT4yMDIxLTA4LTIzVDEzOjAwOjAwPC9yYW5nZUE+PGRpbWVuc2lvbmVMaXN0YT41MDA8L2RpbWVuc2lvbmVMaXN0YT48L25zNDpub2RvQ2hpZWRpTGlzdGFQZW5kZW50aVJQVD48L3NvYXA6Qm9keT48L3NvYXA6RW52ZWxvcGU+","method":"POST"},"parametriRisposta":{"dataOraRisposta":"2021-08-23T11:00:00.106+0000","status":500,"headers":[]}}"

c'è qualche altra impostazione che devo far per abilitare l'autenticazione client dal server verso pago pa?

ringrazio per il supporto

**Comment by nardil** [comment]
Ciao @mallomix,
o c'e' un problema nella configurazione delle java opts oppure nel truststore. 

Dovresti controllare nel server.log di wildfly che all'avvio vengano stampate, tra le altre, le seguenti opzioni:
* `javax.net.ssl.keyStore`
* `javax.net.ssl.keyStorePassword`
* `javax.net.ssl.trustStore`
* `javax.net.ssl.trustStorePassword`

Potresti poi fornirci maggiori informazioni su come hai trustato il certificato di gad.test.pagopa.gov.it, magari allegando direttamente il truststore se e' possibile.

**Comment by mallomix** [comment]
Certo nardil,

questo quello che viene visto da wildfly come input arguments:
-Dprogram.name=standalone.bat
-Xms64M
-Xmx512M
-XX:MetaspaceSize=96M
-XX:MaxMetaspaceSize=256m
-Djava.net.preferIPv4Stack=true
-Djboss.modules.system.pkgs=org.jboss.byteman
-Djavax.net.ssl.trustStore=c:\govpay\pagopa_iss_test_trust.jks
-Djavax.net.ssl.trustStorePassword=password
-Djavax.net.ssl.trustStoreType=jks
-Djavax.net.ssl.keyStore=c:\govpay\pagopa_iss_test.jks
-Djavax.net.ssl.keyStorePassword=password
-Djavax.net.ssl.keyStoreType=jks
-Dorg.jboss.boot.log.file=C:\Users\ciro.salvio\Desktop\InstallazioneGovPay\wildfly-18.0.1.Final\wildfly-18.0.1.Final\standalone\log\server.log
-Dlogging.configuration=file:C:\Users\ciro.salvio\Desktop\InstallazioneGovPay\wildfly-18.0.1.Final\wildfly-18.0.1.Final\standalone\configuration/logging.properties

(le password le ho volutamente camuffate. Parliamo dell'ambiente di COLLAUDO

il truststore e il keystore l'ho creato così:


Dal CRT-KEY al P12 usando OPENSSL:	
openssl pkcs12 -export -in govpaytest_iss_it_cert.crt -inkey govpaytest-iss-it.key -out pagopa_iss_test.p12 
//mettere password della chiave privata (vedere documentazione di riferimento)

dove:
•	govpaytest_iss_it_cert.crt è il solo certificato rilasciato dall'autorità competente relativo al nostro dominio (govpaytest.iss.it)
•	govpaytest-iss-it.key è la chiave generata in fase di creazione del CSR attraverso il tool openssl

Generazione del JKS per il keyStore e trustore

Dal p12 generiamo il JKS per il keyStore e trustore:
keytool -importkeystore -srckeystore pagopa_iss_test.p12 -srcstoretype PKCS12 -destkeystore c:\govpay\pagopa_iss.jks -deststoretype JKS 
//mettere password della chiave privata (vedere documentazione di riferimento)
keytool -importkeystore -srckeystore c:\govpay\pagopa_iss_test.jks -destkeystore c:\govpay\pagopa_iss_test.jks -deststoretype pkcs12

Analogamente per il Trustore:
keytool -import -file govpaytest_iss_it_cert.crt -alias ALIAS -keystore c:\govpay\pagopa_iss_test.jks -deststoretype JKS

dove:
govpaytest_iss_it_cert.crt è il certificato (1 file) reperibile attraverso il proprio collegamento fisico sul portale delle adesioni di PAGO PA

**Comment by nardil** [comment]
Mi sembra tu abbia riportato i soli comandi di creazione del keystore `c:\govpay\pagopa_iss_test.jks`, ma non quelli del trustore `c:\govpay\pagopa_iss_test_trust.jks`.

Dalla descrizione sembra che tu abbia omesso il certificato di gad.test.pagopa.gov.it nel trustore. Eventualmente devi aggiungerlo.

**Comment by mallomix** [comment]
Grazie nardil,  ho scritto male il comando per il truststore, quello corretto è:
keytool -import -file govpaytest_iss_it_cert.crt -alias ALIAS -keystore **c:\govpay\pagopa_iss_test_trust.jks** -deststoretype JKS

però in effetti importo sempre lo stesso certificato che non credo sia quello GAD ma quello client. Quindi mi manca quello GAD che posso reperire dal portale delle adesioni corretto?

grazie come sempre

**Comment by nardil** [comment]
Si, lo scarichi dal Portale delle Adesioni quando crei la Connessione Fisica.

**Comment by mallomix** [comment]
Ciao,

ho rigenerato il keystore,jks e il Trustore.jks aggiugendo nel keystore il certificato nostro con chiave privata e nel trustore quello ottenuto dal portale delle adesioni GAD.
Il pacchetto conteneva 3 certificati :
1) ServerCertificate.crt
2) Intermediate.crt
3) Root.crt

io nel trustore.jks ho importato il ServerCertificate.crt

Fatto questo e modificato il principal dell'intermediario del portale GOV PAY con il soggetto del certificato (CN = gad.test.pagopa.gov.it, OU = pagoPA, O = SIA S.p.A, L = Milano, S = Milano, C = I)  ho riavviato wildfly e verificato che i nuovi keystore e trustore siano stati referenziati.

L'esito delle verifiche è OK ma sul portale GOV PAY, sezione eventi, vedo questo:
![image](https://user-images.githubusercontent.com/89087711/130776325-2bcdbd35-f79d-4836-830a-ca808c2403d2.png)
con il seguente dettaglio:
{"id":2176,"componente":"API_ENTE","categoriaEvento":"INTERFACCIA","ruolo":"CLIENT","tipoEvento":"notifyPagamento","esito":"FAIL","dataEvento":"2021-08-25T12:28:00.052","durataEvento":185,"sottotipoEsito":"null","dettaglioEsito":"javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target","idDominio":"80211730587","iuv":"RF74000000000000000000001","ccp":"n/a","idA2A":"TEST_PAGOPA_API","idPendenza":"1","idPagamento":"1fbab818aa1f4b9692ba71faa8d73798","parametriRichiesta":{"dataOraRichiesta":"2021-08-25T10:28:00.052+0000","url":"https://ecommerce.iss.it/restapi/govpay/pagamenti/80211730587/RF74000000000000000000001?idCarrello=1fbab818aa1f4b9692ba71faa8d73798","headers":[{"nome":"RequestPath","valore":"https://ecommerce.iss.it/restapi/govpay/pagamenti/80211730587/RF74000000000000000000001?idCarrello=1fbab818aa1f4b9692ba71faa8d73798"},{"nome":"Accept","valore":"application/json"},{"nome":"HTTP-Method","valore":"POST"}],"payload":"eyJpZEEyQSI6IlRFU1RfUEFHT1BBX0FQSSIsImlkUGVuZGVuemEiOiIxIiwicnB0Ijp7InZlcnNpb25lT2dnZXR0byI6IjYuMi4wIiwiZG9taW5pbyI6eyJpZGVudGlmaWNhdGl2b0RvbWluaW8iOiI4MDIxMTczMDU4NyIsImlkZW50aWZpY2F0aXZvU3RhemlvbmVSaWNoaWVkZW50ZSI6IjgwMjExNzMwNTg3XzAxIn0sImlkZW50aWZpY2F0aXZvTWVzc2FnZ2lvUmljaGllc3RhIjoiMzc5M2Q1ODgxZGYzNGM2ZTgyNjg4M2YwZGEwNDY0MTciLCJkYXRhT3JhTWVzc2FnZ2lvUmljaGllc3RhIjoiMjAyMS0wOC0yNFQxMToxNjoyNCIsImF1dGVudGljYXppb25lU29nZ2V0dG8iOiJOL0EiLCJzb2dnZXR0b1ZlcnNhbnRlIjpudWxsLCJzb2dnZXR0b1BhZ2F0b3JlIjp7ImlkZW50aWZpY2F0aXZvVW5pdm9jb1BhZ2F0b3JlIjp7InRpcG9JZGVudGlmaWNhdGl2b1VuaXZvY28iOiJGIiwiY29kaWNlSWRlbnRpZmljYXRpdm9Vbml2b2NvIjoiUlNTTVJBMzBBMDFINTAxSSJ9LCJhbmFncmFmaWNhUGFnYXRvcmUiOiJNYXJpbyBSb3NzaSIsImluZGlyaXp6b1BhZ2F0b3JlIjpudWxsLCJjaXZpY29QYWdhdG9yZSI6bnVsbCwiY2FwUGFnYXRvcmUiOm51bGwsImxvY2FsaXRhUGFnYXRvcmUiOm51bGwsInByb3ZpbmNpYVBhZ2F0b3JlIjpudWxsLCJuYXppb25lUGFnYXRvcmUiOm51bGwsImUtbWFpbFBhZ2F0b3JlIjpudWxsfSwiZW50ZUJlbmVmaWNpYXJpbyI6eyJpZGVudGlmaWNhdGl2b1VuaXZvY29CZW5lZmljaWFyaW8iOnsidGlwb0lkZW50aWZpY2F0aXZvVW5pdm9jbyI6IkciLCJjb2RpY2VJZGVudGlmaWNhdGl2b1VuaXZvY28iOiI4MDIxMTczMDU4NyJ9LCJkZW5vbWluYXppb25lQmVuZWZpY2lhcmlvIjoiSXN0aXR1dG8gU3VwZXJpb3JlIGRpIFNhbml0YScgLSBJU1MiLCJjb2RpY2VVbml0T3BlckJlbmVmaWNpYXJpbyI6bnVsbCwiZGVub21Vbml0T3BlckJlbmVmaWNpYXJpbyI6bnVsbCwiaW5kaXJpenpvQmVuZWZpY2lhcmlvIjoiVmlhbGUgUmVnaW5hIEVsZW5hIiwiY2l2aWNvQmVuZWZpY2lhcmlvIjoiMjk5IiwiY2FwQmVuZWZpY2lhcmlvIjoiMDAxNjEiLCJsb2NhbGl0YUJlbmVmaWNpYXJpbyI6IlJvbWEiLCJwcm92aW5jaWFCZW5lZmljaWFyaW8iOiJSb21hIiwibmF6aW9uZUJlbmVmaWNpYXJpbyI6IklUIn0sImRhdGlWZXJzYW1lbnRvIjp7ImRhdGFFc2VjdXppb25lUGFnYW1lbnRvIjoiMjAyMS0wOC0yNCIsImltcG9ydG9Ub3RhbGVEYVZlcnNhcmUiOiIyLjAwIiwidGlwb1ZlcnNhbWVudG8iOiJCQlQiLCJpZGVudGlmaWNhdGl2b1VuaXZvY29WZXJzYW1lbnRvIjoiUkY3NDAwMDAwMDAwMDAwMDAwMDAwMDAwMSIsImNvZGljZUNvbnRlc3RvUGFnYW1lbnRvIjoibi9hIiwiaWJhbkFkZGViaXRvIjpudWxsLCJiaWNBZGRlYml0byI6bnVsbCwiZmlybWFSaWNldnV0YSI6IjAiLCJkYXRpU2luZ29sb1ZlcnNhbWVudG8iOlt7ImltcG9ydG9TaW5nb2xvVmVyc2FtZW50byI6IjEuMDAiLCJjb21taXNzaW9uZUNhcmljb1BBIjpudWxsLCJpYmFuQWNjcmVkaXRvIjoiSVQwMkwxMjM0NTAwMDAwMTExMTEwMDAwMDAxIiwiYmljQWNjcmVkaXRvIjpudWxsLCJpYmFuQXBwb2dnaW8iOm51bGwsImJpY0FwcG9nZ2lvIjpudWxsLCJjcmVkZW56aWFsaVBhZ2F0b3JlIjpudWxsLCJjYXVzYWxlVmVyc2FtZW50byI6Ii9SRlMvUkY3NDAwMDAwMDAwMDAwMDAwMDAwMDAwMS8xLjAwL1RYVC9Db250cmlidXRvIFJlZ2lvbmFsZSIsImRhdGlTcGVjaWZpY2lSaXNjb3NzaW9uZSI6IjkvQ09OVFJJQlVUTyIsImRhdGlNYXJjYUJvbGxvRGlnaXRhbGUiOm51bGx9LHsiaW1wb3J0b1NpbmdvbG9WZXJzYW1lbnRvIjoiMS4wMCIsImNvbW1pc3Npb25lQ2FyaWNvUEEiOm51bGwsImliYW5BY2NyZWRpdG8iOiJJVDAyTDEyMzQ1MDAwMDA5OTk5OTAwMDAwMDEiLCJiaWNBY2NyZWRpdG8iOm51bGwsImliYW5BcHBvZ2dpbyI6bnVsbCwiYmljQXBwb2dnaW8iOm51bGwsImNyZWRlbnppYWxpUGFnYXRvcmUiOm51bGwsImNhdXNhbGVWZXJzYW1lbnRvIjoiL1JGUy9SRjc0MDAwMDAwMDAwMDAwMDAwMDAwMDAxLzEuMDAvVFhUL1Nhbnppb25lIHBlciBkaXZpZXRvIGRpIHNvc3RhIiwiZGF0aVNwZWNpZmljaVJpc2Nvc3Npb25lIjoiOS9TQU5aSU9ORSIsImRhdGlNYXJjYUJvbGxvRGlnaXRhbGUiOm51bGx9XX19LCJydCI6bnVsbCwicmlzY29zc2lvbmkiOm51bGx9","method":"POST"},"parametriRisposta":{"dataOraRisposta":"2021-08-25T10:28:00.237+0000","status":0,"headers":[]}}

mentre per la richiesta di "elenco FR a Pago PA" vedo questo:
![image](https://user-images.githubusercontent.com/89087711/130776494-6a9c79ce-d65e-47c5-a3de-a208698fd987.png)

con questo dettaglio:
{"id":2175,"componente":"API_PAGOPA","categoriaEvento":"INTERFACCIA","ruolo":"CLIENT","tipoEvento":"nodoChiediElencoFlussiRendicontazione","esito":"FAIL","dataEvento":"2021-08-25T12:26:26.864","durataEvento":286,"sottotipoEsito":"500","dettaglioEsito":"Ricevuto messaggio di errore: HTTP 500 [SOAPFaultCode: soapenv:Server - SOAPFaultString: 300 - Errore nel processamento del messaggio di cooperazione]","datiPagoPA":{"idIntermediario":"80211730587","idStazione":"80211730587_01"},"parametriRichiesta":{"dataOraRichiesta":"2021-08-25T10:26:26.864+0000","url":"https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60","headers":[{"nome":"SOAPAction","valore":"\"nodoChiediElencoFlussiRendicontazione\""},{"nome":"RequestPath","valore":"https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60"}],"payload":"PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iPjxzb2FwOkJvZHk+PG5zNDpub2RvQ2hpZWRpRWxlbmNvRmx1c3NpUmVuZGljb250YXppb25lIHhtbG5zOm5zMj0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iIHhtbG5zOm5zMz0iaHR0cDovL3dzLnBhZ2FtZW50aS50ZWxlbWF0aWNpLmdvdi9wcHRoZWFkIiB4bWxuczpuczQ9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvIj48aWRlbnRpZmljYXRpdm9JbnRlcm1lZGlhcmlvUEE+ODAyMTE3MzA1ODc8L2lkZW50aWZpY2F0aXZvSW50ZXJtZWRpYXJpb1BBPjxpZGVudGlmaWNhdGl2b1N0YXppb25lSW50ZXJtZWRpYXJpb1BBPjgwMjExNzMwNTg3XzAxPC9pZGVudGlmaWNhdGl2b1N0YXppb25lSW50ZXJtZWRpYXJpb1BBPjxwYXNzd29yZD5JU1NhbjAxVGVzdDwvcGFzc3dvcmQ+PC9uczQ6bm9kb0NoaWVkaUVsZW5jb0ZsdXNzaVJlbmRpY29udGF6aW9uZT48L3NvYXA6Qm9keT48L3NvYXA6RW52ZWxvcGU+","method":"POST"},"parametriRisposta":{"dataOraRisposta":"2021-08-25T10:26:27.150+0000","status":500,"headers":[{"nome":"Transfer-Encoding","valore":"chunked"},{"nome":"Server","valore":"Apache"},{"nome":"X-OpenSPCoop2-Pdd","valore":"PdDOpenSPCoopEnterprise/2.3.0"},{"nome":"Connection","valore":"close"},{"nome":"Status-line","valore":"HTTP/1.1 500 Internal Server Error"},{"nome":"Set-Cookie","valore":"AA=ede0dbb0.5ca5fad8aaa62; path=/"},{"nome":"X-OpenSPCoop2-PddDetails","valore":"Porta di Dominio OpenSPCoop Enterprise 2.3.0"},{"nome":"Date","valore":"Wed, 25 Aug 2021 10:26:05 GMT"},{"nome":"Content-Type","valore":"text/xml"}],"payload":"PHNvYXBlbnY6RW52ZWxvcGUgeG1sbnM6c29hcGVudj0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iPjxzb2FwZW52OkJvZHk+PHNvYXBlbnY6RmF1bHQ+PGZhdWx0Y29kZT5zb2FwZW52OlNlcnZlcjwvZmF1bHRjb2RlPjxmYXVsdHN0cmluZz4zMDAgLSBFcnJvcmUgbmVsIHByb2Nlc3NhbWVudG8gZGVsIG1lc3NhZ2dpbyBkaSBjb29wZXJhemlvbmU8L2ZhdWx0c3RyaW5nPjxkZXRhaWw+PGRldHRhZ2xpby1lY2NlemlvbmUgeG1sbnM9Imh0dHA6Ly93d3cub3BlbnNwY29vcDIub3JnL2NvcmUvZWNjZXppb25lL2RldGFpbHMiPgo8ZG9taW5pbyBmdW56aW9uZT0iUG9ydGFBcHBsaWNhdGl2YSIgbW9kdWxvPSJSaWNlemlvbmVCdXN0ZVNPQVAiPgo8aWRlbnRpZmljYXRpdm8tcG9ydGE+Tm9kb0RlaVBhZ2FtZW50aURlbGxhUEFUZXN0UGREPC9pZGVudGlmaWNhdGl2by1wb3J0YT4KPHNvZ2dldHRvIHRpcG89IlBST1hZIj5Ob2RvRGVpUGFnYW1lbnRpRGVsbGFUZXN0UEE8L3NvZ2dldHRvPgo8L2RvbWluaW8+CjxvcmEtcmVnaXN0cmF6aW9uZT4yMDIxLTA4LTI1VDEwOjI2OjI3LjE0Mlo8L29yYS1yZWdpc3RyYXppb25lPgo8ZWNjZXppb25pPgo8ZWNjZXppb25lIGNvZGljZT0iT1BFTlNQQ09PUDJfT1JHXzUwMCIgZGVzY3JpemlvbmU9IlNpc3RlbWEgbm9uIGRpc3BvbmliaWxlIiB0aXBvPSJFY2NlemlvbmVJbnRlZ3JhemlvbmUiLz4KPC9lY2Nlemlvbmk+CjwvZGV0dGFnbGlvLWVjY2V6aW9uZT48L2RldGFpbD48L3NvYXBlbnY6RmF1bHQ+PC9zb2FwZW52OkJvZHk+PC9zb2FwZW52OkVudmVsb3BlPg=="}}

Ti ringrazio per ogni eventuale suggerimento

Grazie

**Comment by nardil** [comment]
Il primo errore è di handshake verso il servizio di integrazione dell'applicativo `TEST_PAGOPA_API`. Devi aggiungere al trustore il certificato di `ecommerce.iss.it` per poter comunicare con il servizio.

Il secondo errore è un `Internal Server Error` di pagoPA. Devi aprire una segnalazione al loro help desk per avere supporto.

**Comment by mallomix** [comment]
ottimo grazie, procedo!

**Comment by nardil** [comment]
@mallomix , ho notato che la richiesta a pagoPA non ha un body. Hai registrato almeno un Ente Creditore?

**Comment by nardil** [comment]
Pardon, come non detto: ho letto male i log. La richiesta e' corretta. Da chiarire con pagoPA il motivo dell'errore.
