### ISSUE TITLE
Installazione versione 3.4.0 , partendo da un'installazione 3.3.3

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#385]
Buongiorno,

attualmente sto utilizzando la versione 3.3.3 di GOVPAY.
Per installare la versione 3.4.0 quale è il suggerimento migliore per farlo in modo indolore?
1) Reinstallare tutto daccapo? (sono previste modifiche al modello dati?)
2) Sostituzione dei soli EAR?
3) Altro?
attualmente ho scaricato l'installer, eseguendolo mi sovrascrive eventualmente la base dati presente? devo prima cancellare il DB attuale creato con la versione 3.3.3? 

Ringrazio come sempre del supporto e della pazienza

Saluti

**Comment by nardil** [comment]
Puoi seguire le indicazioni aggiunte nel manuale alla pagina di [aggiornamento](https://govpay.readthedocs.io/it/master/installazione/aggiornamento/index.html)

**Comment by mallomix** [comment]
quindi nel mio caso devo fare un aggiornamento MINOR da 3.3.3 a 3.4.0.
Se non erro devo predisporre:
1) esecuzione dello script \govpay-installer-3.4.0\installer\sql\postgresql\patch\**3.4,sql**
2) compilazione e deploy del codice.

per il secondo punto posso usare l'installer oppure va fatto manualmente? leggendo la documentazione, dopo l'installazione, dovrei poi eseguire il solo step6 del dispiegamento: "Copiare le applicazioni presenti nella directory archivi nella directory <JBOSS_HOME>/standalone/deployments dell’application server." e riavviare il server.
Tutto il resto, tranne lo script al punto1, lo ignorerei poichè già funzionante.

Corretto?  grazie

**Comment by mallomix** [comment]
E' corretto l'approccio che ho indicato per sostituire 3.3.3 con 3.4.2? Sulla documentazione suggerita non è ben approfondita la procedura di aggiornamento

**Comment by nardil** [comment]
Si, e' corretto
