### ISSUE TITLE
Errore nella stampa dell'Avviso multilingua rateizzato

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#386]
**Descrizione del Bug**

La stampa di un avviso bilingue con il pagamento rateale (rata unica + 3 rate) presenta i seguenti difetti:

- [x] Codice fiscale non entra nello spazio previsto
- [x] Vengono proposte due rate uniche e due rate invece di una rata unica e tre rate

**Come riprodurlo:**
Di seguito un CSV che realizza la stampa in questione: 
[TEST.csv](https://github.com/link-it/govpay/files/7038058/TEST.csv)

**Screenshots:**
![Schermata da 2021-08-24 11-12-27](https://user-images.githubusercontent.com/12340738/130591245-b9cd3a68-4203-4c83-a067-b63b350b3bd2.png)

**Comment by pintorig** [comment]
@simo-git in allegato l'input che genera il codice fiscale che occupa molto spazio

[input1.txt](https://github.com/link-it/govpay/files/7040643/input1.txt)

**Comment by pintorig** [comment]
@simo-git  ci sono da fare altre due rifiniture nell'avviso:

- [ ]  Quando viene passata la causale in lingua secondaria nell'input, attualmente l'intestazione della pagina con due rate viene generata cosi:

![Schermata da 2021-08-24 17-36-48](https://user-images.githubusercontent.com/12812160/131803243-68524c28-74a3-493e-af89-ac48f237ea48.png)

Dovrebbe essere invece:
[Rata X e Y - Causale] in italiano * [Rata X e Y - Causale] nella lingua secondaria

- [ ] Nel bollettino postale in alto a destra viene generata la seguente struttura:

![Screenshot from 2021-08-25 09-59-33](https://user-images.githubusercontent.com/12812160/131805263-637e8270-65a3-4afa-80e7-977d98aba67b.png)

invece che quella prevista dalla specifica:
![Screenshot from 2021-09-02 09-57-48](https://user-images.githubusercontent.com/12812160/131805418-6f1e7f98-784b-4d12-a97a-a7186027d90e.png)
![Screenshot from 2021-09-02 09-57-23](https://user-images.githubusercontent.com/12812160/131805420-31e974c7-88f1-4e26-b9f6-76252f1e7bd6.png)

per questa seconda modifica, valutare se servono nuove label in aggiunta a quelle presenti.

**Comment by nardil** [comment]
> Dovrebbe essere invece:
> [Rata X e Y - Causale] in italiano * [Rata X e Y - Causale] nella lingua secondaria

Preciso che va gestito sia il caso di causale tradotta che non:

- **Rata 1 e 2** · Instalment 1 and 2 **- Causale del pagamento**
- **Rata 1 e 2 - Causale del pagamento**  · Instalment 1 and 2 - Payment's reason

**Comment by nardil** [comment]
- [ ] aggiungere numero di rata anche nel template a pagina singola quando si tratta appunto di una rata, come nel caso del template per due rate.
