### ISSUE TITLE
Proprietà it.govpay.check.urlVerificaPDD in govpay.properties

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#388]
Buongiorno,
cosa indica parametro di seguito, contenuto nel file govpay.properties ?

```
# URL della PdD da usare nel servizio di verifica
it.govpay.check.urlVerificaPDD=
```

Govpay non gestisce già tutti i servizi di verifica, attiva ?

Grazie

**Comment by nardil** [comment]
Ciao @giuseppelab ,

e' un refuso di una precedente versione di GovPay.

@pintorig puoi confermare che non sia utilizzato e rimuoverlo dalle properties di configurazione?

**Comment by pintorig** [comment]
@giuseppelab, @nardil confermo che si tratta di un refuso, provvedo alla rimozione dalle properties.

**Comment by giuseppelab** [comment]
Perfetto, grazie mille.
