### ISSUE TITLE
Ultimo idPendenza inserito

### ISSUE THREAD

**Issue by ilsanto17** [link-it/govpay#389]
Ciao a tutti, come recupero l'ultimo id pendenza inserito? grazie

**Comment by nardil** [comment]
La risorsa `/pendenze` mostra i dati delle pendenze ordinate per data di creazione decrescente quindi il primo mostrato e' l'ultimo creato, ovviamente tra quelli che l'utenza che esegue la richiesta e' autorizzata a visualizzare.

**Comment by ilsanto17** [comment]
ok grazie
