### ISSUE TITLE
Documentazione swagger e generale - piccole correzioni da fare -

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#390]
Sullo swagger dei servizi NOTIFICA e VERIFICA https://raw.githubusercontent.com/link-it/govpay/master/jars/client-api-ente/src/main/resources/govpay-api-ec-v1.yaml ho evidenziato i seguenti issues:

->Campi obblicatori api di verifica non rispettano i requisiti delle API stesse
--->Esempio di response GET /pendenze/{idA2A}/{idPendenza} da un messaggio di "campo troppo lungo max 1024 len"
->Non sono documentati i parametri in query che si usano per trasmettere info al destinatario. Vedi POST /pagamenti/{idDominio}/{iuv}  dove oltre al body govpay aggiunge altre informazioni in query string (come l'esito per esempio e l'id del carrello ecc)
->URL endpoint PAGOPA servizi GAD non è "https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60" bensì "**https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T**" (come comunicato da PAGOPA nel portale del supporto a fronte dell'errore 300 che prendevo quando provavo a pagare una pendenza). 

Mi scuso in anticipo se le mie segnalazioni dipendono da una mia negligenza nel leggere correttamente la documentazione, in tal caso chiedo in risposta come agire per essere certo di sviluppare in modo corretto i flussi GOVPAY.

Grazie

**Comment by mallomix** [comment]
> @mallomix non mi risulta che le URL del GAD siano indeicate nella documentazione di GovPay. Puoi darmi il riferimento puntuale di dove l'hai reperita?
no l'ho reperita tra le varie richieste di supporto qui sul git.  Sembrava fosse un URL ben definito e uguale per tutti. Forse sono stato forviato da questo.

**Comment by mallomix** [comment]
Chiedo scusa. HO fatto io casino. La richiesta di supporto era questa: PUT /pendenze - 403 Error #325 . Però li venivano indicati quelli corretti, sono io che ho erroneamente usato quello di PROD sostituendo test nell'url (gad.test ecc ecc).

QUINDI COME NON DETTO SU QUESTO PUNTO

**Comment by nardil** [comment]
Aggiunte le indicazioni sulla sintassi dei queryParam e pathParam delle API di notifica e Verifica.

Per quanto riguarda le informazioni sui queryParam aggiunti alle notifiche risultavano gia' presenti:

https://github.com/link-it/govpay/blob/022ecf7588586aa98263011d0f1c1edc397dfb63/jars/client-api-ente/src/main/resources/govpay-api-ec-v1.yaml#L167-L187
