### ISSUE TITLE
Pagamenti eseguiti ma con stato "NON VERIFICATO"

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#399]
Ciao,

govpay version 3.3.3

pago regolarmente le mie pendenze, ricevo la ricevuta ma lo stato dei pagamenti rimane sempre in "NON VERIFICATO".
Di seguito lo screen shot:
![image](https://user-images.githubusercontent.com/89087711/133624375-f573a290-15e5-44b4-b245-9c1995067fd5.png)

quindi la pendenza è in "PAGAMENTO ESEGUITO" lo stato in "NON VERIFICATO". Quale passaggio mi manca? Quale è la differenza tra un pagamento "verificato" rispetto a uno "non verificato" a livello contabile o formale?

Grazie del supporto

**Comment by nardil** [comment]
Lo stato di verifica indica quali pagamenti falliti sono stati verificati dall'operatore, in modo che non vengano più conteggiati nel badge del cruscotto. 

Questo attributo non ha alcuna valenza contabile.

**Comment by mallomix** [comment]
Grazie Nardil, tutto cristallino.

Un saluto
