### ISSUE TITLE
Generazione Codice A Barre

### ISSUE THREAD

**Issue by ivan86to** [link-it/GovPay#40]
Ciao, nella documentazione di PagoPA 
(http://www.agid.gov.it/sites/default/files/regole_tecniche/condivisioneiuv-monografia-v_1_1.pdf) per gli enti pluri-intermediati con punti di generazione IUV > 1 (vedi tab. 2 pag. 9) il numero di avviso viene generato secondo il seguente schema: 
aux-digit = Fisso 3
application code = Non presente
IUV.. [.. ]
Nel servizio "caricaVersamento" il numero di avviso viene generato correttamente, mentre invece il codice a barre mantiene lo standard aux-digit fisso a 0 e application code ( nel mio caso valorizzato a 01). 
Mi sono perso qualcosa sulla documentazione di Agid oppure il numero avviso e il bar code sono disallineati? 

Ciao!

**Comment by nardil** [comment]
Si, confermo. Lo stesso errore e' presente anche nel QRCode. 

Procediamo alla risoluzione. Grazie per la segnalazione.

**Comment by nardil** [comment]
@ivan86to puoi confermarmi che il branch ac237e99b9f0426c738c9ead47bb64311ef399dd corregge il problema?

**Comment by nardil** [comment]
Pardon... ancora un fix. Il branch da verificare e' il 1c18ba0e0ccac13fecb9809a8f0a755442dcbb8d

**Comment by ivan86to** [comment]
Ti confermo che l'[https://github.com/link-it/GovPay/tree/issue40](url) corregge l'errore sul QR-CODE. Ma non sul bar-code dove mi pare che la logica sia la stessa.

**Comment by nardil** [comment]
Ho fatto un test di verifica e mi risulta corretto:

Numero avviso: **3090112304560142109**
QRCode: PAGOPA|002|**3090112304560142109**|12345678903|1234560
BarCode: 41500112233445568020**3090112304560142109**39021234560

Puoi verificare nuovamente? Grazie.

**Comment by ivan86to** [comment]
Si ti confermo che ora è tutto ok per quanto riguarda l'Aux-Digit 3, per gli altri casi invece ti allego la tabella dal documento Agid Allegato sopra. 

![immagine](https://user-images.githubusercontent.com/8206081/29022959-c0605974-7b6b-11e7-8221-d3cb42c7609c.png)

**Comment by nardil** [comment]
Non ho capito... ci sono configurazioni di govpay per cui il risultano errori di generazione di iuv/barcode/qrcode? 

Se si, puoi darmi dettagli per riprodurle?

**Comment by ivan86to** [comment]
Scusami non riesco a trovare il punto in cui valorizza il campo della tabella domini "aux_digit", in quale classe sta la logica di calcolo di quel campo?

**Comment by nardil** [comment]
Si configura tramite console come dettaglio del Dominio.

Immagino quindi che il problema individuato per gli IUV pluri-intemediati (aux = 3) sia risolto e che non ci siano regressioni per gli iuv mono-intermediati (aux = 0).

Chiudo la issue.
