### ISSUE TITLE
Pagamento avviso tramite app IO

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#402]
Buongiorno,
ho caricato una pendenza ed ottenuto il relativo avviso di pagamento.
Provando a pagare con App IO, mi restituisce il messaggio:

Il pagamento per questo avviso non è disponibile in questo momento, riprova più tardi.

Dal log applicativo GovPay non ricevo richieste in ingresso per verifica avviso.
C'è qualcosa da completare nel processo ?

Grazie,

**Comment by nardil** [comment]
Ciao,

partiamo dal presupposto che piattaforma sia correttamente connessa a pagoPA ed abilitata al Modello 3. 

Puoi verificare che:

- L'AppIO stia operando sull'ambiente pagoPA a cui è agganciato il GovPay in esame (Test esterno o Esercizio)
- Il numero avviso sia conforme alla configurazione pagoPA, ovvero che auxDigit (prima cifra) e codice di segregazione (seconda e terza cifra) siano allineati a quanto indicato nel dettaglio della stazione sul Portale delle Adesioni.

**Comment by giuseppelab** [comment]
Ciao, 
scusami, per piattaforma abilitata al Modello 3 intendi qualche configurazione di GovPay che potrei aver saltato ?
Per il resto, il modello 1 con pagamento on line ha funzionato in tutte le fasi.

Grazie.

**Comment by nardil** [comment]
Intendo abilitata da pagoPA, ovvero che nella configurazione della Connessione Fisica sia stato abilitato "Utilizzo 3° modello"

**Comment by giuseppelab** [comment]
Esatto !!!
Risolto correggendo, lato nodo, l'associazione.

Grazie mille.
