### ISSUE TITLE
Pagamenti eseguiti ma in stato "ANOMALA"

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#403]
Stiamo usando govpay 3.2.2 e abbiamo identificato una pendenza in stato "ANOMALA". Siccome andiamo a verificare lo stato della pendenza per richiedere il pagamento oppure no, come possiamo risolvere? Il pagamento risulta eseguito ma la pendenza non è aggiornata

invochiamo questa richiesta GET:
govpay/frontend/api/pagamento/rs/basic/v2/pendenze/[idapp]/[idpendenza]

Mauro

**Comment by nardil** [comment]
Dovresti verificare nella descrizione il motivo dell'anomalia. Potrebbe esser stato pagato piu' di una volta o con un importo diverso dal dovuto.

**Comment by temptationisla** [comment]
Ciao Lorenzo, dalla descrizione è stato pagato più del dovuto, ma è corretto perchè c'è stata una mmaggiorazione dopo la scadenza per spese di segreteria. Come faccio a ripristinare lo stato "ESEGUITA"?
Grazie

**Comment by nardil** [comment]
In pagoPA non dovrebbe essere possibile pagare un importo diverso da quanto comunicato dall'Ente. La maggiorazione di importo dovrebbe essere stata comunicata comunque a GovPay per produrre una corretta RPT con l'importo maggiorato.

Potresti ricostruire la sequenza di eventi che hanno portato al pagamento di un importo diverso da quello noto a GovPay?

P.S. Se hai necessita' di forzare lo stato ad ESEGUITA, non e' disponibile una API che lo consenta, dovresti agire sul DB (tabella versamenti, colonna stato_versamento)

**Comment by temptationisla** [comment]
Il pagamento anomalo coincide con il giorno dell'aumento, ma prima di procedere veniva aggiornata la pendenza. E' capitato solo una volta e lo stato era in "ESEGUITO" ma la colonna "anomalo" era settata a 1, settandola a zero dopo aver verificato che il pagamento sia effettivamente avvenuto correttamente, ha risolto l'anomalia e ora la chiamata alla pendenza restituisce stato ESEGUITA
Grazie mille per l'assistenza
