### ISSUE TITLE
Installazione GOVPAY 3.4.2 - script DB -

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#404]
Buongiorno,

seguendo la procedura di installazione, viene chiaramente descritto di lanciare il solo script "gov_pay.sql".

Nella directory "patch" ci sono però una serie di script sql:  3.1.1.sql, 3.2.1.sql, 3.1.rc1.sql, ecc ecc fino a 3.4.sql.

Vanno eseguiti anche quelli per avere un DB allineato alla versione applicativa 3.4.2? e se si, con quale sequenza?

Grazie del supporto

Un saluto

**Comment by nardil** [comment]
lo script `gov_pay.sql` crea il database adeguato alla versione prodotta dall'installer a partire da uno schema vuoto.

Nel caso in cui si stia aggiornando e si desideri mantenere i dati preesistenti, si utilizzano gli script di patch come suggerito nel manuale: https://govpay.readthedocs.io/it/latest/installazione/aggiornamento/index.html

**Comment by mallomix** [comment]
Ok allora basta lo script gov_pay.sql se parto da scratch.

Grazie
