### ISSUE TITLE
401 nella chiamata ai wsdl RT di govpay

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#405]
Salve,

in riferimento a questo topic chiuso https://github.com/link-it/govpay/issues/333

ho bisogno di supporto poichè anche PagoPa non riesce a raggiungere le API di govpay con errore 401.
Su wildfly ho inserito il certiticato nel keystore e trustore e correttamente referenziato. 

Le chiamata da GOVPAY a PAGOPA vanno a buon fine, il contrario no.

Ringrazio per il supporto

**Comment by nardil** [comment]
Ciao @mallomix ,

dovresti verificarae se in `govpay_root.log` vedi la chiamata in arrivo ed informazioni utili a risolvere il problema di autenticazione.

Se non vedi niente, verifica sugli apparati di frontiera (api gateway, reverse proxy, ...) che la chiamata sia correttamente inoltrata a GovPay.

**Comment by mallomix** [comment]
Ciao @nardil ,

vedo chiamate con SSLHandshakeException e credo siano quelle da PAGOPA verso di GOVPAY. 
Non capisco però cosa ho sbagliato. 
Allego tutti i log di GOVPAY dove in data 24 Settembre evidenzia appunto queste problematiche.
Mi puoi dare qualche indicazione su dove concentrarmi?

**su govpay_diagnostic vedo questo:**
<1fbab818-aa1f-4b96-92ba-71faa8d73798> 001003 ws <2021-08-24_11:16:24.966> (ERROR) {correlation-req:1fbab818aa1f4b9692ba71faa8d73798} Client-Principal:govpaytest.iss.it To:GovPay S:Pagamenti O:addPagamento
Ritornato errore al client con codice operazione NDP_000: Servizi pagoPA non disponibili.
 
 
<07d7a1a0-66b5-46fc-8187-26dced8200c6> 010001 ndp_client <2021-08-24_11:59:59.894> (INFO) S:Task O:AcquisizioneRendicontazioni
Spedizione della richiesta in corso verso la location https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60 ...
 
 
<af6d3f4f-16f2-49c1-811c-63c2f463feb4> 010001 ndp_client <2021-08-24_12:00:00.025> (INFO) S:Task O:RecuperoRptPendenti
Spedizione della richiesta in corso verso la location https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60 ...
 
 
<af6d3f4f-16f2-49c1-811c-63c2f463feb4> 018054 pendenti <2021-08-24_12:00:00.141> (ERROR) S:Task O:RecuperoRptPendenti
Richiesta al Nodo dei Pagamenti dei pagamenti pendenti per la stazione 80211730587_01 fallita: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 
 
<bc2c8d82-d3c4-4e9e-9cc1-8d4c097af97e> 010001 ndp_client <2021-08-24_13:00:00.014> (INFO) S:Task O:RecuperoRptPendenti
Spedizione della richiesta in corso verso la location https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT60 ...
 
 
<bc2c8d82-d3c4-4e9e-9cc1-8d4c097af97e> 018054 pendenti <2021-08-24_13:00:00.146> (ERROR) S:Task O:RecuperoRptPendenti
Richiesta al Nodo dei Pagamenti dei pagamenti pendenti per la stazione 80211730587_01 fallita: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**su govpay_diagnostic_notifiche vedo questo:**
<1fbab818-aa1f-4b96-92ba-71faa8d73798> 014109 notifica <2021-08-24_11:16:25.098> (ERROR) {correlation-req:1fbab818aa1f4b9692ba71faa8d73798} Client-Principal:govpaytest.iss.it To:GovPay S:Pagamenti O:addPagamento
Notifica di avvio della transazione di pagamento [Dominio:80211730587 Iuv:RF74000000000000000000001 Ccp:n/a] fallito: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
Transazione afferente al carrello di pagamenti [Carrello:1fbab818aa1f4b9692ba71faa8d73798].

io ho referenziato su JAVA OPT in standalone.conf.bat  il trustore e keystore.
Nel keystore ho inserito il certificato govpaytest.iss.it con chiave privata
Nel trustore ho inserito sia il certificato govpaytest.iss.it che quellao di gad.test.pagopa.gov.it  

E' corretto?

Grazie

**Comment by nardil** [comment]
> Le chiamata da GOVPAY a PAGOPA vanno a buon fine, il contrario no.

Dai log che hai inviato, le chiamate da GovPay a pagoPA non stanno funzionando per un problema di handshake. Verifica di aver incluso nel trustore tutta la catena di trust del certificato pagoPA.

Non sono presenti log delle chiamate da pagoPA a GovPay.

**Comment by mallomix** [comment]
Mi scuso Nardil, ho sbagliato io. Ho inserito i log di AGOSTO dove effettivamente non avevo ancora configurato correttamente la parte dei certificati SSL.

Infatti oggi verso PAGOPA non ho problemi. ti allego una richiesta di elenco pagamenti sospesi a pagoPA correttamente effettuata:
{"id":14679,"componente":"API_PAGOPA","categoriaEvento":"INTERFACCIA","ruolo":"CLIENT","tipoEvento":"nodoChiediListaPendentiRPT","esito":"OK","dataEvento":"2021-09-26T15:00:00.009","durataEvento":332,"sottotipoEsito":"200","parametriRichiesta":{"dataOraRichiesta":"2021-09-26T13:00:00.009+0000","url":"https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T","headers":[{"nome":"SOAPAction","valore":"\"nodoChiediListaPendentiRPT\""},{"nome":"RequestPath","valore":"https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T"}],"payload":"PHNvYXA6RW52ZWxvcGUgeG1sbnM6c29hcD0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iPjxzb2FwOkJvZHk+PG5zNDpub2RvQ2hpZWRpTGlzdGFQZW5kZW50aVJQVCB4bWxuczpuczI9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIiB4bWxuczpuczM9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvcHB0aGVhZCIgeG1sbnM6bnM0PSJodHRwOi8vd3MucGFnYW1lbnRpLnRlbGVtYXRpY2kuZ292LyI+PGlkZW50aWZpY2F0aXZvSW50ZXJtZWRpYXJpb1BBPjgwMjExNzMwNTg3PC9pZGVudGlmaWNhdGl2b0ludGVybWVkaWFyaW9QQT48aWRlbnRpZmljYXRpdm9TdGF6aW9uZUludGVybWVkaWFyaW9QQT44MDIxMTczMDU4N18wMTwvaWRlbnRpZmljYXRpdm9TdGF6aW9uZUludGVybWVkaWFyaW9QQT48cGFzc3dvcmQ+SVNTYW4wMVRlc3Q8L3Bhc3N3b3JkPjxyYW5nZURhPjIwMjEtMDctMjhUMTU6MDA6MDA8L3JhbmdlRGE+PHJhbmdlQT4yMDIxLTA5LTI2VDE1OjAwOjAwPC9yYW5nZUE+PGRpbWVuc2lvbmVMaXN0YT41MDA8L2RpbWVuc2lvbmVMaXN0YT48L25zNDpub2RvQ2hpZWRpTGlzdGFQZW5kZW50aVJQVD48L3NvYXA6Qm9keT48L3NvYXA6RW52ZWxvcGU+","method":"POST"},"parametriRisposta":{"dataOraRisposta":"2021-09-26T13:00:00.341+0000","status":200,"headers":[{"nome":"Transfer-Encoding","valore":"chunked"},{"nome":"Keep-Alive","valore":"timeout=7, max=100"},{"nome":"Server","valore":"Apache"},{"nome":"X-OpenSPCoop2-Mittente","valore":"ISStest"},{"nome":"Connection","valore":"Keep-Alive"},{"nome":"Status-line","valore":"HTTP/1.1 200 OK"},{"nome":"X-OpenSPCoop2-Azione","valore":"nodoChiediListaPendentiRPT"},{"nome":"X-OpenSPCoop2-IdMessaggio","valore":"4a2ad792-1f83-4ee9-a5d9-8dcaf3fd02ce"},{"nome":"Date","valore":"Sun, 26 Sep 2021 12:58:48 GMT"},{"nome":"X-OpenSPCoop2-Servizio","valore":"PagamentiTelematiciRPT6T"},{"nome":"X-OpenSPCoop2-TipoServizio","valore":"PROXY"},{"nome":"X-OpenSPCoop2-IdTransazione","valore":"47498a25-8726-46cb-b560-9577c9dd1954"},{"nome":"X-OpenSPCoop2-TipoDestinatario","valore":"PROXY"},{"nome":"X-OpenSPCoop2-Pdd","valore":"PdDOpenSPCoopEnterprise/2.3.0"},{"nome":"Set-Cookie","valore":"AA=374f5715.5cce58a97d3fd; path=/"},{"nome":"X-OpenSPCoop2-TipoMittente","valore":"PROXY"},{"nome":"X-OpenSPCoop2-PddDetails","valore":"Porta di Dominio OpenSPCoop Enterprise 2.3.0"},{"nome":"Content-Type","valore":"text/xml;charset=UTF-8"},{"nome":"X-OpenSPCoop2-Destinatario","valore":"NodoDeiPagamentiDellaPATest"}],"payload":"PHNvYXBlbnY6RW52ZWxvcGUgeG1sbnM6c29hcGVudj0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvc29hcC9lbnZlbG9wZS8iIHhtbG5zOnBwdD0iaHR0cDovL3dzLnBhZ2FtZW50aS50ZWxlbWF0aWNpLmdvdi8iIHhtbG5zOnRucz0iaHR0cDovL05vZG9QYWdhbWVudGlTUEMuc3Bjb29wLmdvdi5pdC9zZXJ2aXppL1BhZ2FtZW50aVRlbGVtYXRpY2lSUFQiIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOnBwdGhlYWQ9Imh0dHA6Ly93cy5wYWdhbWVudGkudGVsZW1hdGljaS5nb3YvcHB0aGVhZCI+PHNvYXBlbnY6Qm9keT48cHB0Om5vZG9DaGllZGlMaXN0YVBlbmRlbnRpUlBUUmlzcG9zdGE+PGxpc3RhUlBUUGVuZGVudGk+PHRvdFJlc3RpdHVpdGk+MDwvdG90UmVzdGl0dWl0aT48L2xpc3RhUlBUUGVuZGVudGk+PC9wcHQ6bm9kb0NoaWVkaUxpc3RhUGVuZGVudGlSUFRSaXNwb3N0YT48L3NvYXBlbnY6Qm9keT48L3NvYXBlbnY6RW52ZWxvcGU+"}}

Quello che non va è l'opposto e cioè da PAGO PA a govpay. In particolare i servizi https://govpaytest.iss.it/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl
non si accedono (401). Provo a inserire nel truststore anche i root.

**Comment by nardil** [comment]
> Quello che non va è l'opposto e cioè da PAGO PA a govpay

Ok, dovresti recuperare il log di GovPay (`govpay.log` e `govpay_root.log`) relativo ad una chiamata da pagoPA che fallisce per avere maggiori indicazioni sul motivo del rifiuto.

**Comment by mallomix** [comment]
Nulla.. anche con il root certificate! 
Sto cercando di capire se arriva a GOVPAY.. anche se quell'errore 401 non lo restituisce GOVPAY?

**Comment by mallomix** [comment]
>>
> 
> Ok, dovresti recuperare il log di GovPay (`govpay.log` e `govpay_root.log`) relativo ad una chiamata da pagoPA che fallisce per avere maggiori indicazioni sul motivo del rifiuto.

Si vero Nardil però visto che anche io con SOAPUI / POSTMAN / BROWSER becco il 401.. magari riesco a fare un pò di indagini in modo autonomo. Il tentativo per esempio di scaricare il WSDL fallisce per 401 quindi non riesco neanche ad effettuare una richiesta corretta

**Comment by nardil** [comment]
> anche io con SOAPUI / POSTMAN / BROWSER becco il 401

La configurazione di default di GovPay prevede la client autentication ssl, quindi e' normale che tu non sia in grado di invocare il servizio: solo presentando un certificato trustato e che riporta il subject indicato nel principal del connettore pagoPA e' possibile invocare il servizio.

**Comment by mallomix** [comment]
Ciao Nardil, si scusami ma allora perchè riesco ad accedere correttamente a https://govpay.mitservizi.com/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl
che è un altro utente di govpay?

**Comment by mallomix** [comment]
> e che riporta il subject indicato nel principal del connettore pagoPA e' possibile invocare il servizio.

Scusami allora mi sfugge ancora una cosa, pedonali. Che intendi per principal del connettore pagoPA? quello descritto nella sezione di govpay Intermediari/principal? Li io ci ho inserito il subject del certificato gad.test.pagopa.gov.it! 

Scusami mi sto veramente incasinando

**Comment by nardil** [comment]
> Li io ci ho inserito il subject del certificato gad.test.pagopa.gov.it!

Si, corretto. 

Le API di pagoPA, quindi i servizi `PagamentiTelematiciRT` e `PagamentiTelematiciCCP`, esposte da GovPay saranno invocabili solo a chi presenta quel certificato ovvero a pagoPA. 

Devi verificare se le chiamate stanno arrivando a GovPay (ancora non c'e' evidenza che il 401 sia dato da GovPay oppure da qualche altro frontend) ed in tal caso verificare che a GovPay stiano arrivando le informazioni sul certificato del chiamante.

**Comment by mallomix** [comment]
Scusami Nardil ma non riesco a capire!

Devo mettere il subject del certificato CN=gad.test.pagopa.gov.it  OPPURE quello di CN=govpaytest.iss.it   dove vengono esposti i servizi govpay PagamentiTelematiciRT e PagamentiTelematiciCCP ?

Ti ringrazio molto

**Comment by nardil** [comment]
> Devo mettere il subject del certificato CN=gad.test.pagopa.gov.it OPPURE quello di CN=govpaytest.iss.it dove vengono esposti i servizi govpay PagamentiTelematiciRT e PagamentiTelematiciCCP ?

Li va il principal dell'utenza autorizzata ad invocare le api pagoPA di GovPay che, nel caso di autenticazione SSL, corrisponde al subject del certificato. Per l'ambiente di test e' `CN=gad.test.pagopa.gov.it, OU=pagoPA, O=SIA S.p.A, L=Milano, ST=Milano, C=IT`. 

Attenzione che nel caso in cui la terminazione SSL non venga effettuata dall'Application Server, e' necessario che chi esegue la terminazione inoltri l'identità del chiamante ed eventualmente [adeguando la modalita' di autenticazione delle api](https://govpay.readthedocs.io/it/latest/integrazione/api/autenticazione/index.html#integrazione-autenticazione).

**Comment by mallomix** [comment]
Ok grazie @nardil ,

allora rimetto il subject che mi hai dato.

per quanto riguarda la terminazione SSL in effetti non termina sull'application server che espone il servizio di GOVPAY ma dal VIP precedente.  Quindi devo cambiare qualcosa sia a livello VIP che come adeguamento delle API? quale tipologia devo usare?

**Comment by nardil** [comment]
> Quindi devo cambiare qualcosa sia a livello VIP che come adeguamento delle API? quale tipologia devo usare?

Dipende da come viene inoltrata l'identità del chiamante a GovPay:

1. Se tramite SSL o AJP, allora l'autenticazione resta SSL
2. Se include il certificato come header HTTP, allora l'autenticazione e' SSL-HEADER
3. Se esplicita l'identità del chiamante come header HTTP, allora l'autenticazione e' HEADER
4. Se presenta credenziali user/passw, allora l'autenticazione e' HTTP-BASIC

> Ripartendo l'applicazione dovrebbe prendere questo XML invece che quello embedded nel WAR, giusto?

Si, se hai abilitato la configurazione esterna di spring-security come indicato al passo 1 della procedura che hai indicato. L'installer valorizza il placeholder `${spring.sec_config_folder}` nel `web.xml` (che eventualmente puoi modificare manualmente):

https://github.com/link-it/govpay/blob/378f7f4aeddc90fa17bd9c9a3670611f3e3897e8/wars/api-pagopa/src/main/resources/web.xml#L6-L9

**Comment by mallomix** [comment]
Grazie @nardil.

allora adesso ho capito come cambiare la configurazione della sicurezza per le API di PAGOPA.  Considerato però che queste API vengono chiamate da PAGOPA, credo che loro non si aspettano di cambiare la modalità di chiamata e sono attestati per tutti i govpay a usare la mutua autenticazione SSL.

Detto questo ho comunque fatto un passo avanti. Infatti il VIP terminava la connessione SSL e per questo le API PAGOPA non venivano autorizzate. Propagando la connessione ssl sul server di destinazione sono riuscito ad accedere ai WSDL da browser. L'unico modo però per accedere è quello di installare il certificato con chiave privata nel browser. 
La controindicazione applicando questa propagazione è che anche la console di govpay backoffice (la gui insomma) se non ho sul browser il certificato installato non ti fa accedere con un bel ERR_BAD_SSL_CLIENT_AUTH_CERT e non ho capito il perchè.

Ma è possibile disabilitare la SSL sul servizio https://govpaytest.iss.it/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl

grazie come sempre

**Comment by nardil** [comment]
> Considerato però che queste API vengono chiamate da PAGOPA, credo che loro non si aspettano di cambiare la modalità di chiamata e sono attestati per tutti i govpay a usare la mutua autenticazione SSL.

pagoPA certamente esegue l'autenticazione SSL, ma non e' detto che questa arrivi fino a GovPay, per questo sono configurabili altre modalita' di autenticazione.

> Propagando la connessione ssl sul server di destinazione sono riuscito ad accedere ai WSDL da browser. L'unico modo però per accedere è quello di installare il certificato con chiave privata nel browser.

E' corretto, solo pagoPA deve essere autorizzato a chiamare quelle API.

> La controindicazione applicando questa propagazione è che anche la console di govpay backoffice (la gui insomma) se non ho sul browser il certificato installato non ti fa accedere con un bel ERR_BAD_SSL_CLIENT_AUTH_CERT e non ho capito il perchè.

Evidentemente e' stato configurata la mutua autenticazione obbligatoria per tutto il contesto `/govpay` sul frontend. Dovresti perfezionare la configurazione in modo che questo vincolo valga solo per `/govpay/frontend/api/pagopa/`

> Ma è possibile disabilitare la SSL sul servizio https://govpaytest.iss.it/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl

Puoi attivare una delle altre modalita' di identificazione agendo sulla configurazione di Spring Security come individuato nei precedenti messaggi.

**Comment by mallomix** [comment]
direi che a questo punto di chiudere l'issue. Ho tutto abbastanza chiaro per procedere con le investigazioni e fine tuning. Devo contattare PAGOPA perchè ancora mi da errore quando provo a pagare un avviso di pagamento sull'app IO configurata per test.
