### ISSUE TITLE
API Notifica e Verifica v2

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#406]
**Necessità:**
Il servizio di notifica delle API Ente esposte dagli applicativi integrati non trasmettono tutti i dati necessari per le operazioni contabili e devono essere adeguate per gestire le nuove api pagoPA

**Soluzione:**
Implementare una nuova versione delle API che recepisca entrambe le esigenze.

**Comment by nardil** [comment]
Proposta openapi: 

https://generator.swagger.io/?url=https://raw.githubusercontent.com/link-it/govpay/feature/406_api_applicazioni_v2/jars/client-api-ente/src/main/resources/govpay-api-ec-v2.yaml

**Comment by pintorig** [comment]
@nardil 
Nella configurazione di una Applicazione e' possibile selezionare la versione del connettore integrazione tramite il campo 'Versione API':

I valori disponibili vengono letti tramite il servizio:

`/govpay/backend/api/backoffice/rs/form/v1/enumerazioni/versioneConnettore`

che ho gia' provveduto ad aggiornare.

![Screenshot from 2021-11-22 16-27-13](https://user-images.githubusercontent.com/12812160/142888595-0eef07fb-cfba-4472-becb-95c3e03d94b7.png)

Attualmente non ci sono altre differenze con la configurazione della versione V1.
