### ISSUE TITLE
Schedulazione esportazione flussi via mail

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#407]
Ciao,
ho configurato (GOVPAY 3.4.2) su un paio di ENTI il connettore per inviare flussi via mail ma non ricevo nulla.

Non trovo riferimenti nei log e sul DB su qualche evento che mi permetta di capire se ci sono problemi. Avete suggerimenti?

Grazie.

**Comment by nardil** [comment]
Ciao @giuseppeformaro ,

intanto verifica che il batch di creazione tracciati sia abilitato consultando il file `govpay_boot.log`:

```properties
it.govpay.batch.caricamentoTracciatiNotificaPagamenti.enabled=true
```

fatto questo, dovresti individuare nei log (in debug) una entry di questo tipo quando il batch viene eseguito 

```java
log.debug("Elaborazione Tracciato GovPay per il Dominio ["+codDominio+"]...");
```

e dovresti trovare quindi una (o piu') entry nella tabella `trac_notif_pag`:

```sql
select * from trac_notif_pag where tipo='GOVPAY' ;
```

Se queste verifiche vanno a buon fine, passiamo ad analizzare la fase di spedizione.

Ti ricordo che il batch viene eseguito alle 3 di mattina.

**Comment by giuseppeformaro** [comment]
Grazie mille!
Risolto, il problema era nel primo dei punti da te indicato: non avevo esternalizzato la props che di default è a false.

**Comment by giuseppeformaro** [comment]
@nardil una domanda,
è normale che in https://github.com/link-it/govpay/blob/master/src/main/resources/db/sql/postgresql/patch/3.4.sql trovo ADD e DROP dei seguenti oggetti:
```
ALTER TABLE rpt ADD COLUMN id_tracciato_mypivot BIGINT;
ALTER TABLE rpt ADD COLUMN id_tracciato_secim BIGINT;
ALTER TABLE rpt ADD CONSTRAINT fk_rpt_id_tracciato_mypivot FOREIGN KEY (id_tracciato_mypivot) REFERENCES trac_notif_pag(id);
ALTER TABLE rpt ADD CONSTRAINT fk_rpt_id_tracciato_secim FOREIGN KEY (id_tracciato_secim) REFERENCES trac_notif_pag(id);

ALTER TABLE rpt DROP CONSTRAINT fk_rpt_id_tracciato_mypivot ;
ALTER TABLE rpt DROP CONSTRAINT fk_rpt_id_tracciato_secim;
ALTER TABLE rpt DROP COLUMN id_tracciato_mypivot ;
ALTER TABLE rpt DROP COLUMN id_tracciato_secim ;
```

**Comment by giuseppeformaro** [comment]
Tutto ok, è bastato riconfigurare i connettori (le configurazioni fatte prima di modificare it.govpay.batch.caricamentoTracciatiNotificaPagamenti.enabled non generavano tracciati).
