### ISSUE TITLE
network e SSL authentication issue

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#409]
Dopo una serie di aiuti e supporto da parte di @nardil che ringrazio come sempre, anche se adesso la situazione è più chiara, ho dei dubbi sulla configurazione dell'infrastruttura su cui poggia l'applicativo GOVPAY e le varie modalità di autenticazioni disponibili.

Premessa:
Ho fatto un SSL passthrough dal VIP che riceve i pacchetti http dall'esterno e diretti all'application server govpay attestato sul dominio govpaytest.iss.it.  Questo dovrebbe garantire che i pacchetti http arrivano così come encrypted dal sistema chiamante all'applicazione che, sulla base della sua configurazione di sicurezza, fa le opportune verifiche.

Quindi avendo impostato nei securiy context di ogni WAR ( li dove presenti: pagamenti, pendenze, pagopa, backoffice, apiuser, ragioneria) la sola BASIC AUTHENTICATION, mentre su pagopa solo la SSL, mi aspettavo un comportamento di questo tipo:

1) invocando le api di PAGOPA si innestava la SSL e quindi se il chiamante non aveva criptato la richieta con il certificato, quest'ultima non veniva autorizzata
2) invocando tutte le altre API, pagamenti, pendenze, backoffice, apiuser, ragioneria, queste chiedevano solo nell'header dell'http le credenziali user/password relative.

Il risultato invece è che per TUTTE le chiamate, console GUI di backoffice inclusa, l'application server richiede che il chiamante abbia criptato i pacchetti con il certificato govpaytest.iss.it, quindi come se abbia sempre attiva la SSL.
Domandina: per default i security context dei vari WAR avevano attiva sia la BASIC che la SSL, che succede? sono richieste entrambi o basta che se ne usa una delle due o tutte e due?

Questa cosa io non riesco a risolverla. Cosa posso controllare, modificare? 
Non so per esempio come ha fatto mitservizi a rendere pubbliche le API RT di govpay accedibili senza problemi di certificati. Posso disabilitare tutto anche l'SSL sul security context xml di pagopa?

Grazie

**Comment by nardil** [comment]
> Il risultato invece è che per TUTTE le chiamate, console GUI di backoffice inclusa, l'application server richiede che il chiamante abbia criptato i pacchetti con il certificato govpaytest.iss.it

Non credo sia l'Application Server, ma piuttosto il frontend che richiede la client auth per tutti i contesti. Controlla l'`access.log` di WildFly per averne conferma

**Comment by mallomix** [comment]
> Controlla l'`access.log` di WildFly per averne conferma

Non ho questo log su WildFly 18. 
Comunque il frontend esisteva prima della modifica di propagare il certificato fino all'AS e per tutte le altre API non c'erano errori di connessione e correttamente per funzionare andavano messe quelle di tipo BASIC AUTH. Dal momento che ho propagato tutti i client (sito, soapui, browser, postgres) non funzionano più se non gli metto sotto il certificato con chiave privata e forzo l'autenticazione client, nonostante l'applicazione sia configurata per richiedere solo quella BASIC.


> Non so per esempio come ha fatto mitservizi a rendere pubbliche le API RT di govpay accedibili senza problemi di certificati. Posso disabilitare tutto anche l'SSL sul security context xml di pagopa?
Come è possibile che questo URL https://govpay.mitservizi.com/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl di un altro cliente govpay è accedibile senza nessun problema di client authentication SSL ?

**Comment by nardil** [comment]
> Dal momento che ho propagato tutti i client (sito, soapui, browser, postgres) non funzionano più se non gli metto sotto il certificato con chiave privata e forzo l'autenticazione client, nonostante l'applicazione sia configurata per richiedere solo quella BASIC.

Con ogni probabilita'  e' il frontend a richiedere l'autenticazione SSL, non WildFly/GovPay. Prova invocando direttamente WildFly (per default sulla porta 8080) bypassando gli apparati di frontiera. Se funziona, devi rivedere la configurazione del frontend in modo che richieda la mutua autenticazione SSL solo per le API su cui la richiedi (al momento solo quelle pagoPA per quanto hai raccontato)

> Come è possibile che questo URL https://govpay.mitservizi.com/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice?wsdl di un altro cliente govpay è accedibile senza nessun problema di client authentication SSL ?

Direi che e' una configurazione da evitare. Le API pagoPA sono esposte a tutti con i rischi che questo può comportare.

**Comment by mallomix** [comment]
Ciao Nardil,

allora la situazione è leggermente diversa. Mi spiego:

da fuori ma anche bypassando tutto e facendo le prove direttamente sulla macchina che ospita l'application server, correttamente utilizzando la porta 8080, i servizi di ragioneria, api user, dashboard ecc.. funzionano bene TRANNE quelle di pagopa che funzionano solo con la connessione https e client authentication SSL. 

MA se io uso la connettività https, quindi invece che localhost:8080 uso https://localhost:8443, qualsiasi servizio vuole la client authentication SSL anche se sto sulla stessa macchina dove sta installato wildfly con govpay... IO NON CAPISCO... però sicuramente è una questione di ignoranza.

io mi aspetto di andare sempre in https... ma i servizi pagopa chiedono l'autenticazione SSL, mentre gli altri quella BASIC come configurato.

**Comment by mallomix** [comment]
@nardil grazie anche alla ricerca di altre issue sempre sull'argomento sto facendo piccoli passi per chiarirmi la root cause e intercettare il furbacchione che mi da noia.
1) ho stabilito con gli esperti che configurare il VIP con pass-throught mi consente di far atterrare tutto il traffico così come arriva sul vip dal dns govpaytest.iss.it porta 443 sulla macchina server GOVPAY porta 8443. Quindi la connessione SSL arriva fino al server govpay senza nessuna manipolazione.
2) i security context di pagopa sono impostato con SSL attiva (solo SSL).
3) gli altri secuiry context sono impostati da default .. quindi BASIC AUTH

adesso succede questo:

1) da una macchina esterna (quindi da internet) provo a collegarmi a questo url https://govpaytest.iss.it/govpay/backend/gui/backoffice/intermediari/dettaglio  prendo un errore 
"Impossibile raggiungere questa paginaLa connessione è stata reimpostata.
Prova a:

Verifica della connessione
Verifica del proxy e del firewall
Usare la diagnostica di rete Windows
ERR_CONNECTION_RESET"

2) provando a connettermi direttamente dal server govpay, quindi bypassando tutta l'infrastruttura a monte, ottengo un bel
"Attenzione: potenziale rischio per la sicurezza  e mi da la possibilità di autorizzare il certificato self signed del server che però non è quello che è trustato in govpay... sembra un certificato di default di wildfly o del server stesso che non trovo da nessuna parte.

Ovviamente stesso discorso con le API pagopa che vogliono il certificato. 

Non so veramente che fare! sono bloccato e non posso consegnare il progetto. Chiunque abbia sperimentato e trovato una soluzione mi sarebbe di grandissimo aiuto.

**Comment by mallomix** [comment]
continua su #412
