### ISSUE TITLE
Visualizzare CBILL nell'avviso di pagamento

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#413]
Buonasera,
Per vedere il codice CBILL nell'avviso bisogna configurare qualcosa nell'ente ?

Grazie,

**Comment by nardil** [comment]
Si, nell'anagrafica dell'ente corrisponde al `Codice Interbancario`

https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/enti/index.html#nuovo-ente-creditore

Ricorda di resettare la cache se vuoi che la modifica sia immediatamente operativa.

**Comment by nardil** [comment]
Il nome e' retaggio di una vecchia dicitura pagoPA. Andrebbe allineata a come viene etichettata sull'avviso, ovvero come `Codice CBILL`

**Comment by giuseppelab** [comment]
Perfetto Grazie.
