### ISSUE TITLE
[Api Verifica e Notifica] - Richiesta chiarimenti sui tentativi di invio

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#418]
Buonasera,
sto utilizzando la versione di GovPay 3.4.3 SNAPSHOT (ad ieri, master del progetto) e ho  riscontrato alcune difficoltà nelle notifiche alla mia applicazione attraverso le Api di Notifica.
Cercherò di essere il più dettagliato possibile tenendo presente che non ho fatto alcuna modifica a classi java o file di properties. La struttura del mio ambiente di lavoro è la seguente :
- **Server A** : su cui è installato GovPay 3.4.3 SNAPSHOT
- **Server B** : su cui sono installate due applicazioni che effettuano pagamenti (**b1** e **b2**) ed una applicazione che fa da backoffice (**b3**) e che deve contenere i dati dei pagamenti effettuati dalle altre due applicazioni. 

Quest'ultima applicazione è quella che viene chiamata da GovPay tramite le api di notifica. Sia nel caso riceva una notifica di avvio, sia nel caso riceva una notifica di esito RT, controllo che sul mio db sia presente un record riferito alla pendenza del pagamento e in caso negativo lo creo al volo e lo popolo con i dati che mi arrivano dalla notifica.
Durante le prove di creazione e finalizzazione di alcuni pagamenti dai due client **b1** e **b2**, GovPay non è riuscito ad inviare contestualmente le notifiche all'applicazione **b3** poichè era momentaneamente spenta. Le notifiche sono state quindi rischedulate. Al riavvio dell'applicazione ho riscontrato le seguenti anomalie (?):
- alcune notifiche di avvio di pagamento sono arrivate successivamente alle notifiche di conclusione con esito per lo stesso pagamento
- per un paio di pagamenti, la notifica di avvio e quella di esito sembrano essere arrivate contemporaneamente, tanto è che ho trovato due record sul db relativi allo stesso pagamento, quando dovrebbe essercene uno solo.

Ora, premesso che almeno per il punto 2 potrei teoricamente intervenire migliorando il salvataggio con una sorta di sincronizzazione, mi potreste spiegare meglio come vengono rischedulate le notifiche nei tentativi successivi al primo che è contestuale all'evento ? Io ritenevo, probabilmente erroneamente, che ci fosse una sorta di coda smaltita in base all'ordine di inserimento.

ho dato una occhiata anche a [questa ](https://generator.swagger.io/?url=https://raw.githubusercontent.com/link-it/govpay/3.5.x/jars/client-api-ente/src/main/resources/govpay-api-ec-v1.yaml)descrizione che avete aggiunto recentemente su swagger ma continua a non essermi chiaro.

Colgo l'occasione per ringraziarvi, come sempre, per la disponibilità e la prontezza nel rispondere.
Buon lavoro

**Comment by nardil** [comment]
La notifica di avvio è utile per gestire eventuali processi da parte dell'applicativo gestore della pendenza quando è distinto dall'applicativo che avvia la transazione.

Faccio presente che nel nuovo modello 3 proposto da pagoPA (SANP v2.4 e successive) le ricevute di pagamento saranno emesse solo in caso di esito positivo.

Prevederemo certamente la possibilità di continuare ad acquisire le RT negative nei casi che le prevedono, ma a nostro avviso l'unico utilizzo per l'EC è quello della conservazione prevista dalla normativa.
