### ISSUE TITLE
Caricamento Massivo

### ISSUE THREAD

**Issue by ivan86to** [link-it/GovPay#42]
Ciao, 
non so se è stato già verificato ma ho visto che nel caricamento massivo dei versamenti da govpayConsole c'è un problema sulla data scadenza. ( O almeno credo sia un problema ) 

Classe it.govpay.core.utils.Utils.java riga 97 
SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY"); <- Viene utilizzato YYYY invece di yyyy questo porta ad una errata gestione delle date. 

Oppure c'è un motivo particolare per cui è stato messo YYYY invece che yyyy?

**Comment by nardil** [comment]
Grazie per la segnalazione!
