### ISSUE TITLE
Caricamento Tracciato CSV tramite API fallito

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#425]
Salve, Sto provando il caricamento di un tracciato csv di pendenze.
La chiamata di post del csv tramite api di backoffice va a buon fine e mi restituisce il numero del tracciato.
Quando però provo a fare la get dello stato del tracciato ricevo questa risposta 

```json
{
    "id": 2,
    "nomeFile": "*******",
    "dataOraCaricamento": "2021-11-05T14:02",
    "stato": "SCARTATO",
    "descrizioneStato": "Errore durante l'elaborazione del tracciato: org.postgresql.jdbc.PgConnection cannot be cast to org.postgresql.PGConnection",
    "numeroOperazioniTotali": 0,
    "numeroOperazioniEseguite": 0,
    "numeroOperazioniFallite": 1,
    "numeroAvvisiTotali": 0,
    "numeroAvvisiStampati": 0,
    "numeroAvvisiFalliti": 0,
    "operatoreMittente": "******",
    "dataOraUltimoAggiornamento": "2021-11-05T14:02",
    "stampaAvvisi": true
}
```

controllando nel log di govpay vedo che durante l'elaborazione lancia l'eccezione che vedete nel file allegato 
[errore_tracciato.txt](https://github.com/link-it/govpay/files/7486235/errore_tracciato.txt)

**Note aggiuntive:**
Utilizzo la versione di GovPay 3.4.3-SNAPSHOT (93725ee), tutte le altre operazioni tramite api (caricamento pendenze, pagamento ecc) funzionano come dovrebbero.

Di cosa si tratta ? un errore di configurazione ?

**Comment by pintorig** [comment]
Ciao @frdidonato, 
questo errore si ottiene quando in un'installazione wildfly+postgres il datasource non utilizza un [driver JDBC deployato in un modulo wildfly](https://govpay.readthedocs.io/it/latest/installazione/configurazione/index.html#il-database) ma direttamente un jar.

Puoi verificare la configurazione dell'installazione?

**Comment by frdidonato** [comment]
Grazie mille @pintorig , era esattamente il mio caso.
una volta fatta l'installazione del modulo e modificata la datasource per richiamarlo l'invocazione funziona correttamente.
