### ISSUE TITLE
Pagamento da portale passando direttamente ENTE e IUV nella richiesta

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#427]
Ciao,
è possibile eseguire una richiesta di pagamento da portale govpay-portal "bypassando" selezione ente e IUV? 

Con una cosa del genere:
https://xxx/govpay/frontend/api/pagamento/rs/public/v2/avvisi/cf_ente/IUV

Grazie in anticipo come sempre!

**Comment by nardil** [comment]
Si, con una richiesta di questo tipo:

```
 POST /govpay/frontend/api/pagamento/rs/basic/v2/pagamenti
 Accept: application/json
 Content-type: application/json"

 {
   "pendenze": [
     {
       "idDominio": "01234567890",
       "numeroAvviso": "301000001234567890"
     }
   ]
 }
```

**Comment by giuseppeformaro** [comment]
Grazie mille!
