### ISSUE TITLE
Portale al Cittadino

### ISSUE THREAD

**Issue by ilsanto17** [link-it/GovPay#43]
Mi chiedevo, l'interfaccia grafica (client) di pago PA in php dove la trovo?

Grazie mille.
buonaserata

**Comment by nardil** [comment]
Ciao @ilsanto17,

se ti riferisci al cruscotto di gestione e monitoraggio di GovPay, e' esposto con il contesto /govpayConsole

Se invece ti riferisci al portale al cittadino, questo non e' incluso nel progetto. GovPay si propone come componente infrastrutturale a cui portali, gestionali di posizioni debitorie e applicativi di segreteria, solitamente preesistenti, si integrano per l'accesso a PagoPa.

**Comment by ilsanto17** [comment]
Si mi riferisco al portale per il cittadino. Non si trova  nulla di gia precompilato??

**Comment by nardil** [comment]
Potresti vedere il progetto [Pagamenti Online](https://github.com/publisys-spa/pagamenti-online) di Publisys. Ho chiesto a @acoviello, che lo gestisce, lo stato di avanzamento e mi ha confermato di essere allineata alla versione 2.4 di GovPay, ma non hanno riversato il codice su GitHub, cosa che intendono fare entro la prox settimana.

**Comment by ilsanto17** [comment]
Grazie mille @nardil..
