### ISSUE TITLE
Modello 3  recupero ricevuta con UTENZA.TIPO.APLLICATIVA

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#431]
Buongiorno, 
nei pagamenti modello 3 sulla pendenza inserita da utenza applicativa e pagata da PSP o da APP IO l'utenza stessa non riesce a recuperare la ricevuta, nella chiamata 

curl -X GET 
            govpay/frontend/api/pagamento/rs/basic/v2/rpp/{idDominio}/{iuv}/{ccp}/rt

prende questo errore

{
  "categoria": "AUTORIZZAZIONE",
  "codice": "403000",
  "descrizione": "Operazione non autorizzata",
  "dettaglio": "Applicazione [XXXXX] non autorizzata ad accedere alla risorsa richiesta: la transazione riferisce un pagamento che non appartiene all'applicazione chiamante."
}

sembra a causa del fatto che nella tabella **pagamenti_portale** il valore del campo **Id_applicazione** rimane a NULL per questo tipo di transazioni. 

La pendenza è stata creata con il servizio  /pendenze/{idA2A}/{idPendenza}  

avete altre evidenze su questo tipo di problematica, oppure magari può dipendere da una errata creazione della pendenza ?

Grazie per il consueto supporto

**Comment by nardil** [comment]
Ciao @asterixol2000 , 

il comportamento e' corretto. Come riepilogato nella [documentazione](https://govpay.readthedocs.io/it/latest/integrazione/api/autorizzazione/index.html), le API Pagamento danno ad una applicazione visibilita' dei pagamenti da lei avviati. Essendo il pagamento avviato modello 3, l'applicazione non ha modo di vederne i dettagli.

Puoi accedere tramite l'API Pendenze dall'applicazione titolare del debito, ovvero quella identificata con l'idA2A con cui e' stata caricata la pendenza.

**Comment by asterixol2000** [comment]
Ciao nardil

grazie per la risposta.  Una precisazione sulla mia domanda originale dove non era chiaramente esplicitato.

La pendenza era stata creata con la stessa utenza applicativa idA2A  che poi veniva utilizzata per la  richiesta della ricevuta (mi sembrava strano che la stessa utenza non potesse accedere alla ricevuta ). In ogni caso con L'API pendenza tutto ok . 

Un cordiale saluto e buon lavoro
