### ISSUE TITLE
Integrazione Transizione di pagamento tramite PagoPa/govPay con PHP

### ISSUE THREAD

**Issue by AntonioGiornetta** [link-it/govpay#432]
Salve a tutti.
Vorrei realizzare un'applicazione (sito web in php) che permetta di poter effettuare un pagamento verso una pubblica amministrazione tramite PagoPa.
Vorrei sapere se è possibile una cosa del genere con govpay:

NumeroTransizione=PagaConPagoPa(CodiceIpa,CodiceServizio,Causale,Importo,CodiceFiscale,PartIva,DatiCartaDiCredito);

se NumeroTransizione>0 allora ok, altrimenti non è andato a buon fine...

La PA, ovviamente, ha già il proprio partner tecnologico che gli fornisce già il portale PagoPA, quindi domanda:
devo diventare partner tecnologico, oppure esiste un partner "free" da poter indicare ?
Spero di essere stato chiaro.

Grazie a tutti.

**Comment by nardil** [comment]
Ciao @AntonioGiornetta , 

se la PA richiede l'uso di un partner tecnologico gia' esistente, dovrai utilizzare le API che ti mette a disposizione per la realizzazione di pagamenti tramite la sua piattaforma. In alternativa l'Ente puo' aderire in modalità' diretta con la propria piattaforma oppure puoi proporti tu come Partner Tecnologico in qualita' di suo intermediario.

Tanto premesso, GovPay espone delle [API REST](https://govpay.readthedocs.io/it/latest/integrazione/api/index.html) per realizzare i vari [casi d'uso](https://govpay.readthedocs.io/it/latest/scenari/index.html) tra cui quello da te ipotizzato, unica eccezione e' in merito ai `datiCartaDiCredito` che non sono gestiti dalla piattaforma dell'ente, ma acquisiti e gestiti direttamente da pagoPA nelle interazioni del pagatore con il WISP.

**Comment by nardil** [comment]
> esiste un partner "free" da poter indicare

No, non esiste un partner "free"
