### ISSUE TITLE
Export ZIP Avvisi di Pagamento da Tracciato - Informazioni sulla customizzazione

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#433]
Buongiorno,
Avrei bisogno di una informazione. Ho implementato il caricamento del tracciato csv tramite api di backoffice e il conseguente download del file zip contenente tutti gli avvisi di pagamento relativi al tracciato.
Il file zip contiene tutti gli avvisi nominati in questo modo :

**idDominio_numeroAvviso.pdf**

è possibile customizzare questo format di esportazione per gli avvisi ? avrei bisogno di qualcosa del genere 

**identificativoPagatore_iuv.pdf**

oppure

**identificativoPagatore_numeroAvviso.pdf**

con identificativo pagatore intendo codice fiscale o partita iva del pagatore.

Versione di GovPay : 3.4.3-SNAPSHOT 
Grazie in anticipo per la disponibilità

**Comment by nardil** [comment]
Non e' una funzionalità per cui e' prevista la personalizzazione. 

La soluzione più semplice e' quella di fare uno script che rinomina i file usando le informazioni contenute nel csv di esito. In alternativa puoi modificare il codice per produrre i file con la nomenclatura desiderata.

**Comment by frdidonato** [comment]
Non ho intenzione di modificare il codice, in questo modo posso installare e aggiornare GovPay senza manutenere personali customizzazioni.
Molto probabilmente utilizzerò il tuo suggerimento di utilizzare il csv degli esiti e creare uno script per rinominare i files.
Ti ringrazio come sempre per la disponibilità

**Comment by nardil** [comment]
Figurati. Se poi vuoi condividere la soluzione trovata possiamo includerla come script di utilita'
