### ISSUE TITLE
Produzione dell’installer dai sorgenti - govpay-master - 

### ISSUE THREAD

**Issue by masdon** [link-it/govpay#436]
Sto avendo problemi nella produzione dell'installe
[Problem.docx](https://github.com/link-it/govpay/files/7656093/Problem.docx)
r

**Comment by masdon** [comment]
E' la prima volta che utilizzo questo canale. Spero di aver proceduto correttamente. Grazie!!!

**Comment by giuseppelab** [comment]
Ciao, ma he tipo di problema riscontri ?

**Comment by masdon** [comment]
Nell'inserimento della nuova issue ho allegato un file in word che descrive il problema; lo allego qui.

Grazie e cordiali saluti

Donato
