### ISSUE TITLE
Gestione notifiche PUSH

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#437]
Ciao,
esiste una classe java di esempio per gestire l'acquisizione delle notifiche (avvio pagamento, termine pagamento) che arrivano da govpay ?

Grazie, ciao.

**Comment by nardil** [comment]
No, ma dovrebbe essere generabile a partire dal descrittore OpenAPI utilizzando uno degli strumenti disponibili in rete, ad esempio: 

https://github.com/OpenAPITools/openapi-generator
