### ISSUE TITLE
Aggiornamento della versione di Log4J - Bug Sicurezza

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#438]
Buongiorno, come avrete appreso nei giorni scorsi Log4j soffre di un bug di sicurezza che permette l'esecuzione di script shell da remoto. 
Vi giro un link per reperire alcune informazioni 
https://www.cybersecurity360.it/nuove-minacce/il-bug-log4j-minaccia-mezza-internet-ecco-il-fix-di-urgenza-per-le-aziende/

In particolare si potrebbe risolvere temporaneamente utilizzando il seguente parametro di avvio della jvm
`-Dlog4j2.formatMsgNoLookups=true`

Il bug sembra essere presente dalle versioni di log4j 2.0 in poi, ma questo parametro è impostato di default a true nella versione 2.15.0. Converrebbe effettuare l'aggiornamento della versione di Log4j nel core di GovPay e aggiornare il master, oppure rilasciare una versione PATCH con questa correzione.

**Comment by nardil** [comment]
E' stata gia' committata la modifica per aggiornare la versione di Log4J alla 2.15.0 che risolve il problema. Sta girando in questo momento la testsuite su jenkins. Appena terminata e confermata la bonta' della versione, provvediamo a rilasciare la nuova versione.

**Comment by nardil** [comment]
> In particolare si potrebbe risolvere temporaneamente utilizzando il seguente parametro di avvio della jvm
> `-Dlog4j2.formatMsgNoLookups=true`

La versione precedentemente usata era la 2.6.x per la quale il fix proposto risulta il seguente:

```
For releases >=2.0-beta9 and <=2.10.0, the mitigation is to remove the JndiLookup class from the classpath: zip -q -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class.
```
(fonte [Apache Log4J](https://logging.apache.org/log4j/2.x/security.html))

**Comment by mallomix** [comment]
> E' stata gia' committata la modifica per aggiornare la versione di Log4J alla 2.15.0 che risolve il problema. Sta girando in questo momento la testsuite su jenkins. Appena terminata e confermata la bonta' della pacchetto, provvediamo a rilasciarlo.

Ciao Nardil, verrò rilasciata come fix del pacchetto 3.4.4? Grazie

**Comment by nardil** [comment]
E' gia' inclusa nel pacchetto 3.4.4

**Comment by mallomix** [comment]
> E' gia' inclusa nel pacchetto 3.4.4

Perfetto, se provengo dalla 3.4.2 basta che sostituisco l'ear giusto?  mentre che provengo da versioni precedenti devo portarmi in 3.4.2 con gli script su DB e poi passare alla 3.4.4 corretto?
Ringrazio tutti come sempre
