### ISSUE TITLE
Adeguamento Codici SIOPE 2017

### ISSUE THREAD

**Issue by acoviello** [link-it/govpay#44]
Ciao @nardil ,
in questi giorni ho parlato con una mia collega del settore contabilità e finanziaria in merito ai codici SIOPE delle voci in entrata degli enti. Lei mi ha fatto notare che la codifica è cambiata e gli script di inserimento dei codici non sono aggiornati secondo [questi tracciati ](http://www.rgs.mef.gov.it/VERSIONE-I/e-GOVERNME1/SIOPE/In-Evidenza/Decreto09062016/). 

[siope.zip](https://github.com/link-it/GovPay/files/1323857/siope.zip)
 Insieme abbiamo prodotto lo script  allegato l'unica cosa è che per funzionare bisogna aumentare il campo COD_TRIBUTO_IUV, io ho eseguito questa alter table per coerenza con gli altri campi  ALTER TABLE "tipi_tributo" ALTER COLUMN "cod_tributo_iuv" TYPE varchar(255); e inserito tutti i campi, considerando che quelli precedenti non li avevo proprio importati sul db.

Fammi sapere se possono andar bene.

**Comment by nardil** [comment]
Ciao @acoviello 
grazie per il contributo! 

Due osservazioni:
1. Il campo cod_tributo_iuv e' gia' di quella dimensione da tempo (0873ebab9fb62c9405c51fd633d9e887e0b35e4b) hai qualche disallineamento sul db?
2. Quel campo indica, se la funzione e' abilitata, come codificare negli IUV generati il tributo pagato. Di conseguenza il campo deve:
    - Essere numerico (per conformita agli iuv tipo 3)
    - essere piu' corto possibile (per non ridurre eccessivamente lo spazio di iuv generabili)

Per renderli numerici e' sufficiente togliere i punti: 1.01.01.06.001 > 1010106001
La dimensione pero' e' eccessiva (prenderebbero 10 caratteri su 15 a disposizione) E' possibile individuare una ricodifica per renderli piu' corti? 

Fammi sapere se hai qualche idea in proposito,
Lorenzo

**Comment by acoviello** [comment]
Lorenzo, 
purtroppo parlando con i miei colleghi del settore, mi hanno detto che non si possono ridurre più di così altrimenti ci sarebbero duplicati.
Si potrebbero utilizzare i primi tre gruppi 10101 per identificare almeno la macro categoria del tributo, ma si perderebbe l'univocità. 
Mi hanno inoltre riferito che il cambiamento è stato drastico dalla precedente codifica quindi non si può fare un mapping tra la prima codifica e quest'ultima e riutilizzare i vecchi codici.
Forse si dovrebbe pensare ad un progressivo interno, probabilmente utilizzando un codice di questo tipo si potrebbero evitare anche modifiche future alla codifica SIOPE (che non dovrebbero cambiare più nel tempo però non si sa mai!).

Che ne pensi?

Alessandra

**Comment by nardil** [comment]
Beh, sicuramente e' una soluzione. Non e' elegante dal momento che introduce la necessita' di tradurre i codici IUV in codici SIOPE, ma al momento non mi sembra ci siano molte alternative. La codifica originale richiede troppi caratteri per essere utilizzata.

Potreste proporre la vostra codifica scrivendo il sql di alimentazione e una tabella di mapping (testuale)  necessaria per la decodifica da inserire in nella documentazione di GovPay

**Comment by ilsanto17** [comment]
@nardil Buongiorno, ho installato govpay. La console e i wsdl sono raggiungibili. Ora ho integrato pagamenti online, ma quando effettuo la build mi da il seguente errore :cannot find the declaration of element ns3:gpAvviaTransazionePagamento

Mi potete dare qualche informazione in merito?

**Comment by nardil** [comment]
Ciao @ilsanto17 , 
dovresti aprire una nuova issue pertinente al tuo problema (questa riguarda i codici SIOPE).

Dovresti inoltre fornire maggiori dettagli sull'operazione che fallisce (build?), possibilmente allegando il dump della richiesta.

**Comment by ilsanto17** [comment]
@nardil  fatto
