### ISSUE TITLE
Mancata attivazione RPT nel pagamento tramite bollettino postale

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#441]
Ciao,
attivato il pagamento con bollettino postale da ritagliare nell'avviso di pagamento.
Il pagamento è stato effettuato; dai log vedo soltanto la richiesta di verifica RPT.
E' normale ? forse bisogna attendere ?

Grazie.

**Comment by nardil** [comment]
Ciao @giuseppelab, dovresti interfacciarti con pagoPA per eventuali chiarimenti sul comportamento del PSP.
