### ISSUE TITLE
Gestione del numero di risultati

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#444]
**Necessità:**
Attualmente la count del numero di risultati rappresenta una problematica in caso di numeri elevati.

**Soluzione:**
- [ ] Prevedere che nel caso sia limitato li numero di risultati conteggiati, l'interfaccia mostri la dicitura  "Trovati oltre xxxxx risultati"
- [ ] Prevedere che la count sia effettuata come ultima richiesta e non sia bloccante per l'uso dell'interfaccia
- [ ] Prevedere che se la count fallisce per timeout, l'interfaccia sia comunque usabile mostrando un messaggio del tipo "Numero di risultati sconosciuto"

**Comment by atatarelli** [comment]
@pintorig  Ho notato che nella API di Backoffice, solo la "GET /pagamenti" di richiesta dei metadati di paginazione (metadatiPaginazione=true&risultatiPerPagina=0) restituisce l'attributo "maxRisultati".

Andrebbe prevista la restituzione dell'attributo "maxRisultati" anche in tutte le altre GET (pendenze, incassi, eventi, flussiRendicontazione, riscossioni, intermediari, domini, tipiPendenza, applicazioni, …).
