### ISSUE TITLE
Attivazione pagamenti spontanei

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#446]
Buondi,
non ho chiaro come attivare i pagamenti spontanei in govpay da govpay-portal.

Ho configurato una pendenza come pagamento spontaneo sia in TIPO PENDENZA che su un singolo ENTE ma non mi è chiaro cosa altro va fatto.

Posso avere chiarimenti?

**Comment by nardil** [comment]
CIao @giuseppeformaro , dovresti seguire le indicazioni della documentazione:

https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/enti/pendenza_spontaneo.html

**Comment by giuseppeformaro** [comment]
Buondi, scusatemi ma non riesco a capire come dalla FORM dove passo alcuni dati di input posso completare l'inserimento della PENDENZA con tutti i dati necessari.

Se ho capito bene va configurata la trasformazione dei dati? E' disponibile un esempio di come crearlo?

Grazie ancora.
