### ISSUE TITLE
Errore (VER_031) in inserimento PENDENZA MULTIVOCE con NUMERO AVVISO

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#448]
**Descrizione del Bug**
Rimane il problema dell'inserimento di una pendenza MULTIVOCE se viene passato anche il NUMERO AVVISO.

**Come riprodurlo:**
Inserimento da API pendenze di un avviso multivoce (come quello descritto nel nuovo manuale GovPay 3.5.0) ma passando anche "numeroAvviso": 3xxx

**Risultato atteso:**
Inserimento della pendenza.

**Ambiente:**
 - GovPay: 3.5.0

**Note aggiuntive:**
Il vincolo doveva essere rilassato con le specifiche SANP v2.4 incluse in GovPay 3.5.0 (dettagli nella segnalazione #364). problematica

**Comment by pintorig** [comment]
@giuseppeformaro 
Ho corretto il comportamento dell'applicazione per consentire il caricamento delle pendenze multivoce con numero avviso definito.
Tuttavia il vincolo resta quando una delle voci e' una Marca da Bollo Telematica poiche' non esistono PSP che supportano il pagamento del Bollo con il modello 3.

**Comment by nardil** [comment]
@pintorig falliscono due test della testsuite:

```
Tests in error: 

  [9:511] Numero avviso su multivoce([pendenza-post-inoltro]): pendenza-post-inoltro.feature:556 - path: $.dettaglio, actual: 'L'inoltro del versamento [Dominio: 12345678901 TipoVersamento:RINNOVO] all'applicazione competente [Applicazione:IDA2A01] e' fallito con errore: Non e' possibile indicare il numero avviso per una pendenza di tipo multivoce se una delle voci e' una Marca da Bollo Telematica.', expected: 'L'inoltro del versamento [Dominio: 12345678901 TipoVersamento:RINNOVO] all'applicazione competente [Applicazione:IDA2A01] e' fallito con errore: Non e' possibile indicare il numero avviso per una pendenza di tipo multivoce.', reason: not equal

  [8:736] Pagamento spontaneo modello 4 inoltrato all'applicazione Numero avviso su multivoce([pagamento-pendenza-modello4-applicazione-inoltro]): pagamento-pendenza-modello4-applicazione-inoltro.feature:809 - path: $.dettaglio, actual: 'L'inoltro del versamento [Dominio: 12345678901 TipoVersamento:SPONTANEO] all'applicazione competente [Applicazione:IDA2A01] e' fallito con errore: Non e' possibile indicare il numero avviso per una pendenza di tipo multivoce se una delle voci e' una Marca da Bollo Telematica.', expected: 'L'inoltro del versamento [Dominio: 12345678901 TipoVersamento:SPONTANEO] all'applicazione competente [Applicazione:IDA2A01] e' fallito con errore: Non e' possibile indicare il numero avviso per una pendenza di tipo multivoce.', reason: not equal



Tests run: 17785, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by giuseppeformaro** [comment]
Buondi,
appena possibile sono disponibile a continuare i TEST con inserimento avviso.

Grazie

**Comment by nardil** [comment]
@giuseppeformaro , la problematica segnalata e' stata risolta, pertanto puoi certamente aggiornare e verificare la corretta gestione

Puoi utilizzare una delle build di jenkins del branch 3.5.x: https://jenkins.link.it/govpay/blue/organizations/jenkins/govpay/activity?branch=3.5.x

**Comment by giuseppeformaro** [comment]
Ciao, riscontro i seguenti problemi:
...
"importo": 4.00,
   "numeroAvviso": 302020210415094021,
   "dataValidita": "2022-04-30",
...

Ma nella response mi trovo:
{
  "idDominio": "xxx",
  "numeroAvviso": "302020210415094000",
  "UUID": "xxx"
}

In pratica le ultime 2 cifre non sono corrette e conseguentemente non lo sono nemmeno per lo IUV:
IUV: 02020210415094000

Inoltre, nel tentativo di pagare con appIO vedo negli eventi della pendenza:
"Il versamento contiene piu' di un singolo versamento, non ammesso per pagamenti ad iniziativa psp."

**Comment by nardil** [comment]
> Ciao, riscontro i seguenti problemi: ... "importo": 4.00, "numeroAvviso": 302020210415094021, "dataValidita": "2022-04-30", ...
> 
> Ma nella response mi trovo: { "idDominio": "xxx", "numeroAvviso": "302020210415094000", "UUID": "xxx" }
> 
> In pratica le ultime 2 cifre non sono corrette e conseguentemente non lo sono nemmeno per lo IUV: IUV: 02020210415094000

Potresti esplicitare la API invocata, la risorsa richiesta ed il payload della richiesta per replicare lo use case?

> Inoltre, nel tentativo di pagare con appIO vedo negli eventi della pendenza: "Il versamento contiene piu' di un singolo versamento, non ammesso per pagamenti ad iniziativa psp."

Sul Portale delle Adesioni hai attivato la versione 2 sulla stazione di interesse?

**Comment by giuseppeformaro** [comment]
Ho rifatto un altro TEST (NAVVISO: 330020210415094328 ma nella request mi riporta già erroneamente: 330020210415094340)

API invocata:
/govpay/backend/api/pendenze/#/Pendenze/addPendenza

La REQUEST:
`{"idDominio":"xxx","idUnitaOperativa":"CU3","causale":"TEST 4 multibeneficiario cod_seg 30 CON NUM_AVVISO","idTipoPendenza":"TARI","soggettoPagatore":{"tipo":"F","identificativo":"xxx","anagrafica":"xxx","indirizzo":"VIA xxx'","civico":"30","cap":88000,"localita":"xxx","provincia":"xx","nazione":"IT","email":"giuseppe.formaro@xxx"},"importo":4,"numeroAvviso":330020210415094340,"dataValidita":"2022-04-30","dataScadenza":"2022-04-30","annoRiferimento":2021,"cartellaPagamento":"202103291218","datiAllegati":{},"tassonomia":"9/0101101IM/","tassonomiaAvviso":"Imposte e tasse","voci":[{"idVocePendenza":"TARI","importo":3,"descrizione":"Importo TARI","ibanAccredito":"IT41Qxxxx","tipoContabilita":"ALTRO","codiceContabilita":"0101101IM/"},{"idVocePendenza":"TEFA","importo":1,"descrizione":"Importo TEFA","idDominio":"xxxx","ibanAccredito":"IT41Qxxx","tipoContabilita":"ALTRO","codiceContabilita":"0201102IM/"}]}`


Se puo essere utile, senza numero avviso come input, lo IUV lo inserisce con un valore conforme: 330000000000030217

**Comment by nardil** [comment]
Ciao @giuseppeformaro , 

> Ho rifatto un altro TEST (NAVVISO: 330020210415094328 ma nella request mi riporta già erroneamente: 330020210415094340)

non ci e' chiara questa affermazione. 

Il caricamento di un avviso multibeneficiario con numero fornito dall'applicativo chiamante e' coperto dalla testsuite e risulta passare con successo. Avremmo bisogno di maggiori informazioni per replicare il tuo usecase.

Potresti riformulare la descrizione del problema che riscontri aggiungendo request e response inviate a GovPay con evidenza dell'anomalia?

**Comment by giuseppeformaro** [comment]
Ciao, spero di essere più chiaro allegando la prova che ho fatto dove si vede il numeroAvviso che gli ho passato:
![problema navviso multibeneficiario req](https://user-images.githubusercontent.com/72001866/159549959-4acd0853-2817-4d8c-8dc2-b7b0e031f5ed.JPG)

Invece diventa:
![problema navviso multibeneficiario](https://user-images.githubusercontent.com/72001866/159549955-e1c6fc90-544a-44ec-852e-43da073e6999.JPG)

Grazie
.

**Comment by giuseppeformaro** [comment]
Buondi,
perdonami, ecco la request:
```
{
   "idDominio": "00297910000",
   "idUnitaOperativa": "CU3",
   "causale": "TEST con NAVVISO",
   "idTipoPendenza": "CANONE_IDRICO",
   "soggettoPagatore": {
     "tipo": "F",
     "identificativo": "SCVxxx63S29D000Z",
     "anagrafica": "FORMARO GIUSEPPE",
     "indirizzo": "VIA FRAGALA'",
     "civico": "30",
     "cap": 88000,
     "localita": "Cosenza",
     "provincia": "CS",
     "nazione": "IT",
     "email": "giuseppe.formaro@xxx.eu"
   },
   "importo": 4.00,
   "numeroAvviso": 330020210415095742,
   "dataValidita": "2022-04-30",
   "dataScadenza": "2022-04-30",
   "annoRiferimento": 2021,
   "cartellaPagamento": "202103291218",
   "datiAllegati": {},
   "tassonomia": "9/0101101IM/",
   "tassonomiaAvviso": "Imposte e tasse",
   "voci":[
   	{
   		"idVocePendenza":"TARI",
   		"importo":3.0,
   		"descrizione":"Importo TARI",
   		"ibanAccredito":"IT41Q076010440000000000000000",
   		"tipoContabilita":"ALTRO",
   		"codiceContabilita":"0101101IM/"
   	},
   	{
   		"idVocePendenza":"TEFA",
   		"importo":1.0,
   		"descrizione":"Importo TEFA",
   		"idDominio":"91006950793",
   		"ibanAccredito":"IT41Q076010440000000000000000",
   		"tipoContabilita":"ALTRO",
   		"codiceContabilita":"0201102IM/"
   	}
   ]
}
```

Questa la response:
`curl -X PUT "https://xxx/govpay/backend/api/pendenze/rs/basic/v2/pendenze/A2A_TEST/00297910000_330020210415095742?stampaAvviso=false" -H "accept: application/json" -H "Authorization: Basic QTJBX1RFU1Q6U2ludGF4JjIwMjE0=" -H "Content-Type: application/json" -d "{\"idDominio\":\"00297910000\",\"idUnitaOperativa\":\"CU3\",\"causale\":\"TEST con NAVVISO\",\"idTipoPendenza\":\"CANONE_IDRICO\",\"soggettoPagatore\":{\"tipo\":\"F\",\"identificativo\":\"SCVxxx63S29D000Z\",\"anagrafica\":\"FORMARO GIUSEPPE\",\"indirizzo\":\"VIA FRAGALA'\",\"civico\":\"30\",\"cap\":88000,\"localita\":\"Cosenza\",\"provincia\":\"CS\",\"nazione\":\"IT\",\"email\":\"giuseppe.formaro@xxx.eu\"},\"importo\":4,\"numeroAvviso\":330020210415095740,\"dataValidita\":\"2022-04-30\",\"dataScadenza\":\"2022-04-30\",\"annoRiferimento\":2021,\"cartellaPagamento\":\"202103291218\",\"datiAllegati\":{},\"tassonomia\":\"9/0101101IM/\",\"tassonomiaAvviso\":\"Imposte e tasse\",\"voci\":[{\"idVocePendenza\":\"TARI\",\"importo\":3,\"descrizione\":\"Importo TARI\",\"ibanAccredito\":\"IT41Q076010440000000000000000\",\"tipoContabilita\":\"ALTRO\",\"codiceContabilita\":\"0101101IM/\"},{\"idVocePendenza\":\"TEFA\",\"importo\":1,\"descrizione\":\"Importo TEFA\",\"idDominio\":\"91006950793\",\"ibanAccredito\":\"IT41Q076010440000000000000000\",\"tipoContabilita\":\"ALTRO\",\"codiceContabilita\":\"0201102IM/\"}]}"`

**Comment by nardil** [comment]
La `curl` riportata indica un payload diverso da quello indicato precedentemente, in particolare il NAV e' diverso nei due tracciati:

**Comment by nardil** [comment]
inoltre non hai riportato la response

**Comment by giuseppeformaro** [comment]
> La `curl` riportata indica un payload diverso da quello indicato precedentemente, in particolare il NAV e' diverso nei due tracciati:

Il problema è proprio questo penso. Io gli passo 330020210415095742 ma nella curl vedo 330020210415095740.

Ecco il log:
```
<d2a04278-0a5d-4399-8d1e-1d953cebdece> 
Type:REQUEST_IN 
Content-Type:application/json 
------ Header ------
Cookie=JSESSIONID=_GqInxxHzlqkTvu_9FKdKAZA8-NJbQEz88RFaeO0.asgpval02; _ga_TNFRGTPR2X=GS1.1.1641890834.9.0.1641890834.0; GovPay_Dashboard_Rifiutati=2022-02-17T19:25:52; _ga=GA1.1.1533636119.1588236762; _ga_3PNES26FWT=GS1.1.1647251175.21
5.1.1647252081.0; GovPay_Dashboard_Sospesi=2022-03-21T12:53:01; route=e09d33b96aec6f675e35e409b422f016
Origin=https://xxx
Accept=application/json
Referer=https://xxx/govpay/backend/api/pendenze/
User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Sec-Fetch-Dest=empty
Sec-Fetch-Site=same-origin
Host=gestel-pay-test.sintaxinformatica.it
Sec-Fetch-Mode=cors
Authorization=Basic QTJBX1RFU1Q6U2ludGF4JjIwMjE0=
sec-ch-ua=" Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"
sec-ch-ua-mobile=?0
sec-ch-ua-platform="Windows"
X-Forwarded-For=109.116.82.xxx
connection=close
content-type=application/json
Accept-Language=it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
Content-Length=976
X-Real-IP=109.116.82.xxx
accept-encoding=gzip, deflate, br
------ Content ------
Size:976
{"idDominio":"00297910000","idUnitaOperativa":"CU3","causale":"TEST con NAVVISO","idTipoPendenza":"CANONE_IDRICO","soggettoPagatore":{"tipo":"F","identificativo":"SCVxxx63S29D000Z","anagrafica":"FORMARO GIUSEPPE","indirizzo":"VIA FRAGALA'","civico":"30","cap":88000,"localita":"Cosenza","provincia":"CS","nazione":"IT","email":"giuseppe.formaro@xxx.eu"},"importo":4,"numeroAvviso":330020210415095740,"dataValidita":"2022-04-30","dataScadenza":"2022-04-30","annoRiferimento":2021,"cartellaPagamento":"202103291218","datiAllegati":{},"tassonomia":"9/0101101IM/","tassonomiaAvviso":"Imposte e tasse","voci":[{"idVocePendenza":"TARI","importo":3,"descrizione":"Importo TARI","ibanAccredito":"IT41Q076010440000000000000000","tipoContabilita":"ALTRO","codiceContabilita":"0101101IM/"},{"idVocePendenza":"TEFA","importo":1,"descrizione":"Importo TEFA","idDominio":"91006950793","ibanAccredito":"IT41Q076010440000000000000000","tipoContabilita":"ALTRO","codiceContabilita":"0201102IM/"}]}

 
 
<d2a04278-0a5d-4399-8d1e-1d953cebdece> 
Type:RESPONSE_OUT 
Content-Type:application/json 
------ Header ------
X-Govpay-IdTransazione=d2a04278-0a5d-4399-8d1e-1d953cebdece
Date=Wed, 23 Mar 2022 12:06:18 GMT
Content-Type=application/json
------ Content ------
Size:105
{"idDominio":"00297910000","numeroAvviso":"330020210415095740","UUID":"525071d9eee749d99f593be5b80e15f1"}
```

**Comment by nardil** [comment]
Quindi il servizio GovPay funziona correttamente, hai solo un problema di input con `cURL`, ho capito male?

**Comment by nardil** [comment]
Perfetto, consideriamo la segnalazione chiusa.
