### ISSUE TITLE
Errore nella verifica autorizzazioni al servizio Incassi

### ISSUE THREAD

**Issue by ivan86to** [link-it/GovPay#45]
Ciao, 
stiamo testando il servizio REST degli incassi. Abbiamo riscontrato un problema in fase di recupero del dettaglio di un incasso richiamando l'URL /govpay/rs/v1/incassi/{trn} 

L'applicazione chiamante è configurata per operare su tutti i domini censiti sul sistema e ho visto che sulla tabella ACL il campo id_dominio è NULL. 

Il servizio va in errore e abbiamo notato che in questo punto -> https://github.com/link-it/GovPay/blob/3221cffaea9b1574d363f01bf961f24daccb8487/govpay-core/src/main/java/it/govpay/core/business/Incassi.java#L329

(riporto parte del metodo per comodità)
public LeggiIncassoDTOResponse leggiIncasso(LeggiIncassoDTO leggiIncassoDTO) ... {
		IncassiBD incassiBD = new IncassiBD(this);
		try {
			[.......]
			**Set<String> domini = AclEngine.getDominiAutorizzati(applicazione, Servizio.INCASSI);**
// In questo punto si rompe perchè domini è uguale a NULL , io ho sostituito temporaneamente con 
// if(domini != null && !domini.contains(incasso.getCodDominio())) { // sperando che sia corretto 
// in questo modo se domini è NULL vuol dire che l'applicazione ha accesso a tutti i domini, o sbaglio? 
			if(!domini.contains(incasso.getCodDominio())) {
				throw new NotAuthorizedException();
			}
			LeggiIncassoDTOResponse response = new LeggiIncassoDTOResponse();
			response.setIncasso(incasso);
			return response;
		} catch (NotFoundException e) {
			return null;
		}
	}

Grazie!

**Comment by nardil** [comment]
Ciao @ivan86to ,
si, l'istruzione da te indicata deve essere corretta come segue:
`if(domini != null && !domini.contains(incasso.getCodDominio())) { ... }`
puoi fare una verifica ed eventualmente un pull request del fix?

**Comment by ivan86to** [comment]
Certamente, stiamo effettuando dei test, sembra essere ok a parte il fatto che abbiamo degli errori 405. Risolviamo questi e faccio una pull. 

grazie!

**Comment by ivan86to** [comment]
Fatto, spero di aver fatto tutto correttamente!

**Comment by nardil** [comment]
Perfetto, grazie
