### ISSUE TITLE
Interrogazione servizi IO con CF non compatibili

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#451]
**Descrizione del Bug**
Il servizio di avvisatura del backend IO prevede la seguente sintassi per il codice fiscale: `[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]` 

I codici fiscali non conformi vengono rigettati per errore sintattico.

**Risultato atteso:**
Il servizio deve essere interrovato convertendo in uppercase l'identificativo del soggetto, verificando preventivamente se rispetta la sintassi dei servizi IO evitando la chiamata in caso contrario ed emettendo opportuno evento di FAIL.

**Comment by pintorig** [comment]
Prima dell'interrogazione dei servizi IO e' presente la validazione dell'identificativo del soggetto secondo il pattern indicato.
