### ISSUE TITLE
cruscotto di backoffice: impossibilità inserimento tipo pendenza su inserimento nuova pendenza (govpay versione 3.2.2.) 

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#454]
buongiorno 

sulla funzione inserimento  pendenza non viene popolata la lista per l'inserimento del tipo pendenza (I tipi pendenze dovrebbero essere correttamente configurate, in quanto è comunque possibile inserire la pendenza tramite API)

Grazie in anticipo per il supporto

![image](https://user-images.githubusercontent.com/36847326/153209171-7554a91e-3d5e-43ac-9cf0-c4add7afb817.png)

**Comment by asterixol2000** [comment]
Buongiorno @nardil ,

ho configurato come da indicazioni, ma quando viene effettuata la pendenzaPOST prendo 400

{"categoria":"RICHIESTA","codice":"SINTASSI","descrizione":"Richiesta non valida","dettaglio":"Il campo idDominio non deve essere vuoto."}

in realtà  il campo è popolato sul form, è presente sulla query string, ma sembra che non venga poi passato sul body della POST (come del resto ancheil campo  idUnitaOperativa).
Ho fatto varie tentativi di modifica sul template ma senza successo ....hai qualche suggerimento?

![image](https://user-images.githubusercontent.com/36847326/154677334-dd568929-82a8-4a87-bb2f-a3a578551439.png)

**Comment by asterixol2000** [comment]
grazie @nardil , .

nella URL ho visto che ci sono ma  temo di non aver capito come passarli nel payload 

dato che gli altri campi definiti nel form angular di inserimento dati  messo  in configurazione,  vengono correttamente trasferiti 
![image](https://user-images.githubusercontent.com/36847326/154687578-1b00dea1-d3a7-4d85-8883-77febb2e575c.png)

devo aggiungere un file di trasformazione freemaker ?

**Comment by nardil** [comment]
Nell'immediato si, l'implementazione lo richiede, ma come anticipato dovrebbe essere superfluo.

@pintorig : a valle della trasformazione l'istanza di `PendenzaPost` deve essere valorizzata con i dati di `idDominio`, `idTipoVersamento` e `idUnitaOperativa` fornite nella URL di richiesta, sovrascrivendo eventuali valori impostati dalla trasformazione.

**Comment by asterixol2000** [comment]
Ok grazie ancora per il supporto . Saluti
