### ISSUE TITLE
Aggiornamento versione

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#456]
Buongiorno,
per passare dalla 3.4.0 alla 3.4.4 occorre prima aggiornare alla 3.4.2 ?
Posso dalla 3.4.0 passare alla 3.4.4 aggiornando solo il deploy del nuovo ear ? oppure occorre eseguire patch sql ?

Grazie.

**Comment by nardil** [comment]
Ciao @giuseppelab ,
puoi seguire le istruzioni del manuale: https://govpay.readthedocs.io/it/latest/installazione/aggiornamento/index.html
