### ISSUE TITLE
Rimuovere dicituda "Per informazioni" dall'avviso

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#457]
**Necessità:**
La dicitura "Per infomrazioni" nei dati dell'EC  è cablata nell'avviso , ma non è prevista dallo standard pagoPA. Va rimossa.

![Schermata da 2022-02-11 17-10-46](https://user-images.githubusercontent.com/12340738/153627009-a40a29b7-a466-4bda-ae13-fe8d89b66c6b.png)

**Comment by pintorig** [comment]
Ricevute modifiche ai template e riportate nel branch utilizzato nel task #480.
