### ISSUE TITLE
Govpay autenticazione

### ISSUE THREAD

**Issue by francoricci** [link-it/govpay#459]
Sapienza è sul nodo PagoPa in modalità diretta utilizzando dei microservizi sviluppati internamente.
Da poco abbiamo scoperto l’esistenza della vostra applicazione e ci piacerebbe capire se possiamo utilizzarla nei nostri ambienti di produzione e sviluppo.

Abbiamo installato il pacchetto EAR su un WIldfly 18 standalone come da indicazione e sembra funzionare.
La prima  necessità è capire se possiamo rimuovere completamente tutti i tipi di autenticazione sia verso il nodo PagoPA che verso il Backend (API Rest).
I nostri ambienti implementano già sistemi di terminazione SSL e autenticazione centralizzati e vorremmo mantenere questa architettura.
La seconda necessità è capire se fosse possibile installare il pacchetto EAR su un WIldfly domain: abbiamo provato in diversi modi ma senza successo.

**Comment by nardil** [comment]
Ciao @francoricci ,

> La prima necessità è capire se possiamo rimuovere completamente tutti i tipi di autenticazione sia verso il nodo PagoPA che verso il Backend (API Rest).

L'identificazione del chiamante e' necessaria per le operazioni di autorizzazione interni all'applicazione, ma non e' necessario che sia tramite SSL. E' possibile configurarne altre tra quelle supportate (basic, header...)

Solitamente in questi contesti chiediamo di configurare l'applicativo che termina la sessione SSL in modo che propaghi via header HTTP le informazioni del certificato client e configuriamo lato govpay l'autenticazione `SSL-HEADER`

https://govpay.readthedocs.io/it/latest/integrazione/api/autenticazione/index.html#integrazione-autenticazione

> La seconda necessità è capire se fosse possibile installare il pacchetto EAR su un WIldfly domain: abbiamo provato in diversi modi ma senza successo.

Si, non ci risultano dipendenze tra il tipo di installazione e l'EAR.

**Comment by francoricci** [comment]
L'intero ciclo di autenticazione ed autorizzaizone è gestito a livello centrale: lo IAM intercetta le chiamate e verifica il contesto di autenticazione e autorizzazione.
Oltre a questo, non utilizzanado la porta di dominio ma lavoarndo su rete GARR, il nodo PagoPA si aspetta che le chiamate arrivino da un preciso IP/Host. Il proxy non fa solo da terminatore SSL ma anche da bastion-host permettendo ai vari nodi applicativi del nostro PagoPA di accedere ai servizi del nodo in modo trasparente. 
Anche le credenziali SSL sono gegstite a livello centrale.

Quindi è importante capire se tramite i file di configurazione di Spring, sia possibile rimuovere completamente le autenticazioni ed autorizzazioni delle API.

Per WildFly domain, abbiamo provato ma, poiché il deploy è diverso e non è possibile fare la copia del'EAR e poi riavviare i nodi, non siamo riusciti a fare il deploy per problemi di dipendenze. 
Siete riusciti a deploiare su Wildfly 18 domain?

**Comment by nardil** [comment]
>L'intero ciclo di autenticazione ed autorizzaizone è gestito a livello centrale: lo IAM intercetta le chiamate e verifica il contesto di autenticazione e autorizzazione.

GovPay deve conoscere l'identità del richiedente per le proprie logiche di autorizzazione. Dando per scontato che l'IAM propaghi l'identità del chiamante, e' sufficiente configurare Spring security affinché individui nella richiesta tale identificativo (CN del certificato, client-id del token, username, qualunque esso sia) come principal dell'utente.
