### ISSUE TITLE
Problema connettore per invio pagamenti in versione 3.5

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#462]
**Descrizione del Bug**
L'introduzione degli altri tipi di connettori ha introdotto regressione su tipo GovPay. In particolare, la modalità di consegna email non funziona con aggiornamento di versione perchè non risulta selezionata ne "Invia tracciato come allegato" ne una Base URL pre configurata che consente di continuare a far funzionare la modalità.

Inoltre, anche scegliendo per risolvere "Invia tracciato come allegato" si aspetta una base uRL mostrando l'errore:
"Richiesta non valida: Il campo downloadBaseUrl non deve essere vuoto."

**Comment by pintorig** [comment]
Ciao @giuseppeformaro, 

> **Descrizione del Bug** L'introduzione degli altri tipi di connettori ha introdotto regressione su tipo GovPay. In particolare, la modalità di consegna email non funziona con aggiornamento di versione perchè non risulta selezionata ne "Invia tracciato come allegato" ne una Base URL pre configurata che consente di continuare a far funzionare la modalità.

mi puoi dire la versione di partenza e quella su cui hai riscontrato il bug?
 
> Inoltre, anche scegliendo per risolvere "Invia tracciato come allegato" si aspetta una base uRL mostrando l'errore: "Richiesta non valida: Il campo downloadBaseUrl non deve essere vuoto."

potresti provare a svuotare la cache del browser per vedere se il problema lato console si risolve?

**Comment by giuseppeformaro** [comment]
Ciao @pintorig,
svuotando la cache non ho più i problemi.

Scusa per la segnalazione errata.
