### ISSUE TITLE
problemi con configurazione mail 

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#463]
Salve,

versione GOVPAY: 3.3.3
ambiente: TEST

ho avuto la necessità di utilizzare l'utilità di GOVPAY nel notificare via mail al soggetto debitore, il pagamento e la ricevuta di pagamento.

1) Ho impostato sul menù "Impostazioni->comunicazione mail->mail server" l'host, porta, utenza, passoword, mail mittente e abilitato l'allegato PDF per la notifica di pagamento e la ricevuta di pagamento nelle rispettive sezioni.

2) ho abilitato sul menù "tipo pendenza-> libera" la notifica al pagamento e alla ricevuta via mail.

Pago correttamente la pendenza, ricevento la mail da PAGOPA ma non quella da GOVPAY con la ricevuta.

Verifico sui LOG impostati a DEBUG se c'è qualche segnalazione ma non c'è traccia della parola "mail" in nessuna parte, ne eccezioni che lasciano pensare a qualcosa sull'invio di mail.

Cos'altro va fatto per abilitare questo servizio?

Ho verificato che dal server govpay si raggiunge correttamente L'host del mail server con la porta 587

Grazie del supporto

**Comment by pintorig** [comment]
Salve @mallomix,

Non trovi la parola mail nei log perche' nel sistema si parla di `promemoria`, prova a cercare i seguenti messaggi stampati dal batch di spedizione:
```
Nessun promemoria da inviare. 
Trovati [N] promemoria da spedire
Spedizione promemoria completata.
Spedizione promemoria disabilitata.
```

In particolare quest'ultimo messaggio viene stampato se la configurazione del mail server risulta disabilitata, controlla di aver abilitato il mail server che hai configurato.

Dovresti effettuare il reset della cache per fare in modo che il batch acceda alla configurazione aggiornata del MailServer e del Tipo Pendenza.

Se non trovi nessuno dei messaggi indicati sopra controlla se i batch sono abilitati (di default lo sono), lo puoi fare controllando il valore della proprieta' `it.govpay.batchOn` all'interno del file `govpay_boot.log`.

Infine puoi controllare se il campo email del debitore o del versante della pendenza e' valorizzato, altrimenti la spedizione del promemoria non viene schedulata

**Comment by mallomix** [comment]
Grazie pintorig per il supporto.

Allora: 
1) properties it.govpay.batchOn = true
2) nei log di govpay trovo solo "gestione promemoria completata". Nessuno degli altri messaggi che mi hai indicato

nella sezione impostazioni della dashboard di govpay ho ABILITATO e configurato il mail server, e ABILITATO la spedizione delle mail per pagamento e ricevuta.
Non trovo sui firewall e sul mail server nessun tentativo di spedizione.

Cosa mi manca? :)

**Comment by pintorig** [comment]
@mallomix

prova a controllare i log che il batch di spedizione stampa ogni minuto:

```
Execuzione task [SpedizionePromemoria] ...
Execuzione task [SpedizionePromemoria] completata con successo
```

Hai fatto il reset della cache?
Il campo email del debitore della pendenza e' valorizzato?

**Comment by mallomix** [comment]
Si pintorig ho controllato tutto!

con la versione govpay 3.3.3 non invia nulla mentre con la 3.4.2 invia! Quindi ci potrebbe essere un problema delle vecchie versioni di govpay.

**Comment by nardil** [comment]
> con la 3.4.2 invia

Direi quindi che possiamo ritenere la issue risolta: e' necessario installare una versione più recente.

**Comment by mallomix** [comment]
YES... dalla 3.4.2 no problem
