### ISSUE TITLE
API pagamento: Acquisizione della ricevuta di pagamento ANONIMO

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#464]
Ciao,
ho un dubbio su come utilizzare le API pagamento per richiedere le RT di pagamenti ANONIMI. Infatti, per questi pagamenti (e per quelli eseguiti da PSP) quando provo a invocare le API passandogli IdDominio, iuv, ccp ricevo:

```
 "codice": "403000",
"dettaglio": "Applicazione [xxx] non autorizzata ad accedere alla risorsa richiesta: la transazione riferisce un pagamento che non appartiene all'applicazione chiamante."
```

Mentre tutto funziona correttamente se sono pagamenti eseguiti con API pagamento dove gli ho passato A2A=xxx.

Manca qualche configurazione oppure è un comportamento corretto?

Grazie

**Comment by nardil** [comment]
Ciao Giuseppe,

è corretto, poichè le API Pagamento danno visibilità ai soli pagamenti avviati dall'utenza chiamante:

https://govpay.readthedocs.io/it/latest/integrazione/api/autorizzazione/index.html

Puoi accedere eventualmente a quelle informazioni con le API Pendenze (se l'applicazione chiamante è titolare della pendenza) o con le API Ragioneria

**Comment by giuseppeformaro** [comment]
Perfetto!

Grazie mille.
