### ISSUE TITLE
it.nota_rata_unica  

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#475]
sul pdf dell'avviso che viene generato (versione 3.4.2 ) non viene visualizzata la nota  
it.nota_rata_unica=Puoi pagare l\u2019importo a partire dal giorno {0}.

è necessario riportare avvisi.properties nella directory  /etc/govpay/  ?
grazie per il supportol

**Comment by nardil** [comment]
Puoi condividere il tracciato di caricamento di pendenza che realizza la problematica?

**Comment by asterixol2000** [comment]
la pendenza è stata creata con questo servizio 

/govpay/backend/api/pendenze/rs/basic/v2/pendenze/A2A_0005/A55/?stampaAvviso=true&avvisaturaDigitale=true

{
  "idTipoPendenza": "abcdef12345",
  "idDominio": 97830880585,
  "idUnitaOperativa": "UO33132",
  "causale": "Servizi vari",
  "soggettoPagatore": {
    "tipo": "F",
    "identificativo": "RSSMRA30A01H501I",
    "anagrafica": "Mario Rossi",
    "email": "paolo.rossi@rmnet.it"
  },

  "importo": 1.4,
  "tassonomia": "Test modello 3",
  "tassonomiaAvviso": "Imposte e tasse",
  "direzione": "Direzione",
  "divisione": "Divisione",
    "documento": {
    "identificativo": "test-005",
    "descrizione": "servizi vari"
        },
  "dataValidita": "2022-03-31",
  "dataScadenza": "2022-12-31",
  "annoRiferimento": 2022,
  "datiAllegati": {},
  "voci": [
  { 
   "idVocePendenza" : "A55",
   "importo": 1.4,
   "descrizione" : "servizi vari",
   "ibanAccredito": "IT79V0306905020100000046110",
   "tipoContabilita": "SIOPE",
   "codiceContabilita": 3321
    }
    
  ]
}

**Comment by nardil** [comment]
@pintorig Puoi confermare che la sezione delle informazioni sia disponibile solo nel modello di stampa  bilingue?

In tal caso @asterixol2000 dovresti indicare la seconda lingua in modo che venga utilizzato quel template:

https://govpay.readthedocs.io/it/latest/howto/bilinguismo.html

**Comment by asterixol2000** [comment]
@nardil , ho fatto una prova con la seconda lingua come suggerito,
e come anticipato appare la sezione delle informazioni, ma è corretto che non compaia la data dopo la dicitura "Rata UNICA entro il" ?
![image](https://user-images.githubusercontent.com/36847326/158983340-481fd62c-2e9e-4439-9451-777a9c8b13a8.png)

**Comment by nardil** [comment]
No... non e' corretto. Dalla grafica direi che la data non e' entrata nello spazio a disposizione. 

Puoi darne conferma riducendo il testo nel file delle traduzioni?

**Comment by asterixol2000** [comment]
corretto cambiando lingua compare....domanda, ma come workaround per far apparire la sezione informazioni su avviso solo italiano, posso pensare di aggiungere una sezione di traduzione che passa spazi nei campi nel file avvisi.properties  ? 
![image](https://user-images.githubusercontent.com/36847326/159000674-2d5bf69b-cc5a-42e2-ae69-e79e95f0133f.png)

**Comment by nardil** [comment]
Si. Tieni presente che i layout sono diversi: non esiste ad esempio un template pagoPA per la pagina con 3 rate nella versione bilingue.

**Comment by asterixol2000** [comment]
ok @nardil grazie per il supporto . Saluti
