### ISSUE TITLE
Importo zero su dettaglio pagamento per pendenze multibeneficiario

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#476]
**Descrizione del Bug**
Se si visualizza un pagamento di una pendenza che contiene più beneficiari l'importo mostrato è 0 come da [allegato.]([url](url))
![pagamento](https://user-images.githubusercontent.com/72001866/159015943-1e2a3f2d-7e14-489a-bd6f-8907a25e02f5.JPG)

**Come riprodurlo:**
Eseguendo un pagamento con più beneficiari.

**Risultato atteso:**
Visualizzazione importo realmente pagato.

**Ambiente:**
 - GovPay: 3.5.1

**Note aggiuntive:**
Nel caso di una sola voce in pendenza tutto è visualizzato correttamente.

**Comment by nardil** [comment]
Ciao @giuseppeformaro ,
 
errore nel file di patch che non tiene conto di essere eseguito piu' volte.

@pintorig : 
correggere la patch 3.5.sql modificando la seguente istruzione:
```sql

-- ERRATA
UPDATE rpt SET versione = 'SANP_230';
-- CORRETTA
UPDATE rpt SET versione = 'SANP_230' WHERE versione is null;
```

@giuseppeformaro Per correggere puoi eseguire questa istruzione su DB

```sql
update rpt set versione='SANP_240' where encode(xml_rpt,'escape') not like '<RPT%';
```

Ci sono comunque degli errori di visualizzazione nel cruscotto gia' segnalati in #466 . Aggiungi li eventuali altre anomalie che potresti rilevare.

**Comment by pintorig** [comment]
Patch corretta in [e743a57](https://github.com/link-it/govpay/commit/e743a57e2fb78a1ed68f2ba2bcaea1391a8deb1a)
