### ISSUE TITLE
Errori nello script di creazione db mysql gov_pay.sql 

### ISSUE THREAD

**Issue by tizianatinnirello** [link-it/govpay#478]
**Ambiente:**
 - OS: RockyLinux 8.4
 - Browser: -
 - GovPay: 3.5.0]
 - AS: WildFly 18.0.1
 - Java: OpenJDK 1.8.0_201
 - DBMS: MariaDB 10.5

Riga 815 correggere Versione dell'api con Versione dell\'api
Dopo la riga 1539 aggiungere una nuova riga     eventi.severita,

**Comment by pintorig** [comment]
@tizianatinnirello ho corretto le segnalazioni, commit b06ba86.
