### ISSUE TITLE
Avvisi 3.0.0 - Rata unica

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#480]
**Necessità:**
Adeguamento ai template di stampa secondo quanto indicato nella nuova specifica pagoPA (https://docs.pagopa.it/avviso-pagamento/) 

**Soluzione**

@simo-git : e' necessario rivedere/gestire i seguenti template

- [ ] [Avviso rata unica con e senza bollettino](https://www.figma.com/file/Zbjx4y41nNvS4qjFzheH0U?node-id=0:1)
- [ ] Avviso con rata unica con due o tre rate senza bollettino postale
- [ ] [Avviso due o tre rate con bollettino](https://www.figma.com/file/Ld9X9iJkMztmW3JuhENgjm?node-id=0:1) 
- [ ] Avviso con rate senza bollettino, una o due linee, due rate per linea 
- [ ] Avviso con rate senza bollettino, una o due linee, tre rate per linea 
- [ ] [Avviso con rate senza bollettino, tre linee, tre rate per linea](https://www.figma.com/file/CtqIoS6ZTATNxFJtcARhbQ?node-id=0:1) 
- [ ] [Avviso per violazione CDS](https://www.figma.com/file/os2kysGJOwD5GwyZIRsG5O?node-id=0:1)

L'analisi del bollettino con rata unica ha evidenziato queste differenze rispetto alla versione precedente:

- Sostituire logo pagoPA con la versione blu
- Correggere il titolo della sezione "Destinatario Avviso" in "Destinatario"
- Rimuovere la dicitura "Cod. Fiscale" dal titolo della sezione destinatario
- Allineare a destra i codici fiscali di creditore e destinatario
- Correggere la dicitura "Lista dei canali di pagamento su www.pagopa.gov.it" in "Vai su pagopa.gov.it" nella sezione "dove pagare"
- Rivedere l'organizzazione di importo e scadenza
- Prevedere la "Info" di variazione di importo e quella di rateizzazione nel caso di presenza anche di rate
- Sostituire la dicitura "Banche e altri canali" con "Dati per il pagamento"
- Correggere il font di "Rata unica entro il ...."
- Riorganizzare le informazioni del pagamento

**Comment by nardil** [comment]
@pintorig 

I caso d'uso da verificare per le stampe senza bollettino postale sono:

- [ ] Rata unica
- [ ] Stampa rata unica + 2 rate
- [ ] Stampa rata unica + 3 rate
- [ ] Stampa rata unica + 4 rate (2 + 2)
- [ ] Stampa rata unica + 5 rate (3 + 2)
- [ ] Stampa rata unica + 6 rate (3 + 3)
- [ ] Stampa rata unica + 7 rate (3 + 4)
- [ ] Stampa rata unica + 8 rate (2 + 6)
- [ ] Stampa rata unica + 9 rate (3 + 6)
- [ ] Stampa rata unica + 10 rate (3 + 7)
- [ ] Stampa rata unica + 11 rate (3 + 8)
- [ ] Stampa rata unica + 12 rate (3 + 9)
- [ ] Stampa rata unica + 13+ rate (come da 4 rate, con una pagina da 9 piena)
- [ ] Tutti i precedenti senza rata unica

**Comment by pintorig** [comment]
Riportate modifiche in 3.6.x per il rilascio in 3.6.3
