### ISSUE TITLE
Inserimento pendenza Multi Beneficiario con codEntrata

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#481]
**Descrizione del Bug**
Da API: le pendenze inserite esplicitando Entrata vanno a buonfine, mentre ci sono problemi per le pendenze inserite tramite RiferimentoEntrata su un ente non intermediato.

Restituisce:
"dettaglio": "Tributo (TEFA) inesistente per il dominio (01907990012)"
ma per enti non intermediati non è possibile configurare un entrata.

**Come riprodurlo:**
Eseguire un inserimento di una pendenza (TEFA non è configurato come tipo entrata perche non lo permette):
...
"codEntrata":"TEFA"
...

**Ambiente:**
 - GovPay: 351

**Comment by nardil** [comment]
CIao @giuseppeformaro ,

come hai evidenziato non e' supportata la possibilita' di utilizzare il riferimento entrata per gli enti non intermediati. Credo che la mancanza sia dovuta unicamente alla console che non ne consente il censimento.

@pintorig : verificare che le API di Backoffice consentano il censimento delle Entrate anche per gli Enti non intermediati e aggiungere alla TestSuite la casistica oggetto della Issue

@atatarelli : aggiungere alla configurazione di un Ente Creditore non intermediato la sezione delle Entrate

**Comment by giuseppeformaro** [comment]
Buondi, se puo essere di aiuto, anche da API è bloccato l'inserimento su un Dominio non intermediato:
`"dettaglio": "La risorsa richiesta non e' disponibile per il dominio 01907990012 non intermediato."`

**Comment by nardil** [comment]
Ciao Giuseppe,

le modifiche sono state completate e puoi provare ad installare la versione dal branch 3.5.x in attesa del rilascio

**Comment by giuseppeformaro** [comment]
Buondi,
scusami mi indichi da dove scaricarlo? Vedo le ultime modifiche al 05apr sul 3.5.x o sbaglio?

Grazie

**Comment by nardil** [comment]
Non sbagli. Puoi compilare i sorgenti oppure scaricare l'installer da Jenkins 

https://jenkins.link.it/govpay/blue/organizations/jenkins/govpay/activity?branch=3.5.x

**Comment by giuseppeformaro** [comment]
Buondi, ok adesso riesco a definire un tipo entrata anche su un Ente non intermediato!

Grazie
