### ISSUE TITLE
Stampa Autorizzazione PT su Avviso di pagamento sezione bollettino postale

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#483]
Buongiorno ,
ho impostato il codice di autorizzazione PT sia a livello di EC che sul singolo CC postale.
La sezione bollettino è correttamente popolata  tranne  per il codice di autorizzazione PT che non compare.
La versione che utilizzo è la 3.4.0 è un bug o sbaglio qualcosa in configurazione?

Grazie per il consueto supporto

**Comment by asterixol2000** [comment]
ora l'autorizzazione compare

**Comment by frdidonato** [comment]
Salve, gentilmente si potrebbe capire come è stato risolto ? ho la versione 3.6.4 di GovPay e nonostante abbia messo il numero di autorizzazione sia sull'EC sia sul conto corrente Postale (Chekkato come Postale), nell'avviso in PDF non vedo la sezione relativa al numero di autorizzazione nel bollettino.
