### ISSUE TITLE
Problema IUR su ricerca Dettaglio di una riscossione

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#484]
**Descrizione del Bug**
Per i pagamenti su stazione in VERSIONE 2,  dalla ricerca in /riscossioni/{idDominio}/{iuv}/{iur}/{indice} ricevo:
"descrizione": "Risorsa non trovata"
usando come IUR il valore ricevuto nel flusso di rendicontazione.

Se puo essere di aiuto: la ricerca va a buon fine se gli passo il valore del CCP nel campo IUR (ed infatti nel DB in pagamenti.iur ho per i pagamenti multibeneficiario il lavore del CCP e non dello IUR).

**Risultato atteso:**
Cosi come su pagamenti con la stazione VERSIONE 1, il servizio dovrebbe restituire i dettagli della riscossione.

**Ambiente:**
 - GovPay: 3.5.1

**Comment by nardil** [comment]
Ciao @giuseppeformaro , 

il problema non mi sembra di GovPay, ma del PSP/pagoPA. Ho anche io verificato che il campo `identificativoUnivocoRiscossione` che arriva nel Flusso di Rendicontazione non risulta corrispondere al `receiptId` della ricevuta.

https://docs.italia.it/italia/pagopa/pagopa-specifichepagamenti-docs/it/v2.5.1/sezione3-specifiche-tecniche/3_04_00_rendicontazione_e_accredito.html

Provvediamo a chiedere un chiariumento a pagoPA.

**Comment by nardil** [comment]
Scusa @giuseppeformaro , contrariamente a quanto anticipato non ho casistiche da verificare.

Per avere conferma dello scenario dovresti condividere la ricevuta (svuotata dei dati sensibili) ed il flusso di rendicontazione, in modo da verificare se effettivamente si tratta di una violazione della specifica da segnalare a pagoPA.

**Comment by nardil** [comment]
Buongiorno @giuseppeformaro , 

abbiamo avuto modo di verificare i primi pagamenti multibeneficiario in ambiente di produzione ed al momento non abbiamo riscontrato la casistica da te rilevata. Se puoi condividere le informazioni su RT e rendicontazione, possiamo verififcare se effettivamente si tratta di un errore del PSP

**Comment by giuseppeformaro** [comment]
Buondi,
in allegato quanto richiesto.

Buon lavoro.

[Flusso_2022-03-31BCITITMM-0000000N6N.zip](https://github.com/link-it/govpay/files/8407426/Flusso_2022-03-31BCITITMM-0000000N6N.zip)

**Comment by nardil** [comment]
Ciao @giuseppeformaro, ti confermo che il PSP (Intesa Sanpaolo) non ha compilato il flusso di rendicontazione correttamente.

Il suggerimento e' quindi di inviare le evidenze a pagoPA segnalando il problema. Il PSP dovrebbe ripubblicare il flusso di rendicontazione con i riferimenti corretti in modo da consentire la corretta riconciliazione.

**Comment by giuseppeformaro** [comment]
Grazie mille, fatto!

PS Infatti in collaudo non ho avuto questo problema con altri PSP. Provvedo a estendere le prove di pagamento reali su altri PSP.
