### ISSUE TITLE
Campi RT e RPP in Inglese per pendenze MULTIBENEFICIARIO

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#485]
Invocando le API:
govpay/backend/api/pendenze/rs/basic/v2/pendenze
se la pendenza è MULTIBENEFICIARIO i campi della rt e della rpp sono in inglese. 

Sarà sempre cosi?

**Comment by nardil** [comment]
Ciao @giuseppeformaro ,
in RPT ed RT ci sono i tracciati originali pagoPA che per la V2 ha rivisto radicalmente la sintassi in favore dell'inglese:

https://github.com/pagopa/pagopa-api/blob/develop/ec/paForNode.xsd

**Comment by nardil** [comment]
Valutiamo la possibilita' di tradurre i tracciati nel formato v1 per retrocompatibilita

**Comment by nardil** [comment]
> Valutiamo la possibilita' di tradurre i tracciati nel formato v1 per retrocompatibilita

La modifica sarebbe non retrocompatibile. Attivare quindi la v2 comporta gestire tale formato nelle integrazioni
