### ISSUE TITLE
Errore stampa RT su pagamento multibeneficiario

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#488]
**Descrizione del Bug**
Nella stampa della ricevuta c'è un errore su ID riscossione come da allegato che fa differire lo iur da quello presente nel flusso.
![Errore IUR](https://user-images.githubusercontent.com/72001866/163575480-4ad9f588-eb92-4198-bab2-c9da9d8a8e82.JPG)

**Come riprodurlo:**
Stampa di un avviso pagato multibeneficiario.

**Risultato atteso:**
Stesso ID riscossione per i due pagamenti.

**Ambiente:**
 - GovPay: 3.5.x

**Comment by nardil** [comment]
> Nella stampa della ricevuta c'è un errore su ID riscossione come da allegato che fa differire lo iur da quello presente nel flusso.

Puoi condividere la `receipt` per verificare che effettivamente ci sia un errore nell'id?

**Comment by nardil** [comment]
Come non detto, veniva erroneamente appeso l'`idTrasfert`. Correggiamo immediatamente.

**Comment by nardil** [comment]
@giuseppeformaro abbiamo effettuato il fix sulla 3.5.x. Appena Jenkins avra' completato le operazioni di verifica, potrai verificare il fix

**Comment by giuseppeformaro** [comment]
Buondi,
confermo la risoluzione.

Grazie
