### ISSUE TITLE
Servizio non disponibile su dettaglio importi TEFA multibeneficiario

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#490]
**Descrizione del Bug**
Aprendo da menu PENDENZE una pendenza di tipo multibeneficiario viene visualizzato errore: Servizio non disponibile.

Nei log:
DEBUG | it.govpay.rs.eventi.GiornaleEventiOutInterceptor:62 | 2c729c3a-1d00-4a83-9dea-4ff568b21a76 | Log Evento API: [API_BACKOFFICE] Method [GET], Url [/govpay/backend/api/backoffice/rs/form/v1/domini/xxx/entrate/TEFA], StatusCode [404]

**Come riprodurlo:**
Visualizzare i dettagli di una pendenza TARI/TEFA con tipo entrata TEFA configurato su un dominio diverso da quello dell'ente emittente.

**Ambiente:**
 - GovPay: 3.5.1

**Comment by nardil** [comment]
Ciao @giuseppeformaro ,

abbiamo provato un multibeneficiario come da te descritto, ma non si riscontra errore. Puoi riprovare da browser anonimo o svuotando la cache del browser?

![Schermata da 2022-04-21 08-31-27](https://user-images.githubusercontent.com/12340738/164389007-baa2ccb0-64e9-4bb5-86e3-e3d9e221b1c8.png)
