### ISSUE TITLE
Annullamento pendenza

### ISSUE THREAD

**Issue by ilsanto17** [link-it/govpay#491]
Buongiorno, sto cercando di annullare una pendenza, ma quando invio il payload a govpay/backend/api/pendenze/rs/basic/v2/pendenze/ida2a/idpendenza
```json
{"op":"REPLACE",
"path":"/stato",
"value":"Annullata"
}
```
ricevo il seguente errore:
```json
{
   "categoria": "RICHIESTA",
   "codice": "SINTASSI",
   "descrizione": "Richiesta non valida",
   "dettaglio": "com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token\n at [Source: (String)\"{\"op\":\"REPLACE\",\n\"path\":\"stato\",\n\"value\":\"Annullata\"\n}\"; line: 1, column: 1]"
}
```
Dove sto sbagliando?
Grazie

**Comment by nardil** [comment]
Ciao,

la `PATCH` prevede in input un array: 

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/link-it/govpay/master/wars/api-pendenze/src/main/webapp/v2/govpay-api-pendenze-v2.yaml#operation/updatePendenza

**Comment by ilsanto17** [comment]
ok, ma ottengo questo:
{
   "categoria": "RICHIESTA",
   "codice": "SINTASSI",
   "descrizione": "Richiesta non valida",
   "dettaglio": "Il campo value indicato per il path '/stato' non e' valido."
}

**Comment by nardil** [comment]
![Schermata da 2022-04-28 15-00-36](https://user-images.githubusercontent.com/12340738/165757884-4854dadd-9221-4059-b47e-c6e6d1b42c50.png)


correggi con `"value": "ANNULLATA"`

**Comment by ilsanto17** [comment]
perfetto grazie
