### ISSUE TITLE
backoffice menu riconciliazioni ver 3.5.1

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#496]
Ciao, ho aggiornato dalla 3.4.0 alla 3.5.1.
Nella gui di backoffice, sto notando che al menu Riconciliazioni, i nomi non mi ritrovo il classico SCT:XXXXXX ma per tutti i record vedo undefined

Grazie.

**Comment by giuseppelab** [comment]
Ho resettato la cache.
come posso fare il test di navigazione anonima ? se col browser ho fatto anche quell
![GP-Riconciliazioni](https://user-images.githubusercontent.com/85696987/166679854-775d2ca0-5965-4088-96e1-96c9b00a67d7.png)
o

**Comment by atatarelli** [comment]
Sembra un problema di dati non presenti. Puoi condividere la chiamata e la risposta del servizio, eventualmente mascherando le informazioni non pubbliche?

**Comment by giuseppelab** [comment]
Si, verificando in questa direzione è un problema di dati non presenti; considera che sono in collaudo per i test passerò in esercizio la prossima settimana.
Intanto chiudo l'issue.
Grazie

**Comment by nardil** [comment]
mi risulta strano che manchino i dati da visualizzare che sono obbligatori in sede di riconciliazione. 

@giuseppelab , hai comunque modo di condividere la risposta del servizio `/riconciliazioni` per capire come mai questi dati sono assenti?

**Comment by giuseppelab** [comment]
No sono ancora riuscito a recuperare la risposta.
Continuo a provare.
