### ISSUE TITLE
Reportistica Entrate Previste non disponibile nel formato richiesto

### ISSUE THREAD

**Issue by ilsanto17** [link-it/govpay#498]
Buongiorno a tutti, sto effettuando una chiamata GET (govpay/backend/api/backoffice/rs/basic/v1/reportistiche/entrate-previste?dataDa='.$data_da.'&dataA='.$data_a.'&risultatiPerPagina=500';) per avere la reportistica delle entrate previste. Se effettuo un test tramite SoapUi funziona perfettamente e risponde con il JSON.
Se la chiamo dalla mia applicazione ottengo questo errore:
{"categoria":"INTERNO","codice":"INTERNAL","descrizione":"Errore interno","dettaglio":"Reportistica Entrate Previste non disponibile nel formato richiesto"}

Come mai?

**Comment by pintorig** [comment]
Ciao @ilsanto17, che valore viene impostato nell'header 'Accept' della request?

**Comment by ilsanto17** [comment]
Nell'header setto solo  
'Content-Type:application/json',
'Authorization: Basic '.......

**Comment by ilsanto17** [comment]
Inserendolo funziona. Grazie
