### ISSUE TITLE
Nessun invio per tipo_esito RICEVUTA appIO

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#504]
**Descrizione del Bug**
A seguito dell'aggiornamento alla 3.5.1 mi sono reso conto che non inviamo più le ricevute (l'errore è il seguente):

```
The following has evaluated to null or missing:
==> rpt.getIdentificativoAttestante()  [in template "TrasformazioneMarkdownAppIO" at line 5, column 61]

Tip: If the failing expression is known to legally refer to something that's sometimes null or...
```

Vi è già capitato?

Grazie

**Comment by pintorig** [comment]
ciao @giuseppeformaro, 
puoi provare ad utilizzare questo template: [appio-body-ricevuta-freemarker.txt](https://github.com/link-it/govpay/files/8851384/appio-body-ricevuta-freemarker.txt).

Puoi caricarlo tramite la console: Impostazioni -> Comunicazione AppIO -> Notifica Ricevuta -> Template Messaggio.

![Screenshot from 2022-06-07 10-12-52](https://user-images.githubusercontent.com/12812160/172330495-1b3ca4fc-69a6-40c3-ba06-3036bcd63405.png)

Esegui il reset della cache e attendi la spedizione delle notifiche.

**Comment by giuseppeformaro** [comment]
Ciao,
confermo la risoluzione del problema con il nuovo template.

PS Solo a titolo informativo: rimane in descrizione_stato il messaggio sopra riportato.

Grazie!
