### ISSUE TITLE
POST pagamenti - 502 Bad Gateway error

### ISSUE THREAD

**Issue by alessia7** [link-it/govpay#507]
Salve,
effettuando la chiamata POST pagamenti ricevo un errore "502 Bad Gateway":
{
    "categoria": "PAGOPA",
    "codice": "PAA_NODO_INDISPONIBILE",
    "descrizione": "Servizi pagoPA non disponibili.",
    "dettaglio": "Ricevuto [HTTP 404]",
    "id": "id",
    "location": "/pagamenti/id"
}

Effettuando una GET by id del pagamento, nella sezione rpp ottengo:

"stato":  "RPT_ERRORE_INVIO_A_NODO",

Qualcuno può aiutarmi? Cosa dovrei fare?

**Comment by nardil** [comment]
Ciao @alessia7, 

l'errore `502 Bad Gateway` indica un problema nell'integrazione a servizi esterni. In questo caso specifico nella fruizione dei servizi pagoPA che nella chiamata alle API rilevano un errore `HTTP 404`.

Dal Giornale degli Eventi puoi verificare l'operazione di "Inviato carrello RPT a pagoPA" per un maggior dettaglio della URL invocata e l'errore rilevato.

Con ogni probabilità è stata configurata una URL sbagliata nella configurazione dell'intermediario.

**Comment by alessia7** [comment]
Grazie della risposta. Vedendo nel dettaglio tutte le chiamate falliscono.
![cattura_fail](https://user-images.githubusercontent.com/49901951/173860592-2bf125bb-5159-4fb4-a70c-0611d9bff0a6.png)

Nella sezione Intermediari ho un solo intermediario configurato secondo la guida messa a disposizione, quindi con i parametri:
Servizi pagoPA : 
- Principal: ndpsym
- Servizio RPT: http://127.0.0.1:8080/govpay-ndpsym/pagopa/PagamentiTelematiciRPTservice
- Autenticazione: Nessuna
e una sola stazione.

E' come se non trovasse proprio il nodo SPC o sbaglio? Io non ho configurato nessun altro intermediario come nodo SPC. Dovrei configurarne uno nella sezione Configurazioni>Intermediari del Cruscotto GovPay? Esiste una guida o documentazione a cui posso fare riferimento? Come dovrei procedere?

**Comment by nardil** [comment]
Il servizio di RPT e' esposto da pagoPA. Nel tuo caso risulta indicata la URL del Simulatore pagoPA che è parte della versione Enterprise di GovPay che presumo non sia disponibile nel tuo ambiente.

Dovresti accreditarti a pagoPA e correggere l'endpoint del servizio.

**Comment by alessia7** [comment]
Come posso ottenere il simulatore senza dover necessariamente accreditarmi a pagoPA?
