### ISSUE TITLE
Pagamenti postali in errore ibanAppoggio

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#508]
**Descrizione del Bug**
A tentativo di pagare un avviso con data matrix o su sito delle poste viene mostrato il seguente messaggio:

`CT446 - Errore tecnico in fase di verifica PAM: 0008 - T2RTMBI - IBAN BANCARIO SU QUOTA PRINCIPALE POSIZIONE FESP. Riprova più tardi o contatta il Servizio Clienti al numero 800.003.322`

**Come riprodurlo:**
Provare il pagamento di una pendenza che usa come ibanAppoggio un CC postale.

**Ambiente:**
 - GovPay: 3.5.1-SNAPSHOT

**Note aggiuntive:**
Nessun problema se IBAN postale viene usato come primo IBAN (IBAN Accredito).

Nel payload vedo: <transferType>POSTAL</transferType> ma l'IBAN che gli passo è poi quello di accredito e non quello di appoggio.

Vi risultano problemi del genere?

Grazie

**Comment by nardil** [comment]
Ciao Giuseppe,

puoi indicarci quale versione di API pagoPA e' configurata sul Portale di Adesione ed i payload dei messaggi di Attivazione della transazione?

**Comment by nardil** [comment]
Risulta un bug risolto in 2cd4730e1d4977d188974a773e266d433ac28d7c

Nei prossimi giorni eseguiremo il rilascio della nuova versione che include il patch. Eventualmente puoi installare in autonomia la versione su master e verificare che risolva il problema.
