### ISSUE TITLE
Required services that are not installed: postgres jdbc 

### ISSUE THREAD

**Issue by pdipax** [link-it/govpay#509]
Ciao a tutti, sto provando ad installare govpay in ambiente linux ubuntu 20.04.
Ho seguito per filo e per segno tutta la procedura come da documentazione usando il dbms postgresql, ma quando voglio avviare l'applicazione riscontro questo errore:

16:44:31,241 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "govpay-ds.xml")]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.jdbc-driver.org_postgresql"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.data-source.\"jboss.naming.context.java.govpay\" is missing [jboss.jdbc-driver.org_postgresql]"]
}

Ho configurato il modulo nell'Application Server nella cartella org/postgresql/main module.xml inserendo questa configurazione
<?xml version="1.0" encoding="UTF-8"?>
        <module xmlns="urn:jboss:module:1.1" name="org.postgresql">
            <resources>
                <resource-root path="postgresql-42.4.0.jar"/>
            </resources>
            <dependencies>
                <module name="javax.api"/>
                <module name="javax.transaction.api"/>
            </dependencies>
        </module>

e nella stessa cartella main ho il file .jar

inoltre nella cartella standalone/deployments ho modificato il file precedentemente copiato dalla cartella dist denominato govpay-ds.xml inserendo nel tag driver tutte queste possibilità: 1)postgresql-42.4.0.jar 2)org.postgresql 3)postgresql
ma continuo a ricevere questo errore e sia nella documentazione che nelle issue non trovo riferimenti. Ho anche provato a scaricare l'installer già compilato come qualcuno suggeriva anche se non ho avuto problemi nella compilazione ma il risultato non cambia.

uso jvm 1.8, wildfly 18.0.0

Qualcuno ha avuto le stesse difficoltà?
Grazie.

**Comment by nardil** [comment]
Ciao @pdipax ,

credo sia un errore di configurazione di wildfly: una volta predisposto il modulo, va definito il driver e riferisci il nome del driver all'interno del datasource: 

```xml
<subsystem xmlns="urn:jboss:domain:datasources:5.0">
   <datasources>
      ....
      <drivers>
         ...
         <driver name="postgresql" module="org.postgresql"/>
      </drivers>
   </datasources>
</subsystem>
```
