### ISSUE TITLE
Supportare la migrazione di stazione

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#511]
**Necessità:**
Quando si cambia stazione ad un EC, ad esempio perche' si passa da V1 a V2, attualmente e' necessario chiedere a pagoPA di migrare l'EC per non variare il codice di segregazione. Questo, oltre che poco pratico, non funziona con gli AuxDigit != 3.

E' necessario che gli avvisi emessi con le stazioni non attualmente impostate per l'EC risultino comunque pagabili anche in caso di non migrazione dell'EC.

**Soluzione:**
Nel caso di pagamento modello 1, non ci sono problemi. La transazione viene gestita dalla stazione configurata su GovPay per l'EC.

Nel caso di pagamento modello 3, e' sufficiente che, in caso di pagamento v1, nella RPT venga memorizzata la stazione con cui il pagamento e' stato attivato, in modo da proseguire nel processo di pagamento con quella stazione e non con quella configurata per l'EC.

**Comment by pintorig** [comment]
Verificato il supporto per i seguenti casi d'uso:

- Pagamento modello 3 di un avviso precaricato per un Ente Creditore a cui viene modificata la Stazione ma non l'AuxDigit
- Pagamento modello 1 di un avviso precaricato per un Ente Creditore a cui viene modificata la Stazione ma non l'AuxDigit
- Pagamento modello 3 di un avviso precaricato per un Ente Creditore a cui vengono modificati la Stazione, l'AuxDigit e il SegregationCode
- Pagamento modello 3 avviso non caricato per un Ente Creditore a cui vengono modificati la Stazione, l'AuxDigit e il SegregationCode
