### ISSUE TITLE
backend app IO

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#518]
Buongiorno, 
come posso per ottenere l'indirizzo della URL del backend app IO da inserire nelle impostazioni ? 
Grazie

**Comment by nardil** [comment]
Ciao Giuseppe, 
[dall'openAPI](https://developer.io.italia.it/openapi.html) del servizio la URL di erogazione e': https://api.io.pagopa.it/api/v1

Per ulteriori dettagli sulle modalita' di erogazione dei servizi del BackendIO dovresti chiedere al supporto AppIO
