### ISSUE TITLE
PDF avviso non conforme alle specifiche del nuovo modello

### ISSUE THREAD

**Issue by tizianatinnirello** [link-it/govpay#519]
AIUTO !!! Il download dell'avviso analogico in formato pdf, sia dal cruscotto che con le API, non mi risulta conforme alle nuove specifiche. 

Eppure [qui #475](https://github.com/link-it/govpay/issues/475) le immagini evidenziano che è stato prodotto il nuovo avviso.

Tracciati caricati con l'api /govpay/backend/api/backoffice/rs/basic/v1/pendenze/tracciati

Versione utilizzata: 3.6.1 ma anche con la 3.6.2 (jenkins) non cambia nulla.

**Comment by nardil** [comment]
Ciao Tiziana,
puoi dettagliare in cosa ti risulta non aderente alla specificala stampa, magari allegando un esempio?

**Comment by tizianatinnirello** [comment]
Ciao Lorenzo, grazie per avermi risposto subito. L’avviso di pagamento dovrebbe essere conforme a queste specifiche https://docs.pagopa.it/avviso-pagamento/allegato-1/esempi (vedi esempio rata unica); in particolare la sezione “QUANTO E QUANDO PAGARE” a me esce così:

 



  

Cordiali saluti.

 

Tiziana

 

 

Da: Lorenzo Nardi ***@***.***> 
Inviato: martedì 2 agosto 2022 09:35
A: link-it/govpay ***@***.***>
Cc: tizianatinnirello ***@***.***>; Author ***@***.***>
Oggetto: Re: [link-it/govpay] PDF avviso non conforme alle specifiche del nuovo modello (Issue #519)

 

Ciao Tiziana,
puoi dettagliare in cosa ti risulta non aderente alla specificala stampa, magari allegando un esempio?

**Comment by nardil** [comment]
@tizianatinnirello mancano gli screenshot

**Comment by tizianatinnirello** [comment]
Ok allego due jpeg il n. 1 è come dovrebbe essere, il n. 2 è come viene prodotto da govpay.

 

 

 

Da: Lorenzo Nardi ***@***.***> 
Inviato: martedì 2 agosto 2022 10:05
A: link-it/govpay ***@***.***>
Cc: tizianatinnirello ***@***.***>; Mention ***@***.***>
Oggetto: Re: [link-it/govpay] PDF avviso non conforme alle specifiche del nuovo modello (Issue #519)

 

@tizianatinnirello <https://github.com/tizianatinnirello>  mancano gli screenshot

**Comment by nardil** [comment]
Ti suggerisco di rispondere via web perché non arrivano gli screenshot rispondendo via mail

**Comment by tizianatinnirello** [comment]
La sezione “QUANTO E QUANDO PAGARE” a me esce così:
![2](https://user-images.githubusercontent.com/56389892/182332075-0c7ed3ac-3cb3-498f-afac-c95c016994ff.jpg)

mentre, come da ultime specifiche, dovrebbe essere così:
![1](https://user-images.githubusercontent.com/56389892/182332472-32cf4aa3-a97c-42ad-a1a6-623a4876b69f.jpg)

**Comment by nardil** [comment]
Ciao @tizianatinnirello , la versione 3.6.2 implementa la monografia degli Avvisi pagoPA v2.  Nel branch 3.6.x e' attualmente presente la versione allineata alla monografia degli Avvisi pagoPA v3.0.0 su cui stiamo ultimando le verifiche prima del rilascio.

Puoi eventualmente usare quella versione per avere il nuovo layout di stampa.

**Comment by tizianatinnirello** [comment]
Buongiorno, ho provato ad utilizzare la versione del branch 3.6.x nonchè quella del master presenti su [(https://jenkins.link.it/govpay/blue/organizations/jenkins/govpay/activity)](https://jenkins.link.it/govpay/blue/organizations/jenkins/govpay/activity), ho quindi sostituito il file govpay.ear (essendo un update di una minor version dovrei solo effettuare questa sostituzione), ma il risultato non cambia, c'è sempre la v2.

**Comment by pintorig** [comment]
@tizianatinnirello 
ho fatto delle prove in locale con l'ultima versione presente nel branch 3.6.x 04d53c0, ho ottenuto il risultato sperato:

![Screenshot from 2022-08-02 11-12-13](https://user-images.githubusercontent.com/12812160/182606915-0d2dc9aa-67ad-460c-9fc6-dfd89f34d582.png)

Per risolvere il tuo problema dovresti installare la versione 3.6.x e ricaricare il tracciato, a questo punto le stampe degli avvisi verranno prodotte con il layout v3.0.0.

**Comment by tizianatinnirello** [comment]
Risolto con l'ultima versione presente nel branch 3.6.x

Grazie
