### ISSUE TITLE
Supporto al caso d'uso Pagamento presso frontend dell'EC nelle SANP 3.1.0

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#520]
**Necessità:**
Modificare le API-Pagamento V2 per supportare il caso d'uso [Pagamento presso frontend dell'EC](https://docs.pagopa.it/sanp/casi-duso/pagamento-presso-frontend-dellec) previsto nelle nuove SANP 3.1.0:

Quando il front end dell'EC riceve la richiesta di pagamento di uno o più avvisi, invece di inviare il carrello di RPT, la inoltra con una [redirect](https://docs.pagopa.it/sanp/ente-creditore/modalita-dintegrazione/integrazione-touch-point-dellec-con-checkout) a Checkout, Per ogni avviso Checkout chiedera' al nodo di attivare il pagamento presso l'EC tramite l'utilizzo della primitiva pagetPayment.
Una volta completato il pagamento ogni EC ricervera' la receipt tramite la primitiva paSendRT.

**Soluzione:**
Aggiungere il supporto alla nuova operazione nelle API Pagamento V2.

La richiesta da inoltrare verso il Checkout deve avere i seguenti parametri:

- returnUrl: l'indirizzo al quale sarà reindirizzato l'utente dopo la conclusione del processo di pagamento;
- fiscalCodePA: identificativo dell'EC che ha attivato il processo di pagamento;
- lang: opzionalmente la lingua da utilizzare;
- un array degli avvisi da pagare, per ognuno dei quale è necessario:
 -- noticeNumber: numero avviso
 -- fiscalCode: codice fiscale dell'EC
 -- amount: importo
 -- agreement: eventuale codice della convenzione tra EC e PSP

Per poter creare tale richiesta l'API dovra' accettare in input una richiesta nel seguente formato:

```yaml
{
  "pendenze": [
    {
      "idDominio": "1234567890",
      "numeroAvviso": "123456789012345611"
    },
    {
      "idDominio": "1234567890",
      "numeroAvviso": "123456789012345680"
    }
    ],
   "urlRitorno": "https://www.comune.it/pagamentopagopa/abcd-efgh-ijklm-12345",
   "lingua" : "it"
}
```

- Il campo _urlRitorno_ diventa obbligatorio.
- Il campo _lingua_ opzionale viene utilizzato per valorizzare il campo _lang_.
- Il Query Parameter opzionale _codiceConvenzione_ verra' utilizzato per valorizzare il campo _agreement_.

Se la richiesta va a buon termine l'esecuzione termina con il redirect verso la URL del Checkout (Aggiungere la possibilita' di configurare la URL del Checkout).

Per decidere la procedura di pagamento da utilizzare modificare l'entita' _Stazione_ aggiungendo la proprieta' _versione_ che pilota il comportamento del sistema.
- I pagamenti avviati per le stazioni con versione = V1 mantengono il comportamento attuale.
- I pagamenti avviati per le stazioni con versione = V2 gestiranno la nuova procedura.

**Comment by pintorig** [comment]
@atatarelli 
Aggiungere la possibilita' di configurare la versione della stazione

- Nella lista delle stazioni di un intermediario visualizzare la versione impostata nella seconda riga dell'elemento:
![Screenshot from 2022-08-04 12-48-35](https://user-images.githubusercontent.com/12812160/182829352-9b7d8aa0-3ea8-4a18-8005-9056771d85a5.png)

- Nella maschera di configurazione aggiungere la select list con i valori [V1,V2] selezionabili:
![Screenshot from 2022-08-04 12-47-32](https://user-images.githubusercontent.com/12812160/182829487-9a8bfd14-9a15-4238-9be0-3b454bd45499.png)

Realizzare l'intervento nel branch [feature/520_pagamento_modello1_sanp_310](https://github.com/link-it/govpay/tree/feature/520_pagamento_modello1_sanp_310).

**Comment by pintorig** [comment]
Alla pagina [Checkout](https://docs.pagopa.it/circolare-pagopa/dettaglio-interventi/pagopa-checkout) e' possibile trovare la roadmap prevista per il nuovo componente.

**Comment by nardil** [comment]
Le specifiche sintattiche per l'invocazione delle API Checkout sono qua:

https://docs.pagopa.it/sanp/appendici/primitive#carts

**Comment by nardil** [comment]
Nella seguente issue sono indicate le URL del servizio Checkout di collaudo e produzione ed un esempio di richiesta:

https://github.com/pagopa/pagopa-api/issues/787
