### ISSUE TITLE
Truststore Location 

### ISSUE THREAD

**Issue by powerzilly** [link-it/govpay#522]
Buongiorno a tutti, 
credo di aver commesso un errore di configurazione dell'intermediario.  Quando si crea una connessione col gad.test ricevo il seguente errore : "unable to find valid certification path to requested target".
In una vecchia issue trovata qui si suggeriva di : 
"devi configurare nell'AS il keystore con la tua chiave privata (quella fornita in fase di configurazione sul portale delle adesioni) ed il trustore con il certificato di pagoPA di collaudo (dovresti avere il link per il download sempre dal portale delle adesioni)"

Ho provato a guardare sul portale delle adesioni ma non trovo i dati sopra citati. 

Qualche consiglio?

In allegato govpay.log

[govpay.log](https://github.com/link-it/govpay/files/9402439/govpay.log)

Grazie in anticipo

**Comment by powerzilly** [comment]
Ciao nardil,
grazie alle tue dritte ho risolto il problema.
Ora però mi da un 'altro tipo di errore. 

"Richiesta elenco flussi rendicontazione fallita: PPT_AUTENTICAZIONE Errore di autenticazione."

A che autenticazione fa riferimento?

**Comment by nardil** [comment]
Ciao @powerzilly ,
verifica se hai valorizzato correttamente la password della stazione confrontandola con quella assegnata dal Portale delle Adesioni, altrimenti devi far riferimento al supporto pagoPA per approfondire l'indagine e risolvere il problema.

**Comment by powerzilly** [comment]
Buongiorno @nardil ,
nel fare copia ed incolla della password si è creato uno spazio iniziale. Eliminando quello ora funziona correttamente.

Ti ringrazio per l'assistenza.
