### ISSUE TITLE
Api Frontend - Operazione non autorizzata

### ISSUE THREAD

**Issue by powerzilly** [link-it/govpay#525]
Buongiorno a tutti.
Ho un problema che non riesco a risolvere. Le api backend funzionano correttamente e le ho già integrate nell'applicazione che stò sviluppando. 
Volevo fare dei test di pagamento per testare il ciclo di lavoro dell'applicazione ma mi sono reso conto che le api frontend non mi permettono di far nulla perchè il sistema mi risponde ad ogni richiesta 

"
"categoria": "AUTORIZZAZIONE",
  "codice": "403000",
  "descrizione": "Operazione non autorizzata",
  "dettaglio": "Operatore [XXXXXX XXXXXX] non autorizzato ad accedere alla risorsa richiesta."
"

Non riesco nemmeno a recuperare l'elenco delle pendenze che genero  on le Api  backend. 
Ho provato a recuperare le informazioni del profilo utente e la risposta è stata 

"
{
  "nome": "XXXXXX",
  "domini": [],
  "entrate": [],
  "acl": []
}
"

Riconosce l'utente ma non riconosce permessi di nessun tipo. 
Sbaglio di sicuro la configurazione di qualcosa ma non ne vengo a capo da solo. Ho già provato tra le impostazioni ma sembra tutto corretto.
Qualche idea o consiglio?

Grazie.

**Comment by nardil** [comment]
Presumo che per api di Frontend tu stia parlando delle API Pagamento. Ti invito a verificare il processo di autenticazione descritto nella documentazione, perche' non e' previsto che le API Pagamento siano fruite da un operatore:

    https://govpay.readthedocs.io/it/latest/integrazione/api/autorizzazione/index.html
