### ISSUE TITLE
Performance del Batch di scadenza RPT

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#538]
**Descrizione del Bug**
Le RPT v2 sono soggette ad un batch che individua quelle scadute per timeout al fine di aggiornarne lo stato.

La query che individua le RPT da far scadere presenta le seguenti inefficienze:

1. Include le RPT gia' chiuse (aggiungere il filtro `stato <> 'RPT_SCADUTA'`)
2. Non applica un filtro temporale (aggiungere il `data_msg_richiesta > '{data ultima esecuzione del batch con successo}'`)
3. Manca l'indice sulla `data_msg_richiesta` (`create index idx_rpt_data_msg_richiesta on rpt(data_msg_richiesta);`)

**Comment by pintorig** [comment]
Il filtro temporale che viene utilizzato e' il seguente:

```
(now - (2 * soglia_scadenza_rpt)) < data_msg_richiesta < (now - soglia_scadenza_rpt)
```
