### ISSUE TITLE
Collegamento fisico di tipo GAD

### ISSUE THREAD

**Issue by ind87moving** [link-it/govpay#541]
Ciao a tutti,
sto cercando di attivare una connesione fisica di tipo GAD sul portale delle adesioni.
Abbiamo correttamente installato l'ultima versione di GovPay sul nostro server.

Purtroppo, non riusciamo a capire cosa bisogna indicare nella richiesta di collegamento fisico nel campo  
"URL servizio RT":

![Schermata 2022-10-28 alle 16 26 20](https://user-images.githubusercontent.com/116882400/198644480-d97da219-fd1c-431b-b371-d7b0c6341a7a.png)

Potete gentilmente aiutarmi?
Vi ringrazio anticipatamente per l'eventuale supporto.

**Comment by ind87moving** [comment]
Hanno chiesto che di inserire in truststore il certificato del GAD.
Sul server wildfly ho abilitato let's encrypt e  acquistato anche il certificato x509 come richiesto da PagoPa.
Purtroppo non riesco a capire come bisogna aggiungere questi 2 nel truststore e successivamente configurare Wildfly per utilizzarli. Tu sapersi per piacere aiutarmi a capire come fare?

Sto leggendo i vari ticket già aperti, ma non riesco a trovare una risposta adatta.
Grazie in anticipo.

**Comment by nardil** [comment]
La configurazione dipende dall'infrastruttura in cui è dispiegato GovPay

# Client

Per il traffico in uscita, dove GovPay opera da client, il certificato va configurato nel connettore SSL dell'Intermediario sulla console di GovPay ([doc](https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/intermediari/index.html)). 

Nel caso in cui la sessione SSL non sia gestita da GovPay ma da altro componente (ad esempio da un API Gateway), il certificato sarà installato su tale componente e nella configurazione dell'intermediario verrà indicata la modalità di autenticazione prevista dalle policy interne.

# Server

Per il traffico in ingresso, dove GovPay opera da server, il certificato va configurato nel connettore https di WildFly.

Nel caso in cui la terminazione SSL non sia gestita da GovPay ma da altro componente (eg reverse proxy o API Gateway) il certificato viene installato su tale componente e le informazioni del certificato chiamante inoltrate a GovPay (via ajp o header http). Lato GovPay, la configurazione Spring-Security delle Api pagoPA deve essere coerente alla modalità con cui le informazioni del chiamante (pagoPA) vengono inoltrate a GovPay ([doc](https://govpay.readthedocs.io/it/latest/installazione/dispiegamento/index.html#modalita-di-autenticazione)).
