### ISSUE TITLE
govpay su mysql/MariaDB in configurazione MASTER/SLAVE

### ISSUE THREAD

**Issue by tizianatinnirello** [link-it/govpay#543]
Utilizzando govpay su Mysql/MariaDB in configurazione MASTER/SLAVE, nel momento in cui si inseriscono le pendenze attraverso 
"/govpay/backend/api/backoffice/rs/basic/v1/pendenze/tracciati",  i log del MASTER crescono a dismisura, tant'è che per circa 3000 pendenze si generano dei master-bin log file per un totale di oltre 150 Gb su disco.
E' un problema solo mio?

**Comment by nardil** [comment]
Salve Tiziana, 

attualmente le stampe dei PDF nel caso di stampe massive (csv)sono memorizzate su DB, quindi l'occupazione di spazio dipende dal numero di pendenze. La quantità di spazio è certamente eccessiva nel tuo caso e l'unico elemento variabile nelle stampe è il logo dell'Ente Creditore.

Da un punto di vista applicativo ti suggerirei di verificare la dimensione del logo caricato nell'anagrafica ente.

**Comment by tizianatinnirello** [comment]
Buongiorno Lorenzo, non mi sono spiegata bene probabilmente, il problema non è lo spazio occupato dal DB (dove peraltro in fase di caricamento imposto il parametro stampaavvisi=false in quanto i pdf verranno generati successivamente), piuttosto riguarda l'esponenziale crescita a dismisura dei log file MASTER-BIN di MariaDB utilizzata poi dai DB Slave per allinearsi con il Master (tipica configurazione Master/Slave di Mysql/MariaDB, NO CLUSTER). 

Spero di essere stata più chiara.

A proposito di stampe PDF: c'è un modo di "ripulire" il DB in modo che non conservi la stampa PDF delle posizioni ormai pagate (anche intervenendo direttamente sul DB con un'operazione di UPDATE?

**Comment by nardil** [comment]
Le stampe sono memorizzate solo in caso se richieste in sede di caricamento massivo da tracciato CSV. Nel caso si richieda una stampa tramite API, questa non viene memorizzata.

Se ho capito bene il tuo scenario non c'è necessità di alcun processo di svecchiamento delle stampe.

**Comment by tizianatinnirello** [comment]
Ok, per le stampe va bene così. Resta il problema della crescita a dismisura del log file in caso di caricamento massivo, francamente non me lo spiego...
