### ISSUE TITLE
Diciture dell'Attestazione di Pagamento non conformi alle SANP

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#544]
**Descrizione del Bug**
Le recenti SANP forniscono indicazioni di nomenclatura dei campi diverse da quelle attualmente presenti nella stampa della ricevuta in formato PDF

https://docs.pagopa.it/sanp/v/sanp-3.2.0/ente-creditore/attestazione-di-pagamento

**Risultato atteso:**

Rivedere le seguenti diciture:
- `Totale` in `Importo operazione`
- `Istituto` in `PSP`
- `IUV` in `Identificativo versamento`
- `CCP` o `ID ricevuta` in `Identificativo pagamento`

**Comment by frobertiFUB** [comment]
Per quanto riguarda il PSP le Specifiche chiedono che sia identificato almeno con **ragione sociale** e **codice fiscale**.

**Comment by nardil** [comment]
Quando si tratta di un pagamento v2 è possibile omettere la colonna Id riscossione nella tabella degli importi dando lo spazio risparmiato alla causale.

**Comment by pintorig** [comment]
Allego due esempi di ricevuta con le modifiche effettuate:

- [Ricevuta pagamento SANP 2.4.0](https://github.com/link-it/govpay/files/10012513/Rt_340000001540704_3400000015407042897.pdf)
- [Ricevuta pagamento SANP 2.3.0](https://github.com/link-it/govpay/files/10012514/Rt_340000001960618_1665491856262.pdf)

**Comment by frobertiFUB** [comment]
Great, thanks!

Il giorno mar 15 nov 2022 alle ore 13:22 Lorenzo Nardi <
***@***.***> ha scritto:
