### ISSUE TITLE
Pagamento POS NEXI

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#551]
Ciao,
per eseguire un pagamento con integrazione POS NEXI, se non ho capito male nella lettura della documentazione, il pagamento viene sganciato dalla piattaforma; ovvero si effettua il pagamento tramite POS NEXI e dopo aver verificato che il pagamento è andato a buon fine, si invia la RPT con i parametri nella URL che determinano già a monte la riuscita del pagamento e viene generata subito la RT.
E' corretto o mi sono perso qualcosa ?
Grazie

**Comment by nardil** [comment]
E' corretto.  Se la transazione pagoPA non viene eseguita o non va a buon fine per qualche motivo, il pagamento sarà poi rendicontato come Pagamento senza RPT (codice esito 9)
