### ISSUE TITLE
Autenticazione a pagoPA via Subscription Key

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#553]
**Necessità:**
Supportare la configurazione della connessione a pagoPA tramite subscriprion key secondo quanto previsto dalla Roadmap pagoPA

https://docs.pagopa.it/circolare-pagopa/dettaglio-interventi/connettivita-e-sicurezza

**Soluzione:**
Prevedere la possibilita' di configurare la connessione ai servizi pagoPA  dell'Intermediario con tipo `Subscription Key` che richiede come unico parametro la Key da passare nelle richieste a pagoPA.

**Comment by pintorig** [comment]
@atatarelli realizzare le modifiche al cruscotto per poter configurare l'autenticazione di tipo Subscription Key per gli intermediari:

Quando un intermediario e' configurato per utilizzare l'autenicazione con Subscription Key l'oggetto `instemediario.servizioPagoPa.auth` contiene la proprieta' obbligatoria `valore`:

``` json
{
	"denominazione": "Soggetto Intermediario",
	"principalPagoPa": "principal",
	"servizioPagoPa": {
		"urlRPT": "https://pagopa/...",
		"auth": {
			"valore": "8daebdf9-558c-4203-aade-0dee45bfc08d"
		}
	},
	"abilitato": true
}
```
La schermata di dettaglio avra' il seguente formato:
![Screenshot from 2022-11-29 18-17-55](https://user-images.githubusercontent.com/12812160/204597879-8c79d8cf-62a9-4b38-89b5-4304e455c81e.png)

Nelle schermate di configurazione aggiungere la voce `Subscription Key` alla select `Tipo Autenticazione`:
![Screenshot from 2022-11-29 17-48-16](https://user-images.githubusercontent.com/12812160/204594476-80a1f323-899a-4bd1-a916-159e17aa17f1.png)

Quando si seleziona  `Subscription Key` la form presenta una casella di testo obbligatoria con label `Ocp-Apim-Subscription-Key`
![Screenshot from 2022-11-29 18-22-34](https://user-images.githubusercontent.com/12812160/204598807-712e42f3-8136-4500-88fb-879e995abbce.png)

**Comment by pintorig** [comment]
Intervento di @atatarelli riportato nel branch 3.6.x con commit 0fd8f830cbc80faedb9d40c01a9b3f87c81ad1d5
