### ISSUE TITLE
API che espongono i datiPagoPA

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#556]
Ciao,
uso l'ultima versione 3.6.4 ma non provo l'API che espone i datiPagoPA (idpsp, ecc).

Potreste darmi indicazioni su come recuperarli?

Grazie.

**Comment by nardil** [comment]
Ciao @giuseppeformaro , 

i dati del psp con cui si e' eseguito il pagamento sono nella ricevuta. Quelli indicati nell'evento corrispondente sono estratti da li.

**Comment by giuseppeformaro** [comment]
Grazie @nardil, 
io vedo i dati che mi interessano solo negli eventi della paSendRTReq e volevo capire se questi dati sono messi a disposizione dalle API interne per interrogarle in un secondo momento.

**Comment by nardil** [comment]
Come anticipato i dati sono presenti nelle ricevute che sono esposte tramite API. Se c'e' una api specifica su cui stai indagando posso essere piu' puntuale

**Comment by giuseppeformaro** [comment]
Sto verificando sulle API che mi tornano i dati delle RT: 
- /govpay/backend/api/backoffice/#/Pagamenti/getRpp
- govpay/backend/api/backoffice/#/Pagamenti/getRt

Ma come dato utile trovo:
```
...
    "istitutoAttestante": {
      "identificativoUnivocoAttestante": {
        "tipoIdentificativoUnivoco": "B",
        "codiceIdentificativoUnivoco": "xxx"
      },
...
```
invece vorrei avere:
```
...
</transferList>
<idPSP>BPPIITRRXXX</idPSP>
<pspFiscalCode>97103880585</pspFiscalCode>
<PSPCompanyName>Poste Italiane</PSPCompanyName>
<idChannel>97103880585_02</idChannel>
...
```

**Comment by nardil** [comment]
Ciao @giuseppeformaro , le informazioni contenute nella RT mostrano i dati comunicati da pagoPA. Attualmente le specifiche prevedono un duplice formato in base al modello di pagamento utilizzato. A tendere la piattaforma convergera' al formato a cui stai auspicando quando sara' introdotto il [Modello Unico di Pagamento](https://docs.pagopa.it/circolare-pagopa/dettaglio-interventi/unico-modello-di-pagamento)
