### ISSUE TITLE
PKIX path building failed: - unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by ind87moving** [link-it/govpay#559]
Buongiorno,

chiedo gentilmente perchè purtroppo non risco a risolvere il problema per la consegna della RT.

Lato NODO quando cercano di inviare la RT viene ritornato il seguente errrore: 
```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

In fase di adesione nellla RT Mod.1 è stato indicato: /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice

Purtroppo dai log (govpay.log) e quelli di Wildfly NON vediamo questo errore

La modalità che sto utilizzando è GAD. La terminazione SSL è effettuata dall'Application Server

Potete dirmi di cosa può trattarsi?
Se avete necessità di ulteriori informazioni, sono a completa disposizione.

Grazie mille per la collaborazione

**Comment by ind87moving** [comment]
Buongiorno,
ho fatto delle modifiche, esponendo ora il certificato acquistato e inviato ad Agid nella fase di richiesta di collaudo.

Richiamando sempre la /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice si riscontra il seguente errore:
Il nodo ci comunica che ora è cambiato:
errore di trasporto, codice 401

Potete per piacere indirizziarmi verso quale potrebbe essere l'errore?
Non sappiamo se l'errore è ritornato per problemi di configurazione dell'application server oppure da govpay.

@nardil puoi per piacere darmi una mano?
Attendo un vostro gentile riscontro.

Grazie mille per la collaborazione

**Comment by ind87moving** [comment]
Ciao,
avevo già aperto 2 ticket in precedenza, ma non ho mai avuto riscontro.
Non vorrei che anche questo ticket facesse la stessa fine.
Grazie.

**Comment by nardil** [comment]
Ciao @ind87moving , 

mi spiace di non essere in grado di supportarti in questo momento. In generale, le richieste come questa, non essendo relative ad un problema del prodotto, hanno tipicamente più bassa priorità. Ovviamente, trattandosi di una community, chiunque sia in grado di aiutarti può rispondere nel frattempo alla tua richiesta di aiuto. 

Considera poi che non hai aperto un ticket a un supporto, ma chiesto aiuto ad una comunità che opera, come tutte le comunità open source, con politiche 'best effort'.

Se non avessi gia' fatto, ti suggerisco intanto di verificare se nelle richieste di aiuto simili alla tua di altri utenti della community trovi indicazioni utili a risolvere i problemi di configurazione di WildFly: https://github.com/link-it/govpay/issues/383 , https://github.com/link-it/govpay/issues/405 , https://github.com/link-it/govpay/issues/412

**Comment by ind87moving** [comment]
CIao @nardil, potrebbe essere utile il ticket #412 ma nel commento di [mallomix](https://github.com/mallomix) [del 05/10/2021](https://github.com/link-it/govpay/issues/412#issuecomment-934207347) non si vedono le configurazioni che aveva riportato. Si può in qualche modo sistemare il commento?

**Comment by nardil** [comment]
Puoi provare a chiedere direttamente a lui se ti riporta le informazioni che ti risultano mancanti

**Comment by ind87moving** [comment]
@nardil purtroppo non ha risposto.
Per piacere, riusciresti a condividere le istruzioni e i comandi per creare il keystore e trustore?
Credo che il problema sia legato a quello.

Secondo me, sto sbagliando qualcosa in quella procedura.
Grazie

**Comment by SC015074** [comment]
Ciao, per i comandi di creazione keystore e truststore puoi guardare questa guida:
https://docs.oracle.com/cd/E19509-01/820-3503/6nf1il6er/index.html

**Comment by ind87moving** [comment]
@SC015074 grazie mille.

Volevo fare un'altra domanda, pagoPA nella chiamata di richiesta alla RT (/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice), deve includere nella chiamata la private key del nostro certificato inviato nella fase di adesione? Quindi, bisogna condividere con pagoPA la chiave privata del nostro certificato?

**Comment by SC015074** [comment]
Ciao, 
la private key del tuo certificato è solo tua e non va condivisa con nessuno.
Seguendo la guida vedrai che ti farà creare un keystore che contiene una chiave privata, e poi una richiesta di certificato (csr) che dovrai far firmare ad una CA riconosciuta (materialmente devi acquistare il servizio di firma di quella richiesta csr).
Una volta ricevuto il certificato firmato dovrai importare la coppia (CA e certificato firmato .cer) all'interno del tuo keystore.
Poi prendi il solo certificato firmato e lo condividi con pagoPA.
Per il truststore dovrai semplicemente creare un'altro keystore che contiene le CA; a seconda della configurazione puoi decidere di importate la CA del tuo certificato, ma è importante che ci siano i certificati di pagoPA (che scarichi dal PDA).
