### ISSUE TITLE
versione 3.6.5 si blocca la gui backoffice

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#567]
aggiornata versione dalla 3.5.1 alla 3.6.5 con modalità file esterni.
aggiunto nuovo file xml; lanciato 3.6.sql ed aggiornato archivio ear.

dopo l'autenticazione alla GUI del BackOffice appare in basso "Operazione non autorizzata: Operazione non piu' disponibile"
Nei log si evidenzia la INFO: 
| INFO  | it.govpay.backoffice.v1.controllers.BaseController:204 | 0d3cb5ef-d0b8-4b11-82d5-03fe7cce194f | Accesso alla risorsa findEnumerazioniLabelTipiEvento non consentito: Operazione non autorizzata, Operazione non piu' disponibile
 | INFO  | it.govpay.backoffice.v1.controllers.BaseController:204 | e7719a51-996d-4752-9f6a-fac2ef81a94c | Accesso alla risorsa findEnumerazioniComponentiEvento non consentito: Operazione non autorizzata, Operazione non piu' disponibile

Quando carica la pagina giornale degli eventi si blocca con il simbolo di caricamento che gira.
Quando si seleziona il dettaglio di un pagamento oppure di una pendenza si blocca con il simbolo di caricamento che gira.

E' saltato qualche passaggio ?

Grazie.

**Comment by pintorig** [comment]
Salve @SC015074,

dovresti ripetere l'accesso alla console dopo aver svuotato la cache del browser e ricaricato l'applicazione.

**Comment by SC015074** [comment]
Ciao @pintorig ,
come da te indicato è andato tutto OK.

Grazie,
