### ISSUE TITLE
Problema inserimento pendenza da gui backoffice

### ISSUE THREAD

**Issue by VincenzoPresta** [link-it/govpay#568]
Salve, ho effettuato il deployment di govpay 3.6.5 su wildfly 18.0.0 e ho cominciato un po' a provare la console di gestione, provando a inserire un ente creditore ecc. Il mio scopo era effettuare la prova di un pagamento per poi effettuare l'integrazione nella mia applicazione spring. Pur avendo abilitato l'inserimento da operatore, quando vado a effettuare la creazione di una nuova pendenza, cliccando su "Ente creditore" nella pagina "Nuova pendenza", non succede nulla, nonostante io abbia precedentemente creato l'ente creditore. Dove sto sbagliando? Vi ringrazio anticipatamente per la risposta

**Comment by nardil** [comment]
Ciao @VincenzoPresta , 

per il caricamento da console e' necessario configurare il tipo pendenza, in particolare la sezione `Inserimento pendenze da operatore`: https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/enti/index.html#tipi-pendenze
