### ISSUE TITLE
update 3.4.2 -> 3.5.0 nuovo modello 3

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#569]
Buongiorno
ho effettuato l'update come da  oggetto applicando come  da indicazioni per il passaggio da una minor version la patch 3.5.sql  fornita con l'installer sul db postgresql  .

con la nuova versione il comportamento è il seguente :

1) i pagamenti modello 3 effettuati con  le nuove primitive risultano avere importo a 0 sul dettaglio pagamento  (mentre su dettaglio pendenza l'importo è indicato correttamente)

2) nella sezione riconciliazione non viene correttamente visualizzato lo IUV

![image](https://user-images.githubusercontent.com/36847326/223465111-ff018c53-7910-4b46-b5c0-335f6f496699.png)

ho letto tra al riguardo tra i bug segnalati degli aggiornamenti da fare sul sulla patch 3.5.sql sull'istruzione 
--ERRATA
UPDATE rpt SET versione = 'SANP_230';
--CORRETTA
UPDATE rpt SET versione = 'SANP_230' WHERE versione IS NULL;

ho quindi ripristinato la situazione sul db come da indicazioni con l'istruzione:

update rpt set versione='SANP_240' where encode(xml_rpt,'escape') not like '<RPT%';

non avendo ottenuto la fix delle anomalie in visualizzazione e visto che la versione 3..5.1  tra le altre cose implementa la fix del bug "#466 Adeguata consultazione pagamenti eseguiti cone le API pagoPA v2 " ho aggiornato alla versione alla 3.5.1 senza però ottenere la fix delle anomalie. Ho forse saltato qualche passaggio ulteriore ?

Grazie in anticipo per il consueto supporto

**Comment by pintorig** [comment]
Salve @asterixol2000 sono stati fatti diversi interventi dalla versione da te indicata quindi ti suggerisco di portare GovPay alla versione [3.6.6](https://github.com/link-it/govpay/tree/3.6.x) e ripetere la verifica. 
Nel caso il problema si presentasse ancora procediamo ad ulteriori analisi.

**Comment by asterixol2000** [comment]
Salve @pintorig  procederò con l'aggiornamento di GovPay come da te indicato e verificherò nuovamente

grazie per il consueto supporto
cordiali saluti
