### ISSUE TITLE
Pacchetto di installazione non compatibile con WildFly 8

### ISSUE THREAD

**Issue by nardil** [link-it/GovPay#57]
Come comunicato da Gibson nella mailing list di GovPay:

> Facendo l'aggiornamento da govpay 2.3.3 a govpay 2.5.4 su Wildfly 8, mentre la console viene caricata correttamente il file govpay.ear non viene caricato a causa di questo errore:

>JBAS015599: Apache CXF library (cxf-xjc-runtime-2.7.0.jar) detected in ws endpoint deployment; either provide a proper deployment replacing embedded libraries with container module dependencies or disable the webservices subsystem for the current deployment adding a proper jboss-deployment-structure.xml descriptor to it. The former approach is recommended, as the latter approach causes most of the webservices Java EE and any JBossWS specific functionality to be disabled.

**Comment by nardil** [comment]
@marklar79  a libreria `cxf-xjc-runtime-2.7.0.jar` non va inclusa nei pacchetti per WildFly. 

L'installer deve essere modificato per gestire questa cosa.

**Comment by nardil** [comment]
Implementato in 2.5 e 2.6

**Comment by SbGibson** [comment]
Se può essere utile a qualcuno noi, in mancanza della patch e seguendo la struttura del pacchetto della 2.3.3, abbiamo spostato i jar delle dipendenze in una directory lib all'interno dell'ear e lasciato nella lib del war solo le librerie di govpay e openspcoop e così ha funzionato anche se la libreria cfx era presente.
