### ISSUE TITLE
31 Marzo 2023 le primitive paaAttivaRPT e paaVerificaRPT verranno dismesse

### ISSUE THREAD

**Issue by ind87moving** [link-it/govpay#572]
Buongiorno,
ho ricevuto la comunicazione da pagoPA che le primitive in oggetto verranno dismesse.
![Comunicazione_PagoPA](https://user-images.githubusercontent.com/116882400/224269456-d6ced5ba-1066-448a-ac5f-11fecb176a0b.png)

Ho guardato nei ticket già aperti, ma non ho trovato nulla interente alla comunicazione suddetta.
Potete gentilemente dirmi se a livello di GovPay comporta qualche modifica?

Grazie

**Comment by nardil** [comment]
Ciao @ind87moving , 

GovPay implementa le nuove API del nuovo modello 3 a partire dalla versione 3.5 e sono esposte sul medesimo endpoint delle vecchie API, pertanto lato PdA e' sufficiente cambiare la versione della stazione.

Faccio presente che nelle API di integrazione di GovPay i tracciati RPT ed RT sono riportati esattamente nella forma nativa, pertanto nel caso di pagamenti modello 3 sulla nuova versione il tracciato sara' quello previsto dalle nuove API. Abbiamo quindi implementato una funzione di retro-compatibilita' che traduce i nuovi tracciati nel vecchio formato. Questa conversione comporta che i campi introdotti nei nuovi formati non trovano corrispondenza nel vecchio e quindi non vengono esposti (eg `metadata` della ricevuta). Per attivare questa funzione e' sufficiente impostare la proprieta `it.govpay.retrocompatibilitaMessaggiPagoPA.v1.enable=true`

**Comment by ind87moving** [comment]
@nardil Grazie per la risposta.
Sarebbe corretto dire che la retrocompatibilità sarebbe da attivare solo se precedente si ha utilizzato la stazione in versione 1? 

Nel caso di collegamento con Ente Creditore con una nuova stazione, sarebbe corretto tenere disabilita questa proprietà?

Grazie

**Comment by nardil** [comment]
E' da attivare se sono in essere integrazioni con applicativi che non supportano il nuovo formato di ricevuta.
