### ISSUE TITLE
Avviso pagoPA: Nome EC su una sola riga 

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#575]
**Descrizione del Bug**
Nel caso in cui il nome dell'ente non rientri nello spazio previsto, deve andare su due linee fino al massimo di 50 caratteri previsto dalla specifica.

**Come riprodurlo:**
Stampare un avviso di un EC dal nome particolarmente lungo.

**Risultato atteso:**
Il nome deve andare su due linee.

**Comment by pintorig** [comment]
Corretto in 3768155ac9fc105633a0d286f3e3b26b8e800aee
