### ISSUE TITLE
Modifica iban su pendenza inserita

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#584]
Buonasera,
su versione 3.6.6 è possibile effettuare la modifica dell'ibanAccredito in una pendenza già inserita ?

Grazie mille,
Buonasera

**Comment by nardil** [comment]
Ciao @SC015074 ,
il cambio di iban è una operazione non gestita via API. E' necessario eseguire una query su DB ce vada a sostituire l'iban con quello nuovo. 

Una volta individuati:
- `id_dominio`: id del dominio da aggiornare dalla tabella `domini`
- `id_iban_vecchio`: id del conto di accredito vecchio
- `id_iban_nuovo`: id del conto di accredito nuovo

```sql
UPDATE singoli_versamenti 
SET id_iban_accredito = '<id_iban_nuovo>' 
FROM versamenti 
WHERE versamenti.id=singoli_versamenti.id_versamento 
AND versamenti.id_dominio='<id_dominio>'
AND versamenti.stato_versamento='NON_ESEGUITO' 
AND id_iban_accredito='<id_iban_vecchio>';
```

**Comment by SC015074** [comment]
Ciao,
perfetto, grazie mille.
Buona giornata.
