### ISSUE TITLE
API-Backoffice: Iban appoggio mancante nei dati della voce pendenza 

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#587]
**Descrizione del Bug**
Nelle API-Backoffice nel dettaglio di una pendenza, all'interno dei dati della voce pendenza manca il campo opzionale Iban appoggio.

**Come riprodurlo:**
Leggere il dettaglio di una pendenza nelle API-Backoffice, se l'entrata ha configurato un iban appoggio questo non viene riportato nei dati della voce pendenza.

**Risultato atteso:**
Iban appoggio correttamente visualizzato nei dati della voce pendenza.

**Comment by nardil** [comment]
Verificare che, una volta corretta l'esposizione del dato, sulla console accedendo al dettaglio della pendenza ed espandendo la voce pendenza, l'informazione sia correttamente visualizzata.
