### ISSUE TITLE
Archivio Centralizza Avvisi :  quesiti

### ISSUE THREAD

**Issue by mgvaresio** [link-it/govpay#588]
Nelle SANP 3.4.0 è indicato quanto segue:
Ogni EC al momento delle creazione di una nuova posizione debitoria deve effettuare il censimento della stessa sull’ACA tramite la paCreatePosition, per mezzo della stessa API è possibile aggiornare la posizione.
1.	In presenza di un elevato numero di posizioni debitorie da inserire/aggiornare l’utilizzo di una primitiva che consenta l’invio di una sola posizione debitoria alla volta può essere oneroso soprattutto in termini di tempo. Sono disponibili modalità alternative per gestire l’invio massivo di posizioni debitorie da inserire o aggiornare o si sta pensando di predisporle? 

2.	Alcune posizioni debitorie non possono essere pagate prima di una certa data.La primitiva paCreatePosition permette di associare solo la data di scadenza ("expirationDate" ) e quindi dal punto di vista dell’EC significa che le posizioni debitorie possono essere inviate all’Archivio Centralizzato esattamente a ridosso del primo giorno utile di pagamento. Sarebbe possibile indicare anche una data di inizio validità per consentire all’EC  di organizzare con sufficiente anticipo l’invio delle posizioni debitorie?

3.	Nelle specifiche pubblicate on-line (https://docs.pagopa.it/sanp/ente-creditore/modalita-dintegrazione/integrazione-tramite-api-sincrone#archivio-centralizzato-avvisi ), in caso di aggiornamento è possibile l’aggiornamento dell’importo o dello stato della posizione debitoria. Come gestiamo quei casi in cui l’EC modifica la data scadenza ? E’ possibile aggiornare anche questa informazione anche se non indicato nelle specifiche? 
5.	La posizione debitoria di tipo spontaneo dovrà essere comunicata all'Archivio?

6.	Quando  si genera una posizione debitoria qual è il termine ultimo per il suo invio all’Archivio Centralizzato?

**Comment by nardil** [comment]
Ciao @mgvaresio 

questi sono quesiti da sottoporre a pagoPA come hai già fatto (https://github.com/pagopa/pagopa-api/issues/909)

Chiudo questa issue ed eventualmente partecipiamo sull'altra.
