### ISSUE TITLE
Modello unico di Pagamento:  processo interrotto prima della redirect finale 

### ISSUE THREAD

**Issue by mgvaresio** [link-it/govpay#589]
Stiamo analizzando la gestione del pagamento con iniziativa sul portale dell’Ente Creditore nell’ambito del nuovo Modello Unico pagoPA.
Consideriamo lo scenario peggiore:
•	il cittadino è sulle pagine del checkout pagoPA e chiude il browser prima di eseguire il redirect finale sul portale dell’EC oppure il redirect è eseguito sulla pagina returnErrorUrl
•	per problemi tecnici la consegna della receipt non va a buon fine
Di seguito i nostri quesiti:
1.	Nel caso di redirect sulla pagina returnErrorUrl, dal punto di vista dell’EC questo come deve essere valutato? Indica con certezza un esito negativo del tentativo di pagamento?

2.	Quando l’esperienza utente ricade nel caso peggiore descritto in precedenza e il gestionale dell’EC rimane privo di qualsiasi informazione sull’esito del tentativo di pagamento (nessuna pagina di redirect e nessuna ricezione della receipt), l’EC come può gestire il processo in stato pending dell’utente?

**Comment by nardil** [comment]
Ciao @mgvaresio 

questi sono quesiti da sottoporre a pagoPA come hai già fatto (https://github.com/pagopa/pagopa-api/issues/908)

Chiudo questa issue ed eventualmente partecipiamo sull'altra.
