### ISSUE TITLE
con stazione in versione 2 cambia la notifica 

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#594]
ciao,
con la versione 2 della stazione, cambia la struttura della notifica push dell'avvio pagamento e riscossione.
è possibile configurare la vecchia struttura json ?

Grazie

**Comment by SC015074** [comment]
Da quanto vedo è cambiata la struttura della notifica del modello 3.
Per i vecchi pagamenti modello 1 ricevo ancora la vecchia struttura json di notifica.

Esiste una configurazione per per ottenere inviare la vecchia notifica per tutto ?
Grazie,

**Comment by nardil** [comment]
Si, e' sufficiente impostare la proprieta: 

`it.govpay.retrocompatibilitaMessaggiPagoPA.v1.enable=true`

**Comment by SC015074** [comment]
Grazie mille. Ciao.
