### ISSUE TITLE
API Interazione pagamenti

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#595]
**Descrizione del Bug**
Invio a URL API Interazione eventi di pagamento anche se Ente non selezionato in Enti Creditori

**Come riprodurlo:**
- Avere 2 Enti (Ente1 e Ente2) con stesso A2A "X"
- Configurare API Integrazione (URL e versione API) e selezionare solo Ente1
- Eseguire un pagamento su Ente2

**Risultato atteso:**
Se Ente2 non è selezionato non deve inviare i pagamenti alla URL specificata.

**Ambiente:**
 - GovPay: Versione: 3.6.4 (9d9ed2c)

Grazie!

**Comment by giuseppeformaro** [comment]
Buodi,
da ulteriori verifiche se puo risultare utile, pare che non tenga in conto del filtro: 
Enti creditori - "Lista degli Enti ed unità operative su cui l’applicazione può operare"

Grazie

**Comment by pintorig** [comment]
Salve @giuseppeformaro, 

se ho interpretato bene, hai due enti creditori (Ente1 ed Ente2) e un'unica Applicazione (A1) che e' autorizzata solo sull'Ente1.
Effettuando un pagamento con l'Ente2, A1 invia la notifica di pagamento anche se non e' autorizzata sull'Ente2.

E' corretto?

**Comment by giuseppeformaro** [comment]
Provo a replicare meglio la casistica ed eventualmente riapro la segnalazione ma mi sa che è stato in mio errore di interpretazione per lo scenario che mi serviva e dove forse devo creare 2 A2A diversi, grazie e scusate.
