### ISSUE TITLE
Personalizzare il messaggio di informazione sull'importo dell'avviso 

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#598]
**Necessità:**
Si vuole aggiungere la possibilita' di personalizzare il messaggio di informazione presente nella sezione importo di un avviso di pagamento:

![Screenshot from 2023-07-28 16-56-03](https://github.com/link-it/govpay/assets/12812160/caa4bb62-9429-4d19-af10-cc5d91e3d415)

**Soluzione:**
Prevedere la possibilita' di personalizzare tale messaggio ed eventualmente nasconderlo (in tal caso nascondere anche l'icona info).
Per controllare il messaggio aggiungere un nuovo campo `messaggioInformazioneImportoAvviso` all'interno delle `ProprietaPendenza`:

``` yaml
ProprietaPendenza:
      type: object
      description: Dati supporto per la gestione del ciclo di vita della pendenza.
      properties:
        linguaSecondaria:
          $ref: '#/components/schemas/LinguaSecondaria'
        descrizioneImporto:
          type: array
          items: 
            $ref: '#/components/schemas/VoceDescrizioneImporto'
        lineaTestoRicevuta1:
          type: string
          description: stringa personalizzata da inserire nella ricevuta
        lineaTestoRicevuta2:
          type: string
          description: stringa personalizzata da inserire nella ricevuta
        linguaSecondariaCausale:
          type: string
          description: >-
              causale della pendenza nella lingua secondaria da inserire nell'avviso
        messaggioInformazioneImportoAvviso:
          type: string
          description: stringa personalizzata da inserire nella sezione informazioni importo
```

Valorizzando il nuovo campo in questo modo `messaggioInformazioneImportoAvviso : "NO" ` il messaggio di informazione verra' nascosto.

Modificare il template jasper per gestire le nuove opzioni di visualizzazione della sezione importo.

**Comment by nardil** [comment]
Proporrei questa gestione alternativa nel caso si desideri disabilitare il messaggio di informativa: se valorizzato sostituisce. Se stringa vuota omette.

E' necessario specificare la lunghezza massima e dare la possibilita' di fornire la versione tradotta in caso di stampa bilingue.

```yaml
        informativaImportoAvviso:
          type: string
          description: se valorizzato, sostituisce il testo standard. Se valorizzato con stringa vuota, l'informativa viene omessa.
          max: ???
        linguaSecondariaInformativaImportoAvviso:
          type: string
          description: se valorizzato, sostituisce il testo standard. Se valorizzato con stringa vuota, l'informativa viene omessa.
          max: ???
```

**Comment by pintorig** [comment]
@nardil possiamo assumere per gli avvisi bilingue che la modifica del messaggio  di informativa pagamento ha senso solo se entrambe le voci personaleizzate sono definite?

**Comment by nardil** [comment]
Direi che:

1. Se non viene impostata la dicitura sostitutiva della lingua principale, non viene modificata neanche quella della lingua secondaria indipendentemente dalla valorizzazione.
2. Se viene impostata la dicitura sostitutiva della lingua principale come vuota, non viene mostrata neanche quella della lingua secondaria, indipendentemente dalla valorizzazione
3. Se viene impostata la dicitura sostitutiva della lingua principale ma non quella della lingua secondaria, la lingua secondaria non viene mostrata
