### ISSUE TITLE
Sezione Ricevute

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#601]
**Necessità:**
Aggiungere la sezione ricevute sul cruscotto di backoffice

**Soluzione:**

Voce Ricevute nel menu' a sinistra:
![Screenshot from 2023-08-02 12-45-59](https://github.com/link-it/govpay/assets/12812160/b3a2fe26-acd1-4ac4-847a-909683e4d756)

## Ricerca ricevute

Schermata di ricerca ricevute:
![Screenshot from 2023-08-02 12-50-50](https://github.com/link-it/govpay/assets/12812160/7775602c-acba-4b6e-a2b1-6878b5625fd3)

La ricerca delle ricevute si fa utilizzando il servizio `/rpp?esito=ESEGUITO`, il parametro esito dovra' essere sempre impostato.

Per i filtri di ricerca proporre quelli indicati utilizzando i seguenti query param:

- EnteCreditore: `idDominio`
- IUV/NumeroAvviso: `iuv`
- Debitore: `idDebitore`
- Data Da: `dataRtDa`
- Data A: `dataRtA`

Per ogni risultato ricevuto `rpp[i]` utilizzare il seguente mapping per decidere quali informazioni visualizzare:

- Titolo sx: `rpp[i].pendenza.causale`
- Titolo dx: `rpp[i].rt.paymentAmount`
- Metadata sx: `rpp[i].pendenza.dominio.ragioneSociale + ', IUV: ' + rpp[i].rt.creditorReferenceId`
- Metadata dx: `rpp[i].rt.paymentDateTime`

In caso di pagamenti con le API SANP 2.3 (vecchio formato della ricevuta):

- Titolo sx: `rpp[i].pendenza.causale`
- Titolo dx: `rpp[i].rt.datiPagamento.importoTotalePagato`
- Metadata sx: `rpp[i].pendenza.dominio.ragioneSociale + ', IUV: ' + rpp[i].rt.datiPagamento.identificativoUnivocoVersamento`
- Metadata dx: `rpp[i].rt.dataOraMessaggioRicevuta`

## Dettaglio Ricevuta

Selezionando una voce della lista risultati si arriva alla schermata di dettaglio, la URL da invocare e': `/rpp/{idDominio}/{iuv}/{idRicevuta}` che restituisce l'oggetto _rpp_.

I dati necessari per invocare il servizio devono essere valorizzati nella seguente maniera:

- idDominio: `rpp.rt.fiscalCode`
- iuv: `rpp.rt.creditorReferenceId`
- idRicevuta: `rpp.rt.receiptId`

In caso di pagamenti con le API SANP 2.3 (vecchio formato della ricevuta):

- idDominio: `rpp.rt.dominio.identificativoDominio`
- iuv: `rpp.rt.datiPagamento.identificativoUnivocoVersamento`
- idRicevuta: `rpp.rt.datiPagamento.CodiceContestoPagamento`

Di seguito le informazioni da visualizzare (similari a quanto gia' mostrato nella vista della pendenza).

![Screenshot from 2023-08-02 14-21-33](https://github.com/link-it/govpay/assets/12812160/ca91c826-f16b-4574-943a-0a81b45c46d1)

![Screenshot from 2023-08-02 14-58-04](https://github.com/link-it/govpay/assets/12812160/61b58793-bfc2-48f4-82b0-259a4dd23322)

In alto a destra e' presente il comando per il download della ricevuta in formato pdf.

**Comment by pintorig** [comment]
@atatarelli puoi eseguire il task nel branch [601-sezione-ricevute](https://github.com/link-it/govpay/tree/601-sezione-ricevute).

Ho gia' aggiunto la voce menu' e la pagina di ricerca.

Sono rimaste da fare:
- Pagina di dettaglio
- Aggiungere il parametro fisso `/rpp?esito=ESEGUITO` alla URL di ricerca.

**Comment by nardil** [comment]
- [ ] Nel dettaglio della pendenza, nella voce di importo, modificare i dati in modo da presentare: `Ente`,`Conto accredito`, `Conto appoggio`, `Tassonomia`
- [ ] Nel dettaglio della riconciliazione, modificare i dati in modo da presentare: `Ente`, `Debitore`,`Tassonomia`
