### ISSUE TITLE
Riproposizione notifiche

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#602]
Ciao,
è possibile riproporre delle notifiche di riscossione già consegnate al gestionale attraverso le API di integrazione ?

Grazie,

**Comment by nardil** [comment]
E' possibile intervenire sulla tabella `notifiche` e impostare la colonna `stato='DA_SPEDIRE'` per le notifiche che si desidera che vengano rispedite.

**Comment by SC015074** [comment]
Grazie mille; provvedo a chiudere.
