### ISSUE TITLE
Supporto SANP 3.6.0

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#604]
**Necessità:**
Allineare le API PagoPA alla versione 3.5.0.
Il nuovo schema si trova [qui](https://github.com/pagopa/pagopa-api/blob/SANP3.5.0/wsdl/paForNode.wsdl).

**Comment by pintorig** [comment]
@nardil 
Come indicato nel [Changelog](https://docs.pagopa.it/sanp/specifiche-attuative-del-nodo-dei-pagamenti-spc/changelog) sono state fatte le seguenti modifiche agli schemi:

- Eliminati Metadata dagli elementi `ctTransferPA` (restano solo nella versione V2)
- Aggiunto campo obbligatorio `companyName` agli elementi `ctTransferPAV2`  e `ctTransferPAReceiptV2` 
- Aggiunto campo boolean `standIn` agli oggetti `paSendRTReq` e `paSendRTV2Request`

**Comment by nardil** [comment]
Aggiorno il titolo della issue

**Comment by pintorig** [comment]
Eseguito aggiornamento degli schemi SANP alla versione 3.6.0.
La gestione del nuovo campo `standIn` per le operazioni `paSendRT` e `paSendRTV2` verra' effettuato all'interno della Issue #607.
