### ISSUE TITLE
Gestione eseguiti senza RPT in flusso di rendicontazione

### ISSUE THREAD

**Issue by SbGibson** [link-it/GovPay#61]
Se si riceve un flusso di rendicontazione contenente un versamento con stato ESEGUITO_SENZA_RPT il software cerca il versamento e se non lo trova solleva un'eccezione interrompendo il caricamento del flusso.

Credo che sia più corretto che in questo caso ci fosse la stessa gestione che c'è per i versamenti non presenti in govpay, per cui il software scrive un log e prosegue con il versamento successivo, altrimenti si rischia di perdere la rendicontazione dei versamenti successivi.

Per riferimento la gestione è nel file govpay/core/business/Rendicontazioni.java alla riga 338

**Comment by nardil** [comment]
Ciao @SbGibson,
al momento la logica e' la seguente:

1. Arriva una rendicontazione senza RPT 
2. Viene cercato internamente il versamento corrispondente
3. Se non si trova, se ne cerca l'applicativo gestore
4. Si interroga l'applicativo per acquisire i dati del versamento

Ci sono due casi in cui l'acquisizione fallisce interrompendo l'acquisizione:
1. Il sistema non riesce ad identificare l'applicativo gestore
2. Il sistema non riesce a contattare l'applicativo gestore

Se la casistica a cui fai riferimento e' la prima, sono d'accordo a gestire l'inconveniente come segnalazione e non interrompere l'acquisizione.

Nel secondo caso invece ritengo corretta la gestione attuale che, in caso di errori temporanei di comunicazione con gli applicativi integrati, interrompe l'acquisizione per ritentare in un secondo momento.

Concordi con questa analisi?

**Comment by SbGibson** [comment]
Scusami, ero convinto di averti risposto dal cellulare ma per qualche motivo non ha preso la risposta. Cmq concordavo con la tua analisi quindi tutto bene. Grazie per il fix.
