### ISSUE TITLE
Allineare valorizzazione Metadata alle nuove specifiche

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#611]
**Necessità:**
Sono state modificate le specifiche di valorizzazione dei metadata nelle RT rendendo l'attuale implementazione (#558) superata

https://docs.pagopa.it/dizionario-dei-metadata/riconciliazione-contabile

**Soluzione:**

1. Allineare la logica di compilazione dei metadata alle ultime specifiche
2. Sulla console di backoffice modificare la vista di dettaglio di una ricevuta inserendo le voci dei metadata nei dati di ciascuna voce di pagamento (transaction)

**Comment by pintorig** [comment]
@nardil 
Prima analisi dei nuovi campi e mapping con i campi esistenti nelle API GovPay.

Si utilizza il campo  `tipologia` di ogni elemento per decidere quale delle 3 tipologie di contabilizzazione utilizzare:
- CORRISPETTIVO_DL118
- INCASSO_TIPICO
- CIVILISTICO

1. Corrispettivo DL 118
  - `RC_TIP_N`: valorizzato con `tipologia`
  - `RC_CAP_N`: valorizzato con `capitolo`
  - `RC_ART_N`: valorizzato con `articolo`
  - `RC_ACC_N`: valorizzato con `accertamento`
  - `RC_AC_N`: valorizzato con `annoEsercizio`  `Campo obbligatorio`
  - `RC_IMP_N`: valorizzato con `importo` `Campo obbligatorio`
  - `RC_CU_N`: valorizzato da proprieta' custom `codiceUfficio`
  - `RC_PF5_N`: valorizzato da proprieta' custom `pf5livello`
  `Capitolo e Accertamento sono fra loro alternativi, uno dei due deve essere inserito. Accertamento e pf_5_livello sono fra loro alternativi.`
  

2. Incasso tipico
  - `RC_TIP_N`: valorizzato con `tipologia`
  - `RC_AC_N`: valorizzato con `annoEsercizio`  `Campo obbligatorio`
  - `RC_IMP_N`: valorizzato con `importo`  `Campo obbligatorio`
  - `RC_CU_N`: valorizzato da proprieta' custom `codiceUfficio`
  - `RC_TI_N`: valorizzato da proprieta' custom `tipoIncasso`  `Campo obbligatorio`
  - `RC_EF_N`: valorizzato da proprieta' custom `emissioneFattura`
  - `RC_ND_N`: valorizzato da proprieta' custom `numeroDocumento`
 `Emissione fattura e nr_documento sono fra loro alternativi.`

3. Civilistico
  - `RC_TIP_N`: valorizzato con `tipologia`
  - `RC_AC_N`: valorizzato con `annoEsercizio`   `Campo obbligatorio`
  - `RC_IMP_N`: valorizzato con `importo`  `Campo obbligatorio`
  - `RC_CU_N`: valorizzato da proprieta' custom `codiceUfficio`
  - `RC_CON_N`: valorizzato da proprieta' custom `conto`
  - `RC_COM_N`: valorizzato da proprieta' custom `commessa`
  - `RC_ND_N`: valorizzato da proprieta' custom `numeroDocumento`
 `Conto, Commessa e Nr Documento sono fra loro alternativi, uno dei tre deve essere inserito.`

Tutto questo fino ad un massimo di 10 entries da inserire nella struttura dati `CtMetadata`

**Comment by nardil** [comment]
Risulta troppo complicato procedere con le proprieta' custom e verificare che i dati obbligatori siano inseriti.

Credo sia meglio:

- Proporre l'introduzione di strutture alternative al json schema dell'elemento "contabilita" che supportino queste tipologie di contabilizzazioni. 
- Trovare anche soluzione al caso TARI-TEFA, gestito in modo completamente diverso
- Proporre una soluzione nel caso in cui i parametri per `CtMetadata` superino le 10 unita' disponibili

**Comment by nardil** [comment]
Da valutare questa soluzione alternativa:

- Lato DB memorizziamo i dati come properties metadata (come previsto da pagoPA).
- Lato API viene fornita la possibilita' di inserire i metadata:
  - Come dati RAW (lista di properties)
  - In uno dei dataset previsti (civilistico, incasso tipico, corrispettivo DL118)

il precedente  servizio `contabilità` viene mantenuto e gradualmente sostituito dal nuovo dataset poichè le informazioni sono utilizzate dai connettori di esportazione dati

**Comment by nardil** [comment]
Sostituito da #692
