### ISSUE TITLE
Nuova connettività - PPT_AUTENTICAZIONE - Password sconosciuta o errata

### ISSUE THREAD

**Issue by tizianatinnirello** [link-it/govpay#613]
Buongiorno, lavorando in ambiente uat, in fase di Richiesta elenco pagamenti sospesi a pagoPA ricevo l'errore PPT_AUTENTICAZIONE - Password sconosciuta o errata

La mia configurazione:
Principal: CN=forwarder.uat.platform.pagopa.it
Servizio RPT: https://api.uat.platform.pagopa.it/nodo-auth/nodo-per-pa/v1
Ocp-Apim-Subscription-Key: My-Subscription-Key
Tipo autenticazione: Nessuna

Ho inserito in truststore sia il certificato+chain di forwarder.uat.platform.pagopa.it che di api.uat.platform.pagopa.it

Non va

**Comment by nardil** [comment]
Ciao Tiziana,

quell'errore, restituito da pagoPA, indica una errata valorizzazione della password nella configurazione della stazione. Sulla nuova connettività pero' quel campo e' stato deprecato e viene ignorato ai fini dell'autorizzazione, pertanto dovrebbe essere inutile verificarne la valorizzazione.  

Dovresti verificare con pagoPA la causa poiché probabilmente dipende da una loro configurazione non compatibile con la nuova connettività.

**Comment by tizianatinnirello** [comment]
Lo sospettavo, ho aperto un ticket. Grazie!

**Comment by nardil** [comment]
Ciao Tiziana,

hai poi risolto? era un problema lato pagoPA?

**Comment by tizianatinnirello** [comment]
E niente, non rispondono. E' frustrante

**Comment by tizianatinnirello** [comment]
Ancora niente.
E comunque ho rovistato ovunque e non vedo traccia di proroghe per l'entrata in funzione della nuova connettività prevista per il 01/10/2023. Francamente a me sembra impossibile...

**Comment by tizianatinnirello** [comment]
A beneficio di tutti: oltre allo stacco delle chiavi è necessario che vengano comunicati gli endpoint da configurare sulla nuova connettività

**Comment by giuseppeformaro** [comment]
Buondi, confermo e aggiungo che anche eventuali regole di ingresso sul FW sono da rivedere (pagoPA si presenta con IP diversi da quelli presenti del documento di COLLAUDO del GAD).
