### ISSUE TITLE
API Interazione pagamenti (notifiche ATTIVAZIONE e RICEVUTA)

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#616]
Utilizzo le API Interazione per inviare eventi di pagamento ed ho verificato che vengono sempre inviate: ATTIVAZIONE e RICEVUTA.

E' possibile discriminare questo comportamento per inviare solo le RICEVUTE o devo intervenire lato gestionale nello scartare le notifiche di eventi ATTIVAZIONE (che hanno un ccp diverso e sono ovviamene senza RT)?

Ambiente:
GovPay: Versione: 3.7.1

Grazie!

**Comment by nardil** [comment]
Ciao Giuseppe,

le API Ente v2 notificano le ricevute che nel modello unico, sono solo positive, pertanto realizzano lo scenario da te desiderato. 

Rimanendo invece alle API v1 non c'e' una funzione per disabilitare la notifica dell'evento di attivazione che eventualmente può essere gestito con un 200 OK al solo fine di evitarne la rispedizione.

**Comment by giuseppeformaro** [comment]
Grazie mille!

Confermo che con V2 non genera più ATTIVAZIONE ma giusto a titolo informativo genera la RICEVUTA anche sui soli tentativi di pagamento ANNULLATI.

**Comment by nardil** [comment]
Se viene emessa ricevuta, questa viene notificata. Nel modello unico, le ricevute sono solo positive, pertanto presumo che il pagamento annullato sia inerente al modello 1.

**Comment by giuseppeformaro** [comment]
Confermo: test fatto con MODELLO 1

Grazie ancora
