### ISSUE TITLE
Autenticazione OAuth2 Client Credential

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#617]
**Necessità:**
Aggiungere come modalita' di autenticazione OAuth2 Client Credential verso i servizi terzi

**Comment by pintorig** [comment]
Schema autenticazione Oauth2 Client Credentials: [Flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow)

Per l'integrazione in GovPay si deve definire un nuovo tipo di autenticazione per il connettore `Oauth2 Client Credentials` per il quale sono necessarie le seguenti informazioni:
- client-id
- client-secret
- oauth2-token-url

Di seguito un esempio di interazione con un servizio protetto tramite Oauth2 in Java:

``` Java
 // OAuth2 client credentials
        String clientId = "YOUR_CLIENT_ID";
        String clientSecret = "YOUR_CLIENT_SECRET";

        // OAuth2 token URL
        String tokenUrl = "OAUTH2_TOKEN_URL";

        // Protected resource URL
        String protectedResourceUrl = "PROTECTED_RESOURCE_URL";

        try (CloseableHttpClient httpClient = HttpClients.createDefault()) {
            // Request an access token using client credentials
            HttpGet tokenRequest = new HttpGet(tokenUrl);
            tokenRequest.addHeader("Authorization", "Basic " + Base64.getEncoder().encodeToString((clientId + ":" + clientSecret).getBytes()));

            HttpResponse tokenResponse = httpClient.execute(tokenRequest);
            int tokenStatusCode = tokenResponse.getStatusLine().getStatusCode;

            if (tokenStatusCode == 200) {
                // Successfully obtained an access token
                HttpEntity entity = tokenResponse.getEntity;
                String accessToken = EntityUtils.toString(entity);

                // Use the access token to access the protected resource
                HttpGet resourceRequest = new HttpGet(protectedResourceUrl);
                resourceRequest.addHeader("Authorization", "Bearer " + accessToken);

                HttpResponse resourceResponse = httpClient.execute(resourceRequest);
                int resourceStatusCode = resourceResponse.getStatusLine().getStatusCode;

                if (resourceStatusCode == 200) {
                    // Successfully accessed the protected resource
                    HttpEntity resourceEntity = resourceResponse.getEntity;
                    String resourceData = EntityUtils.toString(resourceEntity);
                    System.out.println("Protected Resource Response: " + resourceData);
                } else {
                    System.err.println("Failed to access the protected resource. Status code: " + resourceStatusCode);
                }
            } else {
                System.err.println("Failed to obtain an access token. Status code: " + tokenStatusCode);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by pintorig** [comment]
La chiamata verso la URL per ottenere il token deve essere nel seguente formato:

``` makefile
POST /token-endpoint HTTP/1.1
Host: authorization-server.com
Authorization: Basic Y2xpZW50X2lkOmNsaWVudF9zZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read write


```
 L'header `Authorization` deve essere cosi fatto:

``` bash
Authorization: Basic base64(client_id:client_secret)
```

La risposta OK a questa chiamata e' del tipo:
``` json
{
    "access_token": "your-access-token",
    "token_type": "Bearer",
    "expires_in": 3600,
    "scope": "read write"
}
```

La risposta contiene i valori da utilizzare per valorizzare l'header `Authorization` nelle chiamate al servizio:

``` bash
Authorization: Bearer your-access-token
```

Il campo `expires_in` indica la durata del token. Durante tutta la durata del token si possono fare le invocazioni direttamente al servizio senza ripassare dal servizio di autenticazione.

**Comment by pintorig** [comment]
Elenco passi implementazione:

- [ ] Aggiugere properties e nuova modalita' di autenticazione al connettore per salvataggio su db.
- [ ] Aggiungere nuova modalita' di autenticazione allo yaml del backoffice
- [ ] Collegare frontend e backend
- [ ] Test di salvataggio, lettura e sintassi nuovo connettore
- [ ] Creazione classe per l'acquisizione e controllo di validita' del token
- [ ] Aggiungere la nuova modalita' di autenticazione alla classe BasicClientCORE
- [ ] Test di utilizzo nuova autenticazione tramite check nel giornale degli eventi.
- [ ] Adattare Console di Backoffice per supportare la nuova autenticazione
