### ISSUE TITLE
Supporto per Microsoft SQL Server

### ISSUE THREAD

**Issue by pperliti** [link-it/govpay#620]
E' in programma il supporto a Microsoft SQL Server?
Ci vedete particolari criticità?
Grazie.

**Comment by nardil** [comment]
Ciao Paolo,

no, non ci sono piani per il supporto ufficiale, ma di fatto e' stato realizzato. Trovi infatti nei sorgenti gli script e le patch per questo db: `src/main/resources/db/sql/sqlserver`
