### ISSUE TITLE
paSendRTV2RequestRresponse/  PAA_RPT_SCONOSCIUTA

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#625]
alla ricezione della RT viene preso  il  seguente fault .
Come test, ho provato ad utilizzare lo stesso payload sulla paSendRTReq e la ricevuta viene correttamente acquisita .

nuova connettività 
nuovo modello 3
versione govpay `3.7.4`

c'e' da settare qualcosa per processare paSendRTV2Request ?

saluti

```
<soap:Envelopexmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<ns4:paSendRTV2Responsexmlns:ns2="http://www.digitpa.gov.it/schemas/2011/Pagamenti/"xmlns:ns3="http://ws.pagamenti.telematici.gov/ppthead"xmlns:ns4="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd"xmlns:ns5="http://ws.pagamenti.telematici.gov/">
<outcome>KO</outcome>
<fault>
<faultCode>PAA_RPT_SCONOSCIUTA</faultCode>
<faultString>La RPT risulta sconosciuta.</faultString>
<id>xxxxxxxx</id>
<description>No result founds</description>
</fault>
</ns4:paSendRTV2Response>
</soap:Body>
</soap:Envelope>

```

**Comment by nardil** [comment]
CIao @asterixol2000 ,

no, non e' necessario alcun setting. Verifichiamo lo scenario e ti diamo un riscontro

**Comment by nardil** [comment]
@asterixol2000 sicuro che la Receipt oggetto della notifica sia relativa ad una pendenza presente in GovPay e che non sia relativa ad avvisi gestiti da altri intermediari (eg. perche' attivato il broadcast lato pagoPA) ?

**Comment by asterixol2000** [comment]
@nardil 
come come posso verificare se è attivato il broadcast lato pagoPA ?

riassumo lo scenario:

ambiente di collaudo nuova connettività : 
Versione: 3.7.4 (f5e6d0c) assemblata con mvn -Denv=installer_template clean install -P java-1.8,wildfly-18 e passate le pach sul DB per passaggio a major version

generato avviso di pagamento dall EC.(OK)
pagato avviso da app IO (OK)
giornale eventi ->  Ricevuta verifica RPT da pagoPA (v2)  OK 
                              Ricevuta verifica RPT da pagoPA (v2)  OK
                             Ricevuta RT da pagoPA (v2) FAIL.

per testare la problematica ho inviato il payload che va in FAIL sulla paSendRTV2  alla paSendRTReq e la ricevuta viene acquisita.

La mia ipotesi (non so quanto possa avere senso )  è che fallisca qualche controllo aggiuntivo effettuato sulla RT nella versione V2 magari per qualche pacth DB non applicata correttamente nei vari passaggi di versione, mi puoi dire da quale versione è stata introdotta la paSendRTV2 ?

**Comment by nardil** [comment]
E' pagoPA che individua quale versione delle primitive utilizzare. 

Puoi confermarmi se il pagaemnto e' stato attivato con la primitiva `paGetPayment` o `paGetPaymentV2`?

**Comment by nardil** [comment]
Riepilogando: 

il comportamento che hai segnalato sembra indicare che pagoPA utilizzi per un pagamento delle primitive di versione diversa, ovvero:

1. paGetPayment
2. paSendRTV2

mentre l'implementazione attuale assume che siano omogenee, ovvero

1. paGetPayment
2. paSendRT

oppure

1. paGetPaymentV2
2. paSendRTV2

Se questo viene confermato, e' necessario verificare con pagoPA se sia un loro errore di configurazione oppure uno scenario da gestire.

**Comment by asterixol2000** [comment]
Corretto utilizzano primitive diverse
<soapenv:Body><pafn:paGetPaymentReq><idPA>  
 paSendRTV2

Verifico con pagoPA la correttezza della configurazione e ti faccio sapere se si tratta di un errore di configurazione

saluti

**Comment by asterixol2000** [comment]
per il problema segnalato, sono sempre in attesa delle verifiche sulla  confgurazione su pagopa saluti

**Comment by pperliti** [comment]
Confermo anche io quanto segnalato da @asterixol2000.
Utilizzo GovPay v3.7.5, nuova connettività su modello unico. Con il checkout è tutto ok, utilizzando l'App IO si riceve dapprima una paGetPayment (V1) e poi una paSendRTV2. GovPay rifiuta la ricevuta in quanto non rileva una corrispondente paGetPaymentV2. L'utente finale non rileva nulla (il pagamento va a buon fine) ma il pagamento non è presente su GovPay (dunque non è possibile riconcialire). Aperta [issue su pagpPA](https://github.com/pagopa/pagopa-api/issues/943). Sebbene da roadmap la deadline per un fix sull'App IO risultasse marzo 2024, ora si parla di settembre 2024.
Questa anomalia ha un side-effect anche sull'elenco dei flussi di rendicontazione di GovPay.

**Comment by pintorig** [comment]
@pperliti grazie per la segnalazione.
Modifichiamo il comportamento attuale di GovPay cosi da acquisire una RT indipendentemente dalla primitiva utilizzata per l'attivazione.
