### ISSUE TITLE
Associazione e visualizzazione IBAN a tipi pendenza

### ISSUE THREAD

**Issue by pperliti** [link-it/govpay#628]
E' possibile associare un IBAN predefinito (tra quelli censiti per l'ente) a un Tipo Pendenza? (un po' come avveniva per i Tipo Entrata)
Questo eviterebbe di dover associare esplicitamente l'IBAN di accredito alla singola voce di ogni pendenza/versamento e di dover gestire l'associazione IBAN-TipoPendenza esternamente a GovPay.

Grazie!

**Comment by nardil** [comment]
L'entita' "Tipo entrata" esiste ancora. Non e' possibile associare un iban al tipo pendenza, proprio perche' la pendenza ha piu' voci di entrata e ciascuna puo' individuare iban diversi.

**Comment by pperliti** [comment]
Grazie Lorenzo.

Se capisco bene "Tipi Entrata" è stato deprecato in favore di "Tipi Pendenza" e le nuove configurazioni dovrebbero essere fatte utilizzando quest'ultima entità (più flessibile). La flessibilità di poter gestire più voci per pendenza, ciascuna con un IBAN dedicato (che sia lo stesso per tutte le voci oppure no, poco importa), implica che la gestione dell'associazione tra TipoPendenza.Voce e IBAN resta in capo all'EC, vale a dire da nessuna parte si può specificare su GovPay un'associazione di default tra queste due entità, giusto? Immagino sia in linea con la filosofia di GovPay di rimanere agnostico su certe configurazioni (lasciandole gestire esternamente) per poter adattarsi meglio a tutti i contesti. Tuttavia potrebbe risultare utile avere la possibilità di definire un default (che possa comunque essere "sovrascritto" di volta in volta) per tutti quei casi in cui un EC ha 1-2 tipi di pendenza mono-voce che vengono accreditati sempre su un IBAN specifico.
