### ISSUE TITLE
Errore PAA_SYSTEM_ERROR con pagamento da APP IO o altro PSP

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#629]
**Descrizione del Bug**
Nell'effettuare un pagamento con app io ricevo questo errore nel diagnostic log 👍 

```

<c4619d32-49e9-4800-85b7-307097927dab> 013006 ccp <2023-10-04_17:20:50.774> (INFO) {correlation-req:80020270650304000000000210839} From:NodoDeiPagamentiSPC ->  To:************* S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paVerifyPaymentNotice
Ricevuta richiesta di verifica del pagamento [Dominio:****** Iuv: ********** **Ccp:(???Placeholder [context.request.genericProperties[ccp].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [ccp] not exists as key in map )] dal Nodo dei Pagamenti [Psp:(???Placeholder [context.request.genericProperties[codPsp].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [codPsp] not exists as key in map )].**


<c4619d32-49e9-4800-85b7-307097927dab> 013009 ccp <2023-10-04_17:20:50.807> (ERROR) {correlation-req:80020270650304000000000210839} From:NodoDeiPagamentiSPC ->  To:********** S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paVerifyPaymentNotice
Verifica rifiutata con esito KO. Inviato codice di errore PAA_SYSTEM_ERROR: Errore generico.. Dettaglio errore: Operazione non autorizzata
```

mentre ricevo questo errore nel govpay.log 

`2023-10-04 17:20:50.776 | INFO  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:1150 | c4619d32-49e9-4800-85b7-307097927dab | Ricevuta richiesta paVerifyPaymentNotice [****][****][****][*******]
2023-10-04 17:20:50.776 | WARN  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:1813 | c4619d32-49e9-4800-85b7-307097927dab | Errore in PaVerifyPaymentNotice: it.govpay.core.exceptions.NotAuthorizedException: Operazione non autorizzata
it.govpay.core.exceptions.NdpException: it.govpay.core.exceptions.NotAuthorizedException: Operazione non autorizzata
`

Cosa vuol dire ? Pagopa mi dice che da parte loro l'autenticazione con i certificati va a buon fine. L'errore compare solo da pagamento con PSP e non se si procede a pagare con il wisp

**Comment by nardil** [comment]
Ciao @frdidonato ,

dovresti condividere una porzione piu' consistente dei log `govpay.log` e `govpay_root.log` per poterti aiutare ad individuare il problema

**Comment by frdidonato** [comment]
Salve @nardil , ho appena individuato il problema.
Non ho compilato l'ear inserendo la property **it.govpay.pdd.auth=false** nel file di properties govPay.properties.
analizzando lo stack trace ho visto che l'errore veniva lanciato all'interno del controllo 

`if(GovpayConfig.getInstance().isPddAuthEnable()){
					boolean authOk = AuthorizationManager.checkPrincipal(authentication, intermediario.getPrincipal()); 
					
					if(!authOk) {
						GovpayLdapUserDetails details = AutorizzazioneUtils.getAuthenticationDetails(authentication);
						String principal = details.getIdentificativo(); 
						ctx.getApplicationLogger().log("ccp.erroreAutorizzazione", principal);
						throw new NotAuthorizedException("Autorizzazione fallita: principal fornito (" + principal + ") non valido per l'intermediario (" + codIntermediario + ").");
					}
				}`

Nel quale non sarei dovuto entrare avendo quella property a false. Adesso funziona tutto come dovrebbe, chiedo scusa per il disagio e vi auguro buon lavoro
