### ISSUE TITLE
Autenticazione API Keys

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#631]
**Necessità:**
Aggiungere il supporto per l'autenticazione con API Keys

**Soluzione:**
Prevedere la possibilità di indicare la APP-ID e la API-KEY di autenticazione, sia in fruizione che erogazione di servizi.

I due parametri vengono passati tramite header HTTP con nome configurabile nelle properties che per default sono:
- `X-API-KEY`
- `X-APP-ID`

**Comment by pintorig** [comment]
Elenco Implementazione 

### Fruizione
- [ ] Aggiugere properties e nuova modalita' di autenticazione al connettore per salvataggio su db.
- [ ] Aggiungere nuova modalita' di autenticazione allo yaml del backoffice
- [ ] Collegare frontend e backend
- [ ] Test di salvataggio, lettura e sintassi nuovo connettore
- [ ] Aggiungere 2 properties obbigatorie alla configurazione di sistema per indicare gli header in cui inserire i valori impostati per l'autenticazione
- [ ] Test di utilizzo nuova autenticazione tramite check nel giornale degli eventi.
- [ ] Adattare Console di Backoffice per supportare la nuova autenticazione

### Erogazione
- [ ] Aggiungere 2 properties obbigatorie alla configurazione di sistema per indicare gli header da cui leggere i valori necessari per l'autenticazione
- [ ] Aggiungere la modalita' di autenticazione API-KEY per tutti i war di GovPay
- [ ] Nella configurazione di un'applicazione o di un operatore il campo API-ID si imposta attraverso il campo `principal` dell'utenza, API-KEY all'interno del campo `password`
- [ ] Creare un handler di autenticazione per verificare la nuova autorizzazione
- [ ] Aggiungere i test di autenticazione
- [ ] Aggiornare la documentazione
