### ISSUE TITLE
Modalità di integrazione e modello unico

### ISSUE THREAD

**Issue by pperliti** [link-it/govpay#632]
Scenario: **nuova adesione a pagoPA**

Dall'esame della documentazione su pagopa.it e da un primo contatto con il team di operations mi si chiede di indicare:
1. la **modalità di integrazione** (_sincrona_ vs. _asincrona_)
2. il **modello di pagamento supportato** (_modelli 1 e 3_ vs. _modello unico_)

Volendo utilizzare GovPay (current release v3.7.4) come gateway sono a chiedere:
1. GovPay supporta entrambe le modalità? In tal caso quale delle due conviene scegliere? (ad esempio, non mi è chiaro se la primitiva `paCreatePosition` è implementata, la quale mi sembra alla base della creazione dell'ACA, a sua volta vincolante per l'integrazione in modalità sincrona)
2. GovPay supporta già il modello unico? Se sì, conviene comunque scegliere i "classici" modelli 1 e 3 (ben consolidati) o optare per quello unico (dove però mi risulta che lato pagoPA ci siano ancora qualcosa da sistemare)?

Per procedere alla creazione di una connessione devo per forza rispondere a queste due domande.

Un'ultima curiosità a latere (nella documentazione non l'ho trovato esplicitato): che livello di SANP supporta la versione corrente di GovPay? Mi pare di capire che siano supportati sia il "vecchio" modello 2.x (fino alle SANP 2.4.0) che il "nuovo" 3.x (fino alle SANP 3.2.1). E' corretto?

Grazie in anticipo.

**Comment by nardil** [comment]
Ciao @pperliti ,

GovPay supporta la modalità sincrona di integrazione e supporta tutti i modelli di pagamento. Per quanto riguarda le SANP, sono implementate le specifiche fino all'ultima versione rilasciata.

Alcune delle funzionalità più recenti (es. ACA e StandIn) le implementazioni sono in corso in linea con la Roadmap pagoPA. Puoi far riferimento a questa issue per un riepilogo della situazione: https://github.com/link-it/govpay/issues/533

**Comment by pperliti** [comment]
Grazie mille Lorenzo!

Per quanto riguarda il modello unico, mi pare di capire che richieda la versione V2 delle API ma, se ho capito bene, ci sono dei limiti legati alla situazione attuale, ad esempio:
1. l'APP IO ancora funziona con chiamate V1
2. nessun PSP attualmente in produzione gestisce già chiamate V2 (solo V1 per il momento)
Questo almeno mi è stato riferito dal team di Operations.

Stante che GovPay supporta entrambe le API V1 e V2, potrebbe aver senso creare due stazioni (una dedicata alle API V1 e una per le API V2) e inizialmente abilitare la sola V1?

**Comment by nardil** [comment]
PagoPA colloquia con l'EC utilizzando la versione delle API configurata su PdA, indipendentemente dalla versione utilizzata dai PSP.
