### ISSUE TITLE
Pagamenti doppi su GovPay

### ISSUE THREAD

**Issue by pperliti** [link-it/govpay#635]
Una curiosità. E' possibile per GovPay incassare pagamenti doppi a parità di IUV e EC?
Ho provato a simulare 2 GetPayment e 2 SendRTV2 differite per lo stesso IUV (a parità di EC) con receiptId diverse. Mi sarei aspettato che GovPay accettasse entrambe le ricevute (essendo i receiptId distinti) invece ha risposto PAA_RECEIPT_DUPLICATA.
Immagino sia corretto così tuttavia supponiamo per un attimo che un utente si presenti con un avviso presso il PSP X e paghi. Ipotizziamo anche che il nodo stia scodando richieste precedenti a seguito di un problema di carico e che dunque la RT non venga consegnata all'EC (il quale, a sua volta, non può chiudere la pendenza). L'utente potrebbe presentarsi presso un PSP 2 per ripagare l'avviso (non lo farebbe mai avendo già una quietanza liberatoria in mano, ma ragioniamo per assurdo). 
Non appena il nodo torna in condizioni di normale operatività, invierebbe le due RT all'EC: la prima passerebbe, la seconda verrebbe bloccata da GovPay. E' uno scenario realistico? E' corretto rifiutare 2 RT con receiptId diverso a parità di EC e IUV?

Grazie

**Comment by nardil** [comment]
> E' uno scenario realistico?

No. Le logiche introdotte di pagoPA prevengono la possibilita' di doppi pagamenti per uno stesso avviso
