### ISSUE TITLE
Keyword speciali da non stampare negli avvisi di pagamento

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#643]
**Necessità:**
Si vuole definire un'elenco di keyword che se identificate all'interno dell'input della procedura di creazione del pdf di avviso di pagamento non vengono stampate.

**Soluzione:**
Aggiungere una proprieta' di sistema per elencare tutte le keyword.

**Comment by nardil** [comment]
La funzionalità e' mirata ad evitare la stampa dell'identificativo del debitore nel caso di soggetto anonimo. 

Qualora si desideri non stampare il dato in presenza di valorizzazione ad `ANONIMO`, questa funzionalità lo consente. L'implementazione prevederà un elenco di keyword qualora gli applicativi utilizzino valori diversi da quello standard.
