### ISSUE TITLE
voce menu cruscotto su versione 3.7.4

### ISSUE THREAD

**Issue by asterixol2000** [link-it/govpay#645]
Buongiorno, 

sulla versione in oggetto, la voce di menu cruscotto non visualizza piu le label con il totale dei pagamenti rifutati o sospesi (forse per la sostituzione della voce menu pagamenti con quella ricevute) , questo comportamento è corretto ?

grazie
saluti

**Comment by nardil** [comment]
Ciao @asterixol2000 ,

si e' corretto: il processo di pagamento introdotto da pagoPA con il modello unico rende impossibile a GovPay individuare queste casistiche.
