### ISSUE TITLE
Sbloccare un pagamento in corso

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#651]
Ciao,
Da ieri è rimasto un pagamento in corso che non si riesce a sbloccare.
Posso intervenire per fare in modo di rendere pagabile l'avviso ?

Grazie,

**Comment by nardil** [comment]
Se non si desidera che GovPay impedisca transazioni di pagamento simultanee per uno stesso avviso, e' sufficiente impostare le seguenti proprieta':

```properties
# Imposta il numero di minuti che devono passare prima di attivare una nuova transazione di pagamento se la precedente non e' ancora conclusa (false: disabilita, 0: attende idefinitamente)
it.govpay.modello1.timeoutPagamento=false
it.govpay.modello3.timeoutPagamento=false
```

**Comment by SC015074** [comment]
Perfetto grazie.
