### ISSUE TITLE
Valorizzazione paymentMethod a other

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#652]
**Descrizione del Bug**
Ci sono dei casi di channelDescription = "NA" che restituiscono paymentMethod = "other".

Mentre forse dovrebbe essere OTH (salvo specifiche pagoPA più recenti che mi sono perso?)

**Risultato atteso:**
paymentMethod="OTH"

**Ambiente:**
 - GovPay: 3.7.4

Grazie

**Comment by nardil** [comment]
Ciao, puoi fornire maggiori informazioni sulle API che ti risultano esporre un dato non corretto ed esempi che chiariscano lo scenario?

**Comment by giuseppeformaro** [comment]
L'informazione arriva dal webhook a seguito di un pagamento eseguito. In particolare ci sono casi dove ricevo:
```
"channelDescription":"WISP"
"paymentMethod":"CP"
```
e casi dove ricevo:
```
"channelDescription":"NA"
"paymentMethod":"other"
```

Grazie

**Comment by nardil** [comment]
ma quei valori sono diversi da quanto indicato nelle corrispondenti ricevute?

Perché il dato non e' generato da GovPay, ma da pagoPA, quindi al netto di bug di esposizione del dato, e' un comportamento eventualmente da analizzare con pagoPA.

**Comment by giuseppeformaro** [comment]
Nella paSendRT effettivamente arriva:
`...
<paymentMethod>other</paymentMethod>
...`

Però mi aspettavo che corrispondeva a quello che vedo nel registro eventi di govpay:
`..."tipoVersamento":"PO"...`

**Comment by nardil** [comment]
> Nella paSendRT effettivamente arriva: `... <paymentMethod>other</paymentMethod> ...`
> 
> Però mi aspettavo che corrispondeva a quello che vedo nel registro eventi di govpay: `..."tipoVersamento":"PO"...`

@pintorig Le codifiche sono cambiate rispetto al tipoVersamento della v1: nel caso di v2 dobbiamo verificare che il tipoVersamento del giornale degli eventi riporti quanto indicato nel paymentMethod della ricevuta.

**Comment by pintorig** [comment]
@nardil 
Ok, ho modificato il comportamento per le primite PaSendRT e PaSendRTV2: il campo `datiPagoPA.tipoVersamento` viene ora valorizzato con il valore `receipt.paymentMethod`.

**Comment by pintorig** [comment]
Ulteriori modifiche necessarie:
- Modificare la definizione della colonna `tipo_versamento` della tabella RPT da varchar(4) a varchar (35) eliminando la gestione come enum, poiche' nel nuovo schema il campo `receipt.paymentMethod` e' una stringa senza vincoli.
- Nella funzionalita' di conversione dei messaggi nel vecchio formato se il valore presente nel DB non e' riconosciuto dalla vecchia enum verra' inserito il valore `OTH`.
- Aggiungere un nuovo valore alla enum `modello_pagamento` per indicare che si tratta di un pagamento del nuovo modello unico.
