### ISSUE TITLE
Includere il dettaglio dei messaggi nella visualizzazione del dettaglio di un evento

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#654]
**Necessità:**
Includere nella pagina di dettaglio di un evento anche i dati relativi al messaggio di richiesta e di risposta.

**Soluzione:**
Box 'Messaggio di richiesta' dovra' contenere i campi presenti all'interno dell'oggetto `parametriRichiesta`
- principal (utente opz.)
- dataOraRichiesta
- method URL
- Sezione richiudibile `Headers` opzionale che presenta una lista di coppie Nome:Valore
- Sezione richiudibile `Payload` opzionale che presenta il messaggio di richiesta (nel json e' una stringa che contiene un base64 si deve convertire in stringa)

Box 'Messaggio di risposta' dovra' contenere i campi presenti all'interno dell'oggetto `parametriRisposta`
- status
- dataOraRisposta
- Sezione richiudibile `Headers` opzionale che presenta una lista di coppie Nome:Valore
- Sezione richiudibile `Payload` opzionale che presenta il messaggio di risposta (nel json e' una stringa che contiene un base64 si deve convertire in stringa)

Eliminare dalla pagina il link per la visualizzazione nel nuovo tab.

**Screenshots:**
![Screenshot from 2023-11-16 15-39-14](https://github.com/link-it/govpay/assets/12812160/63417785-7e0b-4961-84d7-607bf6e0b435)

**Comment by atatarelli** [comment]
@pintorig Questa è una prima ipotesi di visualizzazione dei dati:

![image](https://github.com/link-it/govpay/assets/35455716/9c0a0332-1f95-47a4-86e8-54db9ff91602)

Non ho trovato un modo ottimale per visualizzare la "sezione richiudibile" per l'header e il payload.
Aspetto suggerimenti oppure esempio se questa modalità di visualizzazione è stata già usata.

**Comment by nardil** [comment]
Non importa che siano accordion, non sono molti dati. 

Gli header sono una lista di coppie nome/valore che puoi rendere sicuramente in forma più leggibile, mentre il payload devi decodificarlo dal base64. 

Ci sono payload che potrebbero essere grandi, ma solo nelle risposte. Valuta tu se gestire questa eventualità in modo particolare (eg. tramite modale)
