### ISSUE TITLE
Attualizzazione con API di Verifica e Notifica

### ISSUE THREAD

**Issue by SC015074** [link-it/govpay#657]
Ciao,
riscontro un problema sull'attualizzazione; se la data di validità è decorsa scatta la verifica pendenza per l'attualizzazione.
la chiamata arriva come /pendenze/IdA2A/idPendenza e fin qui tutto ok.

ma la risposta che torna indietro l'applicativo non viene gestita. 

La risposta è questa :
{
    "idA2A": "idA2A",
    "idPendenza": "0009426089020231121081445156",
    "idDominio": "12345678910",
    "causale": "violazione CDS",
    "importo": 1.1,
    "numeroAvviso": "304000000000123456",
    "voci": [
        {
            "idDominio": "12345678910",
            "idVocePendenza": "0009426089020231121081445156_01",
            "importo": 1.1,
            "descrizione": "violazione CDS",
            "ibanAccredito": "IT00X0111112100000011111111"
        }
    ]
}

l'errore è questo:
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `it.govpay.ec.v1.beans.PendenzaVerificata` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('....')

e mi lascia l'importo originale non modificato.

La risposta che torna l'applicativo è errata ?

Grazie,

**Comment by nardil** [comment]
> La risposta che torna l'applicativo è errata ?

Si, non risulta conforme alle [specifiche del servizio](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/link-it/govpay/master/jars/client-api-ente/src/main/resources/govpay-api-ec-v1.yaml&nocors#tag/Verifica/operation/verifyPendenza): ad esempio mancano i campi `stato` e `soggettoPagatore`
