### ISSUE TITLE
Problemi nella compilazione iniziale progetto stampe

### ISSUE THREAD

**Issue by onofabio** [link-it/govpay#659]
Nel processo iniziale di clean install con maven, nel modulo stampe ho sempre questo errore:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources (default-resources) on project stampe: filtering D:\GovPay\jars\stampe\src\main\resources\avviso\postale\AvvisoPagamento.jasper to D:\GovPay\jars\stampe\target\classes\avviso\postale\AvvisoPagamento.jasper failed with MalformedInputException: Input length = 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources (default-resources) on project stampe: filtering D:\GovPay\jars\stampe\src\main\resources\avviso\postale\AvvisoPagamento.jasper to D:\GovPay\jars\stampe\target\classes\avviso\postale\AvvisoPagamento.jasper failed with MalformedInputException

**Comment by onofabio** [comment]
Progetto versione 3.7.5 
5,185 commits

**Comment by onofabio** [comment]
Pensavo fossero i requisiti minimi.

**Comment by nardil** [comment]
Cosa intendi con `avviando lo script di installazione`?

**Comment by onofabio** [comment]
Ho capito il mio errore.
Al termine del comando prepareSetup.sh vengono creati 2 script di installazione.
Io ho avviato quello che viene creato nella cartella core, mentre quello da avviare è nella cartella target.

Ora devo installare wildfly?
Devo usare una versione specifica?
Nella documentazione parlano della 11 e della 18.
