### ISSUE TITLE
Errore Compilazione

### ISSUE THREAD

**Issue by pasqualeluciano** [link-it/govpay#661]
Buonasera, sto riscontrando un problema durante la compilazione (sicuramente legata alla mia poca esperienza con l'ambiente utilizzato per GovPay) allego screenshot (sembrerebbe un problema legato alla codifica dei caratteri se ho ben capito).
![Screenshot (1827)](https://github.com/link-it/govpay/assets/17334731/9fe3c235-ed68-4ecd-93ce-7c877b0f7c73)

**Comment by nardil** [comment]
Duplicate of #659
