### ISSUE TITLE
Problemi compilazione libraries supporta EC cryptography Bouncy Castle

### ISSUE THREAD

**Issue by onofabio** [link-it/govpay#662]
Ho provato a compilare il progetto su ambiente Ubuntu 20.04.6 LTS, ma nella fase iniziale mi viene restituito un errore per la mancanza di una libreria per cifratura, per cui viene indicato di installare Bouncy Castle, ma le istruzioni non mi fanno capire come fare quest'installazione.

L'errore che mi viene restituirto è questo:

[ERROR] Failed to execute goal org.owasp:dependency-check-maven:8.1.2:aggregate (check owasp) on project bom: Fatal exception(s) analyzing GovPay: One or more exceptions occurred during analysis:
[ERROR] 	UpdateException: org.owasp.dependencycheck.utils.DownloadFailedException: TLS Connection Reset
[ERROR] Please see http://jeremylong.github.io/DependencyCheck/data/tlsfailure.html for more information regarding how to resolve the issue.
[ERROR] 		caused by DownloadFailedException: TLS Connection Reset
[ERROR] Please see http://jeremylong.github.io/DependencyCheck/data/tlsfailure.html for more information regarding how to resolve the issue.
[ERROR] 		caused by SSLException: Connection reset
[ERROR] 		caused by SocketException: Connection reset
[ERROR] 	NoDataException: No documents exist
[ERROR] -> [Help 1]

Ci sono indicazioni per correggere il problema?

Grazie

Versioni:

Maven home: /opt/apache-maven-3.9.5
Java version: 13.0.7, vendor: Private Build, runtime: /usr/lib/jvm/java-13-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-1045-azure", arch: "amd64", family: "unix"

**Comment by onofabio** [comment]
Progetto versione 3.7.5 
5,185 commits

**Comment by nardil** [comment]
L'ambiente di compilazione non e' quello di riferimento indicato in documentazione. 

E' certamente possibile utilizzare uno stack applicativo diverso, ma può richiedere alcune configurazioni o modifiche aggiuntive che se verificate e completate saremo felici di integrarle nel progetto.

**Comment by onofabio** [comment]
Sembra che il problema fosse un blocco del firewall che impediva il download di alcuni file e non un problema di algoritmi di cifratura.
Il messaggio di help mi ha tratto in inganno.
