### ISSUE TITLE
Caricamento RT da Backoffice

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#67]
Un numero crescente di situazioni prevede che lo scambio di RT avvenga fuori dai servizi pagoPA. In particolare accade che a fronte di un errore di inoltro della RPT al PSP nel modello 3, il Nodo ne prende in carico la risposizione, ne accetta una rispedizione della RPT. 

Questi casi sono gestiti chiedendo al service desk pagopa le RT.

E' necessario quindi prevedere una funzionalita' di caricamento manuale delle RT ricevute via PEC sul cruscotto di backoffice.

**Comment by nardil** [comment]
La funzionalita' non copre lo scenario in cui il PSP non riceva la RPT. In questo caso non viene emessa RT che quindi non puo' essere gestita neppure offline.

Pertanto in caso di accettazione della RPT e successivo rifiuto per mancato inoltro e' necessario chiudere la transazione con la notifica, ma senza RT

**Comment by nardil** [comment]
Al momento la funzionalità non sembra risolvere gli scenari target. Sono pero' in studio da parte di AgID strategie per risolvere alla radice la problematica (eg la paaAllegaRPT). Aspettiamo evoluzioni in merito per valutare il percorso migliore.

**Comment by nardil** [comment]
La funzionalita' risulta necessaria da momento che in alcune circostanze il PSP debba revocare l'RT non utilizzando l'apposito servizio.

La RT viene solitamente inviata come tracciato XML. E' percio' necessario fornire ad un operatore di backoffice abilitato in scrittura sui pagamenti la possibilita di rimpiazzare l'RT

**Comment by nardil** [comment]
La casistica e' semplice nel caso si vada a sostituire una RT di non eseguito con una di eseguito, che e' l'unica casistica al momento verificata in produzione. Molto piu' complicata l'altra situazione. Pertanto nella prima versione di questa funzionalita' supporteremo solo questo scenario.

**Comment by pintorig** [comment]
Aggiunta possibilita' di caricare l'RT dalle API di Backoffice come operazione di PATCH del servizio RPP 684f51f71d63596b54f441cd4ca522ce1708d053.

**Comment by nardil** [comment]
Realizzare i seguenti testcase:
- [ ] Caricamento RT positiva di pagamento non eseguito (atteso 200)
- [ ] Caricamento RT negativa di pagamento non eseguito (atteso 200)
- [ ] Caricamento RT negativa o positiva di pagamento non concluso (atteso 200)
- [ ] Caricamento RT negativa di pagamento eseguito (atteso 422, operazione non supportata )
- [ ] Caricamento RT di altro pagamento (atteso 422, operazione non permessa)

**Comment by nardil** [comment]
@simo-git Aggiungere la possibilita di caricare la RT da cruscotto come operazione della transazione di pagamento.
