### ISSUE TITLE
Integrazione GovPay - Nodo dei Pagamenti pagoPa: ambiente di test

### ISSUE THREAD

**Issue by alessandro2024** [link-it/govpay#677]
Salve,
sto implementando un sito istituzionale che prevede sia servizi a pagamento da parte del cittadino che servizi con marca da bollo telematica dopo relativa autenticazione in area riservata con SPID.

Ho installato su un server la piattaforma di intermediazione GovPay e vorrei poter eseguire, tramite le API di integrazione della piattaforma stessa, il pagamento o l'acquisto della marca da bollo telematica in ambiente di test. Come posso configurare GovPay in ambiente di test versus il Nodo dei pagamenti-SPC? Quali le API? 

Grazie

**Comment by nardil** [comment]
Buongiorno,

per poter operare, la piattaforma GovPay deve prima essere abilitata al colloquio con i servizi pagoPA, ovvero:

- Aver creato una stazione di pagamento presso pagoPA indicando la tua di erogazione dei servizi
- Aver ottenuto la Subscription-key di fruizione dei servizi pagoPA
- Aver configurato su pagoPA e GovPay l'intermediazione dell'Ente

Puoi trovare maggiori informazioni sul processi di accreditamento a pagoPA nelle SANP: https://docs.pagopa.it/sanp/ente-creditore/adesione

Fatto questo puoi seguire gli esempi del manuale online per realizzare gli scenari di pagamento

**Comment by alessandro2024** [comment]
Gent.mo,
grazie per la risposta cosi celere.
Ho appena visto che l'ente per cui sto lavorando ha già dei servizi di pagamento verso, come da decreto legge, pagoPa e vedendo nel sito di pagoPA anche l'elenco degli 'Enti Creditori aderenti a pagoPA' verifico la presenza, in questa lista, dell'ente stesso.

Mi chiedevo pertanto, considerando che il processo di pagamento sarà gestito direttamente dal sito istituzionale (dominio istituzionale dell'ente creditore) senza alcun intermediario tecnologico se è necessario anche soddisfare il punto 3 di cui sopra: "Aver configurato su pagoPA e GovPay l'intermediazione dell'Ente".

In GovPay (installato su un server) ho configurato l'ente creditore, le tipologie di pendenze (marca da bollo telematica e pendenza libera) e desideravo cominciare ad integrare il sito istituzionale chiamando le specifiche API di GovPay per:
1- il pagamento di quei servizi conoscendo il 'codice IUV' (stazione di pagamento presso pagoPA);
2- l'esecuzione del pagamento della 'marca da bollo telematica' per quei servizi che la richiedono.

Cosa mi sta mancando prima di procedere? Qualche altra configurazione? 
Prima di passare al collaudo vorrei pertanto implementare il flusso del pagamento in un ambiente di test. 
E' possibile?
Grazie anticipatamente.

**Comment by nardil** [comment]
> Mi chiedevo pertanto, considerando che il processo di pagamento sarà gestito direttamente dal sito istituzionale (dominio istituzionale dell'ente creditore) senza alcun intermediario tecnologico se è necessario anche soddisfare il punto 3 di cui sopra: "Aver configurato su pagoPA e GovPay l'intermediazione dell'Ente".

Si, è necessario configurare il soggetto intermediario in GovPay (in caso di adesione diretta è l'ente stesso)

> Prima di passare al collaudo vorrei pertanto implementare il flusso del pagamento in un ambiente di test.
E' possibile?

Si, pagoPA ha un ambiente UAT dove poter effettuare i test.

**Comment by alessandro2024** [comment]
Gent.mo, 
grazie ancora per le preziose info.
Un ulteriore chiarimento cortesemente, al netto di quanto detto nei precedenti dialoghi.
Per i servizi a pagamento sarà sufficiente effettuare (conoscendo ad es. il valore dell'IUV) una chiamata del tipo:

 POST /govpay/frontend/api/pagamento/rs/basic/v2/pagamenti
 Accept: application/json
 Content-type: application/json"

 {
   "pendenze": [
     {
       "idDominio": "### p.iva ente ###",
       "numeroAvviso": "### IUV ###"
     }
   ]
 }  

e quindi senza la necessità di "caricare" relativa pendenza e successivo pagamento.

Per quanto riguarda invece il pagamento della Marca da Bollo Telematica nel portale GovPay viene detto: "che è realizzabile in maniera analoga ad un qualsiasi pagamento ad iniziativa ente".
Sarà necessario un pagamento spontaneo o dovuto? In entrambi casi comunque dovrò creare e caricare relativa pendenza di Marca da Bollo in GovPay ... ?

Oppure per il pagamento basterà una chiamata diretta del tipo:

{
	"idTipoPendenza" : "BOLLOT",
 	"causale": "### Pagamento ... ###",
	"soggettoPagatore": {
		"tipo": "### F ###",
		"identificativo": "### RSSMRA30A01H501I ###",
		"anagrafica": "### Mario Rossi ###",
		"email": "### mario.rossi@testmail.it ###",
		"cellulare": "### +39 000-0000000 ###"
	},
	"importo": 16.00,
	"tassonomia": "Servizi erogati dal comune",
	"idDominio": "### p.iva ente ###",
	"voci": [
		{
			"idVocePendenza": "1",
			"importo": 16.00,
			"descrizione": "Marca da bollo",
			"tipoBollo": "01",
			"hashDocumento": "### hash del documento ###",
			"provinciaResidenza": "### RO ###"
			
		}
	]
}

Nel JSON di cui sopra ho evidenziato con ### le parti variabili, le altre proprietà dovrebbero andare bene?

Grazie anticipatamente.

**Comment by nardil** [comment]
Ciao @alessandro2024 

l'invocazione della risorsa `POST /pagamenti` delle API di pagamento avvia il modello di pagamento ad iniziativa Ente "Modello 1". Puoi indicare nel payload il riferimento ad una pendenza precedentemente caricata oppure inserire la pendenza se già non presente negli archivi. In entrambi i casi i dettagli della pendenza da pagare devono essere disponibili a GovPay per gestire poi il colloquio necessario al pagamento.

Questa modalità "Modello 1" dovrà essere sostituita dalla chiamata `POST /carts` delle [API Checkout pagoPA](https://docs.pagopa.it/sanp/appendici/primitive#carts) che realizzano c.d. il pagamento "Modello Unico". Attualmente resta preferibile la modalità "Modello 1" perchè in fase di versamento sfrutta il WISP di pagoPA che propone una gamma di metodi di pagamento più ampia rispetto al nuovo Checkout. 

Per quanto riguarda invece la Marca da Bollo, vale quanto detto nella documentazione, ovvero che lo si realizza come una qualsiasi altra pendenza. Unica importante differenza è che non può essere pagato tramite "Modello 3", ovvero stampando l'avviso e andandolo a pagare presso un qualsiasi PSP: il pagamento fallirebbe. Deve invece essere pagato tramite "Modello 1" o Checkout pagoPA ed in fase di versamento vengono proposti i soli PSP che consentono il pagamento della Marca da Bollo.

**Comment by alessandro2024** [comment]
Gent.mo Lorenzo,
quindi nel rispetto del "Modello 1" devo sempre creare una pendenza ex-nova in GovPay sia che si tratti di un servizio a pagamento, sia che si tratti di Marca da Bollo Telematica in modo che venga alimentato l'archivio dei pagamenti in attesa? 

Ovviamente la tipologia di Pendenza (i.e. BOLLOT, SANZIONE) dovrà in primis essere configurata in GovPay e relazionata all'ente creditore. Solo dopo, quindi, potrò procedere al pagamento nel rispetto del "Modello 1" ?

Grazie.
