### ISSUE TITLE
Supporto ai metadata della RT custom

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#692]
**Necessità:**
Possibilità di indicare i metadata da includere nella Ricevuta di pagamento. Attualmente i metadata sono includi automaticamente da GovPay utilizzando i parametri di contabilità, se presenti. 

**Soluzione:**
Aggiungere ai dati di una voce pendenza la possiblità di indicare i metadata, ovvero una lista di 15 proprietà nome/valore. Se valorizzato, va a sostituire l'implementazione di default di GovPay ed inclusi nella risposta alla getPayment.

**Comment by pintorig** [comment]
@atatarelli 
Aggiungere la visualizzazione dei metadata all'interno del cruscotto.
