### ISSUE TITLE
Login , non assegnazione ruoli

### ISSUE THREAD

**Issue by FalboVincenzo** [link-it/govpay#694]
Ho quasi finito di implementare l applicativo govpay , con lo seguente stack java 11 , widfly  26 mysql 5.7 . Tutto è andato liscio come l olio , ma nel momento in cui cerco di effettuare il login con l account creato in fase di compilazione ottengo il seguente errore 

{
    "categoria": "INTERNO",
    "codice": "500",
    "descrizione": "Errore interno",
    "dettaglio": "Errore interno, impossibile autenticare l'utenza"
}

Guardando i log ho notato che non vengono assegnati i ruoli .

![log_wildfly](https://github.com/link-it/govpay/assets/47213621/cc54074e-aba3-458d-b902-f2808a686800)
 La connessione con il db testata , schema creato correttamente.

Grazie anticipatamente

**Comment by nardil** [comment]
Ciao @FalboVincenzo ,

viene indicato un errore interno, quindi nei log di GovPay (per default in `/var/log/govpay/`) dovresti trovare un Error che fornisce maggiori informazioni sulla causa del problema.
