### ISSUE TITLE
Modifica pendenza

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#696]
Ciao,
per modificare una pendenza con il path corretto c'è uno schema ?
provando  con PATCH:
```json
[
    {
        "op": "REPLACE",
        "path": "/dataScadenza",
        "value": "2024-03-31"
    }   
]
```
oppure :
```
[
    {
        "op": "REPLACE",
        "path": "/importo",
        "value": 1.00
    }   
]
```
La response è sempre :
```
{
    "categoria": "RICHIESTA",
    "codice": "SINTASSI",
    "descrizione": "Richiesta non valida",
    "dettaglio": "Il campo path non e' valido."
}
```
Grazie.

**Comment by nardil** [comment]
Ciao @giuseppelab ,

il comando patch non e' stato implementato per tutti i campi della pendenza. Al momento per aggiornare l'importo e' necessario utilizzare il metodo `PUT` fornendo i dati della pendenza aggiornata.

**Comment by SC015074** [comment]
Ciao Lorenzo,
perfetto grazie.
