### ISSUE TITLE
Gestione cambio IBAN

### ISSUE THREAD

**Issue by bianchi74** [link-it/govpay#698]
## Operazioni per la gestione del cambio di IBAN attestato su pagoPA

Buongiorno, 

nell'ambito di un'attività volta alla **sostituzione dell'IBAN** di riferimento per un applicativo integrato con pagoPA per mezzo di govPay, abbiamo proceduto con successo al cambio di coordinate bancarie dalla dashboard e le nuove pendenze vengono correttamente create utilizzando il nuovo IBAN.

Diversamente, tutte le pendenze **create prima del cambio IBAN** ancora contengono al loro interno, nell'oggetto jSON _voci_, il vecchio _ibanAccredito_. Questo fa sì che tali pagamenti siano ancora accreditati sul vecchio conto corrente.

Dovendo urgentemente dismettere il vecchio conto corrente vi chiediamo quale sia la strada più veloce e sicura per aggiornare l'IBAN nelle suddette pendenze.
 
Abbiamo provato con il metodo PATCH, ma ci sembra di capire che quel metodo non sia per tutti i campi.

Inoltre su alcune PUT di prova (fatte per aggiornare altri campi) govPay (API Pendenze) ci restituisce il seguente errore:

{"categoria":"RICHIESTA","codice":"VER_023","descrizione":"Richiesta non valida","dettaglio":"La pendenza (IdA2A:LICPT, Id:L61636-2024-0-A26) ha la voce (1) con un iban di accredito diverso dall'originale."}

Vi ringraziamo anticipatamente per il cortese e (speriamo :-) ) veloce riscontro.

Marco Bianchi

**Comment by nardil** [comment]
Ciao Marco,

dai uno sguardo alla issue #584 che affronta il medesimo scenario.

Un saluto

**Comment by nardil** [comment]
Abbiamo avviato le analisi nella issue #702 per una futura integrazione in GovPay di una funzione che gestisca questo scenario.

**Comment by bianchi74** [comment]
Grazie mille.
Un saluto
