### ISSUE TITLE
Verifica importo

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#700]
Salve,
è possibile far scattare la verifica anche se non è decorsa la data di validità ?
O sono previste altre modalità per la verifica dell'importo in fase di pagamento ? in caso di verifica di importi di notifica SEND ?

Grazie.

**Comment by pintorig** [comment]
Salve @giuseppelab,
e' possibile far eseguire sempre la verifica indicando una data di validità decorsa.

Per gestire il caso da te indicato in cui si deve verificare l'importo dell'avviso in fase di pagamento dalla versione 3.8.0 (Issue #621) sara' possibile realizzare il seguente scenario utilizzando i campi `dataValidita` e `proprieta.dataScadenzaAvviso` di una pendenza:

``` json
{
...
"dataValidita": "2000-11-30",
 "proprieta": {
           "dataScadenzaAvviso": "2023-12-31"
           }
...
}
```

- all'interno del campo `dataValidita` si indica una data decorsa cosi da scatenare la verifica e l'eventuale aggiornamento dell'importo in fase di pagamento.
- nel campo `dataScadenzaAvviso` si inserire la vera data di validita' cosi da visualizzarla nell'avviso di pagamento.

Ulteriori dettagli sulla gestione della data scadenza degli avvisi si possono trovare all'interno della [documentazione](https://govpay.readthedocs.io/it/3.8.x/howto/dataScadenzaAvvisi.html).

**Comment by giuseppelab** [comment]
Salve @pintorig,
ok grazie.
