### ISSUE TITLE
Configurazione intermediario GovPay - PagoPA

### ISSUE THREAD

**Issue by MinguccioPigiamino** [link-it/govpay#712]
Stiamo configurando GovPay in qualità di intermediario PagoPA: tuttavia, anche consultando le guide SANP e https://govpay.readthedocs.io/it/latest/ non ci sono chiari alcuni passaggi per i quali chiediamo se possibile alcuni chiarimenti.

Riporto i parametri attuali e i ns dubbi:

-- Su PagoPA, ci siamo abilitati come partner, generato le API key per la connessione e in creazione stazione inserito endopoint modello unico:
https://<<il nostro FQDN>>/govpay/frontend/api/pagopa/

-- Su GovPay, in creazione intermediario
Principal:
CN=forwarder.uat.platform.pagopa.it    (oppure andrebbe CN=uat.platform.pagopa.it)

Servizio RPT:
https://api.uat.platform.pagopa.it/nodo-auth/nodo-per-pa/v1

Ocp-Apim-Subsciption-Key:
<<api key primaria ottenuta da PagoPA>>

Tipo autenticazione: lasciamo -Nessuna- oppure occorre selezionare SSL, TLS e i dati del JKS? In questo caso occorre trarre la CA dal certificato di api.uat.platform.pagopa.it?

Autenticazione Client: è necessaria?

Ringraziamo anticipatamente per il vostro supporto.

**Comment by nardil** [comment]
Ciao @MinguccioPigiamino ,

- L'endpoint per il modello unico e' `/govpay/frontend/api/pagopa/PagamentiTelematiciCCPservice`
- In caso di comunicazione diretta tra GovPay e pagoPA (collaudo) vanno impostati i seguenti:
   - Principal: `cn=forwarder.uat.platform.pagopa.it`
   - Servizio RPT: `https://api.uat.platform.pagopa.it/nodo-auth/nodo-per-pa/v1`
   - Ocp-Apim-Subscription-Key: `xxxxxxxx`
   - Tipo autenticazione: SSL
   - Configurazione del trustore per api.uat.platform.pagopa.it

**Comment by temptationisla** [comment]
Ciao @nardil ho seguito le tue indicazioni sopra per il principal ma riceviamo questo errore con la versione di Govpay 3.7.7:

<paaInviaRTRisposta><fault><faultCode>PAA_SYSTEM_ERROR</faultCode><faultString>Errore generico.</faultString><id>Autorizzazione fallita: principal fornito (CN=forwarder.platform.pagopa.it) non valido per l'intermediario (03257851208).</id><description>80003610690</description></fault><esito>
