### ISSUE TITLE
Nascondere comando "recupera pagamenti" dal menu' del cruscotto

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#713]
In caso di nuova installazione con il solo modello unico, il comando "Recupera pagamenti" perde di significato.

Per gestire la problematica si deve agire su due punti:

1. Prevedere una proprieta' nella configurazione di GovPay per disabilitare le operazioni legacy.
2. Prevedere una proprieta' nella configurazione del cruscotto per nascondere il comando all'utente.

**Comment by nardil** [comment]
La proprietà per disattivare il batch di recupero pendenti e' già disponibile. 

Manca invece la possibilità di nascondere la voce dalla sezione Manutenzione della console.
