### ISSUE TITLE
Recupero RT TEFA Ente Provinciale

### ISSUE THREAD

**Issue by argomauro** [link-it/govpay#715]
Chiedo supporto per capire come consentire ad un ente Provinciale, che riceve come Beneficiario secondario pagamenti TEFA, di recuperare i dettagli di questi pagamenti.
Su Pagopa Selfcare è stato impostato il broadcast per questo ente e Govpay riceve correttamente i flussi di rendicontazione ma non i dettagli dei singoli pagamenti che nello specifico non sono emessi dall'ente in questione.
C'è un modo di recuperare queste RT?
Grazie

**Comment by argomauro** [comment]
Buongiorno, ad integrazione di quanto descritto aggiungo che l'ente in questione è stato attivato sul Portale delle adesioni , sulla nostra stazione, con "Broadcast" a True ed infatti nei flussi di rendicontazione riceviamo già i pagamenti ma non riusciamo a vedere i dettagli. C'è un modo per accedere a queste RT? Grazie

**Comment by nardil** [comment]
Ciao @argomauro ,

l'attuale versione di GovPay non recepisce le RT di pagamenti gestiti da altri intermediari, pertanto non ne hai visibilità nella console pur vedendone la rendicontazione.

Stiamo pero' sviluppando una soluzione dedicata alla riconciliazione pagoPA che gestisca questo scenario e consenta la riconciliazione completa dei pagamenti di un EC indipendentemente dagli intermediari utilizzati.

**Comment by argomauro** [comment]
Ciao @nardil grazie per la risposta, sarebbe ottimo davvero avere a disposizione questa funzionalità.
Possiamo essere di supporto in qualche modo in questo specifico task?
Nel frattempo che tu sappia possiamo ovviare in qualche modo, anche solo nella ricezione (senza elaborazione o visualizzazione in console) ?

**Comment by nardil** [comment]
Potete configurare una stazione lato pagoPA su cui abilitare il broadcast ricevendo copia delle RT su un endpoint dedicato allo scopo.

**Comment by argomauro** [comment]
Grazie @nardil del suggerimento, avevamo immaginato una soluzione di questo tipo se non fosse che l'ente in questione utilizza Govpay per i suoi pagamenti come EC primario e di conseguenza non riusciamo a configurare lo stesso ente su un'altra stazione come EC secondario per ricevere solo le 'altre' RT.
Non ci resta che provare a creare un workaround su Govpay e fargli registrare da qualche parte tutte le RT a prescindere dai controlli di integrità sui dati dei pagamenti che gestisce per lo stesso ente.
Non so se ci riusciremo nell'impresa ma non vedo altre possibili soluzioni. Cosa ne pensi?
