### ISSUE TITLE
In caso di mancanza del Codice Fiscale viene stampato "ANONIMO" invece che lasciare vuoto il campo

### ISSUE THREAD

**Issue by tizianatinnirello** [link-it/govpay#716]
GovPay: Versione: 3.7.6 (a10e360)

Non va in nessun modo, ho provato con "", "  " e "ANONIMO".

Mi sfugge qualcosa?

**Comment by pintorig** [comment]
Salve @tizianatinnirello,

per utilizzare la funzionalita' richiesta hai bisogno di valorizzare la seguente proprieta' 


```
# Lista di keyword che se individuate all'interno dei campi CF e Anagrafica Debitore vengono sostituite con stringa vuota (separati da ',')
it.govpay.stampe.avvisoPagamento.identificativoDebitore.nascondiKeyword=ANONIMO
```

Fammi sapere se risolve il tuo problema.
