### ISSUE TITLE
[API Notifica] Ricevute PagoPA v2

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#718]
Buongiorno,
Ho implementato nella mia applicazione l'api di notifica per la ricezione delle ricevute di pagamento. Da qualche tempo però arrivano delle ricevute PagoPA v2 (in inglese) e vorrei allineare l'api per gestire anche questo tipo di ricevute.
Vi chiedo quindi : 

- dove posso trovare, tra i sorgenti i dettagli del bean relativo alla ricevuta v2 ?
- come posso, dalla piattaforma di collaudo di pagopa, fare in modo di ricevere una notifica di pagamento di questa versione ? devo avviare il pagamento in qualche modo particolare ?

Grazie come sempre del supporto

**Comment by nardil** [comment]
Ciao @frdidonato ,

- il formato della ricevuta con le API v2 di pagoPA (`ctReceipt`) replica quello originale XML di pagoPA di cui trovi l'XSD nel loro progetto GitHub
- su nuova connettivita' e su Modello Unico, la ricevuta e' disponibile solo in v2. E' sufficiente avviare il pagamento dal Checkout.

Se fosse utile in qualche modo, faccio presente che su GovPay e' disponibile una funzione di retrocompatibilita' per convertire le ricevute v2 in v1 per le API preesitenti all'introduzione del nuovo formato (eg Backoffice v1, Pendenze v1 e v2, ....):  `it.govpay.retrocompatibilitaMessaggiPagoPA.v1.enable=true`

**Comment by frdidonato** [comment]
Ciao @nardil  e grazie per la risposta.
Ho pensato anche io di impostare la funzione di retrocompatibilità in modo da non dover modificare il codice che gestisce la notifica di avvenuto pagamento, ma mi chiedevo se un giorno o l'altro la eliminerete.

Per quanto riguarda il tema della notifica per il momento credo di disabilitarla in favore di una vista che contatti direttamente le api di govpay per visualizzare i pagamenti effettuati, ma alcune informazioni non sono presenti (tipo distinzione tra soggetto pagatore e soggetto versante). Inoltre non è presente una funzionalità di ricerca, ad esempio, per nominativo del soggetto pagatore o versante cosa che per molti utilizzatori risulta essenziale. Tramite la notifica invece ho modo di salvare sul mio db un dato strutturato contenente tutte queste informazioni e posso quindi implementare delle ricerche con più dati.

Avete in programma di migliorare questa ricerca ? parlo sia delle api di pagamento frontend che quelle di backoffice.

**Comment by nardil** [comment]
Le informazioni esposte da GovPay relative alla ricevuta sono quelle messe a disposizione da pagoPA. PagoPA nella versione 2 delle ricevute ha rimosso l'informazione del soggetto versante.

Se altre informazioni risultano non disponibili puoi sicuramente segnalarcelo.

**Comment by frdidonato** [comment]
> Le informazioni esposte da GovPay relative alla ricevuta sono quelle messe a disposizione da pagoPA. PagoPA nella versione 2 delle ricevute ha rimosso l'informazione del soggetto versante.
> 
> Se altre informazioni risultano non disponibili puoi sicuramente segnalarcelo.

Salve nuovamente, mi chiedevo dove venissero inserite, nella Notifica v2 le informazioni relative alla marca da bollo che prima si trovavano nei dati del singolo pagamento, dal quale ero in grado di estrapolare l'xml firmato digitalmente della marca. Ho visto che anche in fase di conversione retrocompatibile con le api v1 l'AllegatoRicevuta non viene compilato
