### ISSUE TITLE
[API Pagamenti Backoffice] - Alcuni pagamenti non vengono restituiti

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#719]
Salve a tutti,
Stavo notando che, interrogando l'api di Backoffice per i pagamenti, non mi vengono restituiti tutti i pagamenti realmente effettuati. Al momento sul cliente X da govpay vedo 167 ricevute ma dall'api mi vengono restituiti 60 Risultati. 
Ho notato che sempre da queste api, la ricerca per IUV non produce alcun risultato se il pagamento è un pagamento PagoPA V2. Sembra in pratica che non mi vengano restituiti i pagamenti con ricevuta V2. Come devo comportarmi per ottenere la lista completa dei pagamenti effettuati su un creditore ? Attualmente utilizzo la versione 3.7.4

**Comment by pintorig** [comment]
Salve @frdidonato,
a partire dalla versione 3.7.0 quando un pagamento viene effettuato con API PagoPA V2 non vengono piu' registrati i tentativi di pagamento. 

La risorsa `/pagamenti` verra' presto deprecata ma e' ancora disponibile in questa fase di transizione poiche' viene garantito il supporto per entrambe le versioni delle API PagoPA.

I dati restituiti pero' so riferiscono ai soli pagamenti effettuati con le API V1 (vecchio Modello 1).

Per aver evidenza di tutti i pagamenti effettuati si puo' utilizzare la risorsa 
`/rpp?idDominio=IDDOMINIO&esito=ESEGUITO`.

**Comment by pintorig** [comment]
Nella prossima versione 3.7.8 deprecare il servizio `/pagamenti` delle API Backoffice.

**Comment by frdidonato** [comment]
@pintorig grazie mille, effettivamente tramite l'api /rpp riesco ad ottenere le informazioni necessarie.

**Comment by pintorig** [comment]
Deprecato servizio `/pagamenti`, intervento realizzato nel commit 91d1e4a60543e9687130dc2dd87ddf7889c1f202.
