### ISSUE TITLE
Errore autorizzazione lettura dettaglio ricevuta api ragioneria v3

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#724]
**Descrizione del Bug**
Attualmente in fase di lettura del dettaglio di una ricevuta nelle API Ragioneria viene controllato se l'applicazione e' proprietaria della pendenza riferita dalla ricevuta.
Il comportamento non coincide con quello della listaRicevute dove l'autorizzazione e' fatta sui domini associati all'applicazione.

**Come riprodurlo:**

1. Caricare e pagare una pendenza per il Dominio1 con l'applicazione A1
2. Interrogo il servizio Ricerca delle ricevute di pagamento con l'applicazione A2 autorizzata per il Dominio1 `http://localhost:8080/govpay/backend/api/ragioneria/rs/basic/v3/ricevute?idDominio=idDominio1`
3. Prendo le seguenti chiavi della ricevuta
`"iuv": "01000000000730501",
"idRicevuta": "010000000007305017560"`
4. Interrogo il servizio Acquisizione di una ricevuta di avvenuto pagamento pagoPA con l'applicazione A2
`http://localhost:8080/govpay/backend/api/ragioneria/rs/basic/v3/ricevute/idDominio1/01000000000730501/010000000007305017560`
5. Ricevo l’output
``` json
{
    "categoria": "AUTORIZZAZIONE",
    "codice": "403000",
    "descrizione": "Operazione non autorizzata",
    "dettaglio": "Applicazione [A2] non autorizzata ad accedere alla risorsa richiesta: la transazione riferisce una pendenza che non appartiene all'applicazione chiamante."
}
```

**Risultato atteso:**
La lettura del dettaglio con l'applicazione A2 deve andare a buon fine poiche' autorizzata sul Dominio1

**Comment by nardil** [comment]
La pipeline sul branch 3.8.x fallisce
