### ISSUE TITLE
API integrazione PUT pendenza con voci MBT e parametro stampaAvviso

### ISSUE THREAD

**Issue by lscorcia** [link-it/govpay#728]
**Descrizione del Bug**
Utilizzando l'API di integrazione PUT pendenza, è possibile passare il parametro query stampaAvviso per farsi generare il PDF dell'avviso da mostrare all'utente. Sfortunatamente però se la pendenza contiene voci di tipo Marca da Bollo Telematica il PDF dell'avviso non ha senso in quanto non è possibile pagare presso PSP avvisi contenenti tale tipo di pendenza. Infatti GovPay nella chiamata di stampa non genera il numero di avviso e il modello non risulta pagabile. Nel QR code sul PDF viene cablato il testo 'null' al posto del numero.

**Come riprodurlo:**
Creare una pendenza mediante l'API PUT pendenza contenente una voce MBT; passare il parametro stampaAvviso a true e visionare il PDF generato.

**Risultato atteso:**
La chiamata all'API di pagamento dovrebbe fallire segnalando che la stampa avviso non è prevista per le pendenze contenenti voci MBT, o se non si vuole farla fallire, per lo meno il PDF generato non dovrebbe avere un QR code.

**Note aggiuntive:**
Anche l'UI di GovPay si comporta in modo incoerente. Aprendo una pendenza con voce MBT e selezionando Stampa Avviso dal menu dei tre puntini in alto a destra, non viene eseguito nulla e non viene mostrato alcun errore all'utente.

**Comment by nardil** [comment]
Ciao @lscorcia ,

anche in caso di Pendenze con pagamento di Marca da Bollo e' associato un Numero Avviso che deve essere noto ai sistemi per poter avviare un Pagamento ad iniziativa Ente (eg per l'invocazione del servizio Checkout). E' quindi necessario verificare che in risposta alla creazione il dato sia presente.

Allo stato attuale dei servizi pagoPA, resta l'impossibilita' di effettuare il pagamento ad iniziativa PSP di una Marca da Bollo, pertanto e' corretto che il sistema non stampi l'avviso che poi risulterebbe non pagabile. Da verificare quindi che l'avviso non venga prodotto.

Riassumendo, in caso di pendenze con MBT:
- [ ] Verificare presenza di numero avviso nella risposta di `POST /pendenze`
- [ ] Verificare che la stampa dell'avviso sia assente in risposta a tutte le risorse che la prevedono oppure che restituiscano errore
- [ ] Verificare che la GUI non consenta il download della stampa avviso in presenza di MBT: opzione in grigio (disabilitata) con un tooltip che chiarisca il motivo della disabilitazione oppure l'opzione disponibile, ma che risulti in un errore di "Avviso non disponibile per pagamenti di Marca da Bollo".
