### ISSUE TITLE
Chiarimenti su scelta modalità integrazione PagoPA (API Sincrone / API Asincrone)

### ISSUE THREAD

**Issue by massicosta74** [link-it/govpay#729]
Gentile team di GovPay,
stiamo adottando la piattaforma GovPay (v.3.7.4) nell'infrastruttura del Ministero della Cultura come gateway verso PagoPA.
Proprio PagoPA ci sta richiedendo di effettuare una scelta sulla modalità di integrazione da adottare, scegliendo tra:
- API Sincrone
- API Asincrone

Non avendo trovato materiale documentativo che spieghi nel dettaglio queste due modalità, prima di rispondere a PagoPA, vorremmo capire in pratica cosa comportano le due scelte, **se GovPay le supporta entrambe**, e che impatto avrebbero sulle primitive GovPay in vista dell'adeguamento da effettuare sul nostro software entro marzo 2025 (entità dell'effort relativamente a entrambe le scelte).

Crediamo che questo chiarimento possa essere utile a tutti i PT che si trovino nella stessa condizione di dover scegliere la modalità di integrazione e rispondere a PagoPA.

Ringrazio in anticipo per la preziosa risposta

**Comment by nardil** [comment]
Ciao @massicosta74 ,

la tipologia di integrazione realizzata da GovPay con pagoPA e' quella SINCRONA, ovvero con repository APA gestito dall'Intermediario/Partner. Per maggiori informazioni sulle implicazioni che questa scelta ha sull'intermediario si rimanda alla documentazione ufficiale e alle discussioni sui vari canali (eg: https://github.com/pagopa/pagopa-api/issues/976 , https://github.com/pagopa/pagopa-api/issues/997)

Le integrazioni necessarie richieste dalla specifica entro il Q1 2025, ovvero il supporto al servizio Stand-in e l'alimentazione dell'ACA, sono in corso di sviluppo ed attualmente in attesa del rilascio da parte di pagoPA in ambiente UAT delle primitive necessarie pianificate da pagoPA per fine Settembre 2024.

Tutte le evolutive realizzate in GovPay di adeguamento alle specifiche pagoPA vengono progettate e realizzate con l'obiettivo di mantenere la retrocompatibilita' con le integrazioni esistenti. Attualmente non sono state individuate criticita' che impediscano mantenere i servizi retrocompatibili.
