### ISSUE TITLE
Nuovo avviso di pagamento v2.1: adeguamento campo destinatario Bollettino Postale

### ISSUE THREAD

**Issue by jack982** [link-it/GovPay#73]
Salve,

il template Jasper Report per la generazione del nuovo avviso di pagamento presenta un refuso: in pratica anziché stampare, nella sezione Bollettino Postale, il nome e cognome del destinatario del pagamento (placeholder $F{nome_cognome_destinatario}), stampa il placeholder $F{ente_creditore}

Jacopo

**Comment by nardil** [comment]
Ciao @jack982 , 
abbiamo verificato e corretto la tua segnalazione tra le modifiche contenute in 44f123322129d558de49064dbee8cbff7109921e e inclusa nella RC3 di prossimo rilascio
