### ISSUE TITLE
Passaggio da GAD a Nuova connettività

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#730]
Abbiamo installato 4 anni fa Govpay ed è tutt'oggi operativa la versione 3.2.2 in ambiente GAD di Pagopa. Ora Pagopa ci obbliga a passare alla nuova connettività, in quanto il GAD verrà dismesso. Quali sono le operazioni da svolgere? In accordo con PagoPa approfitteremo per cambiare anche server verso uno più performante.

Abbiamo le chiavi API per la configurazione verso la nuova connettività. GovPay le gestisce?

**Comment by temptationisla** [comment]
Grazie @nardil, ma sarà cambiato anche tutta la struttura del database immagino

**Comment by nardil** [comment]
Nella documentazione e' descritto come gestire l'aggiornamento di versione e l'applicazione delle patch al database.

https://govpay.readthedocs.io/it/latest/installazione/aggiornamento/index.html

**Comment by giuseppelab** [comment]
Ciao, installata come aggiornamento la 3.7.7 per avviare la migrazione di connettività.
tutto viene raggiunto correttamente tranne le api-pagopa dal nodo (se verifico i wsdl in get rispondono correttamente); Sembra che chiamando in POST come farebbe il nodo pagamenti, govpay restituisce:
{
    "categoria": "AUTORIZZAZIONE",
    "codice": "401",
    "descrizione": "Autenticazione richiesta.",
    "dettaglio": "Full authentication is required to access this resource"
}
Abbiamo provato ad invocare in POST la url :
/govpay/frontend/api/pagopa/PagamentiTelematiciCCPservice?OpenSPCoop2IdTransazione=.........
il file api-pagopa-applicationContext-security.xml è quello rilasciato, senza modifiche.
C'è qualcosa da verificare in configurazione ? 
Grazie

**Comment by nardil** [comment]
Duplicato di #733
