### ISSUE TITLE
Dismissione generazione IUV ISO11694

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#731]
**Necessità:**
Dismettere la generazione degli IUV nel formato ISO11694 e uniformarsi ai soli IUV numerici.

Attualmente il formato ISO11694 e' utilizzato dal vecchio modello1.

**Soluzione:**
~GovPay consenti di scegliere il tipo di IUV da generare per il vecchio modello 1 la proprieta' 
`it.govpay.dismettiIuvIso11694=[false|true]`~

~Eliminare la possibilita' di scegliere il formato ISO11694 ed utilizzare solo IUV numerici.~

**Comment by nardil** [comment]
E' necessario procedere alla completa dismissione dell'uso di IUV ISO11694. Si ripianifica quindi l'intervento nella versione 3.8.0.

**Comment by pintorig** [comment]
Intervento realizzato in #753
