### ISSUE TITLE
svecchiamento tabella eventi

### ISSUE THREAD

**Issue by massicosta74** [link-it/govpay#732]
Salve a tutti,
dopo aver impostato in "Impostazioni/Giornale degli Eventi" tutto acceso (a "Sempre"):
![eventi](https://github.com/user-attachments/assets/6bc5350b-86d2-488a-b4b3-083bd7fdacfd)
abbiamo purtroppo notato un notevole consumo di spazio db, proprio nella tabella "eventi".
Ovviamente abbiamo cambiato queste impostazioni, ma ci chiedevamo se ci fosse un modo per "svecchiare" la tabella eventi, oramai assai ingrossata, eliminando gli eventi più vecchi, senza correre il rischio di compromettere il database.

Grazie come sempre per il supporto

**Comment by nardil** [comment]
Ciao @massicosta74 

gli eventi del giornale hanno finalita' di monitoraggio e diagnostica, quindi la loro eliminazione non ha effetti sul workflow di pagamento. Il periodo di data retantion dipende da vostre esigenze interne (non ci risulta che ci siano normative che regolano questa tipologia di informazioni) come la tipologa e verbosita' degli eventi registrati.

Potete controllare in #707 per recuperare gli script di svecchiamento dati.

**Comment by massicosta74** [comment]
Grazie 1000, molto utile!
