### ISSUE TITLE
Aggiornamento da 3.6.6 a 3.7.7

### ISSUE THREAD

**Issue by giuseppelab** [link-it/govpay#733]
Ciao,
stiamo aggiornando in collaudo la versione di GovPay da 3.6.6 a 3.7.7 (jdk 11 e WildFly 26).
nella nostra situazione il nodo arriva su reverse proxy Apache in ssl e poi Apache gira in BASIC verso GovPay.

Sulla 3.6.6 tutto gira senza problemi; sulla 3.7.7, per le sole api-pagopa rileviamo un messaggio di ritorno con utente non riconosciuto.
La parte BASIC non funziona alla stessa maniera ?

Abbiamo provato a passare tutto in SSL con Apache che gira a GovPay in ajp sulla porta 8009.
Sul log rileviamo il seguente errore:

2024-07-28 14:12:17.941 | INFO  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:1151 | 20f34220-de4a-4d3d-97f8-506ba3bb9258 | Ricevuta richiesta paVerifyPaymentNotice [09613270157][09613270157_02][01426410880][301000000000051601]
2024-07-28 14:12:17.968 | WARN  | it.govpay.web.ws.PagamentiTelematiciCCPImpl:1814 | 20f34220-de4a-4d3d-97f8-506ba3bb9258 | Errore in PaVerifyPaymentNotice: it.govpay.core.exceptions.NotAuthorizedException: Operazione non autorizzata
it.govpay.core.exceptions.NdpException: it.govpay.core.exceptions.NotAuthorizedException: Operazione non autorizzata

Stiamo saltando qualche configurazione ?

Grazie

**Comment by pintorig** [comment]
Ciao @giuseppelab,

 nella versione 3.7.7 le API-PagoPA hanno come default l'autenticazione SSL.

Dovresti eseguire l'installazione con i file di sicurezza esterni e abilitare quindi l'autenticazione BASIC al posto di quella SSL.

**Comment by giuseppelab** [comment]
Ciao @pintorig grazie,
installato con file di sicurezza esterni ed abilitato BASIC e commentato SSL.
Provando la raggiungibilità dei wsdl mi restituisce:
{
    "categoria": "AUTORIZZAZIONE",
    "codice": "401",
    "descrizione": "Autenticazione richiesta.",
    "dettaglio": "Username 'gpadmin' not found"
}
Il comportamento sembra diverso dalla 3.6.6

**Comment by nardil** [comment]
Le modalita' di autenticazione o i default impostati non sono variati dalla versione 3.6 alla 3.7.  L'errore riportato indica che l'autenticazione e' operativa e viene autenticata l'utenza `gpadmin` che non e' quella prevista per il servizio richiesto.

Va verificata l'utenza autorizzata o che il test effettuato sia corretto.

**Comment by giuseppelab** [comment]
Grazie @nardil,
abbiamo applicato la stessa configurazione della 3.6.6; abbiamo provato anche a regredire ed il test da pagoPA è andato a buon fine. 
Ripassando alla 3.7.7 rileviamo lo username not found.
Bisogna creare un nuovo utente amministratore che sia autorizzato alle api-pagopa ?
Grazie,

**Comment by giuseppelab** [comment]
OK, il problema è in wildfly 26. cercherò di capire il motivo.
Grazie ancora.

**Comment by pintorig** [comment]
@giuseppelab

L'autenticazione BASIC delle API PagoPA utilizza le utenze presenti nel file `WIDLFLY_ROOT/standalone/configuration/application-users.properties` verificate di aver riportato le utenze censite nel vecchio AS.

**Comment by giuseppelab** [comment]
Ciao @pintorig, era proprio questo, non erano state migrate le utenze.
Grazie.
