### ISSUE TITLE
Download RT xml

### ISSUE THREAD

**Issue by giuseppeformaro** [link-it/govpay#739]
Ciao,
è possibile scaricare massivamente le RT xml di un Ente se ci vengono richieste?

**Comment by nardil** [comment]
Le API non consentono un download massivo, ma puntuale, pertanto dovreste eventualmente realizzare una procedura che realizzi un download massivo basato su quello puntuale.

Per inviare i tracciati ad un ente e' comunque possibile:

- Configurare il connettore di notifica nell'applicativo per un invio tramite web service
- Attivare nella configurazione dell'Ente il [connettore GovPay](https://govpay.readthedocs.io/it/latest/cruscotto/configurazione/enti/connettore_govpay.html#govpay-configurazione-connettori-govpay) per l'invio tramite mail
- Gestire la cosa da backoffice con un'estrazione da db

**Comment by giuseppeformaro** [comment]
Grazie mille.
