### ISSUE TITLE
Rendicontazioni non disponibili tramite API se non contengono almeno un pagamento transitato su Govpay

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#742]
Buongiorno a tutti. Mi trovo ad affrontare una questione spinosa. Su Govpay (3.7.4) che attualmente utilizzo in produzione stavo cercando di lavorare sulle rendicontazioni e ho cominciato a ricercarle filtrandole per ente creditore da interfaccia grafica. Il numero di risultati restituiti per ogni ente differisce però da quello che mi viene restituito se interrogo, per quello specifico ente, le api di backoffice **/rendicontazioni**.

Sembra infatti che le rendicontazioni restituite tramite api siano esclusivamente quelle nelle quali è presente almeno un pagamento transitato tramite govpay, mentre da interfaccia le ottengo tutte. Stiamo sbagliando qualcosa nell'interrogazione o nella configurazione del profilo dell'applicazione chiamante oppure si tratta di una caratteristica voluta ? in questo caso, come potrei estrapolare tutte le rendicontazioni ricevute per uno specifico ente creditore anche se non contenenti un pagamento transitato su Govpay ?

Grazie come sempre.

**Comment by pintorig** [comment]
Salve @frdidonato, grazie per la segnalazione. Facciamo le verifiche del caso riproducendo il caso d'uso in locale.

**Comment by pintorig** [comment]
@frdidonato abbiamo corretto il problema segnalato con il commit 23b6da9 nel branch di sviluppo 3.7.x.
Puoi aggiornare la tua installazione dal branch indicato o attendere il rilascio della versione 3.7.8 che avverra' a breve.

**Comment by frdidonato** [comment]
@pintorig grazie per la correzione
