### ISSUE TITLE
 principal fornito (CN=forwarder.platform.pagopa.it) non valido per l'intermediario

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#744]
Ho seguito le indicazioni dell'issue #712 per il principal ma riceviamo questo errore con la versione di Govpay 3.7.7:

`<paaInviaRTRisposta><fault><faultCode>PAA_SYSTEM_ERROR</faultCode><faultString>Errore generico.</faultString><id>Autorizzazione fallita: principal fornito (CN=forwarder.platform.pagopa.it) non valido per l'intermediario (xxx).</id><description>xxx</description></fault><esito>`

il test è stato fatto in produzione con le API KEY di PagoPa

Ho anche un'altra richiesta: abbiamo il database mysql con i dati di Govpay aggiornato alla produzione di Pagopa di un mese fa, con le patch per la versione 3.7.7. Consigliate di riallineare il database oppure tutti i pagamenti ed RT dell'ultimo mese si allineano attivando la nuova produzione con GovPay 3.7.7 su un nuovo server?

**Comment by nardil** [comment]
Ciao @temptationisla ,

il certificato che vi sta contattando e' quello di pagoPA di produzione: `CN=forwarder.platform.pagopa.it` che risulta diverso da quello configurato e quindi la chiamata non viene autorizzata. Verificate di aver valorizzato il principal con `CN=forwarder.platform.pagopa.it`.

Per l'aggiornamento di una istanza si consiglia di attenersi alla procedura della documentazione.

**Comment by temptationisla** [comment]
Ciao @nardil , può essere che restituiva errore perchè il principal era valorizzato così?

cn=forwarder.platform.pagopa.it

(con cn minuscolo..... non possiamo rifare un altro test a breve con PagoPa)
