### ISSUE TITLE
Errore di placeholder assente nei diagnostici (codPsp e codCanale)

### ISSUE THREAD

**Issue by Globus-Sviluppo** [link-it/govpay#746]
Salve, 
govpay versione3.7.6, tentando un pagamento in ambiente di test otteniamo l'errore PPT_STAZIONE_INT_PA_ERRORE_RESPONSE dopo aver inserito i dati della carta di credito e confermato. 

il govpay_diagnostic.log riporta:

<b7531fe2-5454-4f19-8b56-c03ec14856eb> 013006 ccp <2024-10-01_19:13:13.991> (INFO) {correlation-req:80000870891303067632300001506} Client-Principal:CN=forwarder.uat.platform.pagopa.it From:NodoDeiPagamentiSPC ->  To:04225880279_01 S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paVerifyPaymentNotice
Ricevuta richiesta di verifica del pagamento [Dominio:80000870891 Iuv:03067632300001506 Ccp:(???Placeholder [context.request.genericProperties[ccp].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [ccp] not exists as key in map )] dal Nodo dei Pagamenti [Psp:(???Placeholder [context.request.genericProperties[codPsp].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [codPsp] not exists as key in map )].
 
 
<b7531fe2-5454-4f19-8b56-c03ec14856eb> 013008 ccp <2024-10-01_19:13:14.293> (INFO) {correlation-req:80000870891303067632300001506} Client-Principal:CN=forwarder.uat.platform.pagopa.it From:NodoDeiPagamentiSPC ->  To:04225880279_01 S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paVerifyPaymentNotice
Verifica completata con successo. Inviato esito OK al Nodo dei Pagamenti [Importo:2.0€ Iban: Causale:"AVVISO SALDO TARI 2023"]
 
 
<3a5e7eb9-7bd5-48ce-9f4a-af32777b0566> 013001 ccp <2024-10-01_19:14:15.625> (INFO) {correlation-req:80000870891030676323000015061727802855625} Client-Principal:CN=forwarder.uat.platform.pagopa.it From:NodoDeiPagamentiSPC ->  To:04225880279_01 S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paGetPayment
Ricevuta richiesta di attivazione del pagamento [Dominio:80000870891 Iuv:03067632300001506 Ccp:1727802855625] dal Nodo dei Pagamenti [Psp:(???Placeholder [context.request.genericProperties[codPsp].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [codPsp] not exists as key in map ) Canale:(???Placeholder [context.request.genericProperties[codCanale].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [codCanale] not exists as key in map )].
 
 
<3a5e7eb9-7bd5-48ce-9f4a-af32777b0566> 002303 pagamento <2024-10-01_19:14:15.773> (INFO) {correlation-req:80000870891030676323000015061727802855625} Client-Principal:CN=forwarder.uat.platform.pagopa.it From:NodoDeiPagamentiSPC ->  To:04225880279_01 S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paGetPayment
Trasmessa RPT attivata al Nodo dei Pagamenti. [Dominio:80000870891 Iuv:03067632300001506 Ccp:1727802855625].
 
 
<3a5e7eb9-7bd5-48ce-9f4a-af32777b0566> 013004 ccp <2024-10-01_19:14:15.844> (INFO) {correlation-req:80000870891030676323000015061727802855625} Client-Principal:CN=forwarder.uat.platform.pagopa.it From:NodoDeiPagamentiSPC ->  To:04225880279_01 S:PagamentiTelematiciCCPservice O:{http://NodoPagamentiSPC.spcoop.gov.it/servizi/PagamentiTelematiciCCP}paGetPayment
Attivazione completata con successo. Inviato esito OK al Nodo dei Pagamenti [Importo:2.0€ Iban: Causale:"AVVISO SALDO TARI 2023"]

Da cosa può dipendere questo? 

**Psp:(???Placeholder [context.request.genericProperties[codPsp].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [codPsp] not exists as key in map ) Canale:(???Placeholder [context.request.genericProperties[codCanale].value] uncorrect, method [org.openspcoop2.utils.logger.beans.context.core.Request.getGenericProperties()] return java.util.Hashtable object, wrong position [codCanale] not exists as key in map )**

Grazie per ogni suggerimento

Maurizio

**Comment by nardil** [comment]
Ciao,

l'errore e' innoquo e dovuto ad una mancata acquisizione del dato da inserire nei log. Ci occuperemo di correggere la gestione del log, ma da questo non dipende alcuna funzionalita' di GovPay

L'errore segnalato e' solitamente dovuto al mancato censimento di uno dei conti di accredito utilizzati da parte dell'Ente Creditore sul portale SelfCare. Faccio presente che le anagrafiche in ambiente di collaudo (UAT) e produzione sono distinti.

Converto la Issue in Bug per correggere la gestione dei log.

**Comment by Globus-Sviluppo** [comment]
Grazie mille, provvediamo a controllare

Maurizio
