### ISSUE TITLE
Segnalazione IUV non conforme

### ISSUE THREAD

**Issue by SbGibson** [link-it/govpay#75]
Buongiorno, ho un problema che credo sia legato alla configurazione di GovPay che però non riesco a risolvere seguendo le istruzioni nel manuale.
Stiamo generando un pagamento con aux digit 0 e codice applicazione 02, così come configurato sul portale AgID. Govpay ci restituisce l'errore "VER_017 - Richiesta non valida - Lo IUV (001900000002032) non e' conforme alle specifiche agid"
Generando l'IUV con codice applicazione 01 lo IUV viene accettato, non troviamo il punto in govpay dove viene configurato il codice applicazione. E' possibile avere un chiarimento?

**Comment by nardil** [comment]
Ciao @SbGibson , 
l'application code che partecipa alla compilazione dello IUV nel caso id aux_digit 0 corrisponde alle utilme due cifre della stazione. Quindi per usare l'application code 02 devi censire in GovPay tale stazione all'intermediario di interesse e modificare la configurazione del Dominio associandolo a quella stazione.

Fammi sapere se riscontri problemi,
Lorenzo

**Comment by SbGibson** [comment]
Ho provato facendo così ma in quel caso il nodo mi risponde con l'errore "Errore applicativo PPT_STAZIONE_INT_PA_SCONOSCIUTA: IdentificativoStazioneRichiedente sconosciuto." perchè AgID ci ha attivato la stazione _01.
Il tutto nasce dal fatto che per l'attivazione del modello 3 sul portale delle adesioni di AgID è necessario specificare il codice applicazione. Nell'ente che stiamo attivando lo 01 è già occupato da un altro intermediario. Abbiamo quindi scelto 02 ma generando IUV con stazione _01 e codice applicazione 02 ho questo problema. Se genero l'IUV con codice 01 tutto funziona ma AgID dice giustamente che poi al momento del pagamento ci sarebbero problemi nel contattare l'intermediario.

**Comment by nardil** [comment]
Allora è un ente pluri-intermediato.
E' corretto quindi censirlo sulla stazione 01 e nella configurazione del Dominio indicarlo come pluri-intermediato (aux-digit 3) ed indicare come codice di segregazione il numero 02.

**Comment by SbGibson** [comment]
Forse il portale di AgID in questo è ambiguo perchè consente di impostare 0 - 02 e alcuni enti li hanno convertiti direttamente loro in 0 - 02.

**Comment by SbGibson** [comment]
Mi correggo, AgID dice "sul Nodo al comune è stata assegnato l’application code 02 con aux digit 0 perché il codice 01 era già stato assegnato ad altro Partner. Ribadiamo che l’application code NON può essere collegato alla stazione usata dal Partner ma è assegnato tenendo conto di eventuali altri Partner."

**Comment by nardil** [comment]
Capisco, ma l'uso di un applicationCode diverso dallo standard per la stazione non è supportato.
In caso di "altri partner" mi risulta opportuna la configurazione multi-intermediario con auxDigit a 3 e codice di segregazione. Ci sono particolarità che lo impediscono?

**Comment by nardil** [comment]
Ritengo inoltre che utilizzare l'auxDigit a 0 su più intermediari/partner possa presentare dei problemi di univocità dello IUV dal momento che non include l'applicationCode. Nella configurazione con auxDigit a 3 lo IUV presenta nelle prime due cifre il segregationCode che garantisce l'univocità dello IUV tra i diversi intermediari.
In fase di riconciliazione si potrebbero cosi presentare dei problemi sia per risolvere eventuali conflitti, sia per scartare pagamenti di altri intermediari.

**Comment by SbGibson** [comment]
Sono d'accordo con te. Il problema è che AgID stessa ha mappato alcuni enti con aux 0 e application 02 creando questo disguido. Stiamo chiedendo la migrazione all'aux 3. Grazie per i chiarimenti.

**Comment by nardil** [comment]
Ciao @SbGibson, siete riusciti a chiarire la problematica con AgID? 

Facci sapere cosi eventualmente valutiamo come poter supportare la configurazione che vi è stata imposta.

**Comment by SbGibson** [comment]
Abbiamo chiesto il passaggio all'aux digit 3 valutando, come dicevi tu che fosse la scelta più corretta. Proprio ieri ci hanno confermato il passaggio e riconfigurando opportunamente govpay siamo riusciti ad inviare i pagamenti quindi direi che, seppur previsto da AgID, il meccanismo con l'aux digit a 0 e application 02 non è vincolante, ci si può adattare ad utilizzare il 3.

**Comment by nardil** [comment]
Bene cosi, chiudo la issue!
