### ISSUE TITLE
Servizio di acquisizione ricevute da PagoPA

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#753]
**Necessità:**
Il servizio di recupero ricevute da PagoPA tramite API SOAP deve essere aggiornato per utilizzare le nuove API REST.

**Soluzione:**

- [x] Integrare le nuove API Rest di recupero [Ricevute](https://github.com/pagopa/pagopa-api/blob/master/openapi/bizEvents.yaml).
- [x] La procedura di acquisizione delle rendicontazioni deve verificare se esiste una pendenza associata anche se non esiste il pagamento e rivedere il check che decide se la rendicontazione appartiene ad un dominio esterno.
- [x] La procedura di recupero della ricevuta deve essere eseguita ogni qual volta viene acquisita una rendicontazione che non identifica un pagamento all'interno di GovPay.
- [x] Escludere la procedura che tenta il recupero tramite le vecchie API SOAP.
- [x] Il batch deve essere eseguito periodicamente per verificare l'esistenza di rendicontazioni che non identificano alcun pagamento all'interno di GovPay
- [x] Aggiungere la possibilita' di configurare nell'intermediario L'API KEY necessaria per utilizzare il servizio di recupero ricevute.

**Comment by pintorig** [comment]
Query che deve eseguire il batch per individuare le RT da recuperare

```sql
-- Rendicontazioni di cui recuperare la RT

 select * from rendicontazioni where id_singolo_versamento is not null and id_pagamento is null and data > now() - interval '8 weeks' order by data desc;
```

**Comment by nardil** [comment]
> [ ] La procedura di recupero della ricevuta deve essere eseguita ogni qual volta viene acquisita una rendicontazione che non identifica un pagamento all'interno GovPay.

Il processo di acquisizione delle RT mancanti deve essere eseguito periodicamente, indipendentemente dal processo di acquisizione delle rendicontazioni, esattamente come era il procedente processo di recupero delle RPT pendenti che questa procedura va a sostituire.

**Comment by nardil** [comment]
Altra info: nella configurazione dell'intermediario la Subscription Key per il servizio di recupero delle Receipt deve essere opzionale. Se non e' impostato, il batch ignora quell'intermediario nella procedura di recovery loggando un warning.

**Comment by nardil** [comment]
Intoltre il recupero della RT deve essere registrato sul giornale degli eventi
