### ISSUE TITLE
Api di Notifica in SSLHandshake solo su alcune applicazioni

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#755]
Salve,
Sto utilizzando in produzione la versione di govpay 3.7.4 e ho ormai all'attivo 71 enti creditori con le relative applicazioni configurate e funzionanti. 
Ogni ente creditore espone una API rest sul dominio dell'ente raggiungibile da internet e su protocollo HTTPS che serve come api di Verifica e Notifica. 
L'applicazione sull'ente che espone le API REST è la stessa configurata su tutti gli altri enti, e sono tutti allineati alla stessa versione.

Le ricevute arrivano correttamente su tutti i backend ad accezione di due enti creditori per i quali, in seguito al tentativo di invio della ricevuta o di notifica di avvio del pagamento, ricevo il seguente errore : 

"
![erroreSSLHandshake](https://github.com/user-attachments/assets/d84e6655-1b66-4a4b-b91c-c2800a2c905d)
"

Questo errore solitamente, per le applicazioni java , significa che nei cacerts della JVM chiamante non è stato importato il certificato https del dominio chiamato e si risolve scaricando il certificato con openssl e importandolo tramite keytool nel keystore. Nonostante non abbia mai effettuato questa operazione per nessuna delle altre 69 applicazioni configurate, ognuna delle quali sul proprio dominio con protocollo https, ho tentato questo approccio per l'ente che mostra questo problema, ma non ho ottenuto nessun miglioramento. L'invocazione dell'API di Notifica continua ad andare in errore e  a presentare lo stesso errore di HandShake. 
Potreste suggerirmi delle strategie di risoluzione ? Ormai mi porto dietro questo problema su questi due enti da un po di tempo

**Comment by nardil** [comment]
Non e' un bug, ma un difetto di configurazione. 

Devi impostare nella configurazione del connettore il trustore da utilizzare per l'handshake contenente il certificato server (o la CA emittente, a seconda delle vostre policy di sicurezza)

**Comment by frdidonato** [comment]
> Non e' un bug, ma un difetto di configurazione.
> 
> Devi impostare nella configurazione del connettore il trustore da utilizzare per l'handshake contenente il certificato server (o la CA emittente, a seconda delle vostre policy di sicurezza)

Ciao @nardil grazie mille per la pronta risposta, come sempre.
Perdonami ma dato che questa operazione di configurazione non l'ho mai fatta in nessuna delle applicazioni attualmente funzionanti, potresti spiegarmi come procedere ? ho provato a dare un'occhiata alla documentazione ma sinceramente non capisco come configurarla, probabilmente perchè non mi intendo molto di queste cose

**Comment by frdidonato** [comment]
Grazie @nardil , adesso sono riuscito a configurare tutto come si deve grazie alle tue indicazioni e funziona
