### ISSUE TITLE
Impossibile aggiungere un dominio dalla console

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#76]
Non riesco dalla console ad aggiungere un dominio / ente creditore. Ho abilitato l'intermediario nel portale delle adesioni pagopa e associato l'ente creditore alla stazione. GovPayConsole risponde con "Impossibile aggiungere il dominio, riprovare più tardi". In console.log non ci sono errori e viene scritto solo questo log:

11:49:43,028 WARN  [net.sf.json.JSONObject] (http--0.0.0.0-8080-3) Tried to assign property uoId:java.lang.String to bean of class it.govpay.bd.model.Dominio
[...OMISSIS...]
11:49:43,084 WARN  [net.sf.json.JSONObject] (http--0.0.0.0-8080-3) Tried to assign property iuvPrefixStrict:java.lang.Boolean to bean of class it.govpay.model.Anagrafica

**Comment by nardil** [comment]
Ciao Mauro,
per analizzare il problema dovresti indicarmi:
- Versione di GovPay
- Tipo e versione dell'application server
- Tipo e versione del dbms
infine dovresti inviarmi, eventualmente in forma privata, lo zip dei della cartella di log.

**Comment by temptationisla** [comment]
Ciao Lorenzo,
govpay è la versione 2.3.3.
Questa è la versione di Jboss:
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /usr/share/jboss-as

  JAVA: /usr/java/jdk1.6.0_45/bin/java

  JAVA_OPTS:  -server -XX:+UseCompressedOops -XX:+TieredCompilation -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.server.default.config=standalone.xml

=========================================================================

12:17:46,745 INFO  [org.jboss.modules] JBoss Modules version 1.1.1.GA
JBoss AS 7.1.1.Final "Brontes"

Il database è postgres:
psql (PostgreSQL) 8.4.20

Ti giro nella tua mail personale lo zip dei log di govpay

**Comment by nardil** [comment]
Dai log risulta che l'installazione non e' corretta. In particolare non risulta disponibile il datasource:
```
2019-05-29 03:08:14.550 | ERROR | Inizializzazione fallita
org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
```

La versione 2.3 di GovPay e' comunque deprecata non supportando il WISP 2.0. Trattandosi di una nuova installazione, dovresti utilizzare l'ultima versione, la [3.1.0-RC1](https://github.com/link-it/govpay/releases/tag/v3.1.0-RC1)
