### ISSUE TITLE
Errore invocazione Web Service Client

### ISSUE THREAD

**Issue by gfalce** [link-it/govpay#78]
Buongiorno,
non riesco ad invocare il Web Service Client GovPay, mi da il seguente errore:
![Immagine1](https://user-images.githubusercontent.com/30801229/59349267-82394180-8d19-11e9-8aa8-d45c7b5adcea.png)
Analizzando il wsdl con un servizio online mi vengono segnalati i seguenti errori:
![Immagine2](https://user-images.githubusercontent.com/30801229/59349291-954c1180-8d19-11e9-8e3e-eb78d463a8e9.png)

Già nel generare il client sia con axis2 che con NetBeans ho avuto problemi, che ho in parte bypassato utilizzando l'arg -B-XautoNameResolution. Nonostante ciò durante la generazione mi vengono segnalati i seguenti messaggi:
![Immagine3](https://user-images.githubusercontent.com/30801229/59349407-dcd29d80-8d19-11e9-9a15-e3f1bec482ee.png)

Come posso risolvere?
Grazie.

**Comment by nardil** [comment]
Ciao @gfalce,

ho fatto alcune modifiche ai WSDL, ininfluenti per la struttura dei messaggi SOAP, in modo da risolvere i problemi segnalati dal validatore online, fammi sapere se risolvono completamente i problemi di generazione dei tools che utilizzi: [wsdl_v25_patch_compatibilita.zip](https://github.com/link-it/govpay/files/3281329/wsdl_25.zip)

**Comment by gfalce** [comment]
Perfetto, sono riuscito a generare lo stub con axis2.. grazie!
