### ISSUE TITLE
Setup iniziale della piattaforma

### ISSUE THREAD

**Issue by temptationisla** [link-it/govpay#80]
Ho un problema con il metodo post delle api di pagamento per eseguire un pagamento. Ho configurato l'applicazione e l'intermediario con l'url .... /govpay/frontend/api/pagopa con autenticazione http basic e dando l'utenza (forse sbagliata). Il nodo pagopa è attivo da ieri.

Allego log richiesta. 
[log1.txt](https://github.com/link-it/govpay/files/3293179/log1.txt)

**Comment by nardil** [comment]
Ciao Mauro,
nella configurazione dell'Intermediario devi indicare la URL del servizio RPT di pagoPA che ti è stata indicata sul Portale delle Adesioni e come principal il subject del certificato utilizzato da pagoPA.

Nel caso di connessione GAD i parametri deovrebbero essere i seguenti:
```
URL: https://gad.test.pagopa.gov.it/openspcoop2/proxy/PA/RPT6T
Principal: /l=Roma/ou=pagoPA/serialnumber=97735020584/.2.5.4.15=Government Entity/.1.3.6.1.4.1.311.60.2.1.3=IT/o=Agenzia per l'Italia Digitale/c=IT/cn=gad.test.pagopa.gov.it/
```

Verifica anche di aver configurato il certificato client sull'AS (quello che hai indicato a pagoPA in fase di adesione) e di aver aggiunto al truststore quello di pagoPA.

**Comment by temptationisla** [comment]
ok, per i servizio RPT, ma su richiesta devo per forza modificare il collegamento fisico nel portale alle adesioni, ma non capisco cosa devo impostare come servizio RT (nel portale alle adesioni). E' corretto https://pagopa.swdweb.it/govpay/ dove ho installato GovPay?

**Comment by nardil** [comment]
Eccolo: https://pagopa.swdweb.it/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice

**Comment by temptationisla** [comment]
Grazie, ho chiesto la modifica al collegamento fisico.
E' corretto che chieda l'autenticazione?

**Comment by nardil** [comment]
Se ti riferisci al servizio RT, si, perchè pagoPA richiede che le comunicazioni siano con mutua autenticazione SSL. 
Pertanto, come anticipato nel messaggio precedente, devi configurare nell'AS il keystore con la tua chiave privata (quella fornita in fase di configurazione sul portale delle adesioni) ed il trustore con il certificato di pagoPA di collaudo (dovresti avere il link per il download sempre dal portale delle adesioni)

**Comment by temptationisla** [comment]
Ciao Lorenzo,
dopo circa 2 settimane hanno attivato il mio collegamento fisico, ho impostato l'url di collaudo in GAD come da suggerito e presente nella documentazione del portale alle adesioni, ho scaricato e installato nel truststore il certificato di pagopa e l'istanza di govpay ha il certificato del sottodominio che ho caricato sul portale. Purtroppo non riesco ancora a eseguire un pagamento di test.
Ho creato una pendenza con il metodo put e richiamando con il metodo get delle api pendenze v2 ho la pendenza caricata correttamente, con idpendenza 10. Ora faccio questa chiamata post con le api di pagamento v2:
"{\"pendenze\":[{\"idA2A\":\"010203040506\",\"idPendenza\":\"10\"}]}"

ma ricevo

{"status":502,"title":"Bad Gateway","type":"https://govpay.readthedocs.io/it/latest/integrazione/errori/errore-http-502.html"}

Se vado nella console il pagamento è in corso e come note ho "Servizi pagoPA non disponibili."


Dove sto sbagliando? Eseguita correttamente questa chiamata non dovrei stressarti più

Scusa il disturbo

Mauro

**Comment by nardil** [comment]
Ciao Mauro,

il servizio RPT non ti sta rispondendo, probabilmente c'e' ancora qualche problema di configurazione del canale SSL. Posso darti informazioni piu' precise se mi invii il log di GovPay (per default salvati in `/var/log/govpay`) e dell'application server, eventualmente puoi inviarmeli privatamente.

- Lorenzo

**Comment by nardil** [comment]
Ciao Mauro,

dai log emerge questo errore: `Caused by: java.net.UnknownHostException: gad.test.pagopa.gov.it`

Dovresti verificare la risoluzione dell'host:

```
telnet gad.test.pagopa.gov.it 443
Trying 89.96.57.105...
Connected to gad.test.pagopa.gov.it.
Escape character is '^]'.
```

**Comment by temptationisla** [comment]
Ciao Lorenzo,
infatti non risolveva il dominio. Ho impostato nel file hosts l'ip erogatore del documento del portale alle adesioni e ora il telnet va a buon fine. Ho anche riavviato il server e fatto la medesima chiamata di pagamento pendenza ma il risultato  non cambia:
{"status":502,"title":"Bad Gateway","type":"https://govpay.readthedocs.io/it/latest/integrazione/errori/errore-http-502.html"}

Ho aggiornato il link con i nuovi log

**Comment by nardil** [comment]
Adesso la chiamata raggiunge pagoPA, ma ricevi in risposta un messaggio di errore di autorizzazione:
```
Errore nell'invocazione del Nodo dei Pagamenti [HTTP Response Code 403]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /openspcoop2/proxy/PA/RPT6T on this server.</p>
</body></html>
```
sembra quindi un problema di configurazione lato Nodo dei Pagamenti,  ma prima di aprire una segnalazione a pagoPA suggerirei di verificare che effettivamente la comunicazione SSL sia con mutua autenticazione.

Puoi ripetere il test abilitando il debug SSL dell'application server? Puoi farlo impostando questa proprieta' JVM: `javax.ssl.debug=true`

**Comment by temptationisla** [comment]
In effetti ho fatto casino con i certificati e ora mi da errore che il keystore not contains the keys in fase di avvio. Utilizzo wildfly ma mi chiede necessariamente una chiave privata per settare il keystore nell'ssl, mentre il certificato gad è un file cer senza chiavi private. Come posso procedere?

**Comment by nardil** [comment]
Devi creare un keystore ed un truststore. 

Nel primo metterai il tuo certificato client, comprensivo di chiave privata, del quale hai gia' condiviso la chiave pubblica con pagoPA in fase censimento della connessione fisica dal Portale delle Adesioni. 
Nel secondo inserirai i certificati server da trustare per il corretto handshake SSL, in particolare quello di pagoPA del GAD e successivamente degli eventuali applicativi che invocheranno i servizi di integrazione di GovPay.

Per la gestione dei certificati puoi utilizzare un qualsiasi tool, come ad esempio [`keytool`](https://docs.oracle.com/javase/6/docs/technotes/tools/windows/keytool.html)  o [`portecle`](http://portecle.sourceforge.net/). Di entrambi (soprattutto del primo) trovi abbondanza di esempi d'uso online.

**ATTENZIONE**: per una limitazione del connettore built-in di Java, devi utilizzare la medesima password di cifratura sia per il keystore che per la chiave privata del certificato client.

Una volta creati, configura la JVM di WildFly per utilizzarli come segue:
```
  -Djavax.net.ssl.keyStore=/etc/govpay/keystore.jks
  -Djavax.net.ssl.keyStorePassword=changeit 
  -Djavax.net.ssl.trustStore=/etc/govpay/truststore.jks
  -Djavax.net.ssl.trustStorePassword=changeit
```

**Comment by temptationisla** [comment]
Ho risolto il problema dei certificati e adesso la risposta è questa:

Risposta: <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>soapenv:Client</faultcode><faultstring>001 - Formato Busta non corretto</faultstring><detail><errore-applicativo xmlns="http://www.openspcoop2.org/core/eccezione/errore_applicativo">
<dominio funzione="PortaApplicativa" modulo="PortaApplicativa">
<identificativo-porta>NodoDeiPagamentiDellaPATestPdD</identificativo-porta>
<soggetto tipo="PROXY">NodoDeiPagamentiDellaPATest</soggetto>
</dominio>
<ora-registrazione>2019-07-08T14:10:24.201Z</ora-registrazione>
<dati-cooperazione>
<erogatore>
<identificativo tipo="PROXY">NodoDeiPagamentiDellaPATest</identificativo>
<identificativo-porta>NodoDeiPagamentiDellaPATestPdD</identificativo-porta>
</erogatore>
<servizio tipo="PROXY" versione="1">PagamentiTelematiciRPT6T</servizio>
<azione>nodoChiediStatoRPT</azione>
</dati-cooperazione>
<eccezione tipo="EccezioneProtocollo">
<codice tipo="117">ECCEZIONE_PROTOCOLLO_117</codice>
<descrizione>Identificazione fallita, credenziali fornite non corrette</descrizione>
</eccezione>
</errore-applicativo></detail></soapenv:Fault></soapenv:Body></soapenv:Envelope>

Non vanno bene le credenziali settate in govpay?

**Comment by nardil** [comment]
Dall'errore sembra che il GAD non sia configurato correttamente. Dovresti aprire un ticket sul Portale delle Adesioni includendo come informazioni aggiuntive i messaggi SOAP di richiesta e risposta scambiati tra GovPay e pagoPA recuperandoli dal file `govpay_dump.log` (puoi cercare la stringa `ECCEZIONE_PROTOCOLLO_117` per individuarli rapidamente)

**Comment by temptationisla** [comment]
il file govpay_dump.log è vuoto

**Comment by temptationisla** [comment]
e in effetti ho questi errori nel log di wildfly:

2019-07-08 15:09:16,823 ERROR [stderr] (MSC service thread 1-2) SLF4J: Class path contains multiple SLF4J bindings.
2019-07-08 15:09:16,824 ERROR [stderr] (MSC service thread 1-2) SLF4J: Found binding in [vfs:/content/govpay.ear/lib/log4j-slf4j-impl-2.6.2.jar/org/slf4j/impl/StaticLoggerBinder.class]
2019-07-08 15:09:16,824 ERROR [stderr] (MSC service thread 1-2) SLF4J: Found binding in [vfs:/content/govpay.ear/lib/slf4j-log4j12-1.5.6.jar/org/slf4j/impl/StaticLoggerBinder.class]
2019-07-08 15:09:16,824 ERROR [stderr] (MSC service thread 1-2) SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2019-07-08 15:09:16,833 ERROR [stderr] (MSC service thread 1-2) SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

Ho aggiornato il file dei log

**Comment by nardil** [comment]
> il file govpay_dump.log è vuoto

Pardon, il dump dei messaggi e' disabilitato per default. 
Puoi abilitarlo configurando la seguente property: it.govpay.context.savataggioDumpSuFile.enabled: true

> e in effetti ho questi errori nel log di wildfly...

Puoi ignorare quella segnalazione di errore in fase di deploy. Verra' risolta nei prossimi rilasci, ma non compromette nessuno dei servizi di GovPay.

**Comment by temptationisla** [comment]
dove si setta quella property? ho provato in logging.properties con savataggio e salvataggio e l'uguale al posto dei 2 punti

**Comment by nardil** [comment]
Puoi configurarla nei seguenti tre modi (in ordine di priorita' in caso di conflitti):
1. come property della JVM di wildfly.
1. nel file di properties esterno (per default `/var/govpay/govpay.properties`) 
1. nel file govpay.properties interno all'ear

**Comment by temptationisla** [comment]
fatto e log popolato, faccio una segnalazione. Grazie come sempre
