### ISSUE TITLE
Backlog cruscotto

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#85]
- [x] Cruscotto: nella colonna del menu, visualizzare il nome utente, non il principal
- [x] Giornale degli Eventi: ordinare i tipi evento nel filtro
- [x] Giornale degli Eventi: mostrare date fino ai millisecondi, anche nel dettaglio
- [x] Tipi pendenza: filtro per descrizione (anche parziale) e identificativo
- [x] Tipi pendenza: valorizzare correttamente "pagabile da terzi" quando impostato a false (viene valorizzato `predefinito`) ed in edit mostrare la stessa label (viene visualizzato "pagabile da altri")
- [x] Tipi pendenza: perfezionare le label mostrate
- [x] Tipi pendenza: dopo una modifica i dati del dettaglio non sono aggiornati
- [x] Pendenze: aggiungere filtro per tipo pendenza

**Comment by simo-git** [comment]
- [x] Cruscotto: nella colonna del menu, visualizzare il nome utente, non il principal
Nel profilo ho solo quel valore nella proprietà "nome"
- [x] Giornale degli Eventi: ordinare i tipi evento nel filtro
- [x] Giornale degli Eventi: mostrare date fino ai millisecondi, anche nel dettaglio
Aggiornato. Questa modifica implica l'utilizzo di un altro tipo di visualizzazione del singolo elemento di lista, poiché le etichette sono esageratamente lunghe. Suggerisco di usare la grafica dei pagamenti.
- [x] Tipi pendenza: filtro per descrizione (anche parziale) e identificativo
Aggiunti. Questi filtri non sono indicati nello swagger
- [x] Tipi pendenza: valorizzare correttamente "pagabile da terzi" quando impostato a false (viene valorizzato predefinito) ed in edit mostrare la stessa label (viene visualizzato "pagabile da altri")
- [x] Tipi pendenza: perfezionare le label mostrate
Allineato con le label nelle note fornite.
- [x] Tipi pendenza: dopo una modifica i dati del dettaglio non sono aggiornati
- [x] Pendenze: aggiungere filtro per tipo pendenza
